### ISSUE TITLE
Tone.Player from AudioBuffer

### ISSUE THREAD

**Issue by sorskoot** [Tonejs/Tone.js#100]
According to the documentation it should be possible to create a player from an AudioBuffer. This doesn't seem to be working.

This piece of code from the constructor of Player uses the url option and ignores the audiobuffer.

 this._buffer = new Tone.Buffer({
	            'url': options.url,
	            'onload': this._onload.bind(this, options.onload),
	            'reverse': options.reverse
	        });

Is there anyway to get "new Tone.Player(buffer);" to work?

**Comment by tambien** [comment]
I think this was addressed with #99 and should be fixed on the `dev` branch. I just tested it and it works for me.
