### ISSUE TITLE
Docs for r12 ?

### ISSUE THREAD

**Issue by cristianvogel** [Tonejs/Tone.js#1007]
Hi,

Due to a stability requirement, I am trying to get familiar with [Tone.js at r12 ](https://github.com/Tonejs/Tone.js/tree/r12) - don't suppose the API reference and/or docs/examples for r12 are still available somewhere? 

Thanks for that and for keeping Tone sounding sweet!

**Comment by chrisguttandin** [comment]
I'm not sure about the examples but the API docs are here: https://tonejs.github.io/docs/r12/AutoFilter

**Comment by tambien** [comment]
Thanks @chrisguttandin!

@cristianvogel you can grab the r12 release [here](https://github.com/Tonejs/Tone.js/releases/tag/r12) which will have all of the example files in there as well.
