### ISSUE TITLE
More than one Transport to facillitate parrarel accurately timed Loops/Sequences

### ISSUE THREAD

**Issue by michaelmariaott** [Tonejs/Tone.js#1009]
Hello,

maybe I am missing something, but I did not find any possibility of running mulitple Loops/Sequences with different (adjustable) speeds independently from each other.

I tried this:
```
let synth1 = new Tone.MonoSynth().toDestination();
let synth2 = new Tone.MonoSynth().toDestination();


let seq1_speed = 1;
let seq1_2n = seq1_speed / 2;
let seq1_p2n = '+'.concat(seq1_2n.toString());
let seq2_speed = .7;

let seq1 = new Tone.Loop(time => {
	synth1.triggerAttackRelease('C4', .1, time);
	synth1.triggerAttackRelease('Eb4', .1, seq1_p2n);
}, seq1_speed);

let seq2 = new Tone.Loop(time => {
	synth2.triggerAttackRelease('G4', .1, time);
}, seq2_speed);

Tone.Transport.start();
seq1.start(0);
seq2.start(0);
```
But there are audible timing-inaccuracies.

**Comment by tambien** [comment]
Instead of `synth1.triggerAttackRelease('Eb4', .1, seq1_p2n);` try `synth1.triggerAttackRelease('Eb4', .1, time + seq1_2n);`

Using the string notation `"+0.5"` is going to be susceptible to loose JS timing. Always use the scheduled time returned from the Transport callbacks when possible.
