### ISSUE TITLE
Tremolo not working

### ISSUE THREAD

**Issue by lukephills** [Tonejs/Tone.js#102]
I can't seem to get it working. Here's an example: http://jsfiddle.net/prespcLb/13/

**Comment by tambien** [comment]
The Tremolo needs to be started before you'll hear it. Also i don't think Tone.Mono is doing anything here; the Oscillator signal is already mono. 

http://jsfiddle.net/3od6qsjt/1/

Tone basically has two genres of LFO-based effects, those with start/stop/sync (AutoPanner, AutoFilter) and those without (Phaser, Chorus). I'm not quite sure which side Tremolo should land on.

I thought maybe a user would want to sync up the Tremolo with the start of the Transport and have everything tempo synced. What do you think? useful or unnecessary?
