### ISSUE TITLE
buffer is either not set or not loaded

### ISSUE THREAD

**Issue by louisabraham** [Tonejs/Tone.js#1022]
I modified the code of https://tonejs.github.io/Midi/index.html with the sampler from https://tonejs.github.io/examples/sampler

```js
currentMidi.tracks.forEach((track) => {
	const synth = new Tone.Sampler({
		urls,
		release: 1,
		baseUrl: "./data/piano/"
	}).toDestination();
	synths.push(synth);
```

I get `buffer is either not set or not loaded`

If I initialize the synth at top level, there is no such issue but I get issues on multi track songs where the same note is played like: on on off off.

**Comment by louisabraham** [comment]
Also, it's very annoying that Sampler has to redownload the audio files on each initialization if it's called multiple times.

**Comment by louisabraham** [comment]
This bug is also very annoying because there is no way (AFAIK) to stop using `disconnect`, clear the notes and connect again (eg with `toDestination`), hence it's impossible to stop and resume playing with Sampler.

**Comment by Pbotsaris** [comment]
Hey Louis,

> I get buffer is either not set or not loaded

The `Tone.Sampler` constructor has an `onload` callback you can use to only trigger when the audio files have been properly loaded.

> Also, it's very annoying that Sampler has to redownload the audio files on each initialization if it's called multiple times.

What do you mean by redownloading? If you are using exactly the same samples,  why are you instantiating multiple samplers? 

> This bug is also very annoying because there is no way (AFAIK) to stop using disconnect, clear the notes and connect again (eg with toDestination), hence it's impossible to stop and resume playing with Sampler.

I am not sure what you mean here. Do you mind posting your complete code?

**Comment by tambien** [comment]
Thanks for chiming in @Pbotsaris, @louisabraham the onload callback is probably the simplest way to wait for the samples to all load

I'm going to close for now
