### ISSUE TITLE
Significant delay when triggering sampler or player from Midi or Mouseclick events

### ISSUE THREAD

**Issue by mypelz** [Tonejs/Tone.js#1031]
We are using Tone.js intensively for our platform since 2 years and consider it as a fantastic piece of work, thanx a lot for your awesome work!!
Recently we started to create latency critical modules and are facing significant delays of the Tone sampler and Tone player, when playing back a mp3/wav soundfile, versus triggering a native AudioSourceBuffer. On Chrome running on MacOS (M1 Powerbook) we measure in average a difference of 100 up to 400ms between the native AudioSourceBuffer playback and the Tone players. As this is beyond the acceptable latency for playing e.g. from a Midi Keyboard we kindly ask for some comments on that. Maybe there are methods to improve latency, any hints and suggestions highly appreciated.

**Comment by marcelblum** [comment]
Biggest difference maker is to set Tone's `context.lookAhead` to 0. By default Tone.js uses a 100ms `lookAhead` which can feel like a ton of latency. With `lookAhead` at 0 then in theory the latency should only be the context's [baseLatency](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/baseLatency) which varies depending on the context `sampleRate` and browser. Can also try tweaking Tone's `context.updateInterval`. Those are the 2 main things to look at, though there's usually room for further microoptimizations depending on your code, if you wanted to post a code example.

**Comment by mypelz** [comment]
Hi Marcel, thanx for your quick answer and interesting hints. In the meantime we found the issue by try and error: 
// This was having the "delay" of approx. 100 ms --> using Tone.now() 
this.sampler.triggerAttack(note, Tone.now(), 1);
// this option works as expected (Tone.context.currentTime)
this.sampler.triggerAttack(note, Tone.context.currentTime, 1);

Nevertheless we did not find precise descriptions about the different Tone time approaches in your documentation. This would be a nice field for improvement for your great API ;-)

**Comment by marcelblum** [comment]
Yeah you're basically just bypassing the `lookAhead` when you do that, `Tone.now()` is `Tone.context.currentTime + Tone.context.lookAhead`. Better way would be to set `lookAhead = 0` once at init, then just `sampler.triggerAttack(note)`.

There's a wiki article about performance that mentions lookAhead, could probably use some expanding though https://github.com/Tonejs/Tone.js/wiki/Performance

**Comment by mypelz** [comment]
But if I understand right this would change the lookAhead in general, so that we have a maybe unwanted impact on other scheduled events in Transport, right?

**Comment by marcelblum** [comment]
Not sure what kind of "unwanted impact" you are fearing; if you set the lookAhead once at startup then all subsequent timings would be the same relative to each other.

**Comment by mypelz** [comment]
I think I have to dig into the concept of the lookAhead further ;-)

Maybee you could help me with a further problem regarding Transport that drives me crazy:
-  we "record" Midi events into an Array and are using Tones time to timestamp every event accordingly.
- when we would like to "play" this "recording", we loop through all events and schedule all note events by using Tone.Transport.schedule, e.g. on the Tone sampler. When starting transport the playback starts super precisely, works like a charm!
- Now my stupid problem: how to pause or stop the "playback" of the scheduled events. I was assuming that I can stop, pause, clear the Transport to achieve this, but this does not work. E.g. Transport stops definitely, but the scheduled events are playing back until the end of the recording. What am I doing wron here??!

**Comment by mypelz** [comment]
Voila a code excerpt:
1. we record an array of events and store it in this.recorder
2. we perpare the playback by passing this array into the method preparePlay() which is scheduling Transport
3. we start playback by starting Transport

Our issue: neither Transport methods stop, cancel, clear can prevent the scheduled events from playing, or do remove events from Tones timeline after we called Tone.Transport.start(). 

Framework: Typescript 4.3.5, Angular 12, Tone 13.4.9.

```
export interface RecorderEvent {
  note: number, // frequency
  state: number, // 1, 0 -> keypress, keyrelease
  velocity: number, // midi velocity
  time: number, // Tone.Time
}
...
this.recorder =  [
  {
    "note": 65.40639132514966,
    "state": 0,
    "velocity": 0.5984251968503937,
    "time": 3.727999999999952
  },
  {
    "note": 195.99771799087463,
    "state": 0,
    "velocity": 0.28346456692913385,
    "time": 4.159999999999968
  },
  {
    "note": 155.56349186104043,
    "state": 0,
    "velocity": 0.5669291338582677,
    "time": 4.170666666666648
  },
...

  preparePlay() {
    console.log('prepare play....')
    console.log(this.recorder.length);
    // clean
    Tone.Transport.cancel();
    this.recorder.forEach((event: RecorderEvent) => {
      Tone.Transport.schedule(time => {
        const scheduledTime = time + event.time;
        if (event.state === 0) {
          this.sampler.triggerAttack(event.note, scheduledTime, event.velocity);
          Tone.Draw.schedule(() => {
            const midi = Tone.Frequency(event.note).toMidi();
            console.log(midi);
            this.activeKeys.set(midi, new ActiveKey(event.velocity));
          },
            scheduledTime);
        } else {
          this.sampler.triggerRelease(event.note, scheduledTime);
          Tone.Draw.schedule(() => {
            const midi = Tone.Frequency(event.note).toMidi();
            this.activeKeys.delete(midi);
          },
            scheduledTime);
        }

        if (event.time === this.recorder[this.recorder.length - 1].time) {
          Tone.Draw.schedule(() => {
            console.log('*** THE END ***');
            Tone.Transport.stop();
            this.playStatus$.next(false);
          }, time + event.time);
        }
      });
      // console.log('scheduled event id: ', id);
    });
    Tone.Transport.scheduleRepeat((time) => {
      // use the time argument to schedule a callback with Draw
      // const lastTime = this.recorder[this.recorder.length - 1].time - offsetTime;
      Tone.Draw.schedule(() => {
        // do drawing or DOM manipulation here
        console.log(time);
      }, time);
    }, "1");
  }

...
```
Thanx a lot in advance for your support!!

**Comment by marcelblum** [comment]
Probably a misunderstanding of where the actual event scheduling is happening, looks like you're not passing a time argument to `Transport.schedule()`. This defaults to immediately, as in, as soon as the Transport starts. So when you stop the Transport those `sampler.triggerAttack()` events have already been scheduled to fire at `scheduledTime`, because they were all scheduled at once on `Transport.start()`, and the sampler is not synced to the Transport by default, so those triggers happen independently of the Transport. I think you'll need to refactor this a bit in order to be able to stop/pause/resume the sequence if that's your aim, can look into using `sampler.sync()` to sync it to the Transport (probably easiest), or can use the `Transport.schedule()` time argument instead of passing `scheduledTime` to `sampler.triggerAttack()`.

**Comment by tambien** [comment]
Thanks for jumping in @marcelblum 

I'm going to close this since it seems like it's been resolved

**Comment by mypelz** [comment]
Dear @tambien and @marcelblum, thanx a lot for your great project and support. Yes we kind of solved the issue based on your hints, but I clearly have to say that understanding transport with its 3 different timelines (audio context, absolute transport time and relative transport time) is really challenging. I think it would definitely help users to consolidate your documentation regarding transport and to expose the documents e.g. from your wiki on https://github.com/Tonejs/Tone.js at #Scheduling.
