### ISSUE TITLE
Multichannel output

### ISSUE THREAD

**Issue by petethomasmusique** [Tonejs/Tone.js#1040]
I've trawled through the Web Audio API standard and suspect this isn't possible yet. But, in case it is. I've an audio interface with 16 outputs. I can route the browser through this and Tone has visibility over the amount of outputs available:
```js
console.log(Tone.Destination.maxChannelCount)
// 32
```

What I'm looking for is the ability to route different synths to different output channels. Something like:
```js
const synthA = new Tone.FMSynth()
const synthB = new Tone.MembraneSynth()
synthA.connect(0)
synthB.connect(2)
```
Is this possible?

Many thanks.

Pete.

**Comment by chrisguttandin** [comment]
I think what you're looking for can already be done with the [ChannelSplitterNode](https://webaudio.github.io/web-audio-api/#ChannelSplitterNode) and [ChannelMergerNode](https://webaudio.github.io/web-audio-api/#ChannelMergerNode).

Tone.js comes with a wrapper for both of them called [Split](https://tonejs.github.io/docs/Split) and [Merge](https://tonejs.github.io/docs/Merge) respectively.

I hope this helps.

**Comment by petethomasmusique** [comment]
Thanks @chrisguttandin I'll give this a try. Are the docs generated from this repo? Ie. if I get a working example together can I contribute to the docs by opening a PR?

Many thanks,

Pete.

**Comment by chrisguttandin** [comment]
Yes, the docs are generated from the source code. I'm not the owner of this repo but I would assume that @tambien values your contribution to the docs.

**Comment by petethomasmusique** [comment]
Grand.
