### ISSUE TITLE
Please make a new release so that you can use tonejs in svelte without having to modify the package.json

### ISSUE THREAD

**Issue by mardax007** [Tonejs/Tone.js#1062]
If you use tonejs in svelte you get an error on build. This is because vite uses nodejs and tonejs hates nodejs.

**Comment by giohappy** [comment]
I'm using Vite + Electron + Tone without any issue. The renderer builds correctly when importing Tone ESM bare module.
Maybe it's something with the configuration of your project?

**Comment by FractalHQ** [comment]
I'm using it just fine in svelte as well.

**Comment by mardax007** [comment]
I haven't used it in months now so if it's fixed I'll close the issue
