### ISSUE TITLE
Transport scheduling callbacks - event id argument

### ISSUE THREAD

**Issue by sfradkin** [Tonejs/Tone.js#107]
Could the callbacks called by the Transport scheduling functions also send the event id along with the time?  This will allow the callback function to know which event is being fired.

**Comment by tambien** [comment]
This would be pretty easy to implement, but i'm not sure what the use case would be. Would you want the id in the callback so that you could cancel the event within the callback?

**Comment by tambien** [comment]
I've been thinking more about this, it seems to me that the responsibility of keeping track of the scheduled ID is up to the code that scheduled it. Shifting that responsibility from the caller of `schedule` to the callee of schedule's callback might not be the best practice. Without a good use case for it, i'm going to leave the API as it currently is. 

If you've got a use-case for this, i'd still be happy to be convinced.

**Comment by sfradkin** [comment]
As with issue 108, once I refactored my code to use Tone.Part, this became unnecessary.
