### ISSUE TITLE
Polyphony and PluckSynth

### ISSUE THREAD

**Issue by spacejack** [Tonejs/Tone.js#1074]
I see that you can't create a PolySynth from the PluckSynth constructor. Is there a way to play multiple PluckSynth notes at the same time?

Also, if I wanted to get something like a piano sound how would you suggest I approach it using the various synths and settings? I don't really know wavetable synthesis and only a few general synth basics, like oscillators, filters, envelopes. I'm not expecting VST-quality piano, but maybe some kind of DX7 or old Roland-like piano? Any tips appreciated.

**Comment by tambien** [comment]
Easiest would be to create multiple instances of the PluckSynth and manage polyphony yourself. 

As far as pianos, i've had good luck with the Salamander Grand piano samples that you can use directly with Tone.Sampler or use a library (not sure if it still works well) that i wrote which wraps it. 

https://github.com/tambien/Piano
