### ISSUE TITLE
Transport Timelines - allow multiple

### ISSUE THREAD

**Issue by sfradkin** [Tonejs/Tone.js#108]
There doesn't appear to be a way to create multiple timelines and have the Transport run those timelines.  It could be useful to schedule groups of future events on multiple timelines and then be able to selectively clear timelines or future events only on certain timelines.

**Comment by tambien** [comment]
Yes, there can only be one Transport and one timeline. But, Tone.Part/Sequence would give you similar abilities of creating multiple independently startable/stoppable/loopable timelines.

**Comment by tambien** [comment]
I think for now, I am going to leave it as a single Transport. The Transport, broadly speaking, is an abstraction around the AudioContext time scheduling, but adds the ability to start/stop/seek.

There are additional abstractions on top of the Transport like Tone.Part which provide similar capabilities to the Transport in terms of scheduling parts on independent timelines at different playback rates. There is also Tone.Clock which would allow you to schedule a repeated callback at various rates and ramp the frequency.

Introducing another Transport also makes all the tempo-relative encodings much more complex. For example, if you wrote `osc.frequency.value = "4n"`, which Transport's bpm would that "4n" be evaluated against?

**Comment by sfradkin** [comment]
I actually refactored my code to use Tone.Part after your comment above.  So, I agree.
