### ISSUE TITLE
I want to simulate the sound of sliding guitar strings. Is there a way to do that?

### ISSUE THREAD

**Issue by Shq123** [Tonejs/Tone.js#1087]
I wanted to make a sound that would slide on the guitar string while plucking it, but I couldn't find the right API

**Comment by tambien** [comment]
This would probably best be done with physical modeling which is outside the scope of this library, if you'd like a sample-based approach you can look at Tone.Sampler or Tone.Player. Maybe with the right samples, some timing and enveloping you can accomplish something similar without needing to synthesize it.
