### ISSUE TITLE
Envelope/Simplesynth is never silent

### ISSUE THREAD

**Issue by mcclure** [Tonejs/Tone.js#109]
I am interested in using tone.js to generate tones. However if I open your samples: 

http://tonejs.org/examples/envelope.html
http://tonejs.org/examples/simpleSynth.html

I notice the sound never stops. The moment I open each of these pages, I am able to hear a quiet tone in my headphones. If I play a sound by pressing the button in the envelope example or a key in the simplesynth example, I hear the oscillator become loud in the fashion I would expect if the sound is being played. But at the end of the tone it does not drop to zero, it just falls back to the quiet but persistent whining hum I heard at page open. I know this is not just sound card noise because in the simplesynth mode the whine is always the same frequency and timbre as the last note I played on the keyboard, so it is clearly just that the oscillator is playing and the envelope never brought it to zero, just near zero.

I do NOT hear the persistent hum in the "oscillator", "noise", "lfo" or "stepsequencer" demos. I DO hear the hum in the "monosynth" and "fmsynth" demos. In the polysynth demo I hear a polyphonic hum after I have played several notes.

I tested on Mac OS X 10.6.8. I tested in Chrome 47.0.2526.106 and Firefox 43.0.3 and got identical results (although there were additional sound quality artifacts in Firefox).

I obviously cannot use the tone.js synths in my app if they result in this background hum…

**Comment by tambien** [comment]
you're right! sorry i let this slip by. 

it's fixed on the dev branch and in the next release. and i added a test to validate the silence.

**Comment by mcclure** [comment]
Oh! That is great, that means I can use Tone for this project. I will try to test with the dev release.
