### ISSUE TITLE
How to fade in or fade out using GrainPlayer?

### ISSUE THREAD

**Issue by rtwalz** [Tonejs/Tone.js#1091]
Hello, new to Tone.js and it seems really powerful so far.

I'm trying to fade in an mp3 sample I'm loading using a GrainPlayer. [According to the docs](https://tonejs.github.io/docs/14.7.77/GrainPlayer), `fadeIn` or `fadeOut` properties don't exist on GrainPlayer. However, the regular `Player` class does have `fadeIn` and `fadeOut` properties. I need to use GrainPlayer because I want to control the playback rate while preserving pitch. How would I go about doing a nice fade-in with GrainPlayer? My initial solution is to slowly raise the volume manually every couple fractions of a second or so, but maybe someone else has a better idea.

**Comment by marcelblum** [comment]
The web audio api has native methods for doing this super smoothly which Tone exposes, check out `GrainPlayer.volume.rampTo(value, rampTime, startTime)` and more broadly https://developer.mozilla.org/en-US/docs/Web/API/AudioParam

**Comment by rtwalz** [comment]
Thank you! This is exactly what I was looking for.
