### ISSUE TITLE
Tone.Transport.scheduleRepeat cannot be disposed of until page-reload

### ISSUE THREAD

**Issue by Smashcat** [Tonejs/Tone.js#1095]
After using the scheduleRepeat function, attempting to use another scheduleRepeat in the same page will cause the previous version to tick, along with the new one. This throws an error about Start time must be strictly greater than previous start.

Example: https://jsfiddle.net/oabcdnm6/

**Expected behavior**
Should allow new values to be entered, and tones played, as they are the first time.

**What I've tried**
Tried initialising, clearing vars etc. Seems like some global vars are being stored in the Tone.js library and cannot be cleared until a page reload.

**Additional context**
Tried in Chrome and Firefox. Same result.

**Comment by dirkk0** [comment]
The demo doesn't work for me.

Something that helped me in a similar situation was using `transport.cancel(0)` which cancels all scheduleRepeats.
https://tonejs.github.io/docs/14.7.77/Transport#cancel

**Comment by abswiz** [comment]
Hey, I think you can also make a note of the eventId for the scheduleRepeat and individually clear it using transport.clear(eventId)
