### ISSUE TITLE
Polyphony for sampler?

### ISSUE THREAD

**Issue by cryptozachary** [Tonejs/Tone.js#1100]
Hello all I've been unsuccessful at determining how to implement a polyphony of 1 for the sampler instrument ( only one note plays at a time ). Is there a property for this? Or a way to check if the sampler is playing a note?

**Comment by 6dyAllen** [comment]
maybe you can release the note before play it

**Comment by cryptozachary** [comment]
Thank you - I will try that!

**Comment by cryptozachary** [comment]
This worked - I just had to change the triggerAttackRelease to triggerAttack , and it would release all currently playing notes. Unfortunately , this workaround does not allow me to set the duration of the note , as it seems to be only set with triggerAttackRelease. Hopefully I can solve this particular problem. Thanks for your help Allen!
