### ISSUE TITLE
Audio crackling using bluetooth devices when switching out of the browser app on Android devices.

### ISSUE THREAD

**Issue by andrewsrichardson** [Tonejs/Tone.js#1104]
Hey 👋

**Describe the bug**

When playing audio on Android Chrome and listening via a connected bluetooth device, switching apps or locking the phone will cause crackling in the audio. The crackling is constant, rather than pops or clicks. After around 30s, the audio will stop, presumably from some sort of crash, but there is no audible change to prove this.

This happens with even the simplest synth implementation. 

Oddly, with no bluetooth device connected, this does not seem to happen.

**To Reproduce**

A reproducable sandbox is [here](https://codesandbox.io/s/tonejs-forked-m0hxhq?file=/src/index.js). Connect to a bluetooth device. Press play on the sound, the switch apps from Chrome to anything other app, or lock the phone.

Phones tested are Pixel 2XL and Samsung Note 10. It doesnt seem specific to any bluetooth device. 

**Expected behavior**
Switching apps does not degrade the performance while using bluetooth devices.

**What I've tried**
Doesn't seem to be a regular performance issue as this never happes while staying in the chrome app. Similarly, without a connected bluetooth device, I seem to be able to run this without issue.

I have tried using a Tone Context with a latencyHint of  'playback', to no avail.

**Additional context**
While I only named 2 devices, this seems like it could be fairly widespread, as I have had a couple of reports of the same bug.

**Comment by chrisguttandin** [comment]
Hi @andrewsrichardson, I vaguely remember that there were a couple of issues with certain Chrome / Bluetooth speakers combinations in the past. Could you try to play some audio with the Web Audio API to see if the problem persists? I guess a single Oscillator should be enough to trigger the bug.

Does your example work as expected in Firefox?

**Comment by andrewsrichardson** [comment]
hey Chris

I tried the Web Audio API with Chrome (updated the [sandbox](https://codesandbox.io/s/tonejs-forked-m0hxhq?file=/src/index.js:51-381)) and the issue does indeed persist.

Oddly, I checked Firefox, and the issue does not persist using either Tone.js or the Web Audio API.

So I decided to also test Opera and Brave browser, both of which also produce the crackling issue for both Tone.js and the Web Audio API.

**Comment by chrisguttandin** [comment]
Thanks for checking this. I think it makes sense that Chrome, Opera and Brave have the same bug since they are all based on Chromium these days. Firefox has its own browser engine.

Maybe it's better to report this on Chromium's bug tracker. https://new.crbug.com/

**Comment by andrewsrichardson** [comment]
Thanks for the direction Chris - I have opened a bug in the Chromium bug tracker [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1349822).

Happy to close this ticket!
