### ISSUE TITLE
Unable to 'connect' Filter to a Player.

### ISSUE THREAD

**Issue by aMadReason** [Tonejs/Tone.js#1105]
Unable to 'connect' Filter to a Player.

Referencing the docs here: [https://tonejs.github.io/docs/14.7.77/Filter](https://tonejs.github.io/docs/14.7.77/Filter) I should be able to 'connect' a lowpass filter to a player, but it doesn't seem to apply.

I can only apply the filter using chain. Is this a bug or am I doing something stupid?

**To Reproduce**

[https://codesandbox.io/s/sound-player-b3ujv8?file=/src/index.js](https://codesandbox.io/s/sound-player-b3ujv8?file=/src/index.js)

**Expected behavior**
I expect to be able to connect and disconnect a filter to a player while that player is started.

**What I've tried**
I can get it working using chain, but that doesn't let me disconnect only the filter from the player.

**Additional context**
Using 14.7.77

Sorry if I've misunderstood something.

**Comment by petethomasmusique** [comment]
Evening!

It looks like you're connecting your filter to the output, and the player itself - which results in it sounding like the filter has no effect.

This should work
```js
const player = track2;
const filter = new Tone.Filter(300, "lowpass").toDestination(); // you've connected your filter to your destination
player.connect(filter) // so there's no need to connect your player there as well
```

Hope that helps!

**Comment by aMadReason** [comment]
Haha, had a feeling I was doing something stupid. Thanks!!
