### ISSUE TITLE
Uncaught TypeError when calling `remove` on a sequence

### ISSUE THREAD

**Issue by scottwhudson** [Tonejs/Tone.js#1106]
**Describe the bug**

According to the [docs](https://tonejs.github.io/docs/r11/Sequence#remove), I should be able to remove an event from an existing sequence using the `remove` function. However, calling `remove` on an existing sequence returns an Uncaught TypeError

**To Reproduce**

Here is a [Svelte REPL](https://svelte.dev/repl/6a1592c099d548658e316a6c8a2b68e8?version=3.49.0) of the issue. I initialize a basic sequence and bind a "Remove Element" button that tries and fails to remove the 3rd element from the sequence. 

**Expected behavior**
I expect to be able to remove events from an existing sequence using this function.

**What I've tried**
I've logged the sequence object to the console and inspected its available methods. A few others seem to be missing that are referenced in the documentation.

**Comment by chrisguttandin** [comment]
Hi @scottwhudson,

the docs that you linked to are for v11. The [current version](https://tonejs.github.io/docs/14.7.77/Sequence) doesn't seem to provide this function anymore. I'm not sure when it was dropped.
