### ISSUE TITLE
How can I add instrument sounds which are not available in the library?

### ISSUE THREAD

**Issue by shivrajsa** [Tonejs/Tone.js#111]
I am exploring this library, I want sounds of Tabla instrument (Tabla : indian classical music instrument), I have soundfont file for the same instrument, how can I use my instrument in tone.js.

**Comment by tambien** [comment]
There's a few ways to do this. You could make an individual Tone.Player for each of the samples. 

```javascript
var C4 = new Tone.Player("path/to/C4.mp3").toMaster();
var CSharp4 = new Tone.Player("path/to/C#4.mp3").toMaster();
```

Another way to do this would be to load all of the urls into an object of Tone.Buffers: 

```javascript
var tablaBuffers = {
  "C4" : new Tone.Buffer("path/to/C4.mp3"),
  "C#4" : new Tone.Buffer("path/to/C#4.mp3"),
  ...
}
```

And then set a single Tone.Player's buffer before starting the sound:

```javascript
//set retrigger to true to be able to trigger a sample 
//before the previous one has finished playing
var player = new Tone.Player({
  retrigger : true
}).toMaster(); 

function triggerNote(noteName, time){
  player.buffer = tablaBuffers[noteName];
  player.start(time);
}

//play C4
triggerNote("C4");
```

There are also a couple of libraries like [Midi.js](https://github.com/mudcube/MIDI.js) and [soundfont-Player](https://github.com/danigb/soundfont-player) made specifically for loading and playing soundfonts which you could use with Tone.js as long as you pass Tone's AudioContext (`Tone.context`) into their constructors.

**Comment by shivrajsa** [comment]
Thank you, It seems useful for me. I have developed a web application using MIDI.js for Indian classical music where user can write & play notations & tabla compositions. Playing part is achieved by MIDI.js. Here is link to my application 
http://vishwamohini.com/music/home.php

Currently user has to refresh the page to stop the melodies in my app because they are played though loop & not as MIDI file. So I am wondering if I can implement a player for MIDI.js when notes are played though loop. 

I am not professional developer, could you please share how to pass Tone's audio context into MIDI.js

**Comment by tambien** [comment]
It doesn't seem like MIDI.js' audio context is settable, so you can set Tone.js' audio context using MIDI.js. 

I think it should be as simple as this:

```javascript
Tone.setContext(MIDI.getContext());
```

Make sure you do this before creating any Tone.js objects since objects created after the context is set cannot be connected to objects created before. 

I hope that helps.

**Comment by shivrajsa** [comment]
I am trying to do as suggested but I don't understand how can I use this context further.
Because MIDI.js has its own noteOn & noteOff functions. Here is basic code.     
 
    `window.onload = function () {
	MIDI.loadPlugin({
		soundfontUrl: "./soundfont/",
		instrument: "acoustic_grand_piano",
		onprogress: function(state, progress) {
			console.log(state, progress);
		},
		onsuccess: function() {
			var test = Tone.setContext(MIDI.getContext());
			var delay = 0; // play one note every quarter second
			var note = 50; // the MIDI note
			var velocity = 127; // how hard the note hits
			// play the note
			MIDI.setVolume(0, 127);
			moog();
			MIDI.noteOn(0, note, velocity, delay);
			MIDI.noteOff(0, note, delay + 2);
		}
	});
    };`
