### ISSUE TITLE
fadeIn and fadeOut Based on Player Loop Size

### ISSUE THREAD

**Issue by abswiz** [Tonejs/Tone.js#1111]
**The feature you'd like**
Tone.Player appears to fadeIn and fadeOut based on the buffer size. A logical assumption would be that the fadeIn and fadeOut should work for a set loop... i.e. fadeIn at the start of the loop and fadeOut at the end of the loop. If no loop is set then the fadeIn and fadeOut working on the overall buffer makes sense.

**Any alternatives you've considered**
We have achieved by slicing the buffer to the loop size and resampling using an offline context where performance is not an issue. In realtime scenarios, we have used linearRampTo to automate the player volume.

**Comment by tambien** [comment]
The best way to do this would be to actually modify the buffer. You could apply the fade in/out directly to the buffer using something like [`Tone.Offline`](https://tonejs.github.io/docs/14.7.77/fn/Offline) and then use that buffer in your player. 

```ts
const fadedAudioBuffer = await Tone.Offline(() => {
  const player = new Tone.Player(originalBuffer).toDestination();
  player.fadeIn = 0.1;
  player.fadeOut = 0.1;
  player.start(0);
}, originalBuffer.duration)

// fadedAudioBuffer is the same as originalBuffer but with fadeIn/Out baked in
const player = new Tone.Player(fadedAudioBuffer)
player.loop = true;
```

The reason that i suggest doing it this way is that the functionality is not easily achievable in the Tone.js code code. There is no callback at the loop points so there's no way to apply a gain envelope at those points.
