### ISSUE TITLE
Feedback When maxPolyphony Is Exceeded

### ISSUE THREAD

**Issue by abswiz** [Tonejs/Tone.js#1112]
**The feature you'd like**
The PolySynth appears pretty resource hungry. A console log is produced when maxPolyphony is exceeded and the sound seems to just cut out. Can this log also be raised as an exception or sent via same callback? This would be useful for end users when providing some context on the system load.

**Comment by tambien** [comment]
Currently it defaults to a `maxPolyphony` of 32. After that, all notes will be silenced. If you'd like to raise the max polyphony, you can pass in a greater value in the constructor.

something like this should work:

```ts
const synth = new PolySynth({maxPolyphony: 64});
```

**Comment by abswiz** [comment]
That's great ... it helps ... and very useful to know. Thank you :)
