### ISSUE TITLE
[CI] Codecov report for `PatternGenerator.ts` file is not deterministic

### ISSUE THREAD

**Issue by satelllte** [Tonejs/Tone.js#1123]
## Please note
**_The bug is not related to the library itself, but rather the tests / CI._**

## Describe the bug

Just opened 3 pull requests with documentation updates, but the code coverage report of `PatternGenerator.ts` was not deterministic.

Failed code coverage report reference: https://app.codecov.io/gh/Tonejs/Tone.js/pull/1120

In these 2 pull requests it failed:
- https://github.com/Tonejs/Tone.js/pull/1120
- https://github.com/Tonejs/Tone.js/pull/1121

This pull request passed:
- https://github.com/Tonejs/Tone.js/pull/1122

<img width="876" alt="image" src="https://user-images.githubusercontent.com/20585619/192580527-8b5ededc-18d4-4ff8-9417-50f632be0a72.png">

## Expected behavior

Code coverage CI tests must be deterministic.

**Comment by satelllte** [comment]
The problem can only be fixed on re-triggering the CI run, for example pushing the empty commit made via `git commit -m 'trigger CI' --allow-empty`. For reference: https://github.com/Tonejs/Tone.js/pull/1121

**Comment by tambien** [comment]
yeah i've noticed that too. probably because there is some randomness in one of the pattern types. I've updated the codecov config to not throw an error when the coverage value changes so slightly
