### ISSUE TITLE
Question: Wiki edit permissions

### ISSUE THREAD

**Issue by satelllte** [Tonejs/Tone.js#1124]
## Question

What's the permissions to edit [Wiki](https://github.com/Tonejs/Tone.js/wiki)? It seems like **anyone** can edit them. Is it fine?

I just made a couple of updates and it allowed me to do this without any review:

- https://github.com/Tonejs/Tone.js/wiki/Connections/_compare/945b16b8553ebced210eb43e299149d6bd69ae72
- https://github.com/Tonejs/Tone.js/wiki/Using-Tone.js-with-React-React-Typescript-or-Vue/_compare/4cbde206948a3eac8cf9c8a48a4050ce9d9a9877
- https://github.com/Tonejs/Tone.js/wiki/TransportTime/96044ae06f4cd58e678a010f988a443647020a18

Please, consider putting some restrictions. Thanks!

**Comment by tambien** [comment]
done! thanks for the heads up and thanks for the edits!
