### ISSUE TITLE
Sequence inaccurate with midi play note

### ISSUE THREAD

**Issue by karkovich** [Tonejs/Tone.js#1130]
**Describe the bug**

wrote simple Sequence that play note every quarter.
the ```synth.triggerAttackRelease``` sounds like it played accurate
however the ```WebMidi.outputs[0].channels[1].playNote``` played inaccurate.

[ ](https://codesandbox.io/s/strange-sunset-8f5or7?file=/src/App.tsx)

**To Reproduce**

I use Ableton/LogicPro/Cubase with midi channel to receive the note and play sample (kick)

**Expected behavior**
played same like the synth

**Comment by ceelian** [comment]
Have you tried to schedule the midi events to be on the exact time like the tone scheduler? Like so: https://webmidijs.org/docs/getting-started/basics#schedule-notes
