### ISSUE TITLE
How to export a song after slowing it down and adding reverb to it?

### ISSUE THREAD

**Issue by Muhammed-Rajab** [Tonejs/Tone.js#1134]
Hey there!

I've been working on this small slowed-reverb music maker project. It basically takes a URL of a song, slows it down, adds reverb to it and export it. I've never worked on a project like this, which includes audio manipulation, etc. After doing some research I found out that I could slow down the song by changing the `playbackRate` on the `Player` instance. I also managed to add reverb to the song. But now I'm facing a serious issue. I need to find out some way to export the modified song into a local format (WAV, MP3, etc). I've searched a lot and I've come across a few libraries like `Recorder.js` and even the recorder provided by `Tone.js`. But this isn't what I want. I want to apply effects to the song and export it, not to record it. Is there any way that I could  achieve this using Tone.js. I know I'm missing a lot of details. A big sorry from my side. I've no knowledge in the field of audio manipulation and `Tone.js` one of the very few libraries that I've found with such great documentation for doing the stuff that I want to. If you want any clarification, let me know. It would be amazing if you guys could help me with this!

**Comment by dirkk0** [comment]
There is no export. The proper way to do this would be to [offline render](https://tonejs.github.io/docs/14.7.58/fn/Offline) the song, but this involves coding and is not easy to do.
A faster and easier fix would be to install something like [Audacity](https://www.audacityteam.org/) and record the output of your machine to a file.

**Comment by jdanford** [comment]
@Muhammed-Rajab you can try using a [Recorder](https://tonejs.github.io/docs/14.7.77/Recorder)
