### ISSUE TITLE
Tone.Transport: process single occurrence events before repeated events

### ISSUE THREAD

**Issue by hiddedejong** [Tonejs/Tone.js#114]
In my specific case, most of the time a single occurrence event does something with repeated events. For instance, scheduling a change of looping parts. Right now, because single occurrence events are processed after repeated events, looping parts will fire their first events, after which the correct part is started.

I'm interested in how you use the single and repeated events, and if it's possible to schedule single occurrence events before repeated events.

Thanks!

**Comment by tambien** [comment]
You bring up a good point. I'm happy to switch that around. So the best processing order is probably `scheduleOnce` events, then `schedule` events and then `scheduleRepeat`.

**Comment by hiddedejong** [comment]
Sounds good!
