### ISSUE TITLE
Popping noises on triggerattackrelease with default SimpleSynth

### ISSUE THREAD

**Issue by mcclure** [Tonejs/Tone.js#116]
[Here is a demo program](http://vote.runhello.com/j/dryad-proto/tone-pop-demo/):
[Here is its source code](https://bitbucket.org/runhello/dryad-artifact/src/3f87fc62bf5368b66f97b9f25c4555ddef28afd4) and [here is the main source file](https://bitbucket.org/runhello/dryad-artifact/src/3f87fc62bf5368b66f97b9f25c4555ddef28afd4/src/app.tsx?at=default&fileviewer=file-view-default) (commit 3f87fc62b)
The test program is using tone 0.6.1 from the website. I test on Chrome 48.0.2564.97 and Firefox 43.0.4 on Mac OS X 10.6.8. (I upgraded to Firefox 44.0 after writing this bug and there were no changes in behavior.)
Click "type here" and type. Each keypress issues a triggerAttackRelease on a PolySynth with 2-polyphony and two SimpleSynths. (A test using one SimpleSynth and no PolySynth resulted in similar behavior.)

When a note issues, I hear a sharp, unpleasant popping noise at the start of the sound play. The sound happens only occasionally (every few seconds) on Chrome but happens on every single trigger on FireFox. 

I captured the output of my sound card. If I analyze the waveform at the point of a pop, I find that at the start of a sound, immediately before the attack, there is a discontinuity, jumping up to a point lower than the normal peak of the waveform and then continuing as normal for the waveform. I do not know how SimpleSynth is implemented, but it looks to me as if the tone generator is not beginning at zero.

Please see [http://vote.runhello.com/j/dryad-proto/tone-bug-report/](http://vote.runhello.com/j/dryad-proto/tone-bug-report/), "pops-1-chrome" and "pops-2-firefox". Included for each test is a FLAC file (if you cannot open this let me know and I will upload a wav) and a screenshot of one discontinuity in a sound editor.

**Comment by mcclure** [comment]
Note: It is possible I am using SimpleSynth incorrectly somehow (for example, there is no attack) but if this is incorrect, maybe it should not be the default.

**Comment by cncocnco** [comment]
I've also discovered this issue and assumed I was doing something bad, but perhaps not. Have you been able to replicate this? 

My testing confirms that it's constant in Firefox. In Chrome and Opera it is less constant but frequent. Safari appears to be immune. I've tested several of the Tone.Monophonic descendants and they all seem to exhibit this behavior.

**Comment by tambien** [comment]
The Firefox popping noise is related to [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1257718) in scheduling ramps. Currently there is a discontinuity between the attack and decay phases. 

Discontinuities on Chrome and Safari should be fixed in r7-dev, but if either of you can create a minimal test case (in the form of a jsbin/jsfiddle or similar) that illustrates this bug, that would be very helpful for validating the latest changes.

**Comment by tambien** [comment]
Closing this issue since it's a few versions back. Hopefully it's fixed. Please reopen with an updated test case if it's not.
