### ISSUE TITLE
Woscope Integration

### ISSUE THREAD

**Issue by joex92** [Tonejs/Tone.js#1166]
**The feature you'd like**
More like a feature, I have a question. Can Tone.js be integrated with the [Woscope library](https://github.com/m1el/woscope)?
Apparently it just needs the Audio Element.

**Any alternatives you've considered**
I made [my own XY Oscilloscope](http://joex.apps.dj/xyosc) with Two.js and Tone.js. But I like Woscope functionality more than what I achieved.

**Additional context**
I'm trying to visualize audio in a XY Oscilloscope.

**Comment by tambien** [comment]
If it requires an audio element then maybe there's a way to get it to work with [MediaStreamAudioDestinationNode](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamAudioDestinationNode)
