### ISSUE TITLE
Where is the examples source codes ?

### ISSUE THREAD

**Issue by ambroiseRabier** [Tonejs/Tone.js#1183]
I'm trying to understand the library by looking at https://tonejs.github.io/examples/sampler , but there is only the webpack JS output in the examples folder. I am not finding the sources files in this repository.

HTML is here: https://github.com/Tonejs/Tone.js/blob/master/examples/sampler.html
Webpack output JS is here: https://github.com/Tonejs/Tone.js/tree/master/examples/js

**Comment by dirkk0** [comment]
Maybe I am understanding you wrong, but the source code is in the HTML file you linked to, everything in the script tag.
