### ISSUE TITLE
Can't set a new voice in Tone.PolySynth

### ISSUE THREAD

**Issue by durbanitas** [Tonejs/Tone.js#1191]
**Describe the bug**

I can't set a new voice (instrument) in a Tone.PolySynth

**To Reproduce**

```js
const polysynth = new Tone.PolySynth(Tone.Synth).toDestination()

const changeVoice = (newVoice) => {
  polysynth.voice = Tone[newVoice] // can't assign new voice
}

const playNotes = () => {
  polysynth.triggerAttackRelease(['A3', 'C5'], '8n')
}
```

```html
<button onclick="playNotes()">Play</button>

<button onclick="changeVoice('FMSynth')">FMSynth</button>
<button onclick="changeVoice('MetalSynth')">MetalSynth</button>
<button onclick="changeVoice('MembraneSynth')">MembraneSynth</button>
```

**Expected behavior**

I would expect that I can change the instrument `Tone.Synth` from this registration: new Tone.PolySynth(Tone.Synth).toDestination() into another voice/instrument afterwards, like `Tone.MetalSynth` or `Tone.MembraneSynth`

**What I've tried**

```js
polysynth.set({voice: newVoice})
```

```js
polysynth.synth = Tone[newVoice]
```

```js
polysynth.set({synth: newVoice})
```

**Additional context**

I didn't find an answer to this behavior in other forums so far.

**Comment by Pbotsaris** [comment]
I'm not an expert but `PolySynth < Voice >` doesn't have a public `voice` property. 

PolySynth is not a synth on its own but a manager of mono synths to achieve polyphony. Changing the voice means disposing of all the underlying synths. You might as well just initialize `Polysynth` again with the desired voice. If your concern is memory consumption, you can dispose of `PolySynth` before instantiating a new object.

```
const polysynth = new Tone.PolySynth(Tone.Synth).toDestination()

const changeVoice = (polySynth, newVoice) => {
  polySynth.dispose()
  return new Tone.PolySynth(newVoice).toDestination()
}
```

**Comment by durbanitas** [comment]
thanks @Pbotsaris . I will go with that. Thought I couldn't be possible, so this was my last hope to get a fix.
