### ISSUE TITLE
Synth as PolySynth with Filter and FilterEnvelope

### ISSUE THREAD

**Issue by toovy** [Tonejs/Tone.js#1202]
Looking at the basic Synth and other variations I cannot really see what is normal on HW synths and VSTs, having a filter that has its own envelope on the synth. Connecting a synth to a filter and triggering the filterEnvelope at the same time the synths triggerAttack is relatively simple and straightforward, easy to solve.

Still I wanted a PolySynth where each voice has its own filter and filterEnvelope. This seems not to be possible, without building it yourself, or am I missing something? I could not find any example and as this is so common in the world of synths I'm confused. In earlier Tone versions I found examples where you could pass a filter and filterEnvelope directly to a Synth, but I seems this feature was removed. Has this not been reimplemented?

So the way it might work would be to extend Synth, let's say created your own FilteredSynth, that connects to a filter, and overwrites triggerAttack to also trigger the filterEnvelope. Then I could pass this as voice into a PolySynth. Is this the way to go?

**Comment by tambien** [comment]
The MonoSynth is pretty much exactly what you're describing, it has a filter and a filter envelope which is triggered when a note is triggered. You can pass MonoSynth into the constructor of PolySynth in order to make it polyphonic
