### ISSUE TITLE
Tone.MultiChannelOutput status

### ISSUE THREAD

**Issue by andrejhronco** [Tonejs/Tone.js#1203]
`Tone.MultiChannelOutput` hasn't been worked on in ~4 years so I was wondering if this is no-longer being worked on / doesn't need any work. I've used it on a couple projects a while ago and it seemed to work well.

Will this become part of Tone's components?

**Comment by tambien** [comment]
I don't plan on supporting it as part of this core library, but it's a fairly simple component, so very possible that it still works after all this time. I don't think that part of the Web Audio API spec has changed at all.
