### ISSUE TITLE
Wavesurfer.js support

### ISSUE THREAD

**Issue by corysimmons** [Tonejs/Tone.js#1223]
**The feature you'd like**
I'd love to use Tone.js as the audio source of truth, and just use Wavesurfer.js for visualizing and scrubbing around a piece of audio. It'd be great if this were tightly integrated or an official plugin.

**Any alternatives you've considered**
I'm currently trying to implement it myself but it's pretty gross. I saw some issue from 4 years ago where they were trying to do something similar by feeding the Tone AudioBuffer into Wavesurfer.

**Additional context**
These two libraries seem like they'd go hand-in-hand.

**Comment by tambien** [comment]
I'm not familiar enough with wavesurfer.js to give much guidance here, but seems like it is probably possible if wavesurfer is build on the Web Audio API to pass the buffer from Tone.js like you're describing.
