### ISSUE TITLE
Question: CDN(HTTPS)

### ISSUE THREAD

**Issue by tgfjt** [Tonejs/Tone.js#123]
Hi :smiley: 

I'm just trying to play some examples at jsfiddle or something like that, but,
Do you have resource on CDN(HTTP**S** not HTTP)?

Anyway thank you for your gread work!

**Comment by tambien** [comment]
github pages will serve the file using SSL if you don't use the CNAME version:

https://tonejs.github.io/CDN/r6/Tone.js

**Comment by tgfjt** [comment]
Awesome! Thanks.
