### ISSUE TITLE
Tone.LFO Inconsistent Low Value

### ISSUE THREAD

**Issue by cncocnco** [Tonejs/Tone.js#125]
I'm experiencing strange behavior with Tone.LFO connected to Tone.Oscillator.detune. The following code does as expect, not changing the pitch of the Oscillator:

	var osc = new Tone.Oscillator(440, "triangle").toMaster().start();
	var lfo = new Tone.LFO({
			"type" : "square",
			"frequency" : 0.5,
			"min" : 0,
			"max" : 0
		}).connect(osc.detune).start();

But if you change the lfo.max value, the pitch of the oscillator when the LFO is at it's minimum value (lfo.min still set at 0) is changed as well, varying somewhat with the value of the lfo.max value. That is, if you set lfo.max to 100, the pitch of the oscillator when the LFO is low will be slightly out of tune and if you set the lfo.max to 1200, the pitch of the oscillator when the LFO is low will be offset by about a semitone.

Is this a bug, or am I doing something wrong?

**Comment by tambien** [comment]
It's kind of neither a bug nor something you're doing wrong. I think it has to do with square-wave approximations.

While an ideal square-wave modulates ±1, which is the behavior that you're expecting in which the extreme should go up the entire octave (when scaled to the max value), the Web Audio API square wave (and probably many others square wave implementations) only goes to somewhere around ±0.85. 

Here's a graph that i made recording the output of a sine wave and a square wave:

![Square Wave Amplitude](https://docs.google.com/drawings/d/130LoVjok7pcto-VTjtLx_ddCyWTyp0OjJYu5bN4vE94/pub?w=958&h=194)

You can see the peak position of the sine wave is ±1, whereas the square wave hits that peak, but then rests a bit lower. Judging by [this wikipedia article](https://en.wikipedia.org/wiki/Square_wave#Characteristics_of_imperfect_square_waves) that seems to be a reality of square wave approximations.

My best advice for fixing this approximation is scaling the `max` of your LFO to compensate for it. So you're max should be more like `1200 * (1 / 0.85)` which will make it closer to an octave.

I'm not sure if this is something that is fixable or normalizable in Tone.js itself or if this is a reality of non-ideal square waves in software. Perhaps someone who better understands implementations of square waves in Web Audio can chime in here.

**Comment by cncocnco** [comment]
Ah, of course, that make sense. Thanks!
