### ISSUE TITLE
Redundant encoding for the URL of the audio source

### ISSUE THREAD

**Issue by ziyuang** [Tonejs/Tone.js#1257]
**Describe the bug**

`Player` will always encode the passed-in URL.

CodeSandbox: https://codesandbox.io/p/devbox/polished-surf-3tzsmz

In the sandbox, you can see `<audio>` can play the file named `喝采　サンプル.mp3` normally, but `Tone.Player` cannot (after uncommenting `player.start()`). And inside `ToneAudioBuffer.load` you can see the requested URL is `%25E5%2596%259D%25E9%2587%2587%25E3%2580%2580%25E3%2582%25B5%25E3%2583%25B3%25E3%2583%2597%25E3%2583%25AB.mp3` --- essentially the `%` has become `%25`.

I will suggest providing an option to not encode the URL in `Player`'s constructor.

**Comment by tambien** [comment]
Could you try this with `tone@15.1.2`? I think the fix should be available there, if you can confirm that it's working ok for you, i can promote that version to `latest` in the near future

**Comment by ziyuang** [comment]
> Could you try this with `tone@15.1.2`? I think the fix should be available there, if you can confirm that it's working ok for you, i can promote that version to `latest` in the near future

I need to do a bit more to wait for the loaded flag after creating the player (I have multiple audio tracks and a video track that need synchronization so I cannot use `onload` directly), but otherwise it plays the audio as expected. Thanks.
