### ISSUE TITLE
PanVol not working with Player?

### ISSUE THREAD

**Issue by VolatileCoder** [Tonejs/Tone.js#1279]
**Describe the bug**

I have stereo MP3s. I'm trying to add stereo sound effects to my game. I'm trying to use PanVol to control the panning and volume in my game, but upon connecting the PanVol, nothing happens. 

**To Reproduce**

                var player = new Tone.Player(uri).toDestination();
                var panVol = new Tone.PanVol(-1, 0).toDestination();
                player.connect(panVol);
                player.autostart = true;

**Expected behavior**
Sound out of left channel only

Actual result: sound out of both channels.

**Comment by VolatileCoder** [comment]
I'm using Tone.js v14.8.49

**Comment by VolatileCoder** [comment]
Actually, when using PanVol with a Player, it ignores Volume as well.

**Comment by dirkk0** [comment]
I usually use the gain node to set the volume.

**Comment by VolatileCoder** [comment]
It's not the volume I'm concerned with as much as the left/right panning.

**Comment by dirkk0** [comment]
could you create a minimal codepen?

**Comment by VolatileCoder** [comment]
Okay, disregard. I was unable to reproduce this when creating a pen; it must be somewhere in my code.

**Comment by VolatileCoder** [comment]
Okay, re-opening. 

I think the issue is that I'm expecting a hard cut, and I'm still hearing audio out of the other channel. 

https://codepen.io/Mark-Milley/pen/BaXaRwq 

If I'm passing in -1, why do I hear any audio out of the right channel, for instance?

**Comment by marcelblum** [comment]
In your code above, you are connecting the Player to **both** the PanVol and Destination. That means you'd always be hearing some of the unaffected Player output directly through the Destination. Seems like you only want the Player connected to the PanVol. So removing the `.toDestination()` from your Player declaration should solve it.

**Comment by VolatileCoder** [comment]
Oh my goodness, that was it the whole time. Thank you so much!
