### ISSUE TITLE
Analyser `getFloatTimeDomainData` does not exist in Safari

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#129]
I'm not sure if it should be the responsibility of Tone.js to fix or warn/block against this, but apparently Safari's Analyser node does not have the `getFloatTimeDomainData` method. Which means that a `Tone.Analyser` with `returnType: 'float'` will fail on an `analyse()` call in Safari.

I've [created this demonstration](https://jsbin.com/zoboxeb/edit?js,console) that will break in Safari.

I have been unable to find any other wider-scale reference to this general Safari bug.

**Comment by JackCA** [comment]
fwiw, this polyfill appears to work well: https://github.com/mohayonao/get-float-time-domain-data

**Comment by SevenSystems** [comment]
> fwiw, this polyfill appears to work well: https://github.com/mohayonao/get-float-time-domain-data

That polyfill can't deal with values beyond -1..1, because they're clamped to 0..255 inside the WebKit code. There's currently no way to get at the actual unclamped waveform at all.

**Comment by ianmcqueen** [comment]
@SevenSystems possibly related WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=190349

**Comment by lbrdar** [comment]
Hey guys, any update on this? 
@SevenSystems what do you mean by "polyfill can't deal with values beyond -1..1", doesn't `getFloatTimeDomainData` always return values from that range anyway?

**Comment by SevenSystems** [comment]
> @SevenSystems what do you mean by "polyfill can't deal with values beyond -1..1", doesn't `getFloatTimeDomainData` always return values from that range anyway?

I highly doubt it, because internally, audio can be at any amplitude and thus any float value. Only the final output stage is between -1..1. That's actually the main reason why getByteTimeDomainData is useless. It's clamped to an arbitrary range.
