### ISSUE TITLE
Distortion on Mobile Safari

### ISSUE THREAD

**Issue by damonholzborn** [Tonejs/Tone.js#134]
I've noticed problems on Mobile safari. On any Tone app I've tried, including the Tone.js examples, the first time a page loads the audio will be distorted. After reloading the page, everything works fine. This seems to only happen when using the internal speaker. I've tested it without issues via the headphone jack, Bluetooth and AirPlay.

I've experienced this on on an iPhone 6plus/iOS 9.3, iPhone 5s/iOS 9.3, and  iPad Mini 1/iOS 8.3. My iPad Air 2/iOS 9.3, however, works fine. Chrome on iOS also seems to be fine (which is strange since Apple forces all browsers to use their JavaScript engine...).

**Comment by markmarijnissen** [comment]
Perhaps a case of the iOS Samplerate bug? Can you check the sample rate of the context?

fix is here: https://github.com/Jam3/ios-safe-audio-context

**Comment by tambien** [comment]
Seems like more of a Safari / Web Audio bug than a Tone.js one. Maybe [file a bug](https://bugreport.apple.com/) with Safari.
