### ISSUE TITLE
player should allow start and endpoints when not looped

### ISSUE THREAD

**Issue by autotel** [Tonejs/Tone.js#136]
The sample player element is awesome as everything in tone js. The only that doesn't make sense is that only allows start and end points when looped. These would be also handy to use when the sample is not looped.

Some more context: I was making a sample trigger using the Nexus UI waveform element. The idea was to make a sort of bootleg drum machine & sampler with this, and would have been great being able to control these sample starting and end points. It would have worked almost as it is in the example if disabling the loop option didn't disable the start and endpoints with it.

![image](https://cloud.githubusercontent.com/assets/15053243/14404885/1abe9ae4-fe8a-11e5-8040-453518f703fe.png)

I sought in the library guts, but I am not that expert in Js.

thanks for this awesome library!

**Comment by tambien** [comment]
Thanks for the issue. This is currently possible (since version 1), I just keep forgetting to add it to the documentation. I just made that change and it will be reflected in the next version. 

The second argument to `start` is the offset and the third argument is the duration.
