### ISSUE TITLE
Is there a way to get less latency out of it?

### ISSUE THREAD

**Issue by DeerMichel** [Tonejs/Tone.js#138]
I have to admit, that current latency is really good - but while playing guitar and put effects on it (also without effects), you can definitely hear the latency. Is there kind of a buffer size property or do we have to wait for better browsers?

**Comment by tambien** [comment]
There's [a great article](http://padenot.github.io/web-audio-perf/#latency) by @padenot about various audio nodes' latency and performance. Generally, latency is going to vary across OSes and there's not a whole lot which is configurable at the moment, though they are adding some [user configurable settings](http://webaudio.github.io/web-audio-api/#idl-def-AudioContextPlaybackCategory) in the Web Audio specification.
