### ISSUE TITLE
Glissando support?

### ISSUE THREAD

**Issue by nickjohnson-dev** [Tonejs/Tone.js#140]
I'm using Tone in the creation of a step sequencer application, and I need to allow one or more glissandos while playing a note. E.g. triggering an attack on C3, gliding over a whole note to E3, and then gliding to G3 over an eighth note, then finally triggering the release.

Currently I'm using passing the notes in my sequence to the triggerAttack/triggerRelease methods of a PolySynth, and I've been unable to find an obvious mechanism of gliding between notes without triggering a separate attack for each new pitch.

I'd love to know how to implement the glissando effect, regardless of the complexity, but would really love to see a simple way of representing it, similar to the array of notes used in generating a chord.

As an aside, thanks for such a spectacular library. It's been exceedingly easy to work with, and barring this one roadblock, I've been able to implement all of the behavior I need just from reading the documentation.

EDIT: I see now that a google group has been opened up for questions like this, so I'll close this issue out if anyone finds it objectionable.

**Comment by tambien** [comment]
I think the easiest way to accomplish this would be to use the synth's `frequency` signal. This is easier to demonstrate with a Monophonic synth. 

`frequency` is a signal and so it's capable of signal automation including ramping. When you do a ramp, you typically need to set an anchor with the current value at the beginning of the ramp and then schedule the ramp like this:

```javascript
var synth = new SimpleSynth().toMaster();
//when the 3 notes should start playing
var startTime = synth.now();

//trigger the envelope start on "C3"
synth.triggerAttack("C3");
//set a ramping anchor point at the beginning ramp
synth.frequency.setValueAtTime("C3", startTime + 1)
//ramp to E3
synth.frequency.exponentialRampToValueAtTime("E3", startTime + 1.5)
synth.frequency.setValueAtTime("E3", startTime + 2)
synth.frequency.exponentialRampToValueAtTime("G3", startTime + 2.5)
//trigger the release of the envelope at the end
synth.triggerRelease(startTime + 3);
```

Another way to do this (again not with PolySynth) is to use `setNote` which will change the frequency value without retriggering the envelope. Then set the synth's `portamento` to your desired glide time.

To do the above with PolySynth, you can just take one of the voices from the `.voices` array and do the same thing that i showed above.

**Comment by nickjohnson-dev** [comment]
Thanks for the great example. This is exactly what I was looking for!

I had played with ramping the frequency, but I had missed the part about setting anchor points and I think that's what made it seem not to work.

Is there a way to grab one of the voices from a PolySynth and be guaranteed it isn't already busy playing a note? I noticed there was an internal collection of active voices, but never saw it populated whenever I tried logging it.

**Comment by christophejourdan** [comment]
Hi,

@tambien, thank you for your example, but is there a way to achieve a glissando into a sequence?

**Comment by tambien** [comment]
@christophejourdan you could do the exact same thing as above, but instead of `var startTime = synth.now()`, just use the time that is passed in by the sequence callback. schedule the current value with `setRampPoint(time)` and then the `exponentialRampToValueAtTime(note, time + glissTime)`
