### ISSUE TITLE
Tone.Transport progresses silently in the background when paused

### ISSUE THREAD

**Issue by taylorbf** [Tonejs/Tone.js#145]
Loving the improvements in r7!

I'm encountering one bug, though. I am using `Tone.Transport` and visualizing `Tone.Transport.position` in a DAW-like GUI, and the Transport doesn't work as expected.

When I call `Tone.Transport.pause()`, the `position` pauses in place as it should. However, when I wait a few seconds and then call `Tone.Transport.start()`, I see that the Transport jumps ahead several bars. It has been silently progressing in the background, I guess?

No scheduled events are called while it is paused. But the Transport does not start where it was paused, it starts many bars later (depending on how long I waited before calling `Tone.Transport.start()` again). I've tested the identical page with r6 and don't encounter this.

**Comment by tambien** [comment]
You're absolutely right! The ticks don't incrementing while paused, but after it's restarted it catches up to where it left off and all the callbacks are invoked for that catch up period.

I just pushed a change which should fix that. i'll edit the release to include this change shortly.
