### ISSUE TITLE
Custom Instrument

### ISSUE THREAD

**Issue by yukulele** [Tonejs/Tone.js#148]
Is it possible to add custom instrument or effect?

**Comment by tambien** [comment]
It's not really a feature right now. You could extend the base Tone.Instrument class and implement `triggerAttack` and `triggerRelease` which would give you all the functionality of an instrument and the internal routing. Same with Tone.Effect: if you extend that base class and connect up `effectSend` to your effect and then through `effectReturn` it'll give you the wet/dry functionality. 

I will look into exposing this on a higher level which would simplify the process. And at the very least  document it in a wiki for anyone who wants to try making their own.

**Comment by tbazin** [comment]
Hi!
Some years down the road, would you consider making the Tone.Instrument abstract class accessible? At the moment it is not exported within Tone/instrument/index.ts.
I have an instrument toggle within an interactive sequencer, and it would be convenient to be able to properly type the returned instruments as Tone.Instrument objects with proper duck typing.

The change is obviously trivial and In could submit a PR, but I could also understand if you think that exposing this abstract class could confuse less code-savvy users 🙂.

**Comment by tambien** [comment]
@tbazin You can access the base class at [Tone/instrument/Instrument.ts](https://github.com/Tonejs/Tone.js/blob/dev/Tone/instrument/Instrument.ts). I don't export it to the top level because, like you mentioned, i have had people confused in the past when they tried to instantiate Tone.Instrument and it didn't make any sound.

**Comment by tbazin** [comment]
OK, right, I was doing that already, I'll just stick to that then.
(Directly importing it just seemed to bother my linters and type-checks a bit, which started to report some errors for Tone.js like it was some code of my own, but I'll double-check my configurations then and fix that issue on my side.)

Thanks for your answer and sorry for the somewhat obvious question!



________________________________
