### ISSUE TITLE
Synth error 'Tone.TimeBase'

### ISSUE THREAD

**Issue by evejweinberg** [Tonejs/Tone.js#153]
Updated to Tone v7 and getting this error: 

Tone7.min.js:7 
Uncaught SyntaxError: Tone.TimeBase: Unexpected token "D3"

**Comment by evejweinberg** [comment]
oh shoot. fixed. I was calling the argument dynamically, and called a 'D' instead of 'D4'

**Comment by tambien** [comment]
Hi Eve!

looks like you might be adding an unnecessary quote to the string. could you try removing "\"" at the beginning and the end of your string concatenation where you generate the note and see if that fixes it?

it seems like you're passing in "\"D3\"" instead of just "D3".
