### ISSUE TITLE
Behavior of Source.sync() and Transport seeking

### ISSUE THREAD

**Issue by taylorbf** [Tonejs/Tone.js#154]
I have a question about the intended design of Source.sync() and the Tone.Transport. This is not a bug, but a more general comment / proposal.

Source.sync( [delay] ) states that the delay argument means "Delay time before starting the source after the Transport has started." As I understand it, this means that each time the transport is started, the source will start N measures after the transport is started, no matter what the transport's current position is. This works well for starting the transport at position 0:0:0 and never stopping it, but if the transport is paused and restarted, it doesn't work as I would expect.

Case:
* A Tone.Player is created using a long source sample (1 minute long).
* The player is synced to the the transport with delay of 1 measure:  `player.sync('1m')`
* The Transport is started. `Tone.Transport.start()` 
* After 1 measure, the player is triggered and starts to play.
* After another measure, the Transport is paused. The player also pauses, mid-playback.
* The Transport starts again from its current position (2:0:0).

Current resolution of this case:
* We will hear silence for 1 measure
* 1 measure after the Transport starts (now 3:0:0), the player will be triggered again from the beginning of the source.

Is this intended?

I expected a different resolution:
* The player starts back up at the location that it was paused.

With the current design -- and I may be misusing the design -- there is not an effective way to schedule audio files on a virtual timeline, seek to a certain point in the timeline, and have all audio files start relative to their location on the virtual timeline (i.e. start in the middle of the audio clip, if necessary).

If this new use case is desired, I think it could be accomplished by editing `Source._syncStart()` to schedule the clip relative to `Tone.Transport.position`, and adjust the starttime offset if necessary:

```
this._syncStart = function (time, offset) {
	   
    var delayFromNow = this.toSeconds(this._startDelay) - this.toSeconds(Tone.Transport.position)

    if (delayFromNow<0) {
        offset = Math.abs(delayFromNow)
        delayFromNow = 0
    } else {
        offset = 0
    }

    time += delayFromNow
    this.start(time, offset)

}.bind(this);
```

Then a `Tone.Transport.seek()` method could be created to handle the stopping and starting of audio files when jumping through the transport timeline. This would replace the current method of setting Tone.Transport.position to a new value.

```
Tone.Transport.prototype.seek = function (time) {

    if (this.state=="started") {
        this.trigger('stop',this.toSeconds("+0"))
    }

    this.position = time

    if (this.state=="started") {
        this.trigger('start',this.toSeconds("+0"))
    }

};
```

Called by: `Tone.Transport.seek('2:0:0')`

I have not sent this as a PR because it changes the design of the Transport and `.sync()`, and I'm not sure if the new design is desired. I also haven't tested it with looping and other features. But I raise it as a potential design direction for syncing to the transport in a way more similar to a virtual DAW paradigm.

**Comment by tambien** [comment]
Hi Taylor. 

Your use-case is definitely the goal of `sync`. I was going for a DAW-style API here. I think your described solution could work for this. I was also considering maybe using `Transport.schedule` to do this syncing...

Please submit a PR on the `dev` branch. I was definitely planning on looking into this further for r8. 

I think my ideal API for this is if `sync` is a state change and subsequent calls to `start` and `stop` after the Source is synced, would be synchronized to the Transport: 

for example: `player.sync().start(0).stop("2m").start("4m")` where all the time values are relative to the Transport position. Then calls to `Transport.seek` or `start` would also start the Source in the right position.
