### ISSUE TITLE
Ability to Prevent Version Console Logging

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#155]
While I love promoting Tone.js in production environments, it would be nice to be able to configure Tone.js to *not* emit the version log in certain scenarios like a test environment where it can cause pollution in test runner logs.

@tambien are you open to allowing this? I can make a PR if you okay the concept.

**Comment by tambien** [comment]
I'm open to it. How would you do it? It's part of an immediately invoked function so there's no point to do a config before...

**Comment by JackCA** [comment]
@tambien I think the only way to do it would be to look at a var on `window` like `window.TONE_SILENCE_VERSION_LOGGING = true` which means I would have to make that assignment before Tone itself is included.

What do you think?

**Comment by tambien** [comment]
sure. that seems reasonable.
