### ISSUE TITLE
Officially maintained on npm?

### ISSUE THREAD

**Issue by kennynaoh** [Tonejs/Tone.js#158]
Hello @tambien ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
I want to ask whether this library is officially maintained on [npm](https://www.npmjs.com/package/tone)?
Please help me confirm that.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8475

**Comment by tambien** [comment]
thanks @kennynaoh! it'd be great to host Tone on cdnjs. i do keep npm up to date with all the releases.

**Comment by kennynaoh** [comment]
Hello @tambien ,
So I think [this website](https://www.npmjs.com/package/tone) is not officially maintained by yours, is it?
If not, I will add this library on [github](https://github.com/Tonejs/Tone.js) first.
Thanks!

**Comment by tambien** [comment]
yes. that's the npm package name that i registered. the `tone` npm package is kept up to date with all the Tone.js releases.

**Comment by kennynaoh** [comment]
Hello @tambien ,
Sorry for late reply.
I found that the version naming scheme on npm and github is totally different.
Because we also need to add old versions.
So I want to confirm that are versions on npm and github the same?
Thanks!

**Comment by tambien** [comment]
@kennynaoh yeah, i use whole number releases but npm wants semantic versioning. so Tone.js r7 would be 0.7.0 on npm (or 0.7.1 after i released a small patch). but they are maintained the same in both places.

**Comment by kennynaoh** [comment]
Thanks @tambien

**Comment by tambien** [comment]
@kennynaoh When can we expect it to be posted on cdnjs.org?

**Comment by kennynaoh** [comment]
We have added this on [cdnjs](https://cdnjs.com/libraries/tone).
Thanks!

**Comment by tambien** [comment]
Awesome!
