### ISSUE TITLE
Events on Trasnport State Change

### ISSUE THREAD

**Issue by patorpey** [Tonejs/Tone.js#159]
Being able to listen for changes in Transport state would be useful, but I haven't found a simple way to do this.

Presently, Tone.Transport fires events "start", "pause", and "stop" at the time that the `Transport.start()` and `Transport.stop()` methods are called, rather than at the time they are scheduled for. Perhaps a different set of event names could be triggered when the changes in playback state actually occur or an event that reports that `Transport.state` has changed.

A workaround is to schedule callbacks or Events at the same times as the start and stop. (This is essentially what's already happening on Clock's internal `_state` Timeline.) However, this requires providing a callback to both the events scheduled on Transport and any user interaction or code that can start, stop, or pause Transport other than scheduled playback.

**Comment by tambien** [comment]
Good point. i can take care of this for r8. i should be pretty easy to do using `Transport.schedule`
