### ISSUE TITLE
Unlocking iOS audio

### ISSUE THREAD

**Issue by AnthonyArtmann** [Tonejs/Tone.js#164]
This library is awesome but I can't work out how you are unlocking iOS audio in the examples.

**Comment by tambien** [comment]
I wrote a small lib which listens for valid user actions and then plays a silent sound. 

https://github.com/tambien/StartAudioContext

That's what i use in the examples. I hope that helps.

**Comment by clhenrick** [comment]
@tambien I'm trying [your oscillator example](https://tonejs.github.io/examples/#oscillator) on my iPhone and after clicking the "enter" button to enable the audio context the oscillator still produces no sound. I've been stumped trying to figure out how to enable an oscillator on Safari iOS. Do you have an example that you know works for you? Thanks in advance.

**Comment by lucasomigli** [comment]
@clhenrick works fine on safari iOS on my iPhone 6... does it happen on other examples as well?

**Comment by tambien** [comment]
@clhenrick I believe this is changed in the more recent iOS, but older iOS versions require that you turn your phone off of silent mode.

**Comment by clhenrick** [comment]
@tambien @lucasomigli thank you that was totally it, I had my phone ringer turned off / in silent mode. Seems strange to me that would disable the Web Audio API yet still allow `<audio>` with an MP3 source to work.

**Comment by tambien** [comment]
@clhenrick yeah it is weird! i think there is some discussion on the Web Audio specification to define this behavior and make it more consistent.

**Comment by MichaelShingo** [comment]
If you want to be able to play Tone.js sounds even when the device is muted, here what you can do. My solution was to play a silent mp3 on user interaction, using a native HTML audio element to activate the sound. I do this before playing the sound that I actually want to hear.

```
    <audio>
    	<source src="/silent.mp3" type="audio/mp3"></source>
    </audio>
```


You can get the audio element to start playing on user interaction. So select the audio element, and call it's play() method right before starting the audio you actually want to hear.

`audioElement.play();
`
I tested on the following devices on LambdaTest (highly recommended if you don't own an iOS device):

- iPhone 8 13.4
- iPhone 12 17.2
- iPhone 13 Mini 17.2
- iPhone 14 17.2
- iPhone 15 17.2

**Comment by 1risS** [comment]
@MichaelShingo thanks for sharing your solution, you saved my participative concert 🙏🏼 ❤️ 📈 🔋
