### ISSUE TITLE
AutoPanner doesn't pan full range

### ISSUE THREAD

**Issue by loderunner** [Tonejs/Tone.js#165]
I was trying to extend `MonoSynth` with a `AutoPanner` (in order to have one auto-pan per voice with `PolySynth`). I found that AutoPanner does not sweep from full left to full right.

You can hear the issue clearly here: http://codepen.io/loderunnr/pen/LRbLmr

In contrast, using my own `LFO` + `Panner` seems to work perfectly: http://codepen.io/loderunnr/pen/gwLRka

**Comment by tambien** [comment]
You're right! The panner used to go between 0-1 and I updated it to be more consistent with the native StereoPannerNode. i forgot to update the AutoPanner's LFO.
