### ISSUE TITLE
Freeverb feedback at > 0.8 room size with Chrome 53

### ISSUE THREAD

**Issue by mmckegg** [Tonejs/Tone.js#166]
This used to work fine, but since Chrome 53, there are some crazy feedback problems when `roomSize` is set to a value higher than `0.8`. High frequencies resonate and get increasingly louder until distortion. I suspect it could be due to https://bugs.chromium.org/p/chromium/issues/detail?id=597432

I have tried to fix this myself, but can't figure out what is causing it, or if it can even be fixed. Also I don't really understand how schroeder reverberators work, so that's probably not helping.

```js
var reverb = new Tone.Freeverb({ roomSize: 0.9 }).toMaster()
var synth = new Tone.Synth().connect(reverb);
synth.triggerAttackRelease("D4", "8n");
// prepare to be deafened! 
```

**Comment by mmckegg** [comment]
Upon investigation, I have discovered that the problem is caused by [changes to the way Q values work](https://github.com/WebAudio/web-audio-api/issues/771). 

Luckily [there's a handy tool to calculate new Q values from old ones](http://rtoy.github.io/webaudio-hacks/more/biquad/biquad-lowpass-q.html?usedB=true). Update the [LowpassCombFilter Q value](https://github.com/Tonejs/Tone.js/blob/master/Tone/component/LowpassCombFilter.js#L42) from `0` to the magic number of `-3.0102999566398125` and the problem disappears. From very quick testing, it also seems to be fine in older versions of Chrome.

**Comment by tambien** [comment]
Good find!
