### ISSUE TITLE
Using StartAudioContext

### ISSUE THREAD

**Issue by AnthonyArtmann** [Tonejs/Tone.js#167]
Sorry to bother you but I am having trouble using StartAudioContext.js to unlock sound on iOS/Safari.

I have included the StartAudioContext.js file.

I have added a button to my index.html
`<button id="playButton">Unlock Audio</button>`

I have added the code to my javascript:
```
var context = new AudioContext();
StartAudioContext(context, "#playButton");
```

But still no sound on iOS after I press the button.

Not sure what I am doing wrong here.

I'll be grateful for any advice.

My demo is at: http://artsystemsstaging.com.au/ToneJS/ (Only the "1" buttons make tones.)

Anthony.

PS. Once again, thankyou SO much for your hard work on this project.  Clearly the leading AudioAPI library.  I am excited to be able to use it on my iOS projects!

**Comment by tambien** [comment]
I think your code just needs a small modification: 

```javascript
StartAudioContext(Tone.context, "#playButton");
```

Instead of making your own context, pass in Tone.context. Now StartAudioContext will get Tone.js' AudioContext running instead of the new one that you created. That should fix it.

**Comment by AnthonyArtmann** [comment]
That worked!  Thanks!
