### ISSUE TITLE
Unable to initialize Tone.Loop

### ISSUE THREAD

**Issue by reckoner165** [Tonejs/Tone.js#168]
Unable to create a Tone.Loop object. Tried the sample code from docs, but I get the following error:

`Tone.Loop is not a constructor`

**Comment by tambien** [comment]
Hey. Do you share your that line of code that's throwing the error?

My guess without seeing the code is that you're missing the `new` keyword.

Should be:

```javascript
var loop = new Tone.Loop(callback, interval)
```

**Comment by reckoner165** [comment]
I did include the `new` keyword. Not including it gave the following error: 

`Tone.Loop is not a function` 
This made sense. 

Here is my code. I've included the entire method:


```
this.play = function(keyCount) {
		if (keyCount === 1){
			sample.start();
			element.style('background-color','#cfc');

		}
		else {

			
			// seq.start();
			// sample.loop = true;
			sample.start();

			var padLoop = new Tone.Loop(function(time){
				//triggered every eighth note. 
				console.log(time);
				sample.start();
			}, "8n");
			loop.start();


		}

	}
```

**Comment by tambien** [comment]
Looks like valid code to me. Are you running Tone.js r7?

**Comment by reckoner165** [comment]
I see! I was using r5. It works with now r7. 

Thank you so much for pointing that out!
