### ISSUE TITLE
Using 'set' on an instrument that contains a PolySynth does not work correctly

### ISSUE THREAD

**Issue by gerardabello** [Tonejs/Tone.js#172]
I created simple class that extends Tone.Instrument that contains a Tone.PolySynth (called `this.voice`) and some effects. Using the default `set` method, I cannot do `set('voice.detune', 10)` because `voice.detune` does not exist (it exists on the underlying instrument, but not in the PolySynth itself). You can manually call `voice.set('detune',10)` because the `set` method of PolySynth understands that you want to update all the underlying voices, but it is not used if you wrap the PolySynth inside another instrument.

I am doing something wrong or this can be improved?

I have a solution but I'm not sure if this is an issue or not.

**Comment by tambien** [comment]
Not sure off the top of my head why this wouldn't work. There is one small particularity with PolySynth.set that you mentioned. it is different than the other `set` methods which all inherit from the same place. PolySynth's `set` method has to iterate over all of it's voices. 

it'd be great to see your solution.

**Comment by gerardabello** [comment]
I created a pull request with my solution: https://github.com/Tonejs/Tone.js/pull/174

**Comment by tambien** [comment]
fixed by #174
