### ISSUE TITLE
Possible issue with Tone.Transport.on

### ISSUE THREAD

**Issue by jackschaedler** [Tonejs/Tone.js#173]
Hi!

First off, thanks so much for Tone.js. It's an amazing library! 

I have a question about the behavior of `Tone.Transport.on` which may or may not be an actual issue. It's likely I'm just misunderstanding the way it's meant to be used. Given the following page:

``` <html>
    <head>
        <script type="text/javascript" src="https://tonejs.github.io/CDN/latest/Tone.js"></script>
    </head>

    <body>
        <button onclick="console.log('stop!'); Tone.Transport.stop();">Stop</button>

        <script>
                Tone.Transport.bpm.value = 120;
                Tone.Transport.loop = true;
                Tone.Transport.loopStart = "0:0:0";
                Tone.Transport.loopEnd = "1:0:0";

                Tone.Transport.on("stop", function (time) {
                    console.log("Transport Stopped At: " + time);
                    console.log("Transport State: " + Tone.Transport.state);
                });

                Tone.Transport.start();
        </script>
    </body>
</html>
```

I see the following in my console

```
Transport Stopped At: 2.075464852607728
BugReport.html:17 Transport State: started
BugReport.html:16 Transport Stopped At: 4.075464852607627
BugReport.html:17 Transport State: started
BugReport.html:7 stop!
BugReport.html:16 Transport Stopped At: 5.50312925170068
BugReport.html:17 Transport State: stopped
```

My expectation is that the transport loop jump at `1:0:0` would not cause the `stop` callback to be fired. However, the first two invocations of the `stop` callback seem to be coming from the transport loop jump. I would expect that `Transport.state` would always be "stopped" in the body of the callback.

**Comment by tambien** [comment]
Right. That's a little confusing. What's going on is to keep the Tone.Sources synced to the Transport, i have the Transport emit a `stop` immediately followed by a `start` event with the new offset to each of the sources when it loops. That way a source like Tone.Player synced to the transport would stop where it was, then restart at the new position of the Transport. 

I will change the name of these loop events to `loopStart` and `loopEnd` to avoid this kind of confusion.

**Comment by jackschaedler** [comment]
Hi @tambien, thanks for the clear explanation. That makes perfect sense.

I think the addition of the `loopStart` and `loopEnd` events will be very helpful. Thanks again!
