### ISSUE TITLE
Sampler bug with triggerAttackRelease?

### ISSUE THREAD

**Issue by n1k0** [Tonejs/Tone.js#175]
Or maybe that's just me misunderdstanding the way all this works, though the [Sampler docs](https://tonejs.github.io/docs/#Sampler) claim that `triggerAttackRelease` should just work; though if I'm doing something like:

```js
// C3.mp3 is a valid, existing, accesible mp3 file
const bass = new Tone.Sampler("./audio/C3.mp3", () => {
  bass.triggerAttackRelease("D3", "16n");
}).toMaster();
```

It fails with:

```
Uncaught TypeError: Failed to set the 'value' property on 'AudioParam': The provided float value is non-finite.(…)
  Tone.Player._start @ Tone.js:20339
  Tone.Source.start @ Tone.js:8882
  Tone.Sampler.triggerAttack @ Tone.js:20596
  Tone.Instrument.triggerAttackRelease @ Tone.js:18122
  (anonymous function) @ sequencer.js:55
  Tone.Player._onload @ Tone.js:20286
  (anonymous function) @ Tone.js:11639
  (anonymous function) @ Tone.js:11899
```

This actually kind of make sense as the sampler has no information about what the original sample pitch is, so I'm wondering if there's any way to just use one sample and be able to play it at any note?

Side note, `triggerAttack(pitchShift)` works fine, so I could probably map target note frequencies to relative shifts but that sounds overkill.

Am I missing anything obvious? Thanks for the great lib btw!

**Comment by tambien** [comment]
Looks like those docs need to be updated. Just like triggerAttack and triggerRelease, the first argument is the interval to repitch the sample by. e.g.`-1` would be a half-step lower and `7` would be pitched up a fifth. 

Similarly, `triggerAttackRelease` should take an interval as the parameter. 

```javascript
// C3.mp3 is a valid, existing, accesible mp3 file
const bass = new Tone.Sampler("./audio/C3.mp3", () => {
  bass.triggerAttackRelease(2, "16n"); // to pitch it up to a D
}).toMaster();
```

In the docs, that function is inherited from Tone.Monophonic. So it includes the example from that.

**Comment by n1k0** [comment]
Oh, I see. yeah, updating the docs is a good idea :)

Side note, I'd be interested in a Sampler derived construct where you provide a file url, an associated pitch and it allows playing it automatically repitched to a given note. Where should I start investigating this idea? Would you guys be interested in having this as a core feature, or should I just create a plugin (if that's even feasible) on my own?

**Comment by n1k0** [comment]
Note: right now to get the base sample being repitched I'm using a map like

```js
const bass = new Tone.Sampler("./audio/C3.mp3").toMaster();
const bassPitchMap = {
  // ...
  B2: -1,
  C3: 0,
  C#3: 1,
  Db3: 1,
};
bass.triggerAttackRelease(bassPitchMap[note], duration, time, volume);
```

I feel like this is overkill and could be heavily automated to make developer lives easier; it could even be just through some option passed to the constructor:

```js
const bass = new Tone.Sampler({url: "./audio/C3.mp3", frequency: "C3"});
bass.triggerAttackRelease("C#3", duration, time, volume); // pitch +1
```

What do you think?

**Comment by tambien** [comment]
i think that'd be cool. please send a PR if you can. 

the parameter name `frequency` is a little inconsistent with how that parameter is used elsewhere in the lib, so i might go with something like `pitch` or `referencePitch`.
