### ISSUE TITLE
current time within a player instance

### ISSUE THREAD

**Issue by reckoner165** [Tonejs/Tone.js#178]
Is there a method (or a way to fold in Tone.Time) to return the current time of a Tone.Player object while it plays a wav file?

I am trying to get the current time instant from one Player and use it to offset the next Player

**Comment by tambien** [comment]
There is no method right now. It's also a little complicated to do that while accounting for the possibility of playbackRate changes. I think I remember seeing that @notthetup had a technique that could achieve this by creating another buffer which just counts up 0-1 and playing that at the same time as the other buffer. Not sure if it'd be worth the performance hit of playing two buffers for each Tone.Player just for that ability though.

Though for most simple cases, i think you could just store the start time in a variable and subtract the current time to get the elapsed time.

**Comment by notthetup** [comment]
As long as no automation functions are used on the `playbackRate` param, you can just use basic math to figure this out. The second you start doing automation it get a lot more hairy (hence my 2nd buffer hack).

**Comment by reckoner165** [comment]
I'm currently doing the stopTime-startTime trick, but I still hear little sample slippages. I'm guessing using % of elapsed time in a given file may give better results. 

Most triggers are manual with mouse hover events, so I think I can do without the second buffer.
