### ISSUE TITLE
Scheduled events sometimes missed

### ISSUE THREAD

**Issue by tomduncalf** [Tonejs/Tone.js#179]
I am using the awesome Tone.js to build a simple four track sequencer, which triggers notes (corresponding to loops) on various samplers. I'm finding that on Chrome 54 on OS X 10.11.3 on a Late 2013 Macbook Pro 15" (top spec so not a slow machine issue), maybe 1 in 10 times, scheduled events simply don't fire. I've added in a console.log to confirm this is the case.

I understand that Tone schedules ahead of time, to ensure timing is as accurate as possible - I wonder if this lookahead window is too small. Is there a way to increase the window?

My code for triggering samples looks like:

```
    props.arrangement.tracks.forEach(track => {
      track.clipSlots.forEach((clipSlot, index) => {
        if (!clipSlot.clip) return;

        if (!this.samplers.get(clipSlot.clip)) {
          this.samplers.set(clipSlot.clip, createSampler(clipSlot.clip));
        }

        const sampler = this.samplers.get(clipSlot.clip);
        if (sampler) {
          Tone.Transport.schedule(() => {
            sampler.triggerAttack(0);
            console.log('trigger ' + sampler)
          }, `${index * 4}:0:0`);
        }
      });
    });
```

(I also noticed this problem on a previous tone project with different code so I don't think it's just an app-specific issue)

Thanks,
Tom

**Comment by tambien** [comment]
Your situation sounds similar to issue #163 which is linked to a [bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=645776) which is being worked on. 

But in the meantime, try use the time returned from `schedule` and pass it into `triggerAttack`. In this snippet you're trying to schedule `triggerAttack` immediately every time, so it is bypassing the lookAhead altogether. 

```javascript
Tone.Transport.schedule((time) => {
  sampler.triggerAttack(0, time);
  console.log('trigger ' + sampler)
}, `${index * 4}:0:0`);
```

**Comment by tomduncalf** [comment]
That's awesome, thanks @tambien! I'll try a different browser for the time being. Thanks very much!

**Comment by tomduncalf** [comment]
Passing in the time and using a tip from the other thread to call `Transport.start('+1')` has made things much more stable, thanks!
