### ISSUE TITLE
Fallback flag

### ISSUE THREAD

**Issue by evanbbb** [Tonejs/Tone.js#183]
On some slower machines, the audio in my project judders for a moment then stops playing entirely but throws no error. I can't seem to find anything within Tone.js that flags that this has happened. Any hint where to look or where to stick my own event so I can create a fallback option?

**Comment by tambien** [comment]
Unfortunately, Web Audio doesn't provide events like that or any indication of the performance of the audio thread, like drops, crackles, etc. so, i'm not sure how this could be added to Tone.js.
