### ISSUE TITLE
Change buffer size?

### ISSUE THREAD

**Issue by tomduncalf** [Tonejs/Tone.js#184]
Is there any way when working with WebAudio/Tone.js to change the audio buffer size? I'm getting a few glitches with a project on iOS and was wondering if there was a simple fix by increasing the buffer size.

Thanks,
Tom

**Comment by tomduncalf** [comment]
Actually I think I might have resolved this instance of the problem - I had an event firing every 100 ticks to update an element'a position which was pretty cpu intensive. Would be interesting to know in general if this is possible though - sounds like the answer for now is no, until the proposed latencyHint option is supported?

**Comment by tambien** [comment]
In general, it's important to avoid updating any visuals from within the Transport callbacks. I am going to write a wiki article on performance considerations/best practices. But the general principle is to keep visual rendering and audio scheduling separate. 

As you mentioned, the buffer/block size is not yet settable in Web Audio, but i've put some Tone.Transport code into r9 which will hopefully alleviate some clicks/crackles by giving the ability to optimize for 'playback' or 'interactivity' similar to the 'latencyHint' option.

**Comment by tomduncalf** [comment]
Thanks very much for the advice (and the amazing library)! That option sounds interesting.
