### ISSUE TITLE
roomSize might be damaged under some parameters

### ISSUE THREAD

**Issue by sunwangshu** [Tonejs/Tone.js#185]
When using this value 0.9 in Chrome, the sound goes crazy like self-excite to infinity. In Safari it sounds ok for now.
It's normal if using roomSize 0.8 in Chrome.

var freeverb = new Tone.Freeverb().toMaster();
freeverb.dampening.value = 2000;
freeverb.roomSize.value = 0.9;
freeverb.wet.value = 1;

**Be really careful** if you want to try out this sample sketch, it's super noisy.
Prepare to shut it down anytime.
http://jsfiddle.net/sunwangshu/rsy6yugu/7/

**Comment by tambien** [comment]
Lovely song. This issue is related to #166 and was resolved.

I went ahead and updated your fiddle to the latest version of Tone and it works fine now: http://jsfiddle.net/rsy6yugu/8/

**Comment by sunwangshu** [comment]
Thanks <3
