### ISSUE TITLE
[r8] Notes played immediately use previous note's pitch

### ISSUE THREAD

**Issue by andyhall** [Tonejs/Tone.js#190]
I believe this is a reoccurrence of #163, but I found that it still reproduces reliably under R8 (in current Chrome). Here is a minimal reproduction:

```js
var inst = new Tone.Synth().toMaster()
var toggle = true

var loop = new Tone.Loop(function (time) {
    var note = toggle ? 'C4' : 'E4'
    inst.triggerAttackRelease(note, 0.2, time)
    toggle = !toggle
    console.log(note, time)
}, '4n')

Tone.Transport.bpm.value = 128
Tone.Transport.start()
loop.start()
```

I understand it's a Chrome issue, but I thought the above code might help isolate possible workarounds. Note that the bug's occurrence depends on BPM - at 128 it happens quickly and repeatedly, while for other values it may take 30 seconds or longer to occur. This is in Mac/Chrome 55.0.2883.95 (64-bit).

For anyone else encountering this, adding any kind of delay seems to entirely avoid the problem:

```js
    inst.triggerAttackRelease(note, length, time + 0.001)
```

**Comment by tambien** [comment]
I've noticed the error occurs more often with events that are closely aligned to the block size (128 samples). This is referenced in the chromium bug. 

Reopened #163. Closing this duplicate.
