### ISSUE TITLE
Disable Tone.Draw() programmatically or automatically

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#194]
The new `Draw` functionality is really cool and it's great to see it in the newest release.

However, there doesn't seem to be a way to disable it for scenarios where there is already an existing usage of `requestAnimationFrame` running alongside it.

Using a single requestAnimationFrame can have a positive performance impact because the `self` of running the function itself can be impactful. Looks like there is other minor overhead from the `_drawLoop` function as well.

Here is a screenshot of the profile I ran to discover this:

<img width="838" alt="screenshot 2017-02-07 15 56 51" src="https://cloud.githubusercontent.com/assets/296167/22717140/40f58b6a-ed4e-11e6-8e41-2607906f6455.png">

Would it be possible to either provide a mechanism to programmatically disable it or to not have it running the callback until there is a scheduled event?

I can help with implementation with a bit of guidance.

**Comment by tambien** [comment]
Makes sense. I think the best fix would be if the draw loop only ran when something is pushed onto the events queue, and that it stops updating when the queue is empty. 

While i was thinking through how to do it, i went ahead an implemented it. (I'll commit it in a moment). but thanks for the offer!

Do you think it'd be useful to be able to manually control the updating? for example, setting `autoupdate = false` and then manually call `Tone.Draw.update()` from within an animation frame. I wasn't sure if there is much overhead with scheduling multiple `requestAnimationFrames` each frame.

**Comment by JackCA** [comment]
@tambien thanks for looking at this.

I agree that the automatic scheduling works well in my situation as I'm not currently using the Draw functionality. 

As to manually being able to update, yes I think that could be useful for power users who are using Draw but want to manage when it is invoked manually in their own loop. 

🎶

**Comment by JackCA** [comment]
@tambien now that I'm looking at this a little closer, the `autoupdate = false` option would be more helpful in my personal scenario. I have scheduled events (in a `Part`) but I'm not using the drawloop for anything at this time.
