### ISSUE TITLE
Best way to schedule midi messages

### ISSUE THREAD

**Issue by killingz0e** [Tonejs/Tone.js#196]
Hi, I am trying to use tone.js to schedule midi messages but so far I couldn't find a realiable solution.

This is my midi controller:
```
import Tone from "tone";

let midiOutput;

export function playNote() {
    midiOutput.send([0x92, 60, 127]);
}

export function init(){
    if (navigator.requestMIDIAccess) {
    navigator.requestMIDIAccess({
        sysex: false 
    }).then(onMIDISuccess, onMIDIFailure);
    } else {
        alert("No MIDI support in your browser.");
        return false;
    }
}

function onMIDISuccess(midiObject) {
    var noteon,
      outputs = [];
      var iter = midiObject.outputs.values();
      for (var i = iter.next(); i && !i.done; i = iter.next()) {
        outputs.push(i.value);
      }
      midiOutput = outputs[0];    
}

function onMIDIFailure(e) {
    console.log("No midi " + e);
}

```

I'd like to schedule playNote() , what is the right way to do it?

I've tried with WAAClock and it works fine but I couldn't manage to use tone.js.

Thanks!

**Comment by killingz0e** [comment]
Tynisynth use this method to schedule samples:

  ```
  tracks.forEach(({name, vol, muted, beats}) => {
      if (beats[index]) {
        try {
          ////////// I was trying to schedule midi here
          Tone.Transport.schedule(function(){
            midiController.playNote();  
          }, time);
         ///////////
          keys.start(name, time, 0, "1n", 0, muted ? 0 : velocities[index] * vol);
        } catch(e) {
        }
      }
    });
```
This is what I was trying, without success:

 Tone.Transport.schedule(function(){
            midiController.playNote();  
          }, time);

**Comment by tambien** [comment]
What kind of error are you getting? Are you starting the Tone.Transport? 

Also FYI, the timing of the callback is going to be approximate and the callback will be invoked _before_ the time of the event, but the time will be passed into the callback of `Transport.schedule`.  You should pass that time into the send method (after converting it to whatever timing units the Midi API needs).

**Comment by killingz0e** [comment]
It is not an error, it is, as you say, a timing inconsistency. The midi api doesn't have a time unit, it can just send messages.

To my understanding tone.js use an appropriate way to deal with timing issues, but I don't know how I can implement it with custom events (such as, in my case, a midi message).

Do you have a suggestion?

**Comment by tambien** [comment]
I'm not very familiar with the WebMidi API, but looking at [the WebMidi Spec](https://www.w3.org/TR/webmidi/#methods-2), the `send` method has an optional time value. To use Tone.js timing with Web Midi you'll need to convert the AudioContext time (in seconds since the context was created) to the  DOMHighResTimeStamp (milliseconds since the page load).  

I think this conversion would look something like this: `var timingOffset = performance.now() - Tone.now() * 1000`. You'll then add that `timingOffset` value to the time that `Transport.schedule` returns and use that to schedule a note with `send`. 

```javascript
Tone.Transport.schedule(function(time){
  midiController.playNote(time * 1000 + timingOffset)
})
```

I haven't tried this code out, but it seems like it'll fix the inconsistent timing.

**Comment by killingz0e** [comment]
Thank you!! 

I haven't noticed the optional time value in the midi specs, and with your offset suggestion it is pretty solid now!

**Comment by pierluigi** [comment]
Apologies for reviving such an old thread, but I'd love some help on how to integrate Tone.js with Webmidi.js to output midi notes through a MIDI output. 

I am pasting some code here to illustrate:

```
import * as Tone from "tone";
import _ from "lodash";
import WebMidi from "webmidi";

document.querySelector("button").addEventListener("click", async () => {
  // document.querySelector("button").hidden = true;
  await Tone.start();

  WebMidi.enable(function (err) {
    if (err) {
      console.log("WebMidi could not be enabled.", err);
    } else {
      console.log(WebMidi.outputs[0]);
      const output = WebMidi.outputs[0];

      const kick = new Tone.MembraneSynth().toMaster();
      const midiLoop = new Tone.Loop((time) => {
        // time is the scheduled time for the event (in the future)
        const toneNow = Tone.now() * 1000;
        const webMidiTime = WebMidi.time;
        const timeDiff = toneNow - time * 1000;
        const timeForMidi = `+${timeDiff}`; // the relative time

        console.table([
          ["time", "Tone.now", "WebMidi.time", "timeDiff", "time for midi"],
          [
            (time * 1000).toFixed(3),
            toneNow.toFixed(3),
            webMidiTime.toFixed(3),
            timeDiff.toFixed(3),
            timeForMidi,
          ],
        ]);
        kick.triggerAttackRelease("C1", "8n", time);
        output.playNote("D4", 3, {
          time: timeForMidi, // This can be a relative value. See: http://djipco.github.io/webmidi/latest/classes/Output.html#method_playNote
          duration: 50,
          velocity: 120,
        });
      }, "4n").start();
    }
  });

  // Transport
  const tx = Tone.Transport;
  tx.bpm.value = 120;
  tx.start();
});

```

This result in out-of-sync, drifting repetitions. 

1) the kick is out of sync with the MIDI event
2) the midi event itself is far from stable 

The console.table outputs some useful info to track the various timing:

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/1078545/80524004-daefe800-8986-11ea-82f7-81cf085027d7.png">

So – I can't figure out why the 2 are out of sync and I could really use some help here!
Thanks 🙇

**Comment by apiel** [comment]
I am having similar issue, the follwoing code seem to work:
```js
Transport.scheduleRepeat(function(time){
    var timingOffset = (now()- time) * 1000;
    setTimeout(() => midiInput.send([0x90, 60, 100]), timingOffset);
    setTimeout(() => midiInput.send([0x80, 60, 0]), timingOffset+200);
    sampler.triggerAttackRelease("C4", "2n", now());
}, "1n");
```
But I am not 100% sure, I wonder if there is not a slight different when not trigger between my laptop and my midi device. I think the midi device still start a little bit earlier.

**Comment by michaelcaterisano** [comment]
Hey @tambien! I've been trying to achieve the same thing. I'm pretty sure the following is not the way to go since `Tone.Draw` is not meant for scheduling audio, but it's gotten me closer than the other approaches mentioned above. In this example, `webMidiOutput` is a [webmidi](https://github.com/djipco/webmidi) output object. I've tried writing this using `Transport.schedule` instead of `Draw.schedule` but haven't figured that out yet. Do you have thoughts on a better way to write this?

```  
const sequence = new Sequence(
    (time, note) => {
      Draw.schedule(() => {
        webMidiOutput.playNote(note, 1, { duration: 100, time: performance.now() });
      }, time);
    },
    ['C5', 'D5', 'E5'],
    '4n',
  );
  sequence.start();
```
