### ISSUE TITLE
Bower removal

### ISSUE THREAD

**Issue by alexthewilde** [Tonejs/Tone.js#197]
Can you explain the reason behind the [removal from bower](https://github.com/Tonejs/Tone.js/commit/285f6a0af4db702b462f304fb38c34f529533162)?

I'm actually depending on the bower component, so for me the only way would be to maintain my own fork with a bower.json.

**Comment by tambien** [comment]
I am always looking for ways to simplify the onboarding of Tone.js, and giving fewer ways to install it seemed helpful. Especially for someone new to programming or javascript, they don't need to go reading about the difference between bower and npm to decide which they should use. It also seems that many other libraries have chosen npm over bower. 

Is it possible for you to switch over to npm? 

I am fine with adding `bower.json` back if npm is not an alternative for you and other users.

**Comment by alexthewilde** [comment]
Thanks for clarifying. I get your point, although I think that bower is still a very common install option. 

My own build process is using bower components exclusively and I'd prefer to keep it that simple if possible.

**Comment by alexthewilde** [comment]
@tambien thanks!!
