### ISSUE TITLE
Firefox Freeverb feedback

### ISSUE THREAD

**Issue by Zaraka** [Tonejs/Tone.js#198]
If you try bus [demo](https://tonejs.github.io/examples/#buses) in Firefox (51.0.1)  and apply some freeverb then trigger note. Note will be played with reverb, but after few seconds a super loud crazy feedback will rip your ears.
If this cannot be fixed, please disable this functionality in firefox, or put up some warning, it's really painful.

**Comment by tambien** [comment]
wow! That is ear splitting. I will definitely take care of that before the next release. 

I'm trying to figure out a way to implement the LowpassFeedbackCombFilter with the IIRFilter. It seems like it'd be pretty straight forward, but I'm not sure on the exact math of the transfer function coefficients... maybe someone who knows more about filter math can help me out?

**Comment by softpunch** [comment]
@tambien -- 
I couldn't _quite_ get it to work with the rest of the Freeverb code 
(I may try again later), 
but in case it's useful in the meantime, 
here's my implementation of your LowpassFeedbackCombFilter using IIRFilter:

https://jsfiddle.net/softpunch/wnotL5ep/

I'm no good at higher level math myself, 
but @mohayonao's filter coefficients make it easier:
https://github.com/mohayonao/biquad-coeffs
https://mohayonao.github.io/biquad-coeffs

You might also find these tools useful:
http://www.earlevel.com/main/2010/12/20/biquad-calculator/
http://rtoy.github.io/webaudio-hacks/more/filter-design/filter-design.html

**Comment by tambien** [comment]
@softpunch Those values are not supposed to be at the current sample rate. instead they match the values of the Freeverb implementation values that i found [here](https://ccrma.stanford.edu/~jos/pasp/Freeverb.html). I divide by the original sample rate to convert it to seconds which allows it to be used at any sample rate.

**Comment by softpunch** [comment]
Got it!

**Comment by tambien** [comment]
@softpunch thanks for looking more into the LPCF. I was hoping that it'd be possible to implement it entirely using the new IIRFilter, but[ it doesn't support adequate lengths](WebAudio/web-audio-api/issues/1153) to make the filter entirely using the IIR. My only other option is to use the Audio Worker once that's available.

**Comment by softpunch** [comment]
So close but so far...
