### ISSUE TITLE
GrainPlayer throws exception

### ISSUE THREAD

**Issue by timpulver** [Tonejs/Tone.js#199]
When setting `drift` in `GainPlayer` I sometimes get an exception:

```
error:Uncaught InvalidStateError: Failed to execute 'start' on 'AudioBufferSourceNode': The offset provided (-1.8573) is less than the minimum bound (0).
```

The higher `drift` is the more likely it is to get the the exception (repeatedly).
Any ideas?

**Comment by tambien** [comment]
The drift is a random amount before or after the scheduled start time that the sample will be started. So if you have a random drift of, lets say, -2 seconds to a buffer which is only 1 second long, you will get that kind of error. 

I will add a safety check to the code to make sure the drift is always in a safe range.

**Comment by timpulver** [comment]
Great, thank you!
