### ISSUE TITLE
get() method for synth options?

### ISSUE THREAD

**Issue by timpulver** [Tonejs/Tone.js#200]
For the creation of presets it would be very helpful to have a `get()` method for all parameters of a synth. Could this be added to the base instrument class? I’m currently implementing tone.js in the visual programming editor [cables](https://cables.gl), where users can change parameters by dragging sliders.

**Comment by tambien** [comment]
very cool! i'm excited to see Tone in cables. 

[`get`](https://tonejs.github.io/docs/#Tone.get) and [`set`](https://tonejs.github.io/docs/#Tone.set) currently exist in all classes since it's implemented in the Tone base class. 

So you can do `synth.get()` which will return all of the parameter.
