### ISSUE TITLE
Is there a validate(tone) function?

### ISSUE THREAD

**Issue by timpulver** [Tonejs/Tone.js#201]
Is there a function to validate a tone?
Correct tones are `"C4"`, `"440"` and `440`, right?
Which octaves are valid?

Also for time I’m currently using this, which is probably not the best:

```
var time = "2n";

try {
    new Tone.TimeBase(time)
    // valid
} catch(e) {
    // not valid
}
```

**Comment by tambien** [comment]
There is no `validate` method for Time or Frequency. And the valid range will change depending on what you're trying to do with the value. For example, according the [spec](https://webaudio.github.io/web-audio-api/#attributes-26), for oscillator frequencies the range that the value could be set is [-Nyquist frequency, Nyquist frequency] or about [-20000, 20000] for a typical sample rate. 

As far as testing whether the input is a valid string, i think that your approach using a try/catch block seems good. You're basically just testing whether or not the string parser can parse the message without throwing an error.
