### ISSUE TITLE
Error when setting Envelope on AMSynth

### ISSUE THREAD

**Issue by timpulver** [Tonejs/Tone.js#202]
When trying to set the envelope on a AMSynth I get an error message.

This works:
```
var synth = new Tone.AMSynth().toMaster();

synth.set("envelope", {
	"attack" : 2,
	"decay" : 0.2,
	"sustain" : 1,
	"release" : 0.8,
});

synth.triggerAttackRelease("C4", "1n");
```

The following does not:
```
var synth = new Tone.AMSynth().toMaster();
var env = new Tone.Envelope({
	"attack" : 2,
	"decay" : 0.2,
	"sustain" : 1,
	"release" : 0.8,
});

synth.set("envelope", env);

synth.triggerAttackRelease("C4", "1n");
```
I get the following error:
```
Uncaught TypeError: Failed to set the 'value' property on 'AudioParam': The provided float value is non-finite.
    at Tone.TimelineSignal.set (Tone.js:3315)
    at Tone.AmplitudeEnvelope.Tone.set (Tone.js:197)
    at Tone.AMSynth.Tone.set (Tone.js:207)
    at app.js:...
```

In the [docs](https://tonejs.github.io/docs/#AMSynth) the type seems to be wrong (`Tone.Oscillator`).

**Comment by tambien** [comment]
Thanks for the note on the docs. I've updated that. Feel free to send PRs about those kinds of issues on the `dev` branch. I'll gladly merge doc fixes. 

As far as your first question, `set` is to change the settings, not to replace the envelope. This is consistent with the way `set` is used throughout the library. Replacing the envelope would require disconnecting the old envelope and reconnecting the new one, which is unnecessary in most situations and would probably produce unwanted side effects in many places.

**Comment by timpulver** [comment]
Thanks, I will consider a PR next time.

What’s the preferred way to access the nodes of a Tone.js object? In case not all parameters are accessible via `set`?
