### ISSUE TITLE
Question : How can I get the actual sound as it is?

### ISSUE THREAD

**Issue by Tabs16** [Tonejs/Tone.js#204]
Hello,
I have just begun using Tone.js and want to implement a functionality which requires playing the sound only for left speaker at one point of time and only right speaker at some other time but I am facing a problem as to how to play the actual sound as is generated.
I am using Tone.Oscillator() but it plays a sound of default frequency and not the original sound.
Thanks :)

**Comment by tambien** [comment]
I'm not sure what you mean by the "original sound". 

As far as the first part of your question, you could use Tone.Panner to modulate between the left and right speaker. For example: to play the sound out of the left speaker for 10 seconds and then switch to the right speaker, you could do something like this: 

```javascript
var panner = new Tone.Panner().toMaster()
//set it all the way left
panner.pan.setValueAtTime(0, -1)
//switch to the right channel after 10 seconds
panner.pan.setValueAtTime("+10", 1)
//create an oscillator and connect it to the panner
var osc = new Tone.Oscillator().connect(panner).start()
```

**Comment by Tabs16** [comment]
For example, my i have an app in which I have to play a series of notes and drums  and then modulate this sound of combined drums and notes into different speakers. If I use Tone.Oscillator it just plays a sound of some frequency but not my original sound.How do I accomplish that?

**Comment by tambien** [comment]
You can module the frequency of Tone.Oscillator by doing something like: 

```
var osc = new Tone.Oscillator().toMaster()
//change the frequency
osc.frequency.value = 220
```

But if you want to play drum sounds or other mp3s, Tone.Oscillator is probably not what you're looking for. 

The [playbackRate example](https://tonejs.github.io/examples/#pianoPhase) plays two different sources out of different speakers. You can see how that is done. 

Let's move this conversation to [the forum](https://groups.google.com/forum/#!forum/tonejs) which is a place for this kind of question. Please post some code to give me a better sense of what you're trying to do.
