### ISSUE TITLE
Cordova and Tone.js

### ISSUE THREAD

**Issue by thipages** [Tonejs/Tone.js#208]
Hi, 
I tried to use Tone.js with Cordova but the code stops at `var synth= new Tone.Synth().toMaster();`
Any ideas?
Thank you

**Comment by tambien** [comment]
What is the error you are getting?

**Comment by terciodejesus** [comment]
Hello! I am use this framework with ToneJs for my end of course project in my university. I am having the same problem and this can be verified [here](https://bugs.chromium.org/p/chromium/issues/detail?id=518863). This happens only chrome browser.

**Comment by terciodejesus** [comment]
@thipages My solution was play a inaudible audio while the app is open.

**Comment by thipages** [comment]
@tambien I will try to identify the error (never done yet with Cordova)
@terciodejesus first thanks, to be more precise : sounds are played properly within Chrome mobile browser but not within Cordova application (apk)

**Comment by thipages** [comment]
@tambien : the error is the following "ReferenceError : Tone is not defined"

This error came from a try/catch on` var synth= new Tone.Synth().toMaster();` called within onDeviceReady function. (The library is correctly referenced in the HTML)

Also I put a 5s timeout before calling ` var synth= new Tone.Synth().toMaster();` , but same result.

Any ideas?
Thank you

**Comment by tambien** [comment]
Usually that error is because you haven't included Tone.js. Are you sure you have Tone.js included on the page and that Web Audio is supported by the environment?

**Comment by thipages** [comment]
yes, it is included. effectively I am not sure that it is supported... Strange anyway

**Comment by tambien** [comment]
If it wasn't supported, Tone.js should throw a different error when it tries to initialize. Something like `AudioContext is not defined`. So, there might be something else going on. I also just did a little research and it seems like Web Audio is supported by Cordova.

Your error makes me think that it is an issue loading Tone.js rather than a Web Audio or Tone.js bug.

**Comment by thipages** [comment]
I confirm that Tone.js is loaded.

Here is more precision about the errorS (console output, see screenshot) [http://titsoft.com/_shared/cordovaTonejs.png](http://titsoft.com/_shared/cordovaTonejs.png)

Does it help?
Thank you

**Comment by tambien** [comment]
Thanks for posting that. Looks like the error is related to Cordova's Content-Security-Policy. 

Tone.Clock [creates a Web Worker from a url blob](https://github.com/Tonejs/Tone.js/blob/master/Tone/core/Clock.js#L282). It seems like the default Content-Security-Policy doesn't allow this. 

I'm not sure exactly how to fix this. try changing some of the [Content-Security-Policy](https://content-security-policy.com/) attributes and see if any of them help.

**Comment by terciodejesus** [comment]
Wich server are you running on localhost?

**Comment by thipages** [comment]
@tambien thanks, I am currently trying to manage it with [cordova-plugin-whitelist](https://github.com/apache/cordova-plugin-whitelist)
@terciodejesus The application is tested on Android for the moment (apk), it may be the localhost

**Comment by tambien** [comment]
@thipages any updates on this? If you've figured it out, i'm sure that others would find it very helpful. If not, maybe i can try to find some other workaround.

**Comment by thipages** [comment]
Still not working. If you have any ideas. Thanks

**Comment by motekulo** [comment]
This is the security policy I use with a cordova app using  Tone js:

<meta http-equiv="Content-Security-Policy" content=
"default-src 'self' ws: data: gap: https://ssl.gstatic.com 'unsafe-eval' 'unsafe-inline';
child-src 'self' blob: * ;
style-src 'self' 'unsafe-inline' http://fonts.googleapis.com/;
font-src *;
media-src 'self' blob: data: ">

That's probably too relaxed, and some things will be unnecessary, so it might be best to gradually remove items that you don't need.

Tone js and cordova is working really well for me, although I'm having some specific device dramas with performance. That's Android though I think!

**Comment by tambien** [comment]
Great to hear you found a solution @motekulo

**Comment by thipages** [comment]
I confirm that this is working. If I or others found a less "relaxed" configuration I propose to communicate it here.
Thank you!!
