### ISSUE TITLE
How to play different Samplers at the same time

### ISSUE THREAD

**Issue by Archieeeeee** [Tonejs/Tone.js#210]
I do not think this can work as expected  but I do not find another way, could you help me, thanks
```
samplerA.triggerAttack();
samplerB.triggerAttack();
```

**Comment by tambien** [comment]
That should work. Both samplers will play immediately. If you need them to play at the _exact_ same time, pass in the same time value (slightly in the future) to both methods:

```javascript
const pitchChange = 0
const time = Tone.now() + 0.1
samplerA.triggerAttack(pitchChange, time)
samplerB.triggerAttack(pitchChange, time)
```
