### ISSUE TITLE
rampTo insists on ramping through all past values

### ISSUE THREAD

**Issue by adiron** [Tonejs/Tone.js#211]
Hi there

I've noticed an issue/feature/something about the way that `Signal`s' `rampTo` works, in which calling rampTo when there is already a value to ramp to results in the signal going through that value as well.

For instance if you drag the slider in the [ramping demo](https://tonejs.github.io/examples/rampTo.html) you will notice that it acts more as a delay than anything.

Is there a way to just get a smooth transition to the last value passed to rampTo()?

**Comment by tambien** [comment]
To make a signal ramp to a new value without completing the previously scheduled curves, you'll have to `cancelScheduledValues` first: 

```javascript
signal.cancelScheduledValues()
signal.rampTo(10, 0.3)
```
