### ISSUE TITLE
How to best use Tone.js with OfflineAudioContext?

### ISSUE THREAD

**Issue by esdu** [Tonejs/Tone.js#216]
Hey folks, we're building an application that requires visualizing the audio. Specifically, we're setting the context to OfflineAudioContext then rendering the result.

Because our application allows the user to change the components, instruments, effects, etc. we're trying to re-render the visualization on every user action. Since OfflineAudioContext can [only be used once](https://github.com/WebAudio/web-audio-api/issues/346) (it [sets its state to "closed"](https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/modules/webaudio/OfflineAudioContext.cpp#338) after rendering) we have to create a new OfflineAudioContext and call `Tone.setContext` on it every time.

It seems like `Tone.setContext` is very expensive, around 500 to 700ms per call. AFAIK - and correct me if I'm wrong - the right way to use OfflineAudioContext is to create a new one every time you want to render something, because creating OfflineAudioContext's is suppose to be cheap.

Any suggestions on how to efficiently use OfflineAudioContext with Tone.js? After taking a quick look at the source, I saw a list of callbacks to be invoked every time a new context is set. I assume this is the reason it's so slow. Are there any callbacks I can safely rip out?

**Comment by tambien** [comment]
The next version of Tone (which i'll hopefully be releasing soon) has new offline rendering capabilities wrapping the OfflineAudioContext which will hopefully fit your needs. 

Regarding your other question, I'm not sure why it would be taking 500-700ms to simply set the context. Creating and rendering the context can take quite some time depending on the complexity and length of the rendering. There's only a hand full of callbacks that run on setContext and i don't think any of them can be cut out. In my measurements it only took between 30-50ms to set a new context. I did a little optimization where i could to get that number even smaller.

**Comment by tambien** [comment]
Following up with the new capabilities in r10: http://tonejs.github.io/examples/#offline

**Comment by esdu** [comment]
Great, thank you! The long time it takes to set context may be a problem with our code. I'll take a closer look.
