### ISSUE TITLE
Checking 'state' of individual items within MultiPlayer

### ISSUE THREAD

**Issue by simulcast** [Tonejs/Tone.js#217]
Hello,

I'm writing a looping app using Tone.MultiPlayer and I can't find a way to access the state of the individual buffers within the MultiPlayer array. If I'm calling play on the first buffer MultiPlayer by going...

```
var sounds = new Tone.MultiPlayer([
'../path/is/here',
'../path/is/there'
]);

sounds.play(0);

```
Is there a way to check to see if that particular buffer is started or stopped? I have been digging through and haven't been able to find anything. I know that the MultiPlayer keeps an _activeSources object, but only gets added to when a buffers is played and not subtracted from when an object is stopped.

Thanks so much for any help!
Tristan

**Comment by tambien** [comment]
That's not possible at the moment, but i'm going to revisit MultiPlayer's API soon and try to accommodate this.

**Comment by simulcast** [comment]
Thanks, Yotam! Would you recommend just using the standard player for now then?

**Comment by tambien** [comment]
If you need to be able to check the state of each playing item, then yes. [Tone.Buffers](http://tonejs.github.io/docs/#Buffers) should make loading and handling many urls easier and can be easily used with Tone.Player or Tone.BufferSource.
