### ISSUE TITLE
Setting loopEnd on Transport not working

### ISSUE THREAD

**Issue by timpulver** [Tonejs/Tone.js#223]
When setting `loopEnd` on `Tone.Transport` while the Transport is already running and the `loopEnd`-time is over, Transport will not go back to `0:0:0`.
This happens e.g. when the current timeline-position is `4:0:0` and `loopEnd`-time is set to `1m`.
Expected behaviour would be, that the timeline instantly jumps to `0:0:0`.
When stopping and restarting the transport everything works fine.

**Comment by tambien** [comment]
This is actually the designed behavior, modeled after the way Ableton Live's transport looping is done. Though changing it to match your expected behavior would make closing #212 much easier...
