### ISSUE TITLE
Disconnection native Web Audio node error

### ISSUE THREAD

**Issue by timpulver** [Tonejs/Tone.js#224]
I have problems disconnecting native Web Audio nodes. The spec says calling `node.disconnect(otherNode)` should only disconnect otherNode. But seems like under certain circumstances all nodes are disconnected. 

In Chrome (latest) the following code works:
```
var audioCtx = new (window.AudioContext || window.webkitAudioContext)();
Tone.setContext(audioCtx);

var source = audioCtx.createBufferSource();
var reverb = new Tone.JCReverb();

source.connect(reverb);
source.connect(audioCtx.destination);
source.disconnect(audioCtx.destination);
source.disconnect(reverb);
```

… while the following does not. I just changed the order of the disconnect calls:
```
var audioCtx = new (window.AudioContext || window.webkitAudioContext)();
Tone.setContext(audioCtx);

var source = audioCtx.createBufferSource();
var reverb = new Tone.JCReverb();

source.connect(reverb);
source.connect(audioCtx.destination);
source.disconnect(reverb);
source.disconnect(audioCtx.destination);
```

Error:
```
Uncaught DOMException: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
```

Any idea why this is happening? Since Chrome 43 calling node.disconnect(otherNode) should be supported.

**Comment by timpulver** [comment]
A similar problem occured multiple times when trying to call `tonejsNode.disconnect(nativeNode, 0, 0)`, with an error message like *Cannot call disconnect, parameter 1 is not of type AudioNode*.

**Comment by timpulver** [comment]
Just read a related issue from 2014 – [#44](https://github.com/Tonejs/Tone.js/issues/44) – in the current Web Audio spec it should be possible to connect one channel of a node to multiple other nodes and disconnect them by calling `node.disconnect(otherNode)` without disconnecting all connections, right!?

**Comment by tambien** [comment]
@timpulver yeah, it should be possible with the updated specification. I believed it's implemented in Chrome and FF. I'm not sure about Safari.

**Comment by tambien** [comment]
@timpulver Just pasted your second snippet into [a jsfiddle](https://jsfiddle.net/anm8ghdr/) and it executes without any error on Chrome, FF and Safari. 

Back in 2014, disconnecting from a specific outlet was not part of the spec, but it has since been added (though, i think it's still not implemented in Safari AFAIK).
