### ISSUE TITLE
this question in latest version 

### ISSUE THREAD

**Issue by himiten** [Tonejs/Tone.js#225]
code just this:
```javascript
let Tone=require("tone");
document.getElementById("play").addEventListener("click",()=>{
    let synth = new Tone.Synth().toMaster();
    synth.triggerAttackRelease("C4", "8n");
});
```

 **in webpack pack and run in browser,then occurred:**
**Uncaught TypeError: Tone.Synth is not a constructor**

**Comment by himiten** [comment]
``let Tone=require("tone");
document.getElementById("play").addEventListener("click",()=>{
    let synth = new Tone.Synth().toMaster();
    synth.triggerAttackRelease("C4", "8n");
});

**Comment by himiten** [comment]
**in webpack pack and run in browser,then occurred: Uncaught TypeError: Tone.Synth is not a constructor**

**Comment by tambien** [comment]
I'm unable to reproduce this error. I use webpack with Tone.js all the time. 

Just to confirm: there's no error when you're building with webpack?

**Comment by tambien** [comment]
@himiten any updates? closing for now.
