### ISSUE TITLE
Demos: Copyright issue (roland tr-808)

### ISSUE THREAD

**Issue by pixelass** [Tonejs/Tone.js#228]
Roland just requested to take my TR-808 emulation offline. They said it's a copyright issue. 

The pen is now private but the link still seems to work. Just to be safe, I guess it's better to remove it from the demos.

THANK YOU ROLAND. THANK YOU VERY MUCH.

**Comment by tambien** [comment]
i liked that example. :(

thanks for letting me know @pixelass

**Comment by pixelass** [comment]
I almost cried when I read the message. I really don't get what the problem is.
I 'm actually selling my vintage 'real' synthesizers from Roland due to that issue.

**Comment by danigb** [comment]
Sad to hear it @pixelass, it was a really nice one. Probably roland get jealous ;-)

**Comment by pixelass** [comment]
Well Roland just killed a developer. 
No more work from me anymore. My accounts on various networks have now been deleted.

My github will also be deleted soon.

**Comment by danigb** [comment]
Don't give them so power...
