### ISSUE TITLE
Tone.Offline Example contains incorrect link to API documentation

### ISSUE THREAD

**Issue by softpunch** [Tonejs/Tone.js#229]
**Tone.Offline** **Example**: https://tonejs.github.io/examples/#offline

In the explanation, 
it links to: https://tonejs.github.io/docs/#Offline

That section does not currently exist.
Instead, it should link to: https://tonejs.github.io/docs/#Tone 

(Ideally, it would link directly to the **.Offline** method of the **Tone** section, 
but I'm not sure if that's possible using the API documentation's current framework.)

**Comment by tambien** [comment]
good catch! It's possible to jump to a specific method like so: https://tonejs.github.io/docs/#Tone.Offline

**Comment by softpunch** [comment]
Nice!

**Comment by tambien** [comment]
i'll update the example soon.
