### ISSUE TITLE
InvalidStateError in Safari

### ISSUE THREAD

**Issue by phesterman** [Tonejs/Tone.js#230]
I just updated a project to use r10.  Everything works perfectly in Google Chrome, but in Safari, I get this error seemingly randomly:

InvalidStateError (DOM Exception 11): The object is in an invalid state.

I'm using a MultiPlayer object and not doing anything tricky, simply playing three or four samples simultaneously as triads or seventh chords.  There's no crash, but occasionally only one sample plays and the error is generated.  After that, all is well for a while and then it happens again at random.

Any ideas?

**Comment by phesterman** [comment]
Here's a little more info about where it occurs in Tone.js:

![screen shot 2017-04-13 at 9 58 35 am](https://cloud.githubusercontent.com/assets/6420524/25010486/e43b2fb4-202f-11e7-8ca3-ff93ff35c499.png)

**Comment by tambien** [comment]
could you please post an example? 

I believe that error occurs when you're trying to stop an object which hasn't been started or is already stopped. but that line above it should ensure that it's only stopped in a valid state.

**Comment by phesterman** [comment]
http://media.wwnorton.com/college/music/hm_fundamentals/html5/nmfojs%20projects/Triads581.html

Try clicking on the chord or Roman numeral symbols in Frame 5, for example.

Thanks.

**Comment by phesterman** [comment]
That seems to fix it...thanks for checking it out!

**Comment by jlangr** [comment]
I'm on 0.12.80, and receiving the same error in Safari using a starter snippet copied from this docs:

  play() {
    var synth = new Tone.FMSynth().toMaster();
    synth.triggerAttackRelease('C4', '4n', '8n');
    synth.triggerAttackRelease('E4', '8n', '4n + 8n');  //  <-- this is what throws
    synth.triggerAttackRelease('G4', '16n', '2n');
    synth.triggerAttackRelease('B4', '16n', '2n + 8t');
    synth.triggerAttackRelease('G4', '16','2n + 8t * 2');
    synth.triggerAttackRelease('E4', '2n', '0:3');
  }
This event is triggered by a button click; the first time I try, I heard a truncated sound, then the exception occurs. See first stack trace below. It triggers from my code at the second triggerAttackRelease line.

The same app running in Chrome throws a different exception; see below stack trace. My apologies if this is operator error.

thanks for any suggestions!

1. SAFARI
[Error] InvalidStateError: The object is in an invalid state.
	start (bundle.js:66788)
	start (bundle.js:66788)
	_start (bundle.js:66987)
	start (bundle.js:66021)
	_start (bundle.js:76490)
	start (bundle.js:66021)
	_triggerEnvelopeAttack (bundle.js:77118)
	_triggerEnvelopeAttack (bundle.js:77860)
	triggerAttack (bundle.js:76978)
	triggerAttackRelease (bundle.js:76912)
	play (bundle.js:82873)
	callCallback (bundle.js:23871)
	dispatchEvent
	invokeGuardedCallbackDev (bundle.js:23909)
	invokeGuardedCallback (bundle.js:23958)
	invokeGuardedCallbackAndCatchFirstError (bundle.js:23972)
	executeDispatch (bundle.js:24237)
	executeDispatchesInOrder (bundle.js:24259)
	executeDispatchesAndRelease (bundle.js:24357)
	forEachAccumulated (bundle.js:24338)
	runEventsInBatch (bundle.js:24499)
	runExtractedEventsInBatch (bundle.js:24508)
	handleTopLevel (bundle.js:27972)
	batchedUpdates (bundle.js:36308)
	batchedUpdates (bundle.js:25710)
	dispatchEvent (bundle.js:28053)
	interactiveUpdates (bundle.js:36363)
	dispatchInteractiveEvent (bundle.js:28030)
	dispatchInteractiveEvent

2. CHROME

Uncaught TypeError: Failed to execute 'cancelAndHoldAtTime' on 'AudioParam': The provided double value is non-finite.
    at Tone.Signal.Tone.Param.cancelAndHoldAtTime (Tone.js:3698)
    at Tone.Signal.(:3000/anonymous function) [as cancelAndHoldAtTime] (http://localhost:3000/static/js/bundle.js:60496:29)
    at Tone.Signal.Tone.Param.setRampPoint (Tone.js:3461)
    at Tone.Signal.Tone.Param.linearRampTo (Tone.js:3544)
    at Tone.AmplitudeEnvelope.Tone.Envelope.triggerAttack (Tone.js:4472)
    at Tone.Synth._triggerEnvelopeAttack (Tone.js:20772)
    at Tone.FMSynth._triggerEnvelopeAttack (Tone.js:21515)
    at Tone.FMSynth.Tone.Monophonic.triggerAttack (Tone.js:20633)
    at Tone.FMSynth.Tone.Instrument.triggerAttackRelease (Tone.js:20567)
    at App.play (App.js:129)
