### ISSUE TITLE
Unavailable methods in Tone.Offline?

### ISSUE THREAD

**Issue by softpunch** [Tonejs/Tone.js#231]
I've been experimenting with **Tone.Offline** (using Chrome on a Macbook Pro).

When I use a **Tone.Part**, the offline context fails to render. 
When I set properties for **synth.oscillator** (from a **Tone.Synth**), the offline render fails as well.
[ie using "synth.oscillator.count = 2" on a Fat oscillator makes the render fail]

These methods work as expected when the Offline context is removed; 
if I remove these methods, the Offline context works as expected.

Are these potential errors that I should further debug and report more specifically? 

Or are certain Tone methods expected to fail inside of an Offline context?

**Comment by tambien** [comment]
There's still a few things that need to be sorted out with the Tone.Offline.

Not sure about why setting an oscillator in Tone.Synth would fail (a simple example would be very appreciated), but if you use any of the Transport event classes (like Tone.Part) make sure that you use the Transport that is passed into the Offline context. 

[This example](https://github.com/Tonejs/Tone.js/blob/master/examples/offline.html) uses Tone.Sequence which extends Tone.Part. Take a look at how an offline version of Tone.Transport is passed into the callback which is used to schedule events.

**Comment by softpunch** [comment]
I passed Transport into the Offline context, 
but I'll give Tone.Part another look.

Here's the odd Tone.Synth failure--
working:
https://badfrienddigital.github.io/Tone-Test-FatOscA/

broken:
https://badfrienddigital.github.io/Tone-Test-FatOscB/

**Comment by softpunch** [comment]
Not sure why my Tone.Part was failing in Tone.Offline before, 
but it appears to be working now!

**Comment by tambien** [comment]
@softpunch checking out your broken link just now with the latest dev build and it seems to be fixed. I've since made a few updates to OfflineContext and the offline rendering which seem to have done the job. 

https://jsfiddle.net/8ja4k8fo/
