### ISSUE TITLE
[Tone.Analyzer, Safari] The index is not in the allowed range.

### ISSUE THREAD

**Issue by dschu-lab** [Tonejs/Tone.js#232]
I'm currently having an issue with the `Tone.Analyzer` in Safari 10.1.
When initializing the `Tone.Analyzer` with a `size > Math.pow(2, 10)` (1024) I get the following error:
`IndexSizeError (DOM Exception 1): The index is not in the allowed range.`

Code
-----
```
const sampleSize = Math.pow(2, 13);
    
this.fft = new Tone.Analyser('fft', sampleSize);
this.panVol = new Tone.PanVol().fan(this.fft).toMaster();
```

[Link to WebpackBin example](https://www.webpackbin.com/bins/-KiZLzyQ4bqgsWSwAG1s)

However, I can't find any information on the interwebz, which browser accepts which size, [while the Tone.js documentation](https://tonejs.github.io/docs/#Analyser) mentions, that `the Value must be a power of two in the range 32 to 32768.` [(Same as in the Web Audio API documentation)](https://webaudio.github.io/web-audio-api/#widl-AnalyserNode-fftSize)

Does Safaris Audio APIs getByteFrequencyData haven't implemented higher sizes? 
Would love to implement a highly accurate equalizer, but the sample size needs to be > 4000 for the lower frequencies.

**Comment by tambien** [comment]
This seems like a Safari bug. Looks like they haven't implemented anything larger than 1024 yet.

**Comment by dschu-lab** [comment]
@tambien Thanks for clarifying, I've opened a bug report on bugreport.apple.com and will update this issue, once they reply. (If they'll reply... :sweat_smile:)

**Comment by tambien** [comment]
This is fixed in the latest Safari. Looks like you're bug report helped!
