### ISSUE TITLE
Problems with examples

### ISSUE THREAD

**Issue by dhowe** [Tonejs/Tone.js#240]
https://tonejs.github.io/examples/#shiny

```
%c * Tone.js r10 * 
/build/Tone.js:735  * Tone.js r10 * 
shiny.html:1 Uncaught (in promise) DOMException: Unable to decode audio data
/build/Tone.js:11864 Uncaught (in promise) Tone.Buffer: could not decode audio data: ./audio/505/hh.mp3
shiny.html:1 Uncaught (in promise) DOMException: Unable to decode audio data
/build/Tone.js:11864 Uncaught (in promise) Tone.Buffer: could not decode audio data: ./audio/505/snare.mp3
```

https://tonejs.github.io/examples/#grainPlayer

```
VM2169 Tone.js:735  * Tone.js r10 * 
grainPlayer.html:1 Uncaught (in promise) DOMException: Unable to decode audio data
VM2169 Tone.js:11864 Uncaught (in promise) Tone.Buffer: could not decode audio data: ./audio/FWDL.mp3
(anonymous) @ VM2169 Tone.js:11864
onError @ VM2169 Tone.js:12107
(anonymous) @ VM2169 Tone.js:12142
```

Chromium Version 57.0.2987.133 (64-bit), OSX 10.10.5

**Comment by tambien** [comment]
Hmmm.. all of the examples use mp3s which are not supported by Chromium. i will consider adding a .ogg fallback if mp3 is not supported. 

For your own project check out `Tone.Buffer.supportsType` which will return a boolean if you give a string of either the file or just the type as a string. i.e. `Tone.Buffer.supportsType('mp3')`

**Comment by dhowe** [comment]
thanks much -- actually I am trying to use tone.js together with p5.js to sonify interactive visuals, and I'm having all sorts of problems with timing (it seems to ignore my note durations and quantization values). I've also tried p5.Tone.js, but then I don't get any sound at all in this case. Is there an example I might check (I see funkyShape, but I want to sonify visuals rather than visualize sound, if that makes sense) ?

**Comment by dhowe** [comment]
any thoughts on this ?

**Comment by tambien** [comment]
All of the examples are in the examples folder or [demos](http://tonejs.github.io/demos) page. 

I'm not aware of any issues of using p5 with Tone.js or with the p5.Tone build (which is identical to the other Tone.js builds, but adds a few lines of code that wraps `Tone.Buffer.load` in p5's [`registerPreload`](https://github.com/processing/p5.js/wiki/Libraries#use-registerpreloadmethod-to-register-names-of-methods-with-p5-that-may-be-called-in-preload)). 

If you can narrow down the problems, please open a new issue with a concise example.
