### ISSUE TITLE
Impossible to force stop a Tone.Player once a stop operation has been scheduled

### ISSUE THREAD

**Issue by jraoult** [Tonejs/Tone.js#241]
As discussed here: https://groups.google.com/forum/#!topic/tonejs/-Hl48fqrWts

I noticed that if I have a scheduled `stop` call on a `Tone.Player` (ie: `myPlayer.stop(5)`) and then I "change my mind" and I want to stop the player right now `myPlayer.stop()`, the last call will be ineffective.

Any call to stop will nullify the `_source` property here and make any subsequent stop call effectively noop:
```js
Tone.Player.prototype._stop = function(time){
 if (this._source){
  this._source.stop(this.toSeconds(time));
  this._source = null;
 }
 return this;
};
```

It seems the reference to the source should be kept until `AudioBufferSourceNode#onended` is executed. As a side effect, it probably means that any call to `start` on an already playing player should immediately stop the previous `AudioBufferSourceNode` before creating and starting a new `AudioBufferSourceNode`.

**Comment by tambien** [comment]
Thanks for the issue. Should be fixed now on the dev branch. Will close the issue when `dev` is merged into `master`.  Here's a [jsfiddle](https://jsfiddle.net/xssv87vf/) with the latest dev build. 

As far as your second comment, that's already the behavior of all of the sources. If they are playing, they will stop and restart: https://jsfiddle.net/4arLarr5/

**Comment by jraoult** [comment]
@tambien too fast for me :) I was planning to submit a PR. Anyway, I'll have a look. Thx for the fix.

**Comment by jraoult** [comment]
Confirming the fix on the Dev branch. It also collateraly fixes `Player#seek` which was broken as well.
