### ISSUE TITLE
Suggestion: Export modules with UMD wrapper

### ISSUE THREAD

**Issue by eliot-akira** [Tonejs/Tone.js#244]
It would be convenient to be able to consume the modules separately from a CommonJS project, for example, using browserify or webpack. The latter may support AMD, but it'd be nice to have a ready-made build wrapped in a [universal module definition](https://github.com/forbeslindesay/umd/blob/master/template.js).

As a workaround for now, I added a gulp task that replaces calls to `define` with `require` and `module.exports` statements. The regex patterns are a bit hairy though..

```js
gulp.task("lib", function(done) {

  // Wrap all modules
  const startModule = `module.exports = (function(){`
  const endModule = '\n})();'

  // core/Tone.js
  const matchCoreStart = /define\(function\(\){/g
  // The end of module
  const matchModuleEnd = /\n}\);/
  // The start of module: extract dependency list
  const matchModuleStart = /define\((\[[a-zA-Z\s"\/,]*\]),[\s\n]*function\s*\(Tone\)\s*{/g

  const toRequire = modules => modules.map(m =>
    // Core
    (m==='Tone/core/Tone' ? `var Tone = ` : '')
    // Dependencies
    +`require('${ m.replace(/^Tone\//, '../') }');`
  ).join('\n')+`\n\n${startModule}`

  gulp.src("../Tone/*/*.js")
    .pipe(replace(/('|")use strict('|");/g, ""))
    .pipe(replace(/\t/g, '  ')) // Tab -> spaces
    .pipe(replace(matchCoreStart, startModule))
    .pipe(replace(matchModuleEnd, endModule))
    .pipe(replace(matchModuleStart, function(match, param, offset, string) {
      let modules
      try {
        modules = JSON.parse(param)
      } catch (e) {
        console.error('NO MODULES FOUND', param)
        return match
      }
      return toRequire(modules)
    }))
    .pipe(gulp.dest("../lib/"))
    .on("end", () => {
      // TODO: Verify result
      done()
    });
});
```

**Comment by eliot-akira** [comment]
The gulp task above generates CommonJS-compatible builds of all modules, into a folder called `lib`. This way I can `require('tone/lib/event/Part')`, which has the generated header:

```js
var Tone = require('../core/Tone');
require('../event/Event');
require('../type/Type');
require('../core/Transport');
```

**Comment by tambien** [comment]
Thanks for the suggestion and the code @eliot-akira, but my plan is move all of the classes to es6 import/exports eventually. I don't think i will add UMD headers to all of the classes before then. I hope when all of the modules are rewritten, people like you who need individual file loading can find an es6 module loader for their build system. In the mean time, i hope you can find an AMD module loader for whatever build system you're currently using.
