### ISSUE TITLE
Time#toBarsBeatsSixteenths() Float Issue

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#246]
In certain conditions, I believe the `Time#toBarsBeatsSixteenths()` function can output undesired results due to floating point math.

The specific conditions I can recreate with:
1. BPM of 100
2. a Time object occurring at `0:1:3`
3. the output of that Time object's `toBarsBeatsSixteenths()` will yield `0:1:3.000`

[Reproduced in JS Bin](https://jsbin.com/kaseyasedu/2/edit?html,js,console)

**Comment by tambien** [comment]
To be clear, your desired output is `0:1:3`? 

Does seem like a floating point math error, where the output for the sixteenths notes might have been something like `3.00001` which was truncated to `3.000`. 

Can you submit a PR if this specific formatting is important to your application?

**Comment by JackCA** [comment]
@tambien that's right. And yes, it's a pretty petty issue -- regardless, I'll give the fix a shot. Thanks for checking it out.
