### ISSUE TITLE
Question about AudioNode

### ISSUE THREAD

**Issue by IamEchelon** [Tonejs/Tone.js#251]
I'm using quokka.js to help me prototype a music idea I have and I'm running into this error:
 
![screen shot 2017-08-09 at 5 27 03 pm](https://user-images.githubusercontent.com/3386882/29145604-c3b2d11c-7d2b-11e7-9882-9bca5e6746a7.png)

I dug into the codebase to see if I could find a way to fix this and submit a PR but I'm not sure if this is an error, an intentional design choice, an issue on quokka's end, or user error on my part. Regardless I'm just looking for some insight.

**Comment by tambien** [comment]
Looks like you're trying to run it within Node.js which is not currently possible. Currently it only runs within browsers that support web audio. I'm currently looking into mohayonao/web-audio-engine to see if one day it'd be possible to run with Node as well
