### ISSUE TITLE
Feature request: Choke groups for MultiPlayer

### ISSUE THREAD

**Issue by jas-ableton** [Tonejs/Tone.js#252]
Humble feature request:

It might be a nice addition to be able to specify choke groups, making the playback of certain buffers in a MultiPlayer mutually exclusive.

The most common use case would be choking an open hi-hat with a closed-hat and vice versa.

I could also see the argument for leaving this as the responsibility of the client to implement around the MultiPlayer.

**Comment by k23Burke** [comment]
@tambien I might give this one a whack if no one else has scooped it up. Been looking for a good excuse to contribute lately.

**Comment by tambien** [comment]
Thanks for your offer @k23Burke but i've decided to deprecate MultiPlayers in favor of a new class called Tone.Players which hopefully fixes a lot of the API issues that people were having with MultiPlayers. I wouldn't want you to waste your time implementing a feature on a deprecated class, but i am curious about what sort of API both of you were imagining to deal with choke groups, maybe this is something that can make it's way into Tone.Players

**Comment by jas-ableton** [comment]
After thinking about this a bit more, I feel like it makes more sense to leave this to the client. I feel like it might be a weird addition to a fairly generic class like Tone.Players.

**Comment by k23Burke** [comment]
Yeah, I started playing around with the MultiPlayer class and noticed some bugs concerning the stopAll and state functionality.  I'll throw a PR into the dev branch in case you want to pull it in.

My original thought for implementing choke groups was to allow the choke index to be passed on instantiation of the new object. 
```javascript
var drumMachine = new Tone.Players({
  'kick': {
    'url': '...',
  },
  ...
  'closed-hi-hat': {
    'url': '...',
    'chokeGroup': 0,
  },
  'open-hi-hat': {
    'url': '...',
    'chokeGroup': 0,
  },
```

However, if you are hoping to create buffers similar to `MultiPlayer` it might not be as smooth. If we forgo including it in the instantiation we could still use the below method to add/edit/remove chokes.

A buffers chokeIndex can be updated via a method, `drumMachine.updateChoke('kick', 0)`, potentially with a null value representing a buffer that will not be choked. Internally there would have to be both a way to look up the chokeIndex of a buffer as well as a way to provide the other buffers at that index. It gets tricky when you think about scheduling sounds in the future and how to choke each buffer appropriately.

i.e. drumMachine.start('closed-hi-hat', 300).start('open-hi-hat', 250) feels like it would output "closed-hi-hat start playing at 300, open-hi-hat stop at 300, open-hi-hat start at 250, and closed-hi-hat stop at 250" which seems alright given this instance but could get hairy when there are several items in a single chokeGroup. It could lead to multiple "stop playing" call on buffers that are not active.

**Comment by tambien** [comment]
MultiPlayer has been deprecated in r11 so i am going to close this. 

Interesting feature request tho. We can continue the discussion and try to find an intuitive API for it that we can fit into another class.
