### ISSUE TITLE
Add ability to stopAll(bufferName) on MultiPlayer

### ISSUE THREAD

**Issue by jas-ableton** [Tonejs/Tone.js#253]
I'd like to be able to stop all currently playing players that are associated with a particular buffer when using the MultiPlayer. Calling stop() currently only allows one to stop the oldest player associated with a buffer.

Potential use case: Calling play() a few times on a long running buffer (maybe a crash cymbal or something) and then wanting to mimic grabbing the cymbal and damping it.

Given the way that `MultiPlayer.stop(bufferName)` is currently written, I think it's "safe" to implement this functionality externally by writing something like:

```
        try {
            while(true) {
                mMultiPlayer.stop("crashcymbal"); 
            }
        } catch(e) {}
```

**Comment by tambien** [comment]
I've decided to deprecate MultiPlayers in favor of a new class called Tone.Players which i think addresses many of the API issues and limitations of Tone.MultiPlayers. 

Tone.Players does have a `stopAll` method.

**Comment by jas-ableton** [comment]
Oh that's excellent to hear. Thanks!
