### ISSUE TITLE
Tone.Player.stopAll() and Tone.MultiPlayer.stopAll() not working after overlapping start calls.

### ISSUE THREAD

**Issue by torinmb** [Tonejs/Tone.js#258]
https://jsfiddle.net/torinmb/507nb7c6/21/

Load two audio files into the example and hit the play button at the bottom to randomly play the two notes at overlapping times. Press stop to call stopAll on the player. All the notes should stop playing.

**Comment by tambien** [comment]
Refactored your jsfiddle to use only Player since i think that is the root of the problem. 

https://jsfiddle.net/yotammann/jfwsgyzn/

Player now tracks all BufferSources which are created with 'start' so they can later be stopped. Please verify fix in your example when you get a chance.
