### ISSUE TITLE
Stuck on 13adf7 with a little snap crackle pop

### ISSUE THREAD

**Issue by dezman** [Tonejs/Tone.js#260]
Hey there, thanks so much for this awesome library. 

I've been using it to create what is basically a polyphonic keyboard by playing little clips of the same mp3 together. 

The goal is to be able to generate and play back any chord on the fly within a web app.

To do this I start with an mp3 that sounds like this -- [one second gap chromatic piano](https://s1.vocaroo.com/media/download_temp/Vocaroo_s15ekFEYd9xu.mp3). You can fast forward to the middle of the track to get out of the low end range and hear what is happening.

I load the file using a buffer like so `var buffer = new Tone.Buffer("blahblah.mp3", cb)` and then in the callback I create a set of players like so `var player = new Tone.Player(buffer).toMaster()` that will be used to play back pieces of the same mp3 at the same time.

To play a chord I run this line `player.start(0, audioFileOffset, lengthOfSound)` within a loop adjusting the `audioFileOffset` to the number of seconds within the buffer mp3 file to the location of each note that needs to be played.

This is all well and good and I am very happy with the outcome! But I have two small issues: One is that there are little pops and cracks in the sound occasionally that I can't figure out. And two is I am stuck on this exact commit hash - `13adf7a3eb39948588760e0bed5e43bf48c42d49` when I upgrade I get no errors, but no sound is produced and I can't seem to figure out what changed to make this approach stop working.

I would love to make a jsFiddle to show an example but I was running into CORS issues and so I just posted the relevant code here:

```
var noteNumberHash = {
  'C5': 72,
  'Db5': 73,
  'D5': 74,
  'Eb5': 75,
  'E5': 76,
  'F5': 77,
  'Gb5': 78,
  'G5': 79,
}

var players = []

var buffer = new Tone.Buffer("https://s1.vocaroo.com/media/download_temp/Vocaroo_s15ekFEYd9xu.mp3", function() {
  generatePlayers()
  playNote(players[0], 'C5')
  playNote(players[1], 'E5')
  playNote(players[2], 'G5')
})

function generatePlayers() {
  for (i = 0; i <= 2; i++) {
    var player = new Tone.Player(buffer).toMaster()
    players.push(player)
  }
}

function playNote(player, pitch) {
  var lengthOfSound = 1

  indexOnKeyboard = noteNumberHash[pitch]
  var audioFileOffset = indexOnKeyboard * lengthOfSound

  player.volume.rampTo(-7, 0)
  player.start(0, audioFileOffset, lengthOfSound)
}
```

Let me know if you would like any other information from me!

Also if you think there is a better approach to achieve what I am going for, I am totally open to trying a different way of loading or playing back the sounds.

**Comment by tambien** [comment]
Looks like you're trying to play all of the notes at time 0. Which has probably already passed by the time the page and all of the code loads and is executed. 

To play immediately, replace the 0 in `player.start(0, audioFileOffset, lengthOfSound)` with either the current time (`Tone.now()`) or a time in the future that you'd like the sounds to play.

**Comment by tambien** [comment]
closing assuming that suggestion fixed it...?
