### ISSUE TITLE
Issue with polyphonic samplers

### ISSUE THREAD

**Issue by eloyer** [Tonejs/Tone.js#261]
Thanks for all the work involved in developing this excellent library! The issue I'm running into is with using polyphonic samplers—even though each voice is using the same samples, they all seem to make their own set of network calls to load the audio, which becomes a performance hit for instruments with many voices (we're talking 30 samples, 24 voices in my case)—you end up with hundreds of duplicative network calls. Aside from addressing that issue, if samplers could report when they've finished loading their samples that would help in that I could provide some feedback to the user while the samples are loading. Thanks...

**Comment by tambien** [comment]
I think a single sampler should be totally polyphonic. so no need to load it into a PolySynth if it's all the same sounds. 

Sampler also accepts a callback as it's second argument. But i just took another look at the docs, and it doesn't seem to be in documented. i'll fix that rn.

**Comment by eloyer** [comment]
If I'm using the second argument to pass in params, as in this example below, then how would I specify the callback? Is there a param for it?

https://github.com/Tonejs/Tone.js/blob/master/examples/sampler.html

**Comment by tambien** [comment]
pass in an 'onload' param to the object: 

```javascript
var piano = new Tone.Sampler({
	'C7' : 'C7.[mp3|ogg]',
	'D#7' : 'Ds7.[mp3|ogg]',
	'F#7' : 'Fs7.[mp3|ogg]',
	'A7' : 'A7.[mp3|ogg]',
	'C8' : 'C8.[mp3|ogg]'
}, {
	'release' : 1,
	'onload' : function(){
		//callback after all the samples are loaded
	}
}).toMaster();
```

**Comment by eloyer** [comment]
Great, thanks. So far, I'm getting "Tone.BufferSource: buffer is either not set or not loaded." errors. All of the samples are loading, but the onload event callback never runs (this is in Safari 10.1.2). Any ideas? Thanks...

```javascript 
this.piano = new Tone.Sampler({
	C0: "C0.wav",
	C1: "C1.wav",
	C2: "C2.wav",
	C3: "C3.wav",
	C4: "C4.wav",
	C5: "C5.wav",
	C6: "C6.wav",
	C7: "C7.wav"
} , {
	'baseUrl': 'stepwise/effects/samples/UIowaPiano/', 
	'onload': function() { 
		console.log('loaded'); 
	}
}).toMaster();
```

**Comment by tambien** [comment]
Are you using the latest release r11? Sampler's API was recently changed, so if you're on r10 it won't work. 

If that's not the issue, can you post an example somewhere?

**Comment by eloyer** [comment]
Yep, I'm on r11. Could it have something to do with running local? My tests have been local, but when I ran the project from a server it worked.

**Comment by tambien** [comment]
Just to recap: 
* using Tone r11
* you're running a local server and accessing your page through `http://localhost` NOT `file://`
* all of the buffers are loading (no `XMLHttpRequest cannot load` errors)
* onload callback is never invoked
* you only experience the error when running locally and not when pushing to a remote server

did i get all that right? 

You mentioned that you're getting the error: `Tone.BufferSource: buffer is either not set or not loaded`. but also that the onload callback was never invoked. If you try to play a note before the samples are loaded, you will get that error.

Please post a larger section of code, or link to an example (even if it's working i can take a look or download it and try running locally). I'm able to get all of this running on my end when i test with a very similar setup.

**Comment by eloyer** [comment]
The only thing that's not accurate in your list is that when I'm running locally I'm using a `file://`` URL.

Here's my example: http://step.works/dev/business-story.html (press keys to advance)

All of the Tone.js stuff happens in this file: http://step.works/dev/stepwise/effects/TonePiano.js

**Comment by tambien** [comment]
i think XHR requires a server to be running. I recommend python's SimpleHTTPServer or [http-server](https://www.npmjs.com/package/http-server) in node.js for developing locally.

**Comment by eloyer** [comment]
OK thanks!

**Comment by tarekuino** [comment]
Hey,

I'm using this piece of code
synth = new Tone.Sampler({
'A0' : 'A0.wav',
'C1' : 'C1.wav',
'D#1' : 'D#1.wav',
'F#1' : 'F#1.wav',
'A1' : 'A1.wav',
'C2' : 'C2.wav',
'D#2' : 'D#2.wav',
'F#2' : 'F#2.wav',

It was working fine with fewer number of files but now its not working anymore.
and im running it inside of a local host and getting error 

![image](https://user-images.githubusercontent.com/34999210/78175073-95f59600-745a-11ea-8d33-d040e83da841.png)

**Comment by tambien** [comment]
is it possible that your server is interpreting the `#` as a hash url parameter? Maybe try replacing the `#` with another symbol, so for example `A#3.wav` -> `Asharp3.wav`.

**Comment by tarekuino** [comment]
SOLVED!!
The problem was using the '#' in the filename

Thank you soo much
