### ISSUE TITLE
[Doc] Setting Transport.seconds triggers a play event when state is "started"

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#263]
If this is the desired behaviour, you might want to add that in the documentation. If not, then it's a bug.

**Comment by tambien** [comment]
When the `Transport.seconds` or `Transport.ticks` change, all synchronized sources and events also need to update their position, which is why the Transport triggers a "stop" and "start" event in quick succession. 

I'll update the documentation to make this more clear.

**Comment by maximedupre** [comment]
Thanks for the reply. It actually does not trigger a "stop" event in my case, only a "start" event.
