### ISSUE TITLE
github.io links to JSFiddles which throw errors - this._analyser.analyse 

### ISSUE THREAD

**Issue by Nogbit** [Tonejs/Tone.js#267]
I was going to report this as a bug, but then I tried the same code in the [dev build fiddle](https://jsfiddle.net/kyqnbr7d/) that your issue template links to and these errors don't occur.  I thought I would report it anyway and hoping that the github.io pages get updated soon.

The errors occur when using the Fiddles or clicking on "result" at https://tonejs.github.io/ for most of the examples and the console fills up with the following error.

```JavaScript
VM1058 Waveform.js:1 Uncaught TypeError: this._analyser.analyse is not a function
    at r._loop (VM870 Waveform.js:1)
```

By the way, this library is flat out amazing and some serious thought and work has gone into this.  I've been diving in the last few days and nearly ready to start writing some code.

**Comment by tambien** [comment]
Thanks for the heads up. I updated it to the new Tone.Waveform API and it should be fixed now.
