### ISSUE TITLE
Feature request: true FFT/IFFT

### ISSUE THREAD

**Issue by mattdiamond** [Tonejs/Tone.js#268]
First off, great library... very comprehensive and intuitive API. Thanks for building this.

I'm wondering if you have any plans to include a true FFT node in addition to an IFFT node. I say "true FFT" because your current implementation uses the Web Audio Analyser Node, which (as I understand it) returns frequency data but no phase data.

And IFFT, of course, would be a full reversal of the process, taking in frequency/phase data and producing the corresponding waveform.

You can do a lot of cool stuff with FFT/IFFT. For example, I built a [phase randomizer app](http://matt-diamond.com/fft.html) using the [JSFFT](https://github.com/dntj/jsfft/) library. It allows you to create interesting drones from audio source material.

It would be cool if Tone.JS had this kind of functionality. It would be even cooler if the FFT/IFFT nodes handled the process of converting between complex numbers and frequency/phase data. I had to add these functions to my code when I was building that phase randomizer app:

```javascript
function complex2freq(obj){
  return {
    amp: Math.sqrt(Math.pow(obj.real, 2) + Math.pow(obj.imag, 2)),
    phase: Math.atan2(obj.imag, obj.real)
  };
}

function freq2complex(bin){
  return {
    real: bin.amp * Math.cos(bin.phase),
    imag: bin.amp * Math.sin(bin.phase)
  };
}
```

**Comment by tambien** [comment]
Thanks for the the question. Currently, i've got no plans to include FFT/IFFT outside of what the AnalyserNode provides, though i am a little swayed given how cool your demo sounds...

One big issue is that it can't currently be done in real time without using the (deprecated) ScriptProcessorNode. I've been focusing entirely on processing that can be done in real-time. 

[Meyda](https://github.com/meyda/meyda/) is good options for doing fft/ifft offline or using the ScriptProcessorNode. i think it might use JSFFT internally.
