### ISSUE TITLE
r11 Deprecation warnings on Chrome 63 /  GainNode.gain.value setter smoothing  and  OscillatorNode.frequency.value setter smoothing

### ISSUE THREAD

**Issue by alperakgun** [Tonejs/Tone.js#282]
I don't know if it requires any action. Just in case, I'm opening this ticket. 

[Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

[Deprecation] OscillatorNode.frequency.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

**Comment by tambien** [comment]
Thanks for the note! I actually opened [a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=649681) about this with Chrome about a year and a half ago. The setter smoothing they had implemented until now was not defined in the specification and was usually not the desired behavior, so i'm glad to finally see it corrected.
