### ISSUE TITLE
Sampler crackles then stops on mobile

### ISSUE THREAD

**Issue by DennisvHest** [Tonejs/Tone.js#285]
Hi, I am using tone.js for playing a midi file using midiconvert. I am using the sampler along with a piano sample (the same one used in the sampler example). Everything plays fine on desktop browsers, but on mobile browsers it seems to play fine for a while but then starts crackling and then stops playing.

I assume this is a performance thing and mobile browsers just can't handle it, but is there any way to optimize this? I have tried changing the latencyHint and reducing the sample file size, but that doesn't seem to really do anything.

Here is my project: [http://midiflip.azurewebsites.net/](http://midiflip.azurewebsites.net/)

Here is a snippet of the code:
```javascript
var piano = new Tone.Sampler({
    'A0': "A0.[mp3|ogg]",
    'C1': "C1.[mp3|ogg]",
    'D#1': "Ds1.[mp3|ogg]",
    ...
}, {
    'release': 1,
    'baseUrl': "/content/audio/"
}).toMaster();
```

```javascript
//Parse the flipped midi file
var flippedMidi = MidiConvert.parse(e.target.result);

Tone.Transport.bpm.value = flippedMidi.header.bpm;

//Create a Tone part for each rack in the flipped midi
for (var trackNr = 0; trackNr < flippedMidi.tracks.length; trackNr++) {
    var track = flippedMidi.tracks[trackNr];

    var midiPart = new Tone.Part(function (time, note) {
        piano.triggerAttackRelease(note.name, note.duration, time, note.velocity);
    },
        track.notes);

    //Get the total time in seconds of the flipped midi sequence
    if (track.notes.length !== 0) {
        var trackEnd = track.notes[track.notes.length - 1].time + track.notes[track.notes.length - 1].duration;

        if (trackEnd > sequenceEnd)
            sequenceEnd = trackEnd;
    }

    midiPart.start(0);
}
```

Thanks for the awesome library!

**Comment by tambien** [comment]
Looks like you're doing everything right from what i can tell. Might simply be a performance limitation of the device... what device are you testing it on? I can't reproduce the issue since i don't have any midi files on my phone.

**Comment by DennisvHest** [comment]
I'm using a Motorola Moto G4, which is a low/mid-end smartphone. I don't have any other devices to really test it on. But yeah, it is probably a performance limitation. I guess i'll have to use a synth on mobile since those do work fine on mobile.
