### ISSUE TITLE
Source of keyboard?

### ISSUE THREAD

**Issue by panfanky** [Tonejs/Tone.js#287]
Hi,
would it be possible to make available the uncompressed code of https://github.com/Tonejs/Tone.js/blob/dev/examples/scripts/Keyboard.js used in Synth examples?

(I tried to develop my own polySynth interface using touchstart and touchend, but ended up in "Aw, snap!" errors with Chrome - but yours seems to work nice)

Or is it licensed and made non-open source on purpose? Just asking. Thanks!

**Comment by tambien** [comment]
The source is very similar to [this](https://github.com/googlecreativelab/aiexperiments-sound-maker/tree/master/src/keyboard). hope that helps!
