### ISSUE TITLE
Add to Tone.js real instruments for music applications

### ISSUE THREAD

**Issue by surikov** [Tonejs/Tone.js#290]
Hi

I can add to Tone.js new synth that plays real instrument (piano, guitar, drums, etc).
All wave tables hosts on GitHub, there are more 1000 instruments.

How I can add this synth in Tone.js?

I created code, see example without drums (you can select any instrument from dropdown menu and play keyboard)

[http://molgav.nn.ru/tonejs1000instr/examples/simpleSynthWebAudioFontInstrument.html](http://molgav.nn.ru/tonejs1000instr/examples/simpleSynthWebAudioFontInstrument.html)

but I can't commit it into master (or dev) branch.

I need access to commit this improvement.

**Comment by tambien** [comment]
cool demo! I think Tone.Sampler could be used to playback these files, but currently there's no way in Tone.js to decode `.sf2` files. If you've got a pure javascript way to decode this file type, please send a pull request. i think that'd be a useful addition to Tone.Sampler. 

I could imagine the API being something like:  

```javascript
const sampler = Tone.Sampler.fromSF2(linkToFile.sf2)
```

I think it'd be most useful to open it up to all sf2 file types, not just the ones that you've got preprocessed and hosted on github.

**Comment by surikov** [comment]
you can't use sf2 files in web due of big size. this is why i convert files into web friendly scripts.

Moreover, good implementation requires extended features for chords, palm mute, AHDSR,  etc.

I can add all this instruments, drums and strum features into your project.

How i can add my improvement into Tone.js? Do i need to create new branch?

**Comment by tambien** [comment]
Fork the project, add your changes and submit a PR. More instructions [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/). 

Be sure to fork the `dev` branch and submit your PR back to the `dev` branch. I don't accept changes on the `master` branch

How do you convert the large sf2's to your json format?

**Comment by surikov** [comment]
ok, i will try. 

Look at my project carefully. There are no JSONs. All instruments are js. So anybody can use sounds from GitHub hosting and avoid CORS problem. There are THOUSANDS of instruments and drums.

**Comment by colemahatmccreary** [comment]
did you guys ever look at this? can't tell if there is a way to run webaudiofont sounds through Tone.

i think it would be a great implementation for both projects, if not already possible.

**Comment by stephaneeybert** [comment]
Any progress on this instruments integration ?

**Comment by praisethemoon** [comment]
> ```js
> const sampler = Tone.Sampler.fromSF2(linkToFile.sf2)
> ```

I have found an external package to load and parse sf2 files, I think it is a pretty cool idea to have this API !

The package to load sf2 files is: https://github.com/Mrtenz/soundfont2 
It also has nice docs 😄 

However I do not really understand the structure of this data (yet) nor the internals of ToneSampler (yet). I will give this a shot but no promises, any tip would be much appreciated!
