### ISSUE TITLE
Tone.Player should consider playbackRate when calculating duration and stopTime

### ISSUE THREAD

**Issue by clademann** [Tonejs/Tone.js#292]
When you change the playbackrate of a Tone.Player, the duration of the source will still be calculated as if the rate was 1, the consequence being that the player will stop either too early (playbackRate < 1) or too late (playbackRate > 1), when it should play up to the end of the source. 
Maybe one could provide a calculated duration (calculatedDuration = originalDuration / playbackRate) as the duration argument for player.start() but that doesn't work for synced players, as there is no duration parameter for Tone.Transport.start().
Thank you very much!

**Comment by tambien** [comment]
good catch. currently the BufferSource invokes `stop` from the `start` method with the computed duration, but if the playbackRate changes, as you point out, then the duration will also change. 

To simplify things, i removed the call to `stop` from within the `start` method. The one downside is that the fadeOut curve used to be automatically applied to the beginning and end of the buffer when calling `start`, but now it is only applied to the start of the buffer, and the fadeOut is only applied when `stop` is explicitly called.

**Comment by clademann** [comment]
Thank you very much!

**Comment by clademann** [comment]
There is still some small issue to resolve: the Tone.source.Player still places the duration-parameter to source.start() so that the source gets clipped to the duration when the playbackRate is < 1. 
I got around this recalculating duration = duration / this._playbackRate.
