### ISSUE TITLE
Question: does tone.js work well on React Native?

### ISSUE THREAD

**Issue by jamesharvey2** [Tonejs/Tone.js#293]
Hello guys,

I haven't really tried this yet. 
Is there anyone using Tone.js on React Native android / iOS? 
React Native is fully based on javascript.. and I think it may work with tone.js without any issue.

Thanks,

**Comment by Idicious** [comment]
I don't believe that the web audio api which Tone.js is based on works outside of a webview on mobile. I looked into web audio with react native and found very little on it. You can look at this issue on it:
https://github.com/facebook/react-native/issues/1179

**Comment by jamesharvey2** [comment]
I found this by the way: 

https://github.com/Izzimach/react-webaudio

**Comment by jamesharvey2** [comment]
and this:

https://github.com/joewood/react-native-amazing-audio

**Comment by Idicious** [comment]
There are several audio packages out there for react native, just none that are based on the web audio api. Using it together with Ionic (or react for that matter) should work as they all work inside of a webview in a hybrid app.

**Comment by jamesharvey2** [comment]
I see.. I was looking to use tone.js on react native because react native is javascript based. 
I'm requesting facebook to implement web audio api:
https://github.com/facebook/react-native/issues/17591

Web Audio API ships with all necessary features any audio app developer will need.. too bad facebook guys didn't implement it. 
What other react native audio package come close to Tone.js? I don't think there's any.

**Comment by jamesharvey2** [comment]
Wait, React Native has WebView as well! 

https://facebook.github.io/react-native/docs/webview.html

What If I use tone.js on this webview then?

**Comment by sinewave440hz** [comment]
@jamesharvey2 Did you ever try this and if so, how did it go?

**Comment by florianmaxim** [comment]
@jamesharvey2 A working example on this would be amazing!

**Comment by kemenesbalazs** [comment]
I am experimenting with Tone.js inside WebView using a WebView bridge solution to create two way communication and serialize-deserialize commands. Will keep you updated if still interested in a solution.

**Comment by kemenesbalazs** [comment]
Used this static html, and a custom hook to dispatch functions in ToneJS via a webview. No 2 way communication, and static strings are an ugly solution. Just keep it here, if anyone wants to setup a quick demo.

`<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tone/13.0.1/Tone.min.js"></script>
    <script>
      // Initialite synth object
      var synth = new Tone.PolySynth(6,Tone.Synth).toMaster();
    </script>
  </head>
  <body>
  </body>
</html>`

`
export type ToneJS = {
  attack: (number) => {};
  release: (number) => {};
};

export const useToneJS = () => {
  const webViewRef = useRef();

  const webView = (
    <WebView
      source={{ html: bridgeSite }}
      originWhitelist={["*"]}
      style={{
        flex: 0
      }}
      javaScriptEnabled={true}
      ref={webViewRef}
    />
  );

  const attack = (hz: number) => {
    webViewRef.current.injectJavaScript(`
      synth.triggerAttack("${hz}");
    `);
  };

  const release = (hz: number) => {
    webViewRef.current.injectJavaScript(`
      synth.triggerRelease("${hz}");
    `);
  };

  return [{ attack, release }, webView];
};`

**Comment by ttm** [comment]
has anyone tried this webview approach recently or has any news regarding the usage of Tone.js on React Native?

**Comment by joshuadutton** [comment]
I just found this: https://docs.swmansion.com/react-native-audio-api, but I don't know yet if it will work with tone.js.

Edit: it likely won't. There is a lot of the API still not covered: https://docs.swmansion.com/react-native-audio-api/other/web-audio-api-coverage

**Comment by michalsek** [comment]
@joshuadutton Hey, thank you for checking us out! As you have properly written, Tone.js isn't supported by the `react-native-audio-api` at the current moment. 

The not covered API is rather a minor problem (we could stub it and by trial-and-error check what is working in tone.js), but the really tricky part is that f.e. tone.js uses `createElement` to create an `<audio />` tag in order to check for supported file types. 

So far we haven't figured out a way to workaround that without creating a custom react-native fork of Tone.js

**Comment by RemyNtshaykolo** [comment]
> [@joshuadutton](https://github.com/joshuadutton) Hey, thank you for checking us out! As you have properly written, Tone.js isn't supported by the `react-native-audio-api` at the current moment.
> 
> The not covered API is rather a minor problem (we could stub it and by trial-and-error check what is working in tone.js), but the really tricky part is that f.e. tone.js uses `createElement` to create an `<audio />` tag in order to check for supported file types.
> 
> So far we haven't figured out a way to workaround that without creating a custom react-native fork of Tone.js

Hello Michael, is this something you have on your roadmap?

Thanks

**Comment by michalsek** [comment]
@RemyNtshaykolo Hey :) 

Yes it is something we keep in our mind from the very beginning. But it is hard to predict when we will be able to support it 😅 

A bit unpredicted list of things to do awaits us :)
- TS layer that would be accepted by standarized-audio-context
- patch-lib that could provide tone.js with native implementations for certain parts
- whatever we would need to do with browser based interfaces like `EventMap` or `EventTarget`


buut we will get there 🙂
