### ISSUE TITLE
React Native WebView & Node Audio API for Tone.js? 

### ISSUE THREAD

**Issue by jamesharvey2** [Tonejs/Tone.js#294]
Hi guys,

I found React Native ships with WebView that is same as that of normal java apps. 
https://facebook.github.io/react-native/docs/webview.html

and there's a node package for web audio api that can be installed in react native.
https://github.com/audiojs/web-audio-api

React Native doesn't have web audio capability... is it possible to use tone.js on webview layer of react native? given that I install that web audio api node package? 
Will it make proper sound through filter, oscillator, etc? 

I wonder if anyone has tried this yet.

Thanks,

**Comment by Idicious** [comment]
In a webview you shouldn't have to install the nodejs web-audio-api, it should just work out of the box as all modern browsers (including webview's I believe) implement the web api. As long as you're in a webview you should be able to use Tone.js
You could actually try and use react native + web-audio-api for node + Tone.js and see if you can get that working. I don't know how close to the actual web audio spec it is so there will probebly be some compatibility issues.
If you don't need a presence in the app store you could consider making it a PWA and skip the native layer altogether unless you need some very specific native functionality and just go with React + Tone.js

https://developers.google.com/web/progressive-web-apps/

The largest downside of this is that iOS doesn't support service workers yet (it is currently in developement) so the offline functionality won't work on iOS.

**Comment by jamesharvey2** [comment]
Hi, thanks for your suggestions.

Yes, that web audio api node is incomplete. It doesn't have all features of real web audio api. 
I'm trying to create a native app using this tone.js... then I guess Cordova would be the solution or perhaps using webview only in react native. 
Too bad facebook guys didn't implement web audio api to react native!

**Comment by jamesharvey2** [comment]
@Idicious 
By the way, I found a native app framework which can use web audio functionality & native control: 

https://github.com/NativeScript/NativeScript/issues/5270#issuecomment-357887761

Native Script can use web functionality while using native UI. You can simply call web functionality to your native UI! www.nativescript.org
NativeScript is based on Angular, Typescript, XML. 
I think it can use Tone.js ?

**Comment by Idicious** [comment]
@jamesharvey2

I think that might work, you'd have to load the Tone.js script into the web view and you could probably make it directly callable in your code with something like the following, I'm unsure of exact syntaxes. 
You might be able to even split it into a service class that exports the Tone variable. 

```
const Tone = webview.window.Tone;
Tone.Transport.start();
```
I'm interested how it works out, this would be pretty awsome.

**Comment by jamesharvey2** [comment]
Yes, I this one is the only Native app framework which supports Web Audio API. 
So you can call web audio api from native UI and use its functionality... 

React Native can't do that.. Cordova can use Web audio API but Cordova isn't the best solution for high quality apps. Other native frameworks like Xamarin don't even care about web audio anyways so.. 

I will give it a try. NativeScript is 90% just Angular 5... although with reduced CSS3 style properties.

**Comment by Idicious** [comment]
This might work the same way with react native, create a webview with a page with the Tone.js script loaded and get a reference to webview.window.Tone to use in the rest of the app. If you could keep the webview invisible you could hook it up however you like to the native UI.

**Comment by jamesharvey2** [comment]
Yes, that would work too. So I have to set webview's display to none and build native UI based on it. 
Then I wonder why so many people were troubled with using Tone.js on React Native. 
A bad news is Facebook team will remove webview from React Native in future version. 
React Native is inarguably better for UI design because it supports SVG, Canvas API, more CSS3 properties.. 
NativeScript ships with bare minimum CSS3 and it doesn't work well with SVG and other UI components. 
Each framework has pro and cons..  I think Angular 5 has better programming logic than React. 
I will try both to find out. 
I want to know if setting webview's display to hidden on react native is possible.

**Comment by jamesharvey2** [comment]
A problem of using Web Audio API on WebView layer is.. some android devices may not work well with HTML5 audio. 
That's what other people pointed out as a downside of using HTML5 audio in an app. 

I want to know if there's a way to get output of HTML5 audio and connect it to android's native output. 
Android's native output uses Java to play sound.

**Comment by Idicious** [comment]
@jamesharvey2 
You might be able to use a ScriptProcessorNode as a master output and then stream from that into native android audio. This would definately incur a latency penalty and I'm not sure why you'd want to do that, the web audio api will output it to the native android audio output.

**Comment by jamesharvey2** [comment]
Oh I see.. so it does output to native audio output. I think someone told me HTML5 audio is not stable on some android devices.. but I guess if that's in a WebView wrapped in a native app, it's fine.

**Comment by tambien** [comment]
Going to close this. Tone.js only works on environment which support the Web Audio API. So WebViews should work fine

**Comment by florianmaxim** [comment]
> This might work the same way with react native, create a webview with a page with the Tone.js script loaded and get a reference to webview.window.Tone to use in the rest of the app. If you could keep the webview invisible you could hook it up however you like to the native UI.
> 
> Something along the lines of:
> 
> ```
> let Tone;
> 
> const webView = new WebView();
> webView.visible = false;
> 
> export default () => {
>        return new Promise((resolve, reject) => {
>            if(Tone == null) {
>                webView.onload = () => {
>                     Tone = webView.window.Tone;
>                     webView.onload = undefined;
> 
>                     return resolve(Tone);
>                }
>                webView.content = 'pagewithtone.html';
>            } else {
>                    return resolve(Tone);
>           }
>        }
> }
> ```
> If the above would be in a file named tone.js use in other files with the following:
> 
> ```
> import getTone from './tone.js';
> 
> getTone.then(Tone => {
>      // use Tone however you like
> })
> ```

Do you have a working example on this?

**Comment by Idicious** [comment]
@florianmaxim Sadly no, this was just pseudo code with an idea that could be tried out. I don't see why it wouldn't work unless hidden webview's are put on low priority so latency becomes a serious issue or the window properties are not accessible from the outside.

**Comment by florianmaxim** [comment]
@Idicious This is actually too bad, because your approach seems so logical to me:  Apparently, the window object is just not accessible..  Plus, there doenst really seem to be any proper synths out there for react native.. Any other approach to get Tone.js to run on RN?

**Comment by kemenesbalazs** [comment]
#293

**Comment by martijnmichel** [comment]
Does anyone know how to do this with react-native-webview ?
