### ISSUE TITLE
Tone.Player and Tone.Players buffer remains null

### ISSUE THREAD

**Issue by Idicious** [Tonejs/Tone.js#295]
I'm sure I must be missing something here. I'm trying to setup a click track, I've tried a few different audio files to make sure they are aren't the problem.

```
/**
 * Loads audio tracks of click and connects them to master output
 */
const clickTrack = new Tone.Players({
    "high" : "/public/audio/click/high.wav",
    "low" : "/public/audio/click/low.wav"
}, () => store.dispatch(transport.clickLoaded())).toMaster();

/**
 * Click track playback loop
 */
const clickLoop = new Tone.Part((time, value) => {
    clickTrack.get(value.type).start();
}, [{type: "low", time: "4n"}, {type: "high", time: "1m"}]);
clickLoop.loop = true;

/**
 * Enables the clickTrack
 */
const startClick = (action) => {
    if(clickTrack.loaded) {
        clickLoop.start();
        store.dispatch(action);
    }
}

/**
 * Disables the clickTrack
 */
const stopClick = (action) => {
    if(clickTrack.loaded) {
        clickLoop.stop();
        store.dispatch(action);
    }
}
```

clickTrack.loaded remains false and the event never fires. I have tried it with 2 seperate players and am having the same issue. I can see the audio files are loaded in the network tab and I'm not getting any console errors or warnings, if I disable the loaded check hower I get the following error no matter how long I wait:

```
Error: Tone.BufferSource: buffer is either not set or not loaded.
    at Tone.BufferSource.start (f:\Sources\Idicious\mmu-react\node_modules\tone\build\Tone.js:15822:1)
    at Tone.Player._start (f:\Sources\Idicious\mmu-react\node_modules\tone\build\Tone.js:22540:1)
    at Tone.Player.Tone.Source.start (f:\Sources\Idicious\mmu-react\node_modules\tone\build\Tone.js:9023:1)
    at Tone.Part../src/services/transport.js.__WEBPACK_IMPORTED_MODULE_0_tone___default.a.Part.type [as callback] (f:\Sources\Idicious\mmu-react\src\services\transport.js:18:1)
```

I have a few similar functions in the same file that are working:

```
    /**
     * Start playback
     */
    const start = (action) => {
        Tone.Transport.start();
        store.dispatch(action);
    }

    /**
     * Set bpm to given value
     * 
     * @param {any} action 
     */
    const setBpm = (action) => {
        const { bpm } = action.payload;
        if(!isNaN(bpm) && bpm > 0 && bpm <= 1024) {
            Tone.Transport.bpm.value = bpm;
            store.dispatch(action);
        }
    }
```

**Comment by Idicious** [comment]
I thought it might be the way I was importing it so I changed it from:
```
import Tone from 'tone';
```
to:
```
import { Players, Part, Time } from 'tone';
``` 

but this made no difference, everything except for the players seems to be working.

**Comment by tambien** [comment]
maybe there is an error decoding the audio files? I am able to recreate a similar snippet without any problems: https://jsfiddle.net/rdsypj05/5/

It's possible that an error is being caught in a try/catch somewhere and never surfacing

**Comment by Idicious** [comment]
@tambien 
It was an issue with the audio files, it's working now. It's a bit odd though considering I tried several audio files which I've loaded and decoded successfully in another project (using vanilla web audio api), both wav and mp3.

**Comment by tambien** [comment]
strange. I don't think Tone.js is doing anything different than a vanilla implementation would do. [simply loading with an XHR and decoding the audio data](https://github.com/Tonejs/Tone.js/blob/dev/Tone/core/Buffer.js#L431). 

If you have a link which minimally reproduces this, that'd be helpful for debugging why it would decode in one situation and not another.

**Comment by nightshining** [comment]
Having a very similar issue. 
* I've linked to multiple cdn's and also tried using a local tonejs lib file, Tone lib properly links. 
* I've tried both local path sound files (mp3) and files on my git repo paths.
* All instances come up with 'Uncaught Error: Tone.BufferSource: buffer is either not set or not loaded.' and when I check that my 'sampler' object has been created it has, says file loaded, but in buffer it still shows 'null'

`var sampler = new Tone.Sampler({
			'C3' : 'https://nightshining.github.io/NSWebGen/assets/samples/chord.mp3'
			//'D3' : 'tones.[mp3|ogg]',
			//'E3' : 'cymbal.[mp3|ogg]',
			//'F3' : 'piano.[mp3|ogg]',
      //'G3' : 'synth.[mp3|ogg]',
		}, {
      //'release' : 1,
      //'baseUrl' : 'https://nightshining.github.io/NSWebGen/assets/samples/'
     }).toMaster();
 sampler.triggerAttack("C3")`

**Comment by JasonPing** [comment]
Hi @nightshining , I try your audio file "https://nightshining.github.io/NSWebGen/assets/samples/chord.mp3" and It works as expected. So your audio file has no issue. Also, we do need to load samples in preload function in the latest version of Tone.js (13.4.9). If p5.Tone.js doesn't work, I think just use the latest version of Tone.js.
