### ISSUE TITLE
set not working as expected when passing args programatically 

### ISSUE THREAD

**Issue by KonVas** [Tonejs/Tone.js#300]
Trying to pass par (string) won't work, but when I change par with "attack" it will work. However, when checking with typeof par it returns string. Trying to control other parameters will work only with detune. Par is coming from a table-matrix with headers as exact label for each parameter. 
![screen shot 2018-02-06 at 18 33 25](https://user-images.githubusercontent.com/6897992/35867965-44bd1244-0b6c-11e8-8613-4e78e0a10b73.png)

```
'click #matrix-input': function(event, template){
            var selected = template.findAll("input[type=checkbox]:checked");
            var par = $(event.target).attr('class');
            var fieldValue = event.target.value;
            if(par !== ""){
                polySynth.set({ //control of envelope properties.
                    "envelope" : {
		                    par : specs[par](fieldValue)
	                  }
                });
                polySynth.set(par, specs[par](Number(fieldValue))); //control other parameters of the synth.
                //console.log(par, fieldValue);
            }
        }
```

**Comment by Idicious** [comment]
```
polySynth.set({ //control of envelope properties.
                    "envelope" : {
		                    par : specs[par](fieldValue)
	                  }
                });
```

This will not set the key of the object to the value in par, the key will be 'par'. This is because of how javascript works btw, it's not a Tone.js specific thing. In order to use the value of par as key you have to do the following:

```
function(event, template){
    var selected = template.findAll("input[type=checkbox]:checked");
    var par = $(event.target).attr('class');
    var fieldValue = event.target.value;
    if(par !== "") {
        var envelope = {};
        envelope[par] = specs[par](fieldValue);
        polySynth.set({ //control of envelope properties.
            "envelope": envelope
        });
        polySynth.set(par, specs[par](Number(fieldValue))); //control other parameters of the synth.
        //console.log(par, fieldValue);
    }
}
```

**Comment by KonVas** [comment]
Great, thanks for the help. How can I change the value of the array that sets the voices of the polySynth, can I do something similar to the "envelope" way as above, or any other better solution would be much appreciated. Thanks!
