### ISSUE TITLE
Modify events of Tone.Part while it plays

### ISSUE THREAD

**Issue by hatsumatsu** [Tonejs/Tone.js#304]
Using `Part` I set up a very basic loop with a bunch of steps via `triggerAttackRelease`. Is there a way to change the note and time of these steps in the loop on the fly while the loop is playing? (Imagine having slider inputs to change the values) Looks like `Part` doesn't have methods to modify its events. Could you point into the right direction how to achieve this?

Thanks in advance!

**Comment by brokyo** [comment]
Don't know if it's exactly what you need but I do this with a self calling function that uses `Tone.Transport.schedule`. It doesn't natively give you all the stuff that comes with `Tone.Part` but you can get there with some math.

Got a [working example here](https://codepen.io/brokyo/pen/opgeMY?editors=0110) if it's of any use :)

**Comment by hatsumatsu** [comment]
@brokyo Thanks, that is exactly what I was looking for. Here is a minimal example for everyone else interested:

`````
// changing these values directly affects the loop
var notes = [
   'C2', 'G2', 'C3'
]
// changing these values directly affects the loop
// ( 0 ... 1 in the bar )
var times = [
   0.25, 0.333, 0.85
]

Tone.Transport.scheduleRepeat( function( time ){            
    synth.triggerAttackRelease( notes[0], '16n', '+' + times[0].toNotation(), 0.5 ); 
    synth.triggerAttackRelease( notes[1], '16n', '+' + times[1].toNotation(), 0.5 ); 
    synth.triggerAttackRelease( notes[2], '16n', '+' + times[2].toNotation(), 0.5 );             
}, '1m' );        
        
Tone.Transport.start();
`````
