### ISSUE TITLE
Changing the frequency of notes

### ISSUE THREAD

**Issue by riyalohia** [Tonejs/Tone.js#305]
Hii!!
I think there is a need of a function (may be setFrequency) that can change the frequency of notes or pitches.
(I am new here ...so not sure if it is already present or not)

**Comment by walterbender** [comment]
On Feb 11, 2018 4:34 AM, "Riya Lohia" <notifications@github.com> wrote:

> Hii!!
> I think there is a need of a function (may be setFrequency) that can
> change the frequency of notes or pitches.
>

setNote() does what I think you are asking.

https://tonejs.github.io/docs/r11/MonoSynth#setnote

regards.

-walter

**Comment by riyalohia** [comment]
@walterbender Thank you :)
