### ISSUE TITLE
Slight delay in triggering a note

### ISSUE THREAD

**Issue by ambewas** [Tonejs/Tone.js#306]
Hi,

I'm building a react library on top of tonejs (https://github.com/ambewas/react-audio-tools) that allows anyone to create an audio application easily by routing different components together. 

I'm adding midi and computer keyboard support for playing.

This is where I've noticed there's always a slight delay between calling `someSynth.triggerAttack(someNote)` and actually hearing the produced sound. 

It is only slight, but very noticeable as a musician. 

Am I doing something wrong in my interpretation of how to use tone.js ? Or is this a known limitation of the library (and perhaps the webaudio api itself) ?

You can hear the problem in the demo -> http://react-audio-tools.surge.sh/

The code I'm using for triggering and releasing monophonic synths can be found here: https://github.com/ambewas/react-audio-tools/blob/master/src/lib/helpers/handleMonophonicNoteTriggers.js

As you can see, I'm basically calling `.triggerAttack()` and `triggerRelease()` based on some logic. At first I figured it might have been an issue with that code, but I've got the same delay if I just call `triggerAttack()` on any keypress.

Thanks in advance for any insight you can provide!

edit
----

I should note that I've ran a profile. In between triggering a midi note & actually calling `triggerAttack(someNote)` there is only a 1 or 2ms delay. 

I've tried scheduling the sound with `triggerAttack(note, '+0.05')` but that only made the timing issue worse. Tried with `+0.005` and then it just doesn't seem to make a lot of difference with or without the schedule...

**Comment by tambien** [comment]
To improve performance and scheduling accuracy, "immediate" scheduling is done with a slight lookAhead value from the current AudioContext time. This value defaults to 0.1s and is adjustable by setting `Tone.context.lookAhead`. 

There are a couple of ways to get around it: either use the raw AudioContext.currentTime value (accessible from `Tone.context.currentTime`) to schedule your events: e.g. `.triggerAttack(Tone.context.currentTime)` or set the lookAhead to a lower number (or 0).

**Comment by ambewas** [comment]
ah awesome! Scheduling with Tone.context.currentTime did the trick. Thanks for the input!

**Comment by Gogul09** [comment]
Thanks a ton! Amazing Tone.js. This really helped me.

**Comment by katerlouis** [comment]
Unfortunately I still do get a delay. Both with my MIDI controller (via usb cable) and by using the mouse with click on a button. The issue is also present on this page: https://tonejs.github.io/examples/sampler.html, also with both mouse and midi keyboard. My front-end triggers the visual changes immediately with both mouse and keyboard; only the audio is delayed. The delay occurs with both the Synth and the Sampler for me. 

I use the library like this:
```js
const synth = new Tone.Synth().toDestination();
const piano = new Tone.Sampler({
  urls: {
    'C4': 'C4.mp3',
    'D#4': 'Ds4.mp3',
    'F#4': 'Fs4.mp3',
    'A4': 'A4.mp3',
  },
  baseUrl: 'https://tonejs.github.io/audio/salamander/',
}).toDestination();

const play = (instrument = piano, note = 'C4', length, delay = 0) => {
  if (instrument === piano && !piano.loaded) {
    return false;
  }

  instrument.triggerAttackRelease(note, length, delay);
};
```

I'm absolutely out of ideas

**Comment by rvanzon** [comment]
@katerlouis did you solve it? I am facing the same problem.

**Comment by dirkk0** [comment]
I think Janne did the `Tone.context.lookAhead = 0` fix in his own project repository.

To acchieve this in your own project, you need to set it to zero.
But I didn't try this myself yet.

**Comment by dirkk0** [comment]
@rvanzon @katerlouis 
If you enter this in the console of the mentioned page, the problem seems to be gone:
https://tonejs.github.io/examples/sampler.html

![image](https://github.com/Tonejs/Tone.js/assets/625394/29471fa7-30be-4708-a433-3c34e59de5aa)

**Comment by rvanzon** [comment]
@dirkk0 so for the late reply. Thanks, that worked! 👍

**Comment by Zilong-L** [comment]
Thanks for the solution! Setting Tone.context.lookAhead = 0 solved the latency issue in my ear training app and made the sound trigger in real-time. 

I’m curious—why does Tone.js introduce this 0.1s delay by default? What’s the reasoning behind it?
