### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by devlato** [Tonejs/Tone.js#309]
Hello,

any chance to get it working on Node?

**Comment by tambien** [comment]
Until the Web Audio API or equivalent is running on Node.js, this isn't possible. There a solid effort on this with [Web Audio Engine](https://github.com/mohayonao/web-audio-engine), but that's the only implementation i know of

**Comment by omerman** [comment]
@tambien There is node-web-audio-api now.
It has polyfills of offline audio context. but when I attempt to use it, it throws an error: 
`Error: Invalid length: 0 is less than or equal to minimum bound (0)`
:(
