### ISSUE TITLE
Writing logic in loops or changing loopEnd behavior?

### ISSUE THREAD

**Issue by brokyo** [Tonejs/Tone.js#311]
One of the reasons I use ToneJS is that it allows me to write evolving music based on logic gates or random chance. For example: I might have a loop like this: `[{note: 'A3', duration: '4n', time: 0}, {note: 'A4', duration: '4n', time: '0:1'}, {note: 'A5', duration: '4n', time: '0:2'}]` and then with a 10% chance I might want to add `[{note: 'A6', duration: '4n', time: 0:3}, {note: 'A7', duration: '4n', time: 1:0}]`

Currently I use a method that builds a one-time array of events, schedules them using `Tone.Transport.schedule`, the calls itself after a timeout and repeats the whole thing. [Very simple version of this example here.](https://codepen.io/brokyo/pen/paZzoy?editors=0010)

This works alright but it feels like I'm fighting the library the entire time and you lose most of the ToneJS niceties like stop, playbackRate, probability, etc. 

I wonder if there is a better way to think about loops (or even some wholly new event category?) SonicPi's [loop](https://github.com/samaaron/sonic-pi/blob/master/etc/doc/tutorial/05.2-Iteration-and-Loops.md), for example, allows you to write logic directly in the loop method and the loop simply restarts when all the events have run.

Ideally I'd love something similar in ToneJS either by directly writing logic in the loop or being able to swap out the loop events array without having to convert time and change `loopEnd`. It would open up a bunch of new ways to compose and make ongoing sonic programs easier which - to me - is the coolest part of ToneJS. 

Is something like this possible or would it be bumping into limits in the way asynchronicity/the web audio API works? I'm happy to work on this myself if given direction but I'm just not sure where to start or how to think about it :)

**Comment by tambien** [comment]
Thanks for the issue @brokyo. i like this idea so i’ve been pondering the best way to go about this for a while. i think it may require more of an overhaul or additional features which i’ll keep for a later version. i’m going to close this for now, but will revive this issue if/when this feature can be implemented.
