### ISSUE TITLE
Tone.Transport reference is inconsistent between offline renderings 

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#314]
The initial `Tone.Transport` object is different than the `Tone.Transport` object after the first rendering, but all the `Tone.Transport` objects after subsequent renderings are the same as before the rendering process. Consider this pseudo-pseudo code

    InitialTransport === TransportAfterFirstOfflineRendering // false
    InitialTransport === TransportAfterSecondOfflineRendering // false
    TransportAfterFirstOfflineRendering === TransportAfterSecondOfflineRendering === TransportAfterThirdOfflineRendering  === ... // true

Of course, during the rendering process the Transport object is always different, since it is re-instantiated with and `OfflineAudioContext`.

I suspect this causes some problems and corrupts the state in between renderings.

**Comment by tambien** [comment]
Good catch. i was only updating the reference to the singleton classes (Transport/Master/Listener) when initializing a new context, but didn't store a reference when setting up the initial context

**Comment by tambien** [comment]
reverted the fixing commit for now since it broke a lot of the CI tests. will investigate further
