### ISSUE TITLE
Sampler won't play sounds further than 24 steps from a given sample

### ISSUE THREAD

**Issue by 4lejandrito** [Tonejs/Tone.js#315]
Hi!

After upgrading to `0.12.0` from `0.10.0` the Sampler won't play sounds further than 24 steps from the given sample (I have just 1 sample). I was simulating every sound of a guitar out of a single sample of the E2 string and it now stops playing after E4.

The code responsible for that is https://github.com/Tonejs/Tone.js/blob/dev/Tone/instrument/Sampler.js#L93.

Is there any specific reason why `MAX_INTERVAL` is hardcoded to 24? Would you consider increasing it or making it configurable?

Thanks!

**Comment by tambien** [comment]
Having the MAX_INTERVAL avoids the possibility of an unbounded `while` loop. i will update it to 8 octaves.
