### ISSUE TITLE
Tone.Mono#connect produces `Uncaught TypeError this.createInsOuts is not a function`

### ISSUE THREAD

**Issue by Lokua** [Tonejs/Tone.js#320]
Getting the following error when using `Tone.Mono`:

```
Uncaught TypeError: this.createInsOuts is not a function
```

Coming from:
```js
	    Tone.Mono = function () {
	        Tone.AudioNode.call(this);
	        this.createInsOuts(1, 0); // <- here
```

This is happening in r11, however r12-dev seems fine.
+ latest: https://jsfiddle.net/Lokua/yaw6az7n/2/
+ dev (working) https://jsfiddle.net/Lokua/grvvmbwn/2/

Cheers and thanks for the AMAZING tools!

**Comment by tambien** [comment]
thanks for the bug report, since it's fixed in the dev release, i'll go ahead and close this issue.
