### ISSUE TITLE
amplitude/frequency modulation with different carrier frequencies

### ISSUE THREAD

**Issue by arikpamnani** [Tonejs/Tone.js#323]
I want to amplitude modulate a signal with carrier signal of different frequencies. I tried it the following way:
```javascript
var synth = new Tone.AMSynth({
	"modulationIndex": modind,
	"oscillator": {
		"type": "sine"
	},
	"envelope": {
		"attack": 0.01,
		"decay": 0.2
	},
	"modulation": {
		"type": "sine",
		"frequency": 440,
		"detune": 0,
		"phase": 0
	},
	"modulationEnvelope": {
		"attack": 0.2,
		"decay": 0.01
	}
}).toMaster();
synth.triggerAttackRelease("C4", "8n");
```
In this case, the frequency of the carrier is 440 Hz, but changing it has no effect. Is there any way in which this can be done?

**Comment by tambien** [comment]
You'll want to adjust the `harmonicity` which is the ratio between the input note (in your case "C4") and the frequency of the modulation oscillator. There is no way to give it a fixed frequency, it will be overridden every time you call triggerAttackRelease.

**Comment by arikpamnani** [comment]
If I do `synth.harmonicity = 2`, then the frequency of the carrier would be 880 Hz (supposing the frequency of the modulator is 440 Hz or "A4")?

**Comment by tambien** [comment]
1. It would be the opposite way around. If the harmonicity=2, the modulator would be 880 when the carrier was set to 440. 

2. the fixed value would be reset as soon as you invoke triggerAttack with a new note.
