### ISSUE TITLE
Access LFO value of Tone.AutoFilter in realtime

### ISSUE THREAD

**Issue by hatsumatsu** [Tonejs/Tone.js#326]
Looking into the returned object of `Tone.AutoFilter` there seems to be no way to access its LFO's value in realtime (e.g. for visualizing the filter in action)? Is there another way accessing this value?

**Comment by tambien** [comment]
This is not currently a feature of the LFO. The best way to do this would be to use [Tone.Waveform](https://tonejs.github.io/docs/Waveform) or [Tone.Meter](https://tonejs.github.io/docs/Meter) to get this signal value.
