### ISSUE TITLE
Tone.Sampler clicks on the edges of attack (end of attack) or release (start of release)

### ISSUE THREAD

**Issue by gaspard** [Tonejs/Tone.js#328]
You can see the darker parts indicating noise at the end of the attack and start of the release.

I tried to see if this was due to a gain jump by blocking the gain to 1.0 and it fixes the issue.

I will continue to investigate why the gain jumps like this and post any findings here.

![image](https://user-images.githubusercontent.com/21707/39001411-8c6edc54-43f6-11e8-8b64-3230313356f8.png)

**Comment by tambien** [comment]
can you post a snippet of the code for sampler?

**Comment by gaspard** [comment]
```ts
const samples = Object.assign
( {}
, ...[ 0, 1, 2, 3, 4, 5, 6, 7 ].map ( k => ( { [ `A${ k }` ]: `/assets/piano/A${ k }v7.mp3` } ) )
)
const synth = new Tone.Sampler
( samples
, { onload: () => {
      console.log ( 'All samples loaded' )
    }
  , attack: 0.0
  , release: 0.5
  }
)
.chain ( Tone.Master )
```

**Comment by gaspard** [comment]
The samples used are: http://archive.org/details/SalamanderGrandPianoV3

But the clicks are really audible and should happen with any sample material. Just use a velocity of 0.6 for example.

**Comment by neutonfoo** [comment]
Hi, I'm having the same issue. Were you able to resolve it? I recreated a very minimal sampler below. The notes in the r12 demo definitely "click" compared to the r11 demo.

https://neutonfoo.github.io/ToneJS-Sampler-Bug/

**Comment by zfan40** [comment]
kind of curious about how is this issue going. Any shareable progress or findings?

**Comment by tambien** [comment]
i'm pretty sure the issue is coming from [this line](https://github.com/Tonejs/Tone.js/blob/dev/Tone/source/BufferSource.js#L321). When it was canceling the previously scheduled stop, it would set it's gain value to 1, which would cause a discontinuity at that moment. 

 i've fixed it in my local dev, but in a refactor broke some tests that rely on the BufferSource. hope to have some time soon to address this and the other Sampler issue which i think is related.

**Comment by neutonfoo** [comment]
It's not ideal, but I reverted to https://github.com/Tonejs/build/tree/35c2014724d5cdf83815ceec9cdfe41dc1e3f1d5 for now. This seems to be the latest version that didn't have the clicking noise.

**Comment by gaspard** [comment]
Thank you !! 🙏❤️
