### ISSUE TITLE
Make AudioNode.chain public?

### ISSUE THREAD

**Issue by salomvary** [Tonejs/Tone.js#330]
The [helper method for chaining multiple AudioNodes](https://github.com/Tonejs/Tone.js/commit/75bf464ceae207495bcac49d74261c0208ffd339#diff-f78004d753e1d0b687f971da9a68f89cR149) seems useful but is flagged as `@private` without any apparent reason. [The commit which added @private](https://github.com/Tonejs/Tone.js/commit/75bf464ceae207495bcac49d74261c0208ffd339) to the previously public method also does not explain why..

**Comment by tambien** [comment]
i think i was just trying to streamline the docs into only vital information

**Comment by salomvary** [comment]
cheers!
