### ISSUE TITLE
short notes break the browser

### ISSUE THREAD

**Issue by zfan40** [Tonejs/Tone.js#332]
https://jsfiddle.net/037sn9yb/

This is an occasionally appearing issue, possibly related to performance.
Please tweak the start('+0.1') to 0.01 0.2 back and forth, or tweak some params of the synth.
you will get "Aw,Snap" from Chrome. 

I have tried multiple times, it will come out...

**Comment by tambien** [comment]
Seems to be an issue with chrome's implementation of `cancelAndHoldAtTime`. If i set `AudioParam.prototype.cancelAndHoldAtTime = false`, Tone.js will use it's fallback and i no longer get the crash. [example](https://jsfiddle.net/61xcd1dk/1/). 

Would be good to file a bug with chromium if you can distill it to a minimal example

**Comment by zfan40** [comment]
superb

**Comment by tambien** [comment]
gonna leave this open to remind me to push a fix
