### ISSUE TITLE
NoiseSynth inaudible

### ISSUE THREAD

**Issue by superbuggy** [Tonejs/Tone.js#333]
NoiseSynth seems to not be producing sound. Tested in Chrome 65 and in Safari 11.0.2.

Was testing the example from the docs after I noticed `NoiseSynth` stopped producing sound in a project where I'd used it previously (it was working before, I swear!). 

```js
var noiseSynth = new Tone.NoiseSynth().toMaster();
noiseSynth.triggerAttackRelease("8n");
```

[Reproduced here](https://codepen.io/superbuggy/pen/GdqMQW)

**Comment by tambien** [comment]
whoops. [this line](https://github.com/Tonejs/Tone.js/blob/a7e2f603d9629cefed1d8c7bae5bac7983917dd5/Tone/instrument/NoiseSynth.js#L78) is supposed to be `time + ...` instead of `time = ...`

**Comment by zfan40** [comment]
I get this too... need some fancy unit test for this 😆

**Comment by tambien** [comment]
lol despite all my fancy unit tests, somehow this passed 🤔

**Comment by cyrusasfa** [comment]
Is this still an issue? `triggerAttackRelease` seems to not do produce any noise either...

`    
....
   let noiseSynth = new Tone.NoiseSynth();
    let synthJSON = {
        "noise": {
            "type": "pink",
            "playbackRate" : 1
        },
        "envelope": {
            "attack": 0.001,
            "decay": 0.5,
            "sustain": 0,
            "release": 0.1
        }
    };

    this.noiseSynth = noiseSynth.toMaster();
....

    self = this;
    this.eventId = Tone.Transport.scheduleRepeat(function(time){
      self.noiseSynth.triggerAttackRelease('16n');
    }, '16n');
`

**Comment by geertdijkstra** [comment]
The NoiseSynth generates noise, but only without the "note duration" parameter. Shouldn't it be the triggerAttack function instead of the triggerAttackRelease function for this synth?
