### ISSUE TITLE
AudioContext "not allowed to start"

### ISSUE THREAD

**Issue by Enteleform** [Tonejs/Tone.js#341]
> **System:**
> &nbsp; &nbsp; Windows 10.0.16299 Pro x64
> &nbsp; &nbsp; Chrome 66.0.3359.139
> &nbsp; &nbsp; Tone.js @ https://unpkg.com/tone@latest/build/Tone.js

&nbsp;
I wrote a Tone.js test in [**CodePen**](https://codepen.io/enteleform/pen/PepqYV) the other day. It was fully functional, but when I checked it out today it was no longer producing audio.

This message shows up in the console, even after commenting all of my JS code, so it seems that the issue is occuring while Tone.js loads:
```
The AudioContext was not allowed to start.
It must be resume (or created) after a user gesture on the page.
https://goo.gl/7K7WLu

Tone.Context @ Tone.js:1277
(anonymous) @ Tone.js:1760
Module @ Tone.js:25
(anonymous) @ Tone.js:1267
(anonymous) @ Tone.js:11
(anonymous) @ Tone.js:14
```

I also checked out the official Tone.js [**examples**](https://tonejs.github.io) and found that the embedded JSFiddle examples work as expected. However, the same examples exhibit the issue mentioned above when accesed via their direct [**JSFiddle**](https://jsfiddle.net/yotammann/jqnLgyja/23/?utm_source=website&utm_medium=embed&utm_campaign=jqnLgyja) addresses. They do not work upon the initial load and produce the AudioContext error message. After clicking on the `Run` button to reload the `Results` panel, they then work as expected.

**Comment by tambien** [comment]
I haven't done much investigation into this, but i think something like [StartAudioContext](https://github.com/tambien/StartAudioContext) should fix this. This has been a restriction on iOS for years and now most desktop browsers are adopting this same restriction. 

Not sure yet what needs to happen on the Tone.js side of things, if anything. but the examples will definitely need to be updated to use StartAudioContext not just on mobile browsers.

**Comment by datramt** [comment]
a simple solution is to add this:
```
    if (Tone.context.state !== 'running') {
        Tone.context.resume();
    }
```

inside your "mousedown" listener

```
document.documentElement.addEventListener(
  "mousedown", function(){
    mouse_IsDown = true;
    if (Tone.context.state !== 'running') {
    Tone.context.resume();
  }})
```

**Comment by Enteleform** [comment]
@tambien
Could `StartAudioContext` be implemented directly in Tone.js? It seems like a breaking change (*on the browser side?*) & an unknown issue to developers. I just checked out the first 12 examples on https://tonejs.github.io/demos, and 8 of them exhibited the AudioContext issue.

**Comment by tambien** [comment]
@Enteleform there may be a few simple things that can be implemented directly in Tone.js that would help people with this issue. Good documentation of this would probably help the most. The underlying change that Chrome made which requires a person to explicitly start the audio needs to be taken care of by the developer.

**Comment by CarloCattano** [comment]
Having the same issues here . Only safari doesnt seem affected by this recent change . I cant run examples online neither on my own .

**Comment by Andrparsons** [comment]
It's probably because of this:

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

Google made the change without telling anyone and it has broken a ton of audio.

**Comment by CarloCattano** [comment]
yep , I solved it like @datramt said . Just need to keep in in mind for the future.

**Comment by Enteleform** [comment]
@CarloCattano 

I ran into a caveat when testing @datramt's mousedown listener solution. It doesn't work until *after* the first mousedown. So in the example I posted with an interactive piano, if the first user interaction is to press one of the piano keys - the audio will not be played. After the first click, however, the audio will play as expected.

@tambien's solution of using [**StartAudioContext**](https://github.com/tambien/StartAudioContext) does not have that caveat, and allows immediate initialization of audio before any user events are fired.

**Comment by nightshining** [comment]
Having the same issue. Added in the code you recommended. Now Tone.Players play back files but all the audio is extremely degraded. Works totally fine on multiple android devices and on mac laptop in chrome and safari. Just happening on ios Chrome and Safari.

**Comment by harking** [comment]
HowlerJS has implemented this solution: https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L278

**Comment by tambien** [comment]
@harking @nightshining you can find a similar solution to the iOS sampling rate issue [here](https://github.com/Jam3/ios-safe-audio-context)

**Comment by tambien** [comment]
Made an [unmute](https://github.com/Tonejs/unmute) button which hopefully addresses all of these issues. moving further discussion over to that repo if necessary

**Comment by dkozar** [comment]
Confirming that the solution to this issue is to call:

```js
Tone.context.resume();
```

... upon first user action in the app, just before starting to play any sounds.

For me this solved a "microphone with no sound" issue with another library (https://github.com/alemangui/pizzicato/issues/115).

**Comment by johnmarinelli** [comment]
I was having this error on my iOS device (iPhone 6) and it didn't work for the longest time.  The solution was to turn the mute button side switch is "off" 😂

**Comment by vincerubinetti** [comment]
For me everything is working fine because I'm only triggering notes via a user interaction. But still, it seems that just creating a synth without playing anything causes a few of these warnings to show up in the dev tools. Seems like some of the constructors in the library are trying to access the audio context or something.

**Comment by susphir** [comment]
https://github.com/Tonejs/Tone.js/issues/341#issuecomment-1575789006
How can I fix it?

**Comment by susphir** [comment]
I don't have access to Martinrdz1192 that profile is been locked
