### ISSUE TITLE
Time Miscalculations

### ISSUE THREAD

**Issue by timothyboie** [Tonejs/Tone.js#342]
Varying Transport.bpm values cause Tone.Time miscalculations.

Example here:
https://jsfiddle.net/timboie/1vztuhz1/

Affects both dev and release builds.

**Comment by timothyboie** [comment]
Time.js Line 113 : has the potential of returning large floating point numbers.

The following line of code should resolve the issue to the thousandths decimal:

quarters = parseFloat(quarters.toFixed(4));

**Comment by tambien** [comment]
thank you! pls submit a PR and if possible also a validation test if you can.

**Comment by timothyboie** [comment]
Ok will do
