### ISSUE TITLE
Tone.Meter getLevel method inacurate

### ISSUE THREAD

**Issue by Idicious** [Tonejs/Tone.js#344]
The method currently reads the peak frequency loudness and then adds 28 db on top of it. +28 db is almost a factor 10 difference in loudness of the signal which doesn't seem like the desired result to me.
The results are currently consistantly significantly higher than calling getFloatTimeDomainData and getting the peak value, while the Meter class says it is reading the RMS value which should be on average a factor 1.4 lower than peak.

A better solution I think would be to use getFloatTimeDomainData instead of getFloatFrequencyData that is currently used and calculating the peak or rms value from that depending on a Meter property. I've implemented this + tests in #276.

**Comment by tambien** [comment]
thanks! sorry haven’t yet merged. will take care of it as soon as i can

**Comment by tambien** [comment]
closed by #276
