### ISSUE TITLE
feature request/discuss: polyphonic api for samplers

### ISSUE THREAD

**Issue by zfan40** [Tonejs/Tone.js#345]
I noticed there is a handy way to trigger polyphonic synth with feeding notes array.
`poly.triggerAttack(["Ab3", "C4", "F5"], undefined, 0.2);`

Well, there is no such syntactic sugar for samplers. Do you think supporting that meaningful?
If so, I might be able to raise a PR.

**Comment by tambien** [comment]
good idea. PR please!
