### ISSUE TITLE
Jsfiddle examples on tonejs.github.io/ use deprecated Time expression syntax

### ISSUE THREAD

**Issue by colinmorris** [Tonejs/Tone.js#350]
Specifically, these three use time expression strings such as '4n + 8n':

- https://jsfiddle.net/yotammann/meodck51/7/?utm_source=website&utm_medium=embed&utm_campaign=meodck51
- https://jsfiddle.net/yotammann/k0caxzwt/21/?utm_source=website&utm_medium=embed&utm_campaign=k0caxzwt
- https://jsfiddle.net/yotammann/w39e6450/10/?utm_source=website&utm_medium=embed&utm_campaign=w39e6450

(cf. #348)

**Comment by tambien** [comment]
fixed this finally!
