### ISSUE TITLE
Qwerty-responsiveness problem with latest release?

### ISSUE THREAD

**Issue by gntsketches** [Tonejs/Tone.js#352]
Hi, I'm a relatively dev, so apologies for any confusion or lack of proper terminology on my part.

I think the latest release may have a performance issue, specifically with 'dropping' notes. My app uses a qwerty-style UI (ala: [Qwerty-Hancock](https://stuartmemo.com/qwerty-hancock/)), and with the minified version of Tone that I downloaded on 3/26/18, all is well. 

However, on the minified version I downloaded yesterday (5/19/18) as well as the one at [https://cdnjs.cloudflare.com/ajax/libs/tone/13.1.13/Tone.js](https://cdnjs.cloudflare.com/ajax/libs/tone/13.1.13/Tone.js), there is about a 25% chance that a note will simply not play on keydown.

I will work on seeing if I can replicate the problem on a jsFiddle & link to it if I can.

Thanks Yotam (and any contributors) for building this fantastic library. I'm a huge fan and tell folks about it whenever I can!

**Comment by tambien** [comment]
what kind of synth are you using? please add a fiddle when you can

**Comment by gntsketches** [comment]
A polysynth. This is all in Chrome, I should also add - I haven't tested other browsers. [This pen](https://codepen.io/anon/pen/yjZrje) is demonstrating similar behavior for me somewhat more responsiveness, maybe dropping one note in 10.

**Comment by tambien** [comment]
i'm unable to reproduce your exact situation. i do get some weirdnesses when there is a repeated key event which happens on my computer when i hold down a key for a moment. I think you can avoid this if you check for `if(!event.repeat)` in your key binding methods. 

i typically use AudioKeys which wraps up the keyboard events nicely. Are you experiencing the same issue with [this fiddle](https://jsfiddle.net/gpzpt64m/)?

**Comment by gntsketches** [comment]
Sorry for the long response time - the fiddle doesn't have the same note-dropping problem (though I experience it as having slightly slower response time for each individual note.) Regarding the key-repeat issue, I do actually handle that in my app - it's not that. 

It's hard to say what's going on here. I'll keep experimenting with it and let you know if I come up with any more constructive data. Unless you hear other reports about this, I suppose it could just be some weird quirk of my system. Thanks for your response.
