### ISSUE TITLE
FMSynth example crashes Chrome

### ISSUE THREAD

**Issue by paulsonnentag** [Tonejs/Tone.js#353]
The FMSynth demo  (https://tonejs.github.io/examples/#fmSynth) crashes my chrome tab (Version 66.0.3359.181 (Official Build) (64-bit)). This occurs when pressing down my mouse and moving it quickly up and down on the diplayed keyboard.

<img width="519" alt="screen shot 2018-05-21 at 15 35 31" src="https://user-images.githubusercontent.com/650540/40310317-a7d07a6e-5d0c-11e8-9b55-2dc3f17537a9.png">

 These are the errors I get when enabling the debug logging flag in chrome:

```
[20183:161863:0521/152342.002693:WARNING:audio_sync_reader.cc(193)] AudioSyncReader::Read timed out, audio glitch count=10
[20183:161863:0521/152342.060817:WARNING:audio_sync_reader.cc(193)] AudioSyncReader::Read timed out, audio glitch count=20
[20183:161863:0521/152342.064765:WARNING:audio_sync_reader.cc(175)] ASR: No room in socket buffer.: Broken pipe (32)
```

I haven't been able to find out what causes this failure. There are some old issues which seam related: (https://github.com/Tonejs/Tone.js/issues/40, https://github.com/Tonejs/Tone.js/issues/332) but they are all closed and should be fixed by now.

**Comment by tambien** [comment]
ouch! that's a hard crash.

it is probably the same bug as #332, but since the examples are using the current master build (tone@r12) the fix for it is only in the latest dev build (tone@^13), they'll still have the crashing issue. i suggest using the latest dev build if you can to avoid this issue. 

i'll try to file a bug with chrome

**Comment by paulsonnentag** [comment]
Thanks, didn't look properly if the current version included that commit
