### ISSUE TITLE
MonoSynth docs refer to ScaledEnvelope rather than FrequencyEnvelope

### ISSUE THREAD

**Issue by colinmorris** [Tonejs/Tone.js#355]
In the [MonoSynth docs](https://tonejs.github.io/docs/r12/MonoSynth), the text at the top and the diagram refer to `filterEnvelope` as a `Tone.ScaledEnvelope`. Actually, it's a `Tone.FrequencyEnvelope` (which is important to know, because the two classes take different parameters for their constructor).

**Comment by tambien** [comment]
good catch! fixed it. thanks
