### ISSUE TITLE
Analyser example uses private method (AudioNode.fan)

### ISSUE THREAD

**Issue by colinmorris** [Tonejs/Tone.js#357]
The source of [this demo of `Tone.Analyser`](https://tonejs.github.io/examples/#analysis) includes this code:

		var player = new Tone.Player({
			"url" : "./audio/FWDL.[mp3|ogg]",
			"loop" : true
		}).fan(fft, waveform).toMaster();

I couldn't find documentation on `fan()` in `Player` or any of its ancestor classes. It turns out that's because [it's marked as private](https://github.com/Tonejs/Tone.js/blob/r12/Tone/core/AudioNode.js#L229), so it has no generated documentation.

I'd suggest either making `fan` public, or changing the example code to use two calls to `connect()`, so as not to confuse newbies browsing the examples (like me).

**Comment by tambien** [comment]
thanks, but this was already fixed in the latest dev build. 

related to #330 

1026c34163bdb840b3303bc1bdf423e535a333dd
