### ISSUE TITLE
PluckSynth velocities do not seem to affect volume

### ISSUE THREAD

**Issue by tomthecollins** [Tonejs/Tone.js#358]
Thanks for the great work on this package!

I saw there was already an issue raised with PluckSynth, but I think this one is separate.

This fiddle triggers 8 notes with PluckSynth, which should be successively louder, but they sound like the same volume to me, then 8 notes with FMSynth, which do sound successively louder: 
https://jsfiddle.net/tomthecollins/kqrk5dxc/

(Try in Firefox as Chrome is bust for Tone.js right now.)

**Comment by tambien** [comment]
[PluckSynth.triggerAttack](https://tonejs.github.io/docs/r12/PluckSynth#triggerattack) currently does not have a velocity value like FMSynth and the other synths since it works through a totally different synthesis method. 

i can look into adding it to the API.

**Comment by tomthecollins** [comment]
Thanks for quick response. It's not crucial in my opinion. The docs had just led me to think otherwise:
https://tonejs.github.io/docs/r12/PluckSynth#triggerattackrelease

**Comment by tambien** [comment]
oh! good catch. cause it inherits from another class which implements that method. The pluck synth doesn't even have a release, so should also not have a triggerAttackRelease method. i'll see what kind of comment i need to add to remove it from the docs
