### ISSUE TITLE
Some sounds drop fairly soon after playing

### ISSUE THREAD

**Issue by Ecafracs** [Tonejs/Tone.js#359]
In my app, I noticed the kick drum would sometimes drop, and no longer work until I restarted.
This seems to be happening in r12 and r13.  Haven't had it in r11 yet.

I happened to stumble on a fairly reliable case.
To recreate it, go to my jsfiddles below, and replace the drum pattern with this: K|K|S||K|K|S
Solo the drums, play, and the kick stops working after about 10-25 seconds.
(In my developing app running locally, it seems to fail after exactly 3 kicks, very reliably.)

R11: https://jsfiddle.net/Ecafracs/9una8zbt/
R12: https://jsfiddle.net/Ecafracs/r62ub31k/
R13: https://jsfiddle.net/Ecafracs/stq8udL2/

Interestingly enough, variations to this pattern don't seem to break as quickly as this one.  Tone must really hate the basic rock beat. ;-)

**Comment by tambien** [comment]
lol. tone tries to keep an open mind about all the beats people might make :)

Ok i think i identified a problem where the underlying oscillator was being turned off in some situations. pushed a change yesterday which seems to have fixed this issue: https://jsfiddle.net/w81s6kyx/

For the future, please pair down your example as much as possible to just the part of the code which exhibits the issue, it'll help me debug it much faster.
