### ISSUE TITLE
Synced player does not play with the appropriate offset

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#360]
fit('should start the player in sync with the transport position', (done) => {
        let playSpy = spyOn(AudioBufferSourceNode.prototype, 'start');
        Tone.Transport.seconds = 5;

        fixture.detectChanges();
        getTestScheduler().flush();

        let startCb = (time) => {
            expect(playSpy).toHaveBeenCalledTimes(1);
            expect(playSpy).toHaveBeenCalledWith(time, 5)

            done();
        }

        Tone.Transport.on('start', startCb);
        Tone.Transport.start()
    });

Results with

    Expected spy start to have been called with [ 1.2551927437641723, 5 ] 
    but actual calls were [ 1.2551927437641723, 8.881784197001252e-16 ].

Even though the transport is at 5 seconds, the player is started with an offset of `0.00`. 

Player is setup like this before the verification occurs:

    this.player =  new Tone.Player()
    this.player.sync().start()

I think I'm doing this right and this is a bug. Let me know. Cheers!

**EDIT**

Somehow it works/the test passes when I start the player like this: `this.player.sync().start(0)`.

**Comment by tambien** [comment]
without any arguments to ‘start’ it will default to the current transport time
