### ISSUE TITLE
Player Position Inaccurate

### ISSUE THREAD

**Issue by tboie** [Tonejs/Tone.js#361]
The player position property is inaccurate after the first play.

This fiddle demonstrates the issue (dev build):
https://jsfiddle.net/timboie/982r3yh7/

**Comment by tambien** [comment]
i spent a while working through this, and there are too many complexities in tracking the player position (loopStart/loopEnd and playbackRate changes) to do it robustly the way that i was trying. I've decided to remove this feature until I find a better way to go about it.
