### ISSUE TITLE
CodeExample for Analyzer in github docs could be more plausible

### ISSUE THREAD

**Issue by TimSusa** [Tonejs/Tone.js#362]
Hello, 

at first thanks to your amazing framework. I love it! I am studying your docs, while playing around with tone.js, react and redux. The code example at https://tonejs.github.io/docs/r12/Analyser could be more plausible. It only shows, how an osc is connected to master. Nothing is mentioned about the Analyzer. How do I connect the analyzer correctly? I would love to see a real life example there. 

Best, 

Tim.

**Comment by tambien** [comment]
PRs welcome! that example is actually an inherited example specifically for the 'toMaster' method. though it does seem a little confusing, i think it's better to leave in inherited examples than strip them out. 

There's a useful example [here](https://tonejs.github.io/examples/#analysis) which shows you how to connect up the Analyser (or one of it's children, Tone.FFT and Tone.Waveform).
