### ISSUE TITLE
Sampler velocity values not affecting volume of sound

### ISSUE THREAD

**Issue by tomthecollins** [Tonejs/Tone.js#363]
Hi!

I'm using triggerAttackRelease with a Sampler, and, according to the docs (and intuition), it should be possible to set the velocity. In [this](http://tomcollinsresearch.net/tonejs_issues/sampler_velocity_issue.html) example, the notes should be getting successively louder in runs of 8. They all sound the same loudness to me. (And I'm also hearing the clipping mentioned in #328.)

Thanks in advance for your time, Yotam!

**Comment by jhwoodward** [comment]
I also noticed this

**Comment by TomAuger** [comment]
I have just rebuilt the DEV branch with all the latest commits and am still seeing this issue. 

mySampler.triggerAttackRelease(frequency, duration, Tone.now(), velocity);//always plays max volume, even when velocity is 0 or very small.

**Comment by rupertparry** [comment]
This still appears to be an issue – not working for me.

**Comment by TomAuger** [comment]
@rupertparry Are you using the latest dev build? Just curious.

**Comment by rupertparry** [comment]
Ah I assume not – I'm using the latest package available on NPM – looks like 0.12.80
