### ISSUE TITLE
Unable to change a property if a scheduleRepeat is too frequent

### ISSUE THREAD

**Issue by anthonydugois** [Tonejs/Tone.js#364]
I have a weird behavior when I use `scheduleRepeat`. What I'd like to be able to do is `scheduleRepeat` a trigger of a synth, start the Transport, and then be able to perform subsequent update on the synth.

This works only if the repeat is not too frequent (according to my tests, not less than about 2 seconds). If the repeat is too fast, the update of the synth does not seem to work.

You can test this right here : https://codesandbox.io/s/mj2645x1l9?module=%2Fsrc%2Findex.js (change the `repeat` variable to `2` and the synth update performed in the `setTimeout` will work).

Is this behavior intended?

Let me know if you need more details. And BTW thanks for the great work!

**Comment by tambien** [comment]
Thanks @anthonydugois. 

Not sure i'm hearing the same behavior. I've set `repeat=0.1` and hear the first 20 or so notes with the sine wave and the subsequent notes play with the sawtooth wave. this is what i would expect the behavior to be. [here's my code](https://jsfiddle.net/m1r8kszn/)

**Comment by anthonydugois** [comment]
It seems that you do not use the same version of Tone in your code on JSFiddle. Your code does work for me too, so I assume the bug has been resolved in the last version of Tone. Thanks.
