### ISSUE TITLE
Add the possibility to stop receiving inputs from a channel

### ISSUE THREAD

**Issue by anthonydugois** [Tonejs/Tone.js#366]
I love the system of buses of Tone. However, it seems that it is not currently possible to stop receiving inputs from a channel. For example:

```javascript
Tone.Master.receive("channel0");
Tone.Master.receive("channel1");

// ...

// Unable to stop receiving from the previously defined channels :(
```

This will tell `Tone.Master` to receive inputs from `channel0` and `channel1`. But then I can't cancel the reception from `channel0` for example. Maybe it would be a good idea to implement this feature:

```javascript
Tone.Master.receive("channel0");
Tone.Master.receive("channel1");

// ...

Tone.Master.cancelReceive("channel0");
```

Let me know if you think it's possible, and if that's the case, I'd be happy to send a PR. :)

**Comment by tambien** [comment]
There is no way currently to control this from the `receive` function, but the `send` method returns a Tone.Gain which can be used to change the level or disconnect the send entirely from the receiving node. 

Does that work for your use-case?

**Comment by anthonydugois** [comment]
Not exactly; my point was more that even if you disconnect every node previously connected using `send`, the receiving node still "expose" a channel on which it's possible to send inputs. What I was pointing out is that it's not currently possible to say "I do not want this node to receive inputs from this channel anymore".

Maybe this example is better:

```js
const reverb = new Tone.Freeverb().toMaster();
const distortion = new Tone.Distortion().toMaster();

// These effects receive inputs from the same channel
reverb.receive("channel");
distortion.receive("channel");

// Now I don't want the distortion effect to receive from this channel anymore,
// which means that even if I send to "channel" later, it will not be connected to the distortion effect
distortion.cancelReceive("channel");
```

What do you think?

**Comment by Idicious** [comment]
Busses generally work the other way around. An audio channel can have either a bus, mic or no input (which generally means it plays audio tracks if any are assigned to it) in most DAWs. Other channels can send to a bus from their sends section.

**Comment by tambien** [comment]
i agree with @Idicious. i prefer the send-centric way of thinking about it with the current API. 

@anthonydugois one way to achieve what you're trying to do would be to 'receive' to a GainNode and then connect/disconnect that GainNode to whichever routes you'd like and that'll give you a sort of cancelable bus like you're looking for.
