### ISSUE TITLE
DX7 synth

### ISSUE THREAD

**Issue by zeroware** [Tonejs/Tone.js#367]
Hello,

I was wondering if a DX7 synth could be included to tone.js. 
I found this excellent JS implementation : https://github.com/mmontag/dx7-synth-js which may be a good starting point.
I'm new to synth but I'm willing to help if you think it's a good idea.

**Comment by tambien** [comment]
@mmontag has made a great implementation which as far as i can tell should be totally interoperable with Tone.js as long as both are sharing the same AudioContext. i don't really see a need to reimplement it in this code-base. 

i would be open to branching out the code-base with satellite repos which maybe all follow a couple simple guidelines for interoperability or extend Tone.js in some way (how we'd do that TBD). i've registered @tonejs on npm which would be a good place to publish these sorts of synths, plugins or functions. i can work on a wiki which could have some best practices for making a tone.js plugin if there is interest in this kind of thing.

**Comment by mmontag** [comment]
Thanks for the mention. I was just browsing Tone.js yesterday while researching some reverb algorithms. Such a cool project. :) I would love to hear ideas about guidelines for interoperability, since we don't really have a VST standard to work with.
