### ISSUE TITLE
Sampler velocity still seems not to work, even in current dev build

### ISSUE THREAD

**Issue by TomAuger** [Tonejs/Tone.js#371]
I have just rebuilt the DEV branch with all the latest commits and am still seeing this issue.

mySampler.triggerAttackRelease(frequency, duration, Tone.now(), velocity);//always plays max volume, even when velocity is 0 or very small.

**Comment by TomAuger** [comment]
Hmmm. did another rebuild and it DOES appear to work. Closing this issue.

**Comment by fabb** [comment]
It's broken in 0.12.80, but it works in 13.4.5.
