### ISSUE TITLE
'Cannot read property 'loaded' of undefined' when object is defined

### ISSUE THREAD

**Issue by matthewBtindall** [Tonejs/Tone.js#376]
Bugs and feature requests only please.

For help questions, check out the forum: https://groups.google.com/forum/#!forum/tonejs

If possible, please include a link which illustrates the issue.

https://jsfiddle.net/hy762ff0/ (tone@latest)
https://jsfiddle.net/2jusapvr/ (tone@next)

**Comment by matthewBtindall** [comment]
I am loading a float32Array into a buffer, this works fine, however when i attempt to pass this buffer to a player, on the 'onload' i get a `Cannot read property 'loaded' of undefined` error, when trying to call any methods on the object that passed to the callback. However if i simply console.log the object it isn't undefined, code below:

```
let buffTemp = new Tone.Buffer().fromArray(float32Temp);
    myPlayer = new Tone.Player({
        'url': buffTemp,
        'loop': true,
        'onload': p => {
            console.log(p); //Player
            console.log(p.loaded) //Cannot read property 'loaded' of undefined
        }
    }).toMaster();
```

thanks in advanced, Matt

**Comment by tambien** [comment]
Seems like because the onload callback is invoked before the constructor has finished, it doesn't have all of it's properties. Solution is probably to defer the onload callback if a buffer is passed in instead of a URL.

**Comment by matthewBtindall** [comment]
What would be the most efficient way to defer the callback? I have been using a simple SetTimeout however i have been told to avoid using such functions by many people. Thanks for your reply i really appreciate it.

Matt

**Comment by tambien** [comment]
I should also note that you don't need the onload callback in your specific case since the Buffer does not need any loading. 

```javascript
const myPlayer = new Tone.Player({
  'buffer': buffTemp,
  'loop': true,
}).toMaster();

//myPlayer can be used at this point. 
//no async callback necessary
myPlayer.start()

```
