### ISSUE TITLE
Buffer overrun

### ISSUE THREAD

**Issue by TomAuger** [Tonejs/Tone.js#378]
I'm encountering consistent buffer overrun (that typical "clipping" sound you hear when the CPU gets overtaxed) with the Tone.Sampler object.

To reproduce the issue: `setInterval()` to 20ms and trigger 1 to 5 `sampler.triggerAttackRelease()`.

After a few seconds the clipping gets so bad audio just stops altogether. If you pause, let the buffers flush, and restart, you get playback again for a while and then after a few seconds, the clipping comes back.

I have attempted to mitigate this by extending `Tone.BufferSource.prototype.start` to include a polyphony limiter, but very strangely this approach has not proved to be successful.

When the number of active buffers exceeds 300 for a period of time, the clipping begins. This is likely linked to the length of the sample itself.

Any information you can provide on how to effectively limit the CPU usage or avoid clipping would be immensely appreciated.

Thank you for this great library, and for your time - the most precious commodity of all!

**Comment by TomAuger** [comment]
Things I have done to attempt to mitigate the clipping:

1. Every time `Tone.BufferSource.prototype.start` is called I add that buffer to a global array. I hook into `BufferSource.onend` and remove that buffer from the array when it is done. That way I can check to see how many active buffers are playing at any time.

2. When `Tone.BufferSource.prototype.start` is called, I check the global array. If we have exceeded an arbitrary number of currently playing BufferSources, I trigger 'oldestBufferSource.stop(Tone.now())' which should effectively purge that Buffer. It certainly stops playing immediately, but the clipping persists, strangely enough, even when my "polyphony" limit is set extremely low (like 4!)

3. Trying an alternate approach, I don't even allow `sampler.triggerAttackRelease()` to be called when the number of active buffers exceeds a certain amount (I have experimented with numbers from 20 to 500). This works, for a time, but there seems to still be a "saturation point" after many seconds, where the sample length has overrun the buffer length and clipping starts to occur.

4. My final approach was to limit the number of samples that could be triggered in any given interval. I have had some success by limiting the # samples to under 10 every 20ms, but while that stops the clipping, it also creates a poor user experience where notes simply don't play when the user attempts fast passages, so this is not really a good option.

I'm out of ideas, and hope you can suggest any known limitations or perhaps the root cause of the problem so I can better formulate a mitigation strategy.

Thanks again for your time.

**Comment by TomAuger** [comment]
Still trying to extract a simplified stress test from my project code. 

The samples are all about 10sec in length. I'm loading 3-4 Sampler instruments, each with on average 5 "partials".

Currently what's working is to prevent triggering additional samples once the user reaches an arbitrary pre-determined "saturation limit". This isn't a great user experience, so I'd love the FIFO culling approach to work!

```
Tone.BufferSource.prototype.start = function(time, offset, duration, gain){
	//console.log(" + ", time, offset, duration, gain);

	// Prevent buffer playback if we have exceeded max # buffers playing
	// (or if there's no volume... what's the point?
	if (_playingBuffers.length >= MAX_BUFFERS || gain <= 0) return this;


	// // shut down the samples FIFO-style
	// while (_playingBuffers.length >= MAX_POLYPHONY){
	// 	let oldestSampleSource = _playingBuffers.shift(); // pulls it off early - onended won't find it
	// 	oldestSampleSource.stop(Tone.now());
	// 	//console.log("stopping", oldestSampleSource);
	// }

	_playingBuffers.push(this);
	_numPlayedNotesThisInterval++;

	this.onended = function (buffer) {
		let index = _playingBuffers.indexOf(buffer);
		if (index > -1) {
			_playingBuffers.splice(index, 1);
		}
	};

	return bufferSourceStart.bind(this)(time, offset, duration, gain);
};
```

**Comment by redfoxDW** [comment]
I think I am running into similar issues with my page.
Currently I am using a sampler with 37 mp3 files (each about 15kb, at 22050 kHz, 2 channels).
Everything works excellent on Desktop browsers, but on my iPhone 6 i experience the following:
When I play midi music, the sound starts cutting out more and more after a minute or 2.
The time seems to be pretty persistent, even with very different audio encoding.

**Comment by redfoxDW** [comment]
Interestingly enough, I was not able to reproduce the issue when playing the keys manually.
Yes, the sounds starts crackling a lot when I swipe on the keyboard  wildly, but everything normalizes quickly. This is not the case with the cut outs that happen when playing the Tone.Parts. Once the sound is screwed, only a page refresh helps.

**Comment by redfoxDW** [comment]
> > It seems like it happens on the Releases only. Could anyone confirm this?
> 
> What do you mean by this exactly? Is there any other way you're building your project that does NOT have these issues?
> 
> Right now the only solution we've found is to periodically do a `window.location.reload(true);` which of course is sub-optimal.

Please disregard my previous comment. I did a new implementation of my prototype in react and now I am experiencing the same issue as you described it. I think there was something messed up in my code earlier that had caused the strange effect on iOS.

I just ran a test with 5 samplers, each 37 samples in Safari on iOS on my iPhone 6.
A lot of crackling and a very hot phone, but otherwise fine.

**Comment by TomAuger** [comment]
We have currently noticed a pretty severe memory leak involving undisposed callbacks. We are looking into it further to see if we can shed light on what part of the code might be causing it, or whether it's something within the WebAudio implementation itself. Currently we are testing on Microsoft Edge.

**Comment by TomAuger** [comment]
Yes, that is the workaround we used as well. Below is a bit of a brute-force override that illustrates two different attempts to use an external "playing buffer" to keep tracks of the current polyphony, and then either pull notes off the end (didn't work) or gate them coming in when the number of notes in the "playing buffer" exceeded a certain amount. 

It also demonstrates tacking "buffer.dispose()" to the `onended` event of the BufferSource.

You could probably accomplish the garbage collection / memory management more simply by just getting a reference to the BufferSource and hooking into its `onended` method, without going this override route.

@tambien I feel like you should probably implement the `buffer.dispose()` as a default within `Tone.BufferSource.prototype._onended`. I can't conceive of a use case where the average developer WOULDN'T want the buffer to be GC'ed when it's all done (at least in the case of 1-shot samples).



```
Tone.BufferSource.prototype.start = function (time, offset, duration, gain) {

    // Prevent buffer playback if we have exceeded max # buffers playing
    // (or if there's no volume... what's the point?
    if (_playingBuffers.length >= MAX_BUFFERS || gain <= 0)  return this;

    // // shut down the samples FIFO-style
    // while (_playingBuffers.length >= MAX_POLYPHONY){
    // 	let oldestSampleSource = _playingBuffers.shift(); // pulls it off early - onended won't find it
    // 	oldestSampleSource.stop(Tone.now());
    // 	//console.log("stopping", oldestSampleSource);
    // }

    _playingBuffers.push(this);
    _numPlayedNotesThisInterval++;

    this.onended = function (buffer) {
    	buffer.dispose();
	    let index = _playingBuffers.indexOf(buffer);
        if (index > -1) {
            _playingBuffers.splice(index, 1);
        }
    };

    return bufferSourceStart.bind(this)(time, offset, duration, gain);
};
```


You might also consider implementing a kind of Polyphony limiter, possibly using one of the methods I've described here. 

As a reference, consider how BEADS does it: http://www.beadsproject.net/doc/net/beadsproject/beads/ugens/PolyLimit.html
https://github.com/orsjb/beads/blob/master/src/beads_main/net/beadsproject/beads/ugens/PolyLimit.java

(A quick glance suggests they limit new signals going IN, rather than truncating the oldest signals)

The problem I was having with Tone.js implementing a sort of FIFO Poly limiter was the way you handle the `stop()` method - it often adds a ramp or time effect, so you don't stop immediately.

My workaround (with inconclusive results!) was to implement a `stopImmediately()` method, that attempted to kill the buffer right away. Here's the full code below, if you're ever going down that road and are curious to see some ideas:

```
  // Over-ride some Tone.js methods to implement Polyphony limiting
	let bufferSourceStart = Tone.BufferSource.prototype.start;

	Tone.BufferSource.prototype.start = function(time, offset, duration, gain){
		// Don't waste time queueing up something that has no volume
		if (gain > 0) {
			// shut down the last playing sample
			while (_playingBuffers.length >= MAX_POLYPHONY){
				let oldestSampleSource = _playingBuffers.shift(); // pulls it off early - onended won't find it

				stopBufferImmediately.bind(oldestSampleSource)();
				log(["stopping", oldestSampleSource], "buffer");
			}

			_playingBuffers.push(this);

			return bufferSourceStart.bind(this)(time, offset, duration, gain);
		}

		return this;
	}

	// Currently just a straight copy of Tone.js with redundant timeout commented out
	Tone.BufferSource.prototype.stop = function(time){

		time = this.toSeconds(time);

		//if the event has already been scheduled, clear it
		if (this._stopTime !== -1){
			this.cancelStop();
		}

		//the fadeOut time
		var fadeOutTime = this.toSeconds(this.fadeOut);

		//cancel the previous curve
		this._stopTime = time + fadeOutTime;

		if (fadeOutTime > 0){
			//start the fade out curve at the given time
			if (this.curve === "linear"){
				this._gainNode.gain.linearRampTo(0, fadeOutTime, time);
			} else {
				this._gainNode.gain.targetRampTo(0, fadeOutTime, time);
			}
		} else {
			//stop any ongoing ramps, and set the value to 0
			this._gainNode.gain.cancelAndHoldAtTime(time);
			this._gainNode.gain.setValueAtTime(0, time);
		}

		Tone.context.clearTimeout(this._onendedTimeout);
		this._onendedTimeout = Tone.context.setTimeout(stopBufferImmediately.bind(this), this._stopTime - this.now());

		return this;
	};

	// Called after the buffer has timed out
	function stopBufferImmediately(){
		if (!this._sourceStopped){
			this._sourceStopped = true;

			//stop any ongoing ramps, and set the value to 0
			this._gainNode.gain.cancelAndHoldAtTime(Tone.now());
			this._gainNode.gain.setValueAtTime(0, Tone.now());

			this._source.stop(0);
		}
	}


	// This is called by AudioScheduledSourceNode.onended in the WebAudio API
	// When the buffer has completely stopped
	Tone.BufferSource.prototype._onended = function(){

		// It should already be gone but...
		let index = _playingBuffers.indexOf(this);
		if (index > -1) {
			_playingBuffers.splice(index, 1);
		}

		log(_playingBuffers, "buffer");

		this.dispose();
	};



    init();

})();
```

**Comment by tambien** [comment]
i added auto-disposing to BufferSources and OscillatorNodes. I'm reticent to add a MAX_POLYPHONY on BufferSourceNodes. choosing the right number is going to depend on too many factors such as the buffer length, the cpu, platform, and other UI thread processes. it seems like it could be handled better on the end application developers side doing the things that you suggested already such as throttling retriggers and using short samples. 

though, maybe exposing a BufferSourceNode polyphony counter would be helpful for people wanting to implement a polyphony limitation.

**Comment by tambien** [comment]
This issue is stale, so i'm going to close it. @TomAuger the research that you've done is very helpful, but it seems like the problem might come down to general performance issues of Web Audio and not necessarily something that can be specifically addressed in the library. i'm always working to improve the performance of the library at the same time the Web Audio API implementations are becoming more performant, so hopefully this issue will go away with time. and if there is something specific and actionable like your suggestion to have an option for limiting polyphony, that can be brought up in a PR. Thanks again for looking deep into it!
