### ISSUE TITLE
need to call start() on autoPanner setup

### ISSUE THREAD

**Issue by zfan40** [Tonejs/Tone.js#379]
potential feature request:
I noticed the setup for AutoPanner is
`new Tone.AutoPanner("4n").toMaster().start();`
which calls start(), while almost all the other effects don't need to.
the comment says start is to call LFO. Well the usage across all effects seems not to be very consistent

**Comment by tambien** [comment]
Thanks for the comment. A couple other LFO-based effects like Tremolo and AutoFiler also have a 'start' method. This enables people to synchronize the effect to their tempo/song. Say for example, if you wanted the panning to fall exactly on the quarter note, it'd be really hard to do if the AutoPanner started when it was constructed. 

I agree it leads to a slightly more verbose API, but i wouldn't want to lose the ability to synchronize these effects to the rest of the music. Maybe the solution is to include an 'autostart' constructor parameter. but that's exactly the same verbosity (`new Tone.AutoPanner({frequency : '4n', autostart : true'}).toMaster()`) unless autostart defaults to true, which breaks some backwards compatibility...

**Comment by zfan40** [comment]
Thanks for clarification.
Guess there are tons of tradeoffs I haven't thought of
