### ISSUE TITLE
Tone.js Microphone example doesnt work on IOS 11.4 Safari

### ISSUE THREAD

**Issue by fariskas** [Tonejs/Tone.js#380]
The example here:
https://tonejs.github.io/examples/#mic

When i tap on the Open Mic button, the button changes to 'Close Mic' as extected. 
But the canvas has doesnt change as no microphone input is detected.
on console log, i see `Error : Invalid constraint`.

I've also allowed Safari to use microphone and camera in the iOS settings.

Device : iPod touch 16gb, IOS 11.4
Browser: Safari

**Comment by tambien** [comment]
I'm unable to recreate this error on my iPhone, works normally for me. Could you paste more details from the error? like what exactly the constraint was. have you had success with other websites that use the UserMedia API to get microphone or video access?

**Comment by fariskas** [comment]
sorry for the late reply.

the constraints i used  are `{ audio: true, video:false }`. 
and it gets stranger. I just tried on an iphone 7 IOS 11.4. safari works ok. but on Chrome [v68] doesnt work at all.

Now i see 'getUserMedia is not supported by your browser' printed at the bottom of the tonejs mic example.

On other examples i tried, chrome doesnt even requests for the user's permission to allow audio like expected. Probably a chrome issue? But chrome v68 should support `navigator.mediaDevices.getUserMedia` right?

**Comment by tambien** [comment]
i think that Chrome on iOS doesn't yet support UserMedia, but Safari on iPhone works fine for me. I saw some grumblings on StackOverflow that maybe it's an iPod Touch specific issue. Which seems to be consistent with what we're experiencing. [check out the comments in this issue](https://stackoverflow.com/questions/45692526/ios-11-getusermedia-not-working).

**Comment by fariskas** [comment]
thanks. noted.

**Comment by tambien** [comment]
going to close for now since there doesn't seem like i can do anything about this iPod Touch issue.
