### ISSUE TITLE
Move away from Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [Tonejs/Tone.js#381]
The Buffer constructor `new Buffer(...)` is unsafe and deprecated. Could it be replaced with `Buffer.from(...)` in [these places](https://github.com/Tonejs/Tone.js/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22)?

**Comment by tambien** [comment]
Thanks for the issue, though `new Buffer` in all these situations refers to a Tone.Buffer which is an AudioBuffer wrapper not the node.js data structure that has the same name. We could consider renaming it in a refactor, to avoid this confusion, but it would break of a lot of things.
