### ISSUE TITLE
Tone.Transport and Safari 12.0

### ISSUE THREAD

**Issue by phesterman** [Tonejs/Tone.js#395]
I do most of my development in Chrome and test periodically in Safari.  I discovered today that there may be a problem with Tone.js r12 and Safari 12.0.  All my code that relies on Tone.Transport works just as it should in Chrome, but now fails completely in Safari...it's as if the transport doesn't respond to Tone.Transport.start().  I just tried the Tone.js Sequencing/Timing examples.  Step Sequencer, Events, Playback Rate, and Transport Sync don't work in Safari 12 either.

Peter

**Comment by tambien** [comment]
Did you test if Tone.context.state === 'running'? before the Transport is started? it may be related to additional autoplay restrictions which Safari introduced in 12.0

**Comment by phesterman** [comment]
When I tested Tone.context.state it reported “suspended”.  As you suspected, it wasn’t working correctly because of the autoplay restriction and enabling auto-play fixes it, thankfully.  I’d missed the boat on that.    Unfortunately, the ramifications of the autoplay restriction are kind of frightening for the music ed applications I’m developing.

Thanks for the quick reply.

Peter


On Oct 10, 2018, at 4:07 PM, Yotam Mann <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you test if Tone.context.state === 'running'? before the Transport is started? it may be related to additional autoplay restrictions which Safari introduced in 12.0

**Comment by tambien** [comment]
i agree, changes in autoplay have been hard to design around for many web audio applications. i started a little project which tries to help with some of the issues: 

https://github.com/Tonejs/unmute

**Comment by phesterman** [comment]
Thanks for that!  I guess this whole auto-play thing is sort of a moving target right now regardless of browser, isn’t it?


On Oct 10, 2018, at 4:43 PM, Yotam Mann <notifications@github.com<mailto:notifications@github.com>> wrote:


i agree, changes in autoplay have been hard to design around for many web audio applications. i started a little project which tries to help with some of the issues:

https://github.com/Tonejs/unmute
