### ISSUE TITLE
Crackling with overlapping sound

### ISSUE THREAD

**Issue by Ecafracs** [Tonejs/Tone.js#397]
I have a MetalSynth that crackles when triggering after an existing note hasn't ended yet.

https://codepen.io/Ecafracs/pen/QZJxXE

Most loop intervals between 160ms and 590ms for a note with duration 500ms causes the crackling.

**Comment by tambien** [comment]
i am unable to recreate this issue with your link. what OS and browser are you using? 

one thing i noticed glancing at the code tho, is that your frequency is set to 10, which is below what most speakers/headphones can produce. if you set it to something above 100 does it work better?

**Comment by Ecafracs** [comment]
This crackling is occurring on Chrome 70.0.3538.67 / MacOS 10.14  
FWIW, I just tried on my Pixel/Chrome and it crackles there, but on my iPad/Chrome it doesn't.

Changing the frequency to 100 or higher doesn't improve the crackling.  I actually found a workaround already of setting the attack to 0.01 instead of 0.001, but I filed in case there's some underlying bug that could be fixed.

**Comment by tambien** [comment]
i'm going to close this issue since i'm unable to recreate and it seems to be fixed in your case
