### ISSUE TITLE
iOS audio + aframe 

### ISSUE THREAD

**Issue by charlievan1** [Tonejs/Tone.js#398]
Hey, I'm trying to make an aframe webVR project using Tone.js for my interaction design class. I can't seem to get any audio working on iphone. I've looked into it and I am trying to get StartAudioContext.js to work, but I'm a huge noob. I'm sure its a simple fix, I would be very grateful for any help. 

Please see my code below. 

https://glitch.com/edit/#!/sprinkle-columnist

Thanks

**Comment by tambien** [comment]
this sounds like it's related to the autoplay policy on iOS. hopefully StartAudioContext can help you out if you set it to a button. You can also take a look at [unmute](https://github.com/Tonejs/unmute) which will add a physical button to the top right corner which can mute/unmute your page. 

Another gotcha which i see sometimes is even if you did all of these steps, but still have the iOS mute rocker switch on, it'll be muted until the mute is off.

**Comment by charlievan1** [comment]
Thank you!

**Comment by charlievan1** [comment]
So I’m using version 13.3.11, and now web audio shows up on my iPhone lock screen. However, my tone.js oscillations are still not audible. They work on Firefox though. 

Strange!

**Comment by charlievan1** [comment]
Hey I got it working on someone else’s phone! It was just my crappy phone. 

Thanks again.
