### ISSUE TITLE
Consider exporting modules from dist folder

### ISSUE THREAD

**Issue by Idicious** [Tonejs/Tone.js#399]
Currently the npm install only exposes a single Umd export. To make it easier to load modularly it would be nice to copy the source folders to dist  (easiest solution, most bundlers work with it), or transpile to es6 and export that from dist folder.
I'm using tone in a react app created through 'create react app', this hides the webpack configuration and everything generally works out of box. In order to load tone modularly I either have to eject (not optimal) or maintain a fork of react-scripts-ts where I alter the webpack configuration. This is doable but not ideal, the only reason this is needed is because of the webpack path rewrite to the source folder.

An often used structure for the dist folder in npm is :

- Tone.min.js (umd, main in package json)
- es (dir)
   - index.js
   - core (dir)
      - Transport.js
   - source (dir) 
      - Source.js

import Transport from 'tone/es/core/Transport' 
import { Transport } from 'tone/es' 

This does not run the risk of breaking current builds but allows for deep imports without path rewrites since it's picked up by default module resolution. As said the most straightforward solution would be to include the amd source files in the dist folder on npm, disadvantage is no treeshaking, unsure of default bundler support, webpack does work out of the box with amd. 

- Tone.min.js (umd, main in package json)
- core (dir)
   - Transport.js
- source (dir)
   - Source.js

import Transport from 'tone/core/Transport'

**Comment by Idicious** [comment]
@tambien This looks good to me, my only issue currently is the required webpack path rewrite. I've run into a tiny 'issue', but it's no real problem. Currently unless you import Bus as `import 'tone/core/Bus'` somewhere in the codebase for Bus's doesn't work since it has no export to use directly but is not included in core/Tone itself.

**Comment by tambien** [comment]
yes that's true since some modules only install themselves after they've been imported. i'm looking into other ways to structure the library, maybe the solution is to bundle all of the 'core' modules, 'instruments', etc. 

not sure why it requires any modification to the webpack paths? with `tone@next` installed, i think both should work without any custom config

**Comment by Idicious** [comment]
I just upgraded to the tone@next version, as far as I can see the structure is unchanged, main in package.json is still pointing to build/Tone.js, and there are no sub directories under build, also no esnext:main in the package.json.

![image](https://user-images.githubusercontent.com/7814026/48069968-10bf7080-e1d7-11e8-91a5-a0a42791e3c7.png)

**Comment by tambien** [comment]
@Idicious did you try `import Transport from 'tone/Tone/core/Transport'`? that's currently the only way to deep require a module and shouldn't require any custom build

**Comment by Idicious** [comment]
It works :-) I Upgraded to create-react app v2 as well, works perfectly. I'm working on new typescript typings for tone that works with deep imports as well.

**Comment by tambien** [comment]
great will close for now. i'll link any updates on different ways to import/bundle the code to this issue going forward.
