### ISSUE TITLE
Can't create a Split in Firefox

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#400]
Run [this](https://jsfiddle.net/zfo5py6g/5/) with Firefox 63. The problem does not occur with Chrome.

Error: InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable

**Comment by Smona** [comment]
Having the same problem here. Firefox 63 is now stable so this needs to be addressed.

**Comment by tambien** [comment]
thanks for the issue, but this has already been fixed on `tone@next`. upgrade to the dev release to see that change in there. hope to have time to make an official release on the `tone@latest` channel soon. 

https://jsfiddle.net/8z6awune/

**Comment by maximedupre** [comment]
Thanks, I updated to `v13.3.11` and it works. Hopefully this version is not too unstable :). Cheers!

**Comment by maximedupre** [comment]
Hi @tambien, is it possible to re-open this bug? It seems like it stopped working, even with `tone@next` (see your link)

**Comment by tambien** [comment]
I see an error in the console in Firefox, but it does not seem to be specific to Tone.Split. and from my testing it seems like Split works fine in firefox. It seems like refreshing a page with Web Audio on it, prints that error to the console.

I tried with [this page](https://webaudioapi.com/samples/oscillator/) which does not use any Tone.js on it and got the same error.
