### ISSUE TITLE
Making Tone.js modular

### ISSUE THREAD

**Issue by ricardomatias** [Tonejs/Tone.js#402]
@tambien, are there plans to make the library modular? F.ex separating it into multiple packages per domain.

Personally, I'm pondering externalising the part that it is related to the Time domain. I think there are plenty of cases where it's not necessary having an "audio engine". Another advantage would be as a lower barrier to people wanting to contribute, since it's quite daunting right now to delve into the code, even though it's well documented.

If there's an interest in doing so, then I'd draft some kind of roadmap. Otherwise, I'll just probably anyhow hack it away for myself.

**Comment by spencerudnick** [comment]
I've considered doing something similar, with the goal of a more modular
Tone.js built with ES6 / TypeScript. If others are interested it could be
useful.

**Comment by spencerudnick** [comment]
In particular, I want to leverage Tone's timing and MIDI implementations
without having to incorporate the Tone wrappers for the Audio context. From
what I've seen this is very difficult currently.

**Comment by Idicious** [comment]
You can already import the AMD source files seperately. For example `import Transport from 'tone/Tone/core/Transport'`. This works as long as you have a module bundler that support AMD imports, such as webpack.
I'm currently working on a comprehensive typescript definition project that works with deep imports. I'm mostly done and using it already in a project.

**Comment by spencerudnick** [comment]
@idicious I would be very interested to see this version you have!

**Comment by tambien** [comment]
this multipackage approach is something i've been looking into recently as well. i've registered `@tonejs` organization on npm. i was thinking of separating out `@tonejs/shim` and maybe `@tonejs/core`, but eventually could also separate out `@tonejs/time` as you mentioned and some other packages to make it easier to build more modular components on top of the library. 

I looked into [lerna](https://github.com/lerna/lerna) a little, but i'm not sure that this is what i need exactly. i don't think i will move things into separate repos since they all rely on a common set of build tools and tests, but having a monorepo with multiple packages seems appealing. If anyone has experience with lerna or with monorepos, please chime in with how it might work in Tone.js. 

@ricardomatias: As @Idicious mentioned, you can deep require every module and it will pull in it's dependencies if you're using something like webpack, so it's possible to grab some of the timing components without pulling in the entire audio engine part.

**Comment by spencerudnick** [comment]
🔥

**Comment by fabb** [comment]
> In particular, I want to leverage Tone's timing and MIDI implementations without having to incorporate the Tone wrappers for the Audio context.

Maybe a related question on modularity: I imagine it might be desirable to use non-Tone.js AudioNodes inside of a project that uses Tone.js (or just its supposed timing/midi parts). These might be implemented without Tone.js in mind, and released as npm packages without a Tone.js dependency. They might be implemented in a way to be controlled with an interface of native AudioParams.
So to be pulled into a project using Tone.js, as far as I have understood there needs to be a wrapper layer that makes the AudioParams interface controllable with Tone.Signals that also supports scheduling and other Tone.js specific features.
That wrapper around that specific AudioNode synth/effect could even be published as an own npm package to be reusable for many projects. It would need a dependency on Tone.js, or if Signal could be extracted as a module, just on that.

If I got any concepts of Tone.js wrong, I‘m happy to learn more, I‘m just getting into this.

**Comment by redfoxDW** [comment]
I feel this is worth throwing into the discussion:
What about Shader and ShaderPass import? There are many in the examples that I would consider worth having in an independent package. Also what is currently the best practice if I have an ES6 project and want to use the npm module in combination with some of the Example Shader classes?

**Comment by Idicious** [comment]
@fabb You already can connect a Tone node to a native audio node, the reverse would require using the currently undocumented audionode.input property.
So you can do `nativenode.connect(tonenode.input)` as well as `tonenode.connect(nativenode)`

**Comment by fabb** [comment]
Thaht‘s nice! But how would I trigger notes based on Tone.js‘ Transport in this native audio node synth?

**Comment by spencerudnick** [comment]
You would need to create a wrapper interface for the native node, perhaps
create a class which encompasses a gain and audio source. Then expose an
interface which handles the incoming midi commands to control gain and
frequency.

**Comment by Idicious** [comment]
@spencerudnick This is ofcourse essentially what the Tone synths do.

**Comment by spencerudnick** [comment]
Exactly :)

**Comment by fabb** [comment]
So I would actually mimick the interface of Tone synths in my wrapper, right? So for Tone it‘s actually no more a native audio node but it thinks it‘s a Tone synth?

**Comment by spencerudnick** [comment]
If your class fulfills the same interface, Tone won't know the difference.

**Comment by fabb** [comment]
The magic of javascript... Let‘s see how hard it is to fulfil that interface. It would be awesome to extract a Tone.js wrapper for the aufionode part of the Viktor NV-1 synth.
https://nicroto.github.io/viktor/

**Comment by tambien** [comment]
it shouldn't be a problem to mix native web audio nodes or other web audio modules as long as they share the same AudioContext. You don't need to mimic a Tone.js synth interface for it to be able to interoperate with Tone.Transport or any other Tone.js component.

**Comment by fabb** [comment]
> You would need to create a wrapper interface for the native node, perhaps create a class which encompasses a gain and audio source. Then expose an interface which handles the incoming midi commands to control gain and frequency.

Ok, when I want to play the external synth using Tone Patterns, I need to somehow sync the attack and release commands to the provided `time` and `duration` (and maybe other parameters need to be synced as well using `Tone.Signal`).
I'm not yet completely sure how such a wrapper that bridges between Tone scheduler and the 3rd party instrument would need to look like, and if it could be generalized and broken out into a separate component.

**Comment by tambien** [comment]
The time value returned from the event classes (like Tone.Pattern) is just the raw Web Audio clock time. A native or third party component that can be scheduled using the AudioContext time could take this time and use it to synchronize with the Tone.Transport.

**Comment by tambien** [comment]
Going to close this issue since Tone currently has the ability to load individual modules, though i aspire to better grouping in the future and potentially releasing sub packages. I will reference this issue if/when that happens.
