### ISSUE TITLE
Most examples do not work in Safari on Mac

### ISSUE THREAD

**Issue by i3games** [Tonejs/Tone.js#406]
The following examples played from the website (tone.js r12) do not work, i.e. they fail silently without error message in Safari 12.0.1 on Mac 10.14.1. The examples not listed work.

* Envelope: no sound
* Player: Start button needs to be kept pressed down to play the track
* Mixer: no sound
* FatOscillator: no sound
* Metal Synth: no sound
* Granular Synthesis: No sound
* LFO Effects: no sound
* Spatialization/ Panner3D: no sound
* Step Sequencer: no sound
* Events: (not sure)
* Playback Rate: no sound
* Transport Sync: no sound
* Control Voltage: no sound
* Ramping Values: no sound
* Animation Sync: no sound, no visuals
* Envelope: no sound, no visuals

**Comment by tambien** [comment]
thanks for the issue, this is probably related to the Autoplay policy on Safari. planning on updating soon as more browsers adopt a similarly strict Autoplay policy.

**Comment by fabb** [comment]
Since the same Autoplay Policy is now also affective for Chrome, all the same examples are broken for Chrome as well. Please ask authors to fix them, they are awesome!

**Comment by tambien** [comment]
@eltomito the solution is to invoke `Tone.context.resume` from an explicit user action. There is little that a library can do to get around the Autoplay policy, it is something that each developer must do for their own application. i will add a note to the top of the README

**Comment by tambien** [comment]
fixed with the latest release!

**Comment by tambien** [comment]
🙄 oh man, why would they do that?!
