### ISSUE TITLE
Tone Master multi send

### ISSUE THREAD

**Issue by luisArandas** [Tonejs/Tone.js#412]
Is there a way to send Tone.Master from current page to another context -> for example page2.html ?
Best, Luis

**Comment by spencerudnick** [comment]
Check out: https://react raining.com/react-router/

If you are unfamiliar with React, look through their docs to get a sense
for how the framework abstracts HTML and DOM interaction.



If you're interested in sharing data between tabs  / windows, there's the
new BroadcastChannel API (MDN docs: https://mzl.la/2A2NOYe). You could
theoretically broadcast a buffer array or an object reference, but
AudioContexts are still intentionally isolated.

**Comment by luisArandas** [comment]
Thank you very much.
Best, Luis

**Comment by spencerudnick** [comment]
Suggest the create-react-app npm package.

```
$ npm install -g create-react-app
$ create-react-app my-app
```

**Comment by tambien** [comment]
as @spencerudnick mentioned, the AudioContext is window specific and there is no built-in Web Audio way pass audio from one page to another. Might be something you can do with WebRTC?
