### ISSUE TITLE
PolySynth Voice Inconsistency

### ISSUE THREAD

**Issue by tboie** [Tonejs/Tone.js#415]
Chord notes are not being played. Delayed audio artifacts can be heard for larger chord lengths. 

Tone@next affected
Tone@latest OK

Demonstration and more information here:
https://jsfiddle.net/timboie/r8uskqb1/

**Comment by tambien** [comment]
Should be fixed now. i went with a slightly different way of finding free voices which is to check for the lowest envelope value a small time into the future. might not be fool-proof, but worked well in my testing. 

[here's your fiddle with the latest version](https://jsfiddle.net/pa06zgfd/2/)
