### ISSUE TITLE
Sounds unexpectedly not triggering

### ISSUE THREAD

**Issue by Ecafracs** [Tonejs/Tone.js#416]
This is a really weird one.  I have a kick, snare, and cowbell sound, and a loop triggering all three sounds.  This works fine.
If I comment out the call to play the snare sound, the other two sounds stop working as well.

See the codepen and the line to comment out.
https://codepen.io/Ecafracs/pen/ZVLJKB

Trying across different platforms, it seems only Android/Chrome doesn't have this problem.  But on Windows 10/Chrome(71) iPad/Chrome, MacOS/Chrome(71), and ChromeOS(71) this is not working.

Oh, and I'm sure you're aware, but the stupid new autoplay policy means you have to click in the window to get sound.

**Comment by tambien** [comment]
Weird bug, but this seems to be just an autoplay policy thing. Somehow the snare was able to enable playing, but without the snare, audio remained disabled. 

the solution is just to add `Tone.context.resume()` to the onclick handler to ensure that the audio context is started. 

https://codepen.io/yotam/pen/KbaBOP

**Comment by Ecafracs** [comment]
Thanks for looking into it, that was pretty dumb on my part.
Now instead of wondering why it didn't work, I'm wondering why it worked at all.
