### ISSUE TITLE
No sound on raspberry pi (3b+)

### ISSUE THREAD

**Issue by dhowe** [Tonejs/Tone.js#417]
No error, but no sound either, in chromium 65.0.33

**Comment by dhowe** [comment]
whats the simplest bit of code I can run to just test tonejs playing a sample ?

**Comment by dhowe** [comment]
I solved the problem by loading startAudioContext.js first, but a) I'm not sure why this is needed, and b) it doesn't seem to be documented

**Comment by tambien** [comment]
glad to hear it works on a Raspberry Pi! The universal adoption of the autoplay policy is pretty recent and i haven't updated the docs and examples fully to reflect this. i'll add a line to the README.
