### ISSUE TITLE
Arithmetic Expressions for Note Time Values seem Broken

### ISSUE THREAD

**Issue by fabb** [Tonejs/Tone.js#418]
The [example for `Tone.Part` in the Wiki](https://github.com/Tonejs/Tone.js/wiki/Events#tonepart) suggests that arithmetic can be used for note time values:

```
var part = new Tone.Part(function(time, pitch){
	synth.triggerAttackRelease(pitch, "8n", time);
}, [["0", "C#3"], ["4n", "G3"], ["3 * 8n", "G#3"], ["2n", "C3"]]);
```

=> `"3 * 8n"`

This does not seem to work, the note is not played back: https://jsfiddle.net/hbt5q9mf/

The feature would be useful though when wanting to specify a melody (e.g. the note at `"0:3:0"` could also be specified as `"3 * 4n"` or `"2n + 4n"`).

Should such arithmetic expressions be supported, or is the example in the Wiki wrong?

**Comment by fabb** [comment]
Closing since arithmetic expressions were removed in 0.12.0, as stated in the release notes:

> BREAKING CHANGES:
> 
> Tone.TimeBase and all classes that extend it not longer support string expressions.
> RATIONALE :
> * Since all classes implement valueOf, expressions can be composed in JS instead of as strings
> * e.g. Time('4n') * 2 + Time('3t') instead of Time('4n * 2 + 3t')
> * this change greatly simplifies the code and is more performant

I updated the Wiki page accordingly: https://github.com/Tonejs/Tone.js/wiki/Events/3537ef75fd55ab729c5ad7f14771feae901a8bac

**Comment by tambien** [comment]
@fabb thanks for updating that page! i thought i removed all the references to the deprecated string expressions. tone@13 introduces a new object notation which will hopefully give you the same expression abilities. 

For example: `Time("4n*3 + 8n*5")` can be written like this `Time({"4n" : 3, "8n" : 5})`

**Comment by tambien** [comment]
good catch! i'll be sure to update that

**Comment by fabb** [comment]
one more ;-)
https://tonejs.github.io/docs/r12/Type#time

**Comment by tambien** [comment]
@fabb fixed in the latest dev docs: https://tonejs.github.io/docs/dev/Type#time
