### ISSUE TITLE
Is it possible to re-sync the player position or start time with offset?

### ISSUE THREAD

**Issue by tareq0065** [Tonejs/Tone.js#419]
I have added multiple players dynamically. But for the purpose, I need to update or re-sync the player start time or position after added. like as default the start position will be 0, but after added with start time 0 I need to update the start time to 4. Is it possible to do that?

**Comment by tambien** [comment]
I think calling 'unsync' and then calling sync, then start with the new start time should do it.

**Comment by tareq0065** [comment]
@tambien Thanks for your reply. I have a question about your concern. Can I load a player with a specific id and sync or un-sync later by selecting with that id?

**Comment by tambien** [comment]
if i understand your question correctly, no you'll have to keep track of the player yourself. The Transport id system is only for keeping track of scheduled events not sources like Tone.Player.

**Comment by tareq0065** [comment]
Yeah Thanks a lot, bro. I have managed to track the player. I need a little more help on that. I have created a timeline bit ruler for a simple daw. But the timeline is not synchronized to the Tone.Master. I have used 3000px for the total width for my daw and added an interval of 24px so that I can create a bit ruler for my timeline. Is there any way to synchronize my timeline with the Tone.Maste so I can create a perfect timeline bit ruler for my project? Never mind I am new to Tone.js
![rul](https://user-images.githubusercontent.com/25137925/50723928-dad33580-110e-11e9-9922-c00e4ff7b89c.png)

**Comment by Idicious** [comment]
@tareq0065 The time line is a measure of progress over time, so depending on the bpm and time signature you could space out the ticks. You would have to determine a unit of time you want to display for a given distance. A possible measure for this would be samples per pixel. If your audio is at 48khz, and you have 48000 samples per pixel, than one pixel represents one second of time. So a marker at 1 second would be at pixel 1. You can convert a Tone beat to second with TransportTime('1n').seconds.
Hope this gets you started, will add examples later.

**Comment by tareq0065** [comment]
@Idicious Thanks. I have created the timeline. I have got the total length of the canvas and created a loop to create a bar every 12px. That means the cursor will go 12px in every second. Also I have snapped tracks when I am dragging. The step is 12px. My bit ruler is working good now. I am adding the code if it helps someone.

    createBitRuler() {
        const step = 12;
        const barposition = 96;
        const zoom = 1;
        const canvas = document.getElementById("bitruler");
        const bitrular = canvas.getContext("2d");
        bitrular.clearRect(0,0,canvas.width,canvas.height);
        bitrular.beginPath();
        bitrular.font = "10px Arial";
        let counter = 1;

        for (var i = 0; i < canvas.width; i += step) {
            var y = (i / barposition === parseInt(i / barposition)) ? 0 : 10;
            if(i / barposition === parseInt(i / barposition)) {  // every 8th position
                let countertext = counter/zoom // if you have zoom countertext will be used instead the counter
                bitrular.fillText(counter,i+step, 8);
                counter++;
            }

            bitrular.moveTo(i + 10, y);
            bitrular.lineTo(i + 10, 15);
        }
        bitrular.lineWidth = .50;
        bitrular.strokeStyle = '#b4b4b4';
        bitrular.stroke();
    }
When I am dragging the tracks I am unsyncng the track from master and re syncing after drop with new position. But the problem is that previous track is still playing one time after drop. I need to get the current sync posiotion every time I drop and totaly destroy the previous one synced. Do I use dispose for this? I mean dispose and unsync then re-sync the current player?
![syncpositios](https://user-images.githubusercontent.com/25137925/50733280-11fc2200-11b5-11e9-800d-f3fd43f91c76.png)

**Comment by Idicious** [comment]
Here is a codepen with a d3 based zoomable, infinately scrollable timeline. Which library are you using to draw the waveforms? 

https://codepen.io/idicious/pen/zjeqPm

**Comment by mhtkmr** [comment]
> @Idicious Thanks. I have created the timeline. I have got the total length of the canvas and created a loop to create a bar every 12px. That means the cursor will go 12px in every second. Also I have snapped tracks when I am dragging. The step is 12px. My bit ruler is working good now. I am adding the code if it helps someone.
> 
> ```
> createBitRuler() {
>     const step = 12;
>     const barposition = 96;
>     const zoom = 1;
>     const canvas = document.getElementById("bitruler");
>     const bitrular = canvas.getContext("2d");
>     bitrular.clearRect(0,0,canvas.width,canvas.height);
>     bitrular.beginPath();
>     bitrular.font = "10px Arial";
>     let counter = 1;
> 
>     for (var i = 0; i < canvas.width; i += step) {
>         var y = (i / barposition === parseInt(i / barposition)) ? 0 : 10;
>         if(i / barposition === parseInt(i / barposition)) {  // every 8th position
>             let countertext = counter/zoom // if you have zoom countertext will be used instead the counter
>             bitrular.fillText(counter,i+step, 8);
>             counter++;
>         }
> 
>         bitrular.moveTo(i + 10, y);
>         bitrular.lineTo(i + 10, 15);
>     }
>     bitrular.lineWidth = .50;
>     bitrular.strokeStyle = '#b4b4b4';
>     bitrular.stroke();
> }
> ```
> 
> When I am dragging the tracks I am unsyncng the track from master and re syncing after drop with new position. But the problem is that previous track is still playing one time after drop. I need to get the current sync posiotion every time I drop and totaly destroy the previous one synced. Do I use dispose for this? I mean dispose and unsync then re-sync the current player?
> ![syncpositios](https://user-images.githubusercontent.com/25137925/50733280-11fc2200-11b5-11e9-800d-f3fd43f91c76.png)

@tareq0065 Have you resolved this issue of the player still playing from an inital position even after updating to the new position?

**Comment by tareq0065** [comment]
@mhtkmr Yes I have solved it by calculating the offset left and the position of the dragged playhead.
