### ISSUE TITLE
Loop not firing

### ISSUE THREAD

**Issue by charlesswanson** [Tonejs/Tone.js#420]
Hi, I'm just getting started learning Tone.js. I don't understand the behavior I'm seeing so I want to check whether I've overlooked something in the docs, or it is a bug.

I'm trying to play a Tone.BufferSource in a loop. However, the loop's callback will only fire if I also include an unrelated line:
```
new Tone.MembraneSynth().toMaster()
```

A repro is as follows:
1.) load https://codepen.io/charlesswanson/pen/dweNaW?editors=1010 in Chrome
2.) open chrome's console
3.) click start in the codepen
Expected: the console shows "loop" log entries periodically. Actual: no log entries

The logs will show if you rerun the codepen after changing false to true:
```
const createSynth = false;
```
This repros for me on codepen and my local environment. It does not repro for me in jsfiddle. I'm using https://unpkg.com/tone@latest in both codepen and jsfiddle.

**Comment by charlesswanson** [comment]
Here's another example: https://codepen.io/charlesswanson/pen/OrZpRr?editors=1010
The loop starts for me in Firefox, but not Chrome. Maybe there's a race condition?

**Comment by charlesswanson** [comment]
Turns out to be the same problem as: https://github.com/Tonejs/Tone.js/issues/416
This fixes it:

> the solution is just to add Tone.context.resume() to the onclick handler to ensure that the audio context is started.

**Comment by tambien** [comment]
I will think about ways to make this error more apparent through console logging since i think this will be a very common issue going forward.
