### ISSUE TITLE
FFT getValue() returning unexpected results when connected to a synth.

### ISSUE THREAD

**Issue by FuzzyWobble** [Tonejs/Tone.js#423]
I am getting some wild FFT values when I connect it to a synth. 

After playing the first note the values go all over the place and never normalizes. It says the expected output for getValue() of FFT is -1 to 1. I get values much larger than that. 

Is this a bug or have I hooked it up wrong?

I tried the same thing with Tone.Analyser("fft",FFT_COUNT) and it gave the same results. 

Tone.Analyser("waveform",FFT_COUNT) seems to be working fine.

<img width="458" alt="screen shot 2019-01-11 at 12 38 15 pm" src="https://user-images.githubusercontent.com/1490568/51050143-d4750b80-159d-11e9-906e-4178bd768494.png">

Output from FFT: 
<img width="1145" alt="screen shot 2019-01-11 at 12 37 15 pm" src="https://user-images.githubusercontent.com/1490568/51050145-d8089280-159d-11e9-99da-2285dc594b64.png">

Thanks!

**Comment by tambien** [comment]
Error was in the docs. those float values are decibel levels at each of the frequency bins. that snippet was copy-pasted from the Tone.Waveform which returns -1 to 1.

**Comment by FuzzyWobble** [comment]
Thanks!

Is it possible to explain how you have the nice clean FFT and WAVEFORM data from this example: https://tonejs.github.io/examples/analysis.html

I looked at the code but have no idea how it is being rendered... Especially given I can't really make sense of my FFT values...

**Comment by tambien** [comment]
The waveform example takes the array values between -1 to 1 and scales them between 0 and `canvas.height`, and scales the index of the array values to between 0 to `canvas.width`.  [code here](https://github.com/Tonejs/ui/blob/master/src/viz/oscilloscope.js#L24). 

A similar technique for the fft, but i scale values between -100 to 0. [code here](https://github.com/Tonejs/ui/blob/master/src/viz/fft.js#L24)

**Comment by jamesgrubb** [comment]
Hi in the linked code example you use Math.scale is this from Underscore or something similar?

**Comment by pkl** [comment]
@jamesgrubb 
These should work:
https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/esnext.math.clamp.js
https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/math-scale.js

**Comment by codeitloadit** [comment]
> Error was in the docs. those float values are decibel levels at each of the frequency bins. that snippet was copy-pasted from the Tone.Waveform which returns -1 to 1.

How come the values are all negative? I mean, I get that they are negative because they are decibel levels, but they are way lower than the decibel level of the output. Is that because with all of them combined the final result is equal to their output level as a whole?

I am actually trying to make a tuner (pitch detection) using the FFT, but I am new to audio processing and I'm wondering if this is the best way to go about it. Maybe I'd be better off analyzing the Waveform data?

**Comment by micuat** [comment]
@codeitloadit hi I just came across this (which was helpful to understand what the range of fft is) and know it's late but I explain you why - basically decibel is a logarithm of the original scale. `log(1)` returns 0 no matter what the base is, and `log(0)` is `-Infinity`. So when the input is close to 0 (silence), the dB output will end up with a huge negative number. You can use `Math.max(-100, fft.getValue()[n])` to clamp the output if that is easier for processing.
