### ISSUE TITLE
Notes playing double or not at all in Chrome

### ISSUE THREAD

**Issue by eltomito** [Tonejs/Tone.js#425]
Hi!

I'm developing a simple web app using Tone.js. From what I've tried, it works in Firefox/Linux the Android browser and mobile Safari but it behaves odd in Chrome/Linux.

The problem is illustrated by this jsfiddle that should play 8 alternating notes (C3, C4, C3, C4...) but some of the notes are either doubled or suppressed in Chrome:

https://jsfiddle.net/cpx7y0vn/

Here's a video of what this jsfiddle does in FF and in Chrome on Linux.

https://vimeo.com/311313520

Am I doing something wrong? It behaves the same if I use Tone.Part instead of Transport.schedule() .
It seems something like the now closed issue #163 . Is there a workaround?

Thank you for your time!

**Comment by tambien** [comment]
very interesting. thanks for the thorough bug report. seems to have something to do with the attack duration being 0 and how safari and FF handle a linearRampToValueAtTime with duration 0 versus how chrome handles it. if you change the attack value to (even really small values like 0.001), you don't get that discrepancy. i will look into this more and either set a non-zero minimum attack time or see if i can track down the root of the problem somewhere else.
