### ISSUE TITLE
Polysynth Voice Inconsistency

### ISSUE THREAD

**Issue by tboie** [Tonejs/Tone.js#426]
Playing less voices than the max set in PolySynth results in various audio inconsistencies. 

Tone@next affected (13.4.10) (Chrome 71.0.35, Firefox 64.02)
https://jsfiddle.net/timboie/7cs3zkbh/

Tone@0.12.80 OK

**Comment by tambien** [comment]
what sort of audio inconsistencies? I'm clicking the green square and hearing 3 random notes play.

**Comment by tboie** [comment]
Updated jsfiddle link with correct demo (oops!).  

https://jsfiddle.net/timboie/7cs3zkbh/

Try tapping the green square then holding the green square at random intervals.  Some notes are not played back with fullness of sound for a short time (~1sec).

Here is a video for better reference:
https://youtu.be/V8zratasJ_g

This happens on chrome v71 as well

**Comment by tboie** [comment]
using triggerRelease(notes) instead of releaseAll() seems to be OK with tone@next.  need to do more testing

**Comment by tambien** [comment]
Playing with this now on Chrome 72, i am unable to recreate this issue anymore. i wonder if it was a problem that version of Chrome? tested both with triggerRelease and releaseAll. lmk if you can confirm that.

**Comment by tboie** [comment]
issue confirmed using  v13.7.7 and Chrome 72.  releaseAll appears to affect the next triggerAttack call when used.

**Comment by tambien** [comment]
how does it affect the next triggerAttack call?

**Comment by tboie** [comment]
Same sound "inconsistencies/artifacts" as shown in the demo.  

It's difficult to reproduce these occurrences in a controlled manner than live, but here are some differences I noticed while using the updated polysynth:

- Some notes sound shallow and missing a full body of sound.
- Some chord notes stay stuck on.
- Old polysynth handled more voices.  (Compared number of voices each version could handle before not working on my system).
- releaseAll seems to be a source of audio problems as demonstrated.  Especially if triggered more than once. 

These problems could be on my end.  Maybe missing some details, wrong usage, system problem, but the old version was intuitively more reliable and stable from my experience. 

Going to switch back to the older polysynth for now to ensure my observations hold true.

The polysynth is a wicked feature, and just want the best for it :)

**Comment by hoshikitsunoda** [comment]
Sorry for a newbie question.
I'm trying to use Tone.PolySynth() inside the React component.
I have it set like this:

`synthNoEffect = new Tone.PolySynth())`

then call it in handler:

`handleSingleNote = () => {
    this.synthNoEffect.triggerAttack(this.state.note)
  }

  handleSingleNoteRelease = () => {
    this.synthNoEffect.releaseAll()
  }`

App listens to keypress to trigger and keyup to release.
When I try to play continuous note by holding a key, the note stutters instead of making continuous note.
Is it because of React and Tone.js compatibility? It sounds fine when I tested as vanilla js.

**Comment by tboie** [comment]
Need to see component code @hoshikitsunoda

**Comment by hoshikitsunoda** [comment]
@tboie 
Sorry about the delay.
Not sure what the best way to share is so just pasting a link to my repo:

https://github.com/hoshikitsunoda/react-synth

Let me know if there's better way to share the code.
Thanks!

**Comment by tboie** [comment]
@hoshikitsunoda Is your keypress event listener being called continuously while pressed down?

**Comment by hoshikitsunoda** [comment]
@tboie Yes. I tried keydown too but still the same result. DuoSynth, AMSynth and FMSynth works fine but MonoSynth and PolySynth are stuttering.

**Comment by tboie** [comment]
@hoshikitsunoda both keydown and keypress events are called repeatedly when a key is held down.  

See example here:
https://jsfiddle.net/timboie/L54ubz8h/

Is triggerAttack being called repeatedly?  If so, only allow 1 call to triggerAttack

**Comment by hoshikitsunoda** [comment]
@tboie added event.repeat conditional to eventlistener callback and now it works like a charm:) Thank you so much for help!!

**Comment by tambien** [comment]
@tboie i think this is fixed now on the `typescript` branch. I reworked the PolySynth a lot. It does not do any voice stealing which seemed to be a major source of the bugs, but i also optimized voice creation so there shouldn't be a major cost to over-provisioning polysynth voices. 

Here's your fiddle with the latest build: https://jsfiddle.net/yotammann/t2b7ksza/

it doesn't cause any of those glitches that you had noticed before.

**Comment by tboie** [comment]
This is awesome @tambien!  I'll dig into this when I get a chance.  Definitely have to get caught up with the typescript branch.  Getting familiar with typescript myself over the past few weeks.  Thanks!

**Comment by tambien** [comment]
i just pushed a change to the typescript branch which does not require a polyphony argument, just the synth voice type and the synth's options. The voice allocation and disposing is handled entirely under the hood with the option of setting 'maxPolyphony'. 

If you get a chance to try it out on the typescript branch: `tone@^14.3.5`, it'd be great to know how it performs in the wild.

**Comment by tambien** [comment]
typescript branch is now in 'dev'. going to close. please open a new issue if there is still a problem with this component. PolySynth ended up being much more complicated than i though to get all of the details right, hopefully the new typescript version works well.
