### ISSUE TITLE
Tone.min.js link on main page leads to 404

### ISSUE THREAD

**Issue by faxinadu** [Tonejs/Tone.js#428]
Just a heads up that the link on the main page to the minified library leadas to a 404 -
https://tonejs.github.io/build/Tone.min.js

Cheers

**Comment by tambien** [comment]
thanks! the [main build](https://tonejs.github.io/build/Tone.js) is now minified and includes a Tone.map.js file, so there's no non-minified version anymore. 

In general i'm hoping people use something like https://unpkg.com/tone instead of relying on that link.

**Comment by faxinadu** [comment]
great thanks :) most of all glad to see this repo is super active after spending about a month going through buggy half abandoned sound libs.
