### ISSUE TITLE
PolySynth Portamento

### ISSUE THREAD

**Issue by tboie** [Tonejs/Tone.js#429]
PolySynth portamento not accurate/functional when playing less notes than number of voices set for all monophonic synths.  Functionality is impacted for ratio of notes being played to max voices set for polysynth.

tone@next and tone@latest affected

Chrome 71 & Firefox 64

Example here:
https://jsfiddle.net/timboie/rLg3mtfn/

**Comment by tambien** [comment]
This is actually the intended behavior. PolySynth chooses a voice based on the available voices and portamento is only possible if it's reallocating the same voice. So if you've got available voices it's going to use those instead of gliding between already playing voices.
