### ISSUE TITLE
"Uncaught TypeError: Failed to execute 'connect' on 'AudioNode': No function was found that matched the signature provided." starting in 13.7 (maybe 13.6)

### ISSUE THREAD

**Issue by rodw** [Tonejs/Tone.js#434]
I'm afraid I don't have time to whittle this down to a minimal example that reproduces the problem right now, but perhaps this info will be sufficient to identify the problem and I don't want to lose the detail I _do_ have so far. I'll follow up with more details as I can.

I'm using Tone.js (and in particular, Tone.js's `OfflineAudioContext`) together with [webaudio-tinysynth](https://github.com/g200kg/webaudio-tinysynth) to synthesize music.  This is running within an [Electron](https://electronjs.org/) application.

My program works correctly with Tone 13.5.0, but when I upgrade to 13.7 I consistently get this error:

```
Uncaught TypeError: Failed to execute 'connect' on 'AudioNode': No function was found that matched the signature provided.
```

I have confirmed that swapping between Tone 13.5.0 and Tone 13.7.1 will consistently make the program work or not work (respectively).

The specific line on which the error occurs is [Line 1293 in webaudio-tinysynth.js](https://github.com/g200kg/webaudio-tinysynth/blob/5d9a615c6520c020d6fce8b48cef2592ad04cec2/webaudio-tinysynth.js#L1293).  In my case that works out to something like this:

```
DynamicsCompressorNode.connect(OfflineAudioContext)
```

(where `DynamicsCompressorNode` is a instance of Chrome's implementation of the [WebAudio DynamicsCompressorNode](https://developer.mozilla.org/en-US/docs/Web/API/DynamicsCompressorNode) and `OfflineAudioContext` is an instance of Tone's `OfflineAudioContext`) as a result of calling:

```
tinysynth.setAudioContext(Tone.context, Tone.Master)
```

from within a `Tone.Offline` context.

For what it is worth I don't think there is anything special about that particular pairing, I seem to get the same error with any `AudioNode.connect(OfflineAudioContext)`.

The only info I can find from googling that error message suggests that it is triggered by setting a `NaN`-valued or `Infinity`-value AudioParam, but after trying to hunt that down for a long time I'm not sure that's actually the problem I'm running into.

**Comment by tambien** [comment]
I've made these changes over the past couple of days which i think is what's causing your issue. Unfortunately, this is the new intended behavior and not a bug and will take a slight refactor to your code to upgrade to the latest version. 

AudioNode.prototype.connect/disconnect _used_ to be overwritten with a method which would accept Tone.js nodes in addition to native Web Audio Nodes. I think it's pretty well agreed upon that it's [not great to modify built-in classes or methods](https://humanwhocodes.com/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/), and as the library is more widely used, the potential for this causing issues in other people's code and libraries increases. With some encouragement from @chrisguttandin, I've decided that it's best to move away from overwriting any native methods. 

There are two ways to fix this issue, either replace instances where you're connecting native nodes to Tone.js nodes with `Tone.connect(srcNode, dstNode, [inputNum=0], [outputNum=0])`. Or as a stop-gap, you can overwrite the native AudioNode.prototype.connect yourself to go back to the previous behavior: 

```javascript
const nativeConnect = AudioNode.prototype.connect
AudioNode.prototype.connect = function(dstNode, inputNum, outputNum){
  if (dstNode instanceof Tone){
    Tone.connect(this, dstNode, inputNum, outputNum)
  } else {
    nativeConnect.call(this, dstNode, inputNum, outputNum)
  }
}
```

I haven't tested this code, but it's pretty similar to what was in there before.

**Comment by rodw** [comment]
Thanks @tambien 

Just to make sure I understand you correctly, by this:

> replace instances where you're connecting native nodes to Tone.js nodes with Tone.connect(srcNode, dstNode, [inputNum=0], [outputNum=0])

You mean that if I start with this:

```
srcNode.connect( dstNode, [inputNum=0], [outputNum=0] )
```

it should change to this:

```
Tone.connect(srcNode, dstNode, [inputNum=0], [outputNum=0])
```

(which is your original example).

Right?

**Comment by tambien** [comment]
that should do it. all Tone.connect does is grabs the correct input from Tone.js which encodes it's inputs a little differently than Web Audio. Since they're all abstractions, each class has an 'input' and 'output' node. Tone.connect looks for that input node so that it could connect to it.

**Comment by jaqarrick** [comment]
@tambien This solution doesn't seem to work when using React/Typescript:

I'm getting following error:

```Unhandled Rejection (TypeError): AudioNode.connect: Argument 1 does not implement interface AudioNode```

I'm passing streams with WebRTC, so the getUserMedia in my code is just an example. Outside of React/TS this works just fine following your solution.

[Here's a link to the full gist.](https://gist.github.com/jaqarrick/d59a5ee4886fe81ba7b29361c2531a16)

Thanks in advance!


```

	//Tone Audio Node 
	const toneGain = useMemo(() => new Tone.Gain), [])

	useEffect(() => {
		//Set Tone Context to AudioContext
		Tone.setContext(ac)

		//Connect Tone Vol Node to Destination
		Tone.connect(toneGain, Tone.context.destination)
	}, [toneGain])

	const connectStream = useCallback(
		(stream: MediaStream) => {
			//create media stream source
			const src: MediaStreamAudioSourceNode = ac.createMediaStreamSource(stream)
			//connect the source to Tone Volume Node
			Tone.connect(src, toneGain, 0, 0)
		},
		[toneGain]
	)

	const initUserMedia = useCallback(async () => {
		const stream: MediaStream = await navigator.mediaDevices.getUserMedia({
			audio: true,
		})
		connectStream(stream)
	}, [connectStream])
```

**Comment by tambien** [comment]
After you set a new context, `Tone.context` is still referring to the old one. (This has been since version 14.x). Try `Tone.getContext().destination` instead when connecting nodes.

**Comment by jaqarrick** [comment]
That solved the issue! Thanks :)

**Comment by NoubaaB** [comment]
![react](https://user-images.githubusercontent.com/39311144/135617394-72082fbe-9e28-43a4-a862-94dfeaa7b081.png)
