### ISSUE TITLE
Difficulties understanding time notation

### ISSUE THREAD

**Issue by sikko** [Tonejs/Tone.js#440]
I have a question about [this page in the documentation](https://github.com/Tonejs/Tone.js/wiki/Time#notation)

If "2m" = two measures, then what does "4n" stand for? The page says "4n" = quarter note.
Shouldn't it say "4n" = 4 quarter note ? or is it actually "4n" = 1 quarter note ?

**Comment by tambien** [comment]
you can think of "m" as a measure multiplier and "n" is a measure divider. So "4m" is 4 measures and "4n" is 1/4 of a measure (or a quarter note).

**Comment by sikko** [comment]
Thanks so much, that's much clearer now. Maybe this explaination should be added to the docs?

**Comment by tambien** [comment]
@sikko yes! feel free to add. the wiki should be editable by anyone with a github account.
