### ISSUE TITLE
 help for my pan flute web sampler

### ISSUE THREAD

**Issue by panfluterman** [Tonejs/Tone.js#445]
Please guys I need to make a sampler web application that reads midi songs and shows the note that is being played in a pan flute, could you help me? example
https://www.youtube.com/watch?v=UnRfZAJa8Nw

**Comment by tambien** [comment]
hi @panfluterman. great video reference. sounds like an interesting project. these github issues are for bugs and feature requests. You might have more luck on StackOverflow or the Tone.js forum. i think you'd also get a more useful answer if you were able to make your question more specific. 

[here's an example](https://github.com/googlecreativelab/chrome-music-lab/tree/master/pianoroll) of decoding midi and visualizing it on a piano roll.
