### ISSUE TITLE
Get Master output buffer

### ISSUE THREAD

**Issue by MileanCo** [Tonejs/Tone.js#446]
I would like to do the following, play a URL (wav file), add some effects, and then get the buffer and save to a file. However, when I call player.buffer.get(), it just returns the original buffer (but I can hear the effects on Master output). Any ideas? If its not possible it should be a feature.

```
      var player = new Tone.Player(url, function() {
        make_download(player.buffer.get());
      });

      // Effects
      var limiter = new Tone.Limiter(-6);
      var delay = new Tone.Delay(0.2);
      var eq = new Tone.EQ3(-10, 3, -20);

      player.chain(limiter, delay, eq, Tone.Master);
```

**Comment by tambien** [comment]
i think the best way to do that would be with [Tone.Offline](https://tonejs.github.io/docs/r13/Tone#offline-static). give it a callback and a duration and it'll  render everything in that callback using the web audio's OfflineAudioContext. 

to do it in the online context is possible but much more complicated. you can look into the MediaRecorder API, or recorder.js.

**Comment by Catsvilles** [comment]
@MileanCo Hi! Did you actually had any results with this? I try to use Tone.Offline but no matter what the buffer I get doesn't contain any effects but only the original sound. Please, advice if you had any success with this! Thank you very much! :)

**Comment by conner1reimers** [comment]
> @MileanCo Hi! Did you actually had any results with this? I try to use Tone.Offline but no matter what the buffer I get doesn't contain any effects but only the original sound. Please, advice if you had any success with this! Thank you very much! :)

Hi! Did you ever find a way around this? I'm having the same exact problem :( Been searching for a while

**Comment by Catsvilles** [comment]
@conner1reimers Sorry, just saw this, I hope you solved your problem until now, if not - let me know.

**Comment by Coremotor** [comment]
> @conner1reimers Sorry, just saw this, I hope you solved your problem until now, if not - let me know.

I faced the same problem, tell me how to solve it?
