### ISSUE TITLE
Activating the Transport loop should not change the Transport position

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#448]
...if the Transport position is already within the loop.

In the fiddle, you can see that I set the Transport position to 7 seconds and activate the loop. The Transport position goes to 7 and then to 5, then all the way to 10. It should instead go from 7 to 10, then loop 5 to 10.

Fiddle: https://jsfiddle.net/e5nrg3qa/8/

**Comment by maximedupre** [comment]
Hey @tambien 

The commit referenced above states that it fixes this issue, yet I see no difference by using the typescript branch. 

Any other modification I need to do other than changing the version to typescript? Looking at the changed code from the commit does not make it clearer for me.

Thanks again.

**Comment by tambien** [comment]
Is this the expected behavior: https://jsfiddle.net/yotammann/ac3s4y0w/

**Comment by maximedupre** [comment]
I'm confused. Why is Tone.Transport.seconds not incremented each second? The only values displayed are "0", "15" and "6.9". The transport is started and the value is being refreshed every 0.1 second, so there should definitely be other values being shown. Am I missing something?
