### ISSUE TITLE
Tone.min.js link broken on installation wiki page

### ISSUE THREAD

**Issue by digitaldybbuk** [Tonejs/Tone.js#449]
Looks like this link is broken: https://tonejs.github.io/build/Tone.min.js as linked on https://github.com/Tonejs/Tone.js/wiki/Installation

**Comment by digitaldybbuk** [comment]
![screen shot 2019-02-23 at 2 17 09 pm](https://user-images.githubusercontent.com/1059285/53291226-bb9f6e80-3775-11e9-9031-96900b48bdf6.png)

**Comment by tambien** [comment]
Related to #428. I've removed the Tone.min.js, since now the original file is minified and i include a Map file in addition. I just fixed this reference. Feel free to update any place where you see it in the docs / wiki.
