### ISSUE TITLE
Reverb pre-delay behaviour

### ISSUE THREAD

**Issue by DannyDane** [Tonejs/Tone.js#450]
Hi,

In Tone.Reverb the preDelay value is the time it takes to fully ramp in the reverb. In the code, you use the linearRampToValueAtTime method for that. 
But as far as I know in most reverbs the preDelay value is the time before the reverb starts. So before the preDelay time there is no reverb at all. In code, you would use the setValueAtTime method for that.

Am I wrong here? Or did you make a deliberate choice to use a ramping signal?

**Comment by tambien** [comment]
Thanks for the tip! there's no deliberate choice there, i just wasn't sure how most reverbs handled pre-delay. Pull requests are definitely welcome! otherwise i'll make that update when i've got a moment.
