### ISSUE TITLE
Add super-simple HTML5 example?

### ISSUE THREAD

**Issue by RobJacobson** [Tonejs/Tone.js#451]
I'm a complete newbie to Tone.js.  I'm having some basic problems with following the tutorials on the website.  E.g., the examples on the website all require external scripts, and I'm not sure what they do.  I'm also finding it difficult to import Tone.js into a modern "app.js" file under ES6+.  (I've read the docs but they don't answer these questions.)

Would it be possible to create a "stupid simple example" in pure HTML5/ES6+, using the CDN libaries?  It wouldn't need to be more complicated than the following:

1.  Show a button in HTML that says "click me," or the equivalent.

2.  Have a separate "app.js" file that responds to the click and plays a single note using Tone.js (using external linking to the CDN libraries).

Thank you.

**Comment by isaacpearl** [comment]
Just created a pull request to add this!

**Comment by RobJacobson** [comment]
Thank you!  Exactly what I needed!
