### ISSUE TITLE
Cannot get Tone.Player reverse to work

### ISSUE THREAD

**Issue by cantonbecker** [Tonejs/Tone.js#456]
Hi there,

I can't seem to get the Tone.Player reverse member to work. everything else works great -- volumes, fades, playbackRate etc. but when I flag "reverse" : true it doesn't impact my playback. Bug?

Live demo:
https://shepardspi.com/noreverse.html

`
		var playerReverse = new Tone.Player({
			"url" : "./songs/shepardspi/drone-1/3.[mp3|ogg]",
			"loop" : true,
			"reverse" : true
		}).toMaster();
`

**Comment by tambien** [comment]
thanks! it wasn't checking the input object for the reverse attribute. should be fixed now

**Comment by tambien** [comment]
looks like it wasn't as simple as i thought, since the check needs to be done _after_ the buffer has loaded. the simple fix in the mean time is to just set `player.reverse = true` after the buffer has loaded, that should work. i will dive into this more when i've got a moment.

**Comment by cantonbecker** [comment]
Awesome, thanks for the work-around. It's working on my test page now: https://pisongs.com/temp/noreverse.html

Meanwhile, I have a bigger problem in trying to launch my project. I'm trying to keep some of the load off my server by offloading the MP3/OGG files to a cloudfront/amazon S3 server, e.g.
https://d1wo7z5fsnzixj.cloudfront.net/shepardspi/loop-1/5.mp3

**But oh now, I've run afoul of "_XMLHttpRequest cannot load ... not allowed by Access-Control-Allow-Origin_" issues.**

I think that in order to get JS XML HTTP requests to work for a different domain, one normally needs to implement CORS, as per https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Frankly, I think this is over my head.

So:

1) Do you know of anyone who's done this before (used Tone.js to load cross-domain samples)
2) Can you point me in the right direction, or tell me who I can hire?

I'm anxious to launch my music-making site (https://pisongs.com) by "Pi Day" (3/14) which is this Thursday. That's why for the scramble.

Thanks.

**Comment by tambien** [comment]
The CORS stuff has to be done on the server-side. A quick search pulls up [this page](https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/).

**Comment by cantonbecker** [comment]
Thanks for encouraging me to have a second look. Seems like it's something I set in Amazon's S3 bucket configuration. Already got it (partly) working.

**Comment by cantonbecker** [comment]
Solved the CORS stuff, but still stuck on getting that player.reverse=true work-around to work in my actual application.

My application creates a bunch of players like this:

```
	var loopPlayer310 = new Tone.Player({
		"url" : "/shepardspi/loop-2/6.[mp3|ogg]", "loop" : true, "volume" : -12, "fadeIn" : 8, "fadeOut" : 8, "reverse" : true
	}).toMaster();

```

And then, since the "reverse" isn't being respected, I set up a second function like this:

```
	function redundantSetReverse() {
		loopPlayer310.reverse = true; loopDronePlayer300.reverse = true; loopDronePlayer350.reverse = true; loopDronePlayer351.reverse = true;  	
	}

```
And at first I invoked redundantSetReverse using Tone.Buffer.on('load',redundantSetReverse); but that didn't seem to do anything, so then I resorted to this kludge -- just waiting 15 seconds to try to reverse the loops:

`	setTimeout(redundantSetReverse, 15000);
`

Still no luck. Here's my actual application. All of the JS is rendered into the single HTML document, so you can do a view source and get a sense of the entire picture:

https://pisongs.com/shepardspi/?debug=1

Any idea why I'm still unable to get those loops to reverse? Thanks!

**Comment by tambien** [comment]
i think if you remove the initial setting of reverse in your constructor parameters object, it should work. 'reverse' guards against double setting (since then it would just be forward again) and since the buffer is not actually being reversed in the constructor, just the flag changed, it then stops you from _actually_ setting it the second time you call `reverse=true`.

**Comment by tambien** [comment]
i think i've fixed the API issue for real this time, so this work around might not be necessary any longer.

**Comment by cantonbecker** [comment]
WORKS! Super pleased, and also super happy to get rid of that workaround. :) Thanks a lot @tambien - you've singlehandedly made sure that my song will be a lot more interesting when it launches on Thursday.
