### ISSUE TITLE
Still can't get Tone.Player reverse to work

### ISSUE THREAD

**Issue by cantonbecker** [Tonejs/Tone.js#458]
I confess I'm not very skilled with GitHub, but I *think* I'm doing this right.
I rebuilt Tone.js from scratch, and made sure that that one line was changed in core/Buffer.js, and uploaded it to my server. Made triple-sure to clear my browser cache. I still don't get any reverse action on my loop.

Ideas? Here's the basic test:

https://pisongs.com/temp/noreverse.html

**Comment by tambien** [comment]
Let's continue this thread on the previous issue. #456
