### ISSUE TITLE
Changing BPM Tone.Transport not changing the bpm of the dynamically added player

### ISSUE THREAD

**Issue by tareq0065** [Tonejs/Tone.js#459]
I have changed the bpm value of transport. I have a function to add and synced player's dynamically. like below

`   new Tone.Player({
            url: item.url,
            onload: (song) => {
                this.addTrack({
                     id: id,
                    song: song
                })
            }
        }).toMaster().sync().start(position/10);`

above the position is also has dynamic value. The initial Tone settings are below. 
`       Tone.Transport.bpm.value = 120;
        Tone.Transport.timeSignature = [1, 8];
        Tone.Transport.loop = true;
`
Then I am adding it to my state like below:

  `addTrack(track) {
  _this.setState({
                tracksList: [
                    ..._this.state.tracksList,
                    track
                ]
            })
  }`

Now the problem is when I am changing the Tone.Transport.bpm.value dynamically the player's or the synced tracks is not playing by the bpm value.

**Comment by tambien** [comment]
that's not an unreasonable expectation, but the Player does not do tempo matching through adjusting the playbackRate as part of `sync`. That would require both having the playbackRate be an AudioParam (currently it's just a number) and probably also the ability to change the playbackRate without changing the pitch, which is possible in Tone.GrainPlayer, but not Player.

**Comment by tareq0065** [comment]
@tambien Thanks for your reply bro. Sorry, I didn't get any doc about Tone.GrainPlayer. Is there anything I could get help on that?

**Comment by tareq0065** [comment]
Thanks for your reply bro. Seems the Tone.GrainPlayer not loading from URL like the Tone.Player does.
`new Tone.GrainPlayer({
            url: this.state.item.url,
            onload: (song) => {
                console.log('song:', song.buffer.duration);
                _this.setState({
                    currenttrack: song,
                    isLoadingTrack: false
                });
            }
        }).toMaster().sync().start(0);`

**Comment by ChenPaulYu** [comment]
Hey @tareq0065 , 
I encountered the same problem with React, Do you solve this ? 
Although I replace the Players to the GrainPlaye. The problem still

My code is here
https://codesandbox.io/s/transport-sync-forked-vzto2
