### ISSUE TITLE
Disconnect from PanVol Not Working

### ISSUE THREAD

**Issue by tboie** [Tonejs/Tone.js#461]
Unable to disconnect from PanVol

Tone.js v13.8.1

example:
https://jsfiddle.net/timboie/bhemrv2d

**Comment by tboie** [comment]
EQ3 not disconnecting also

**Comment by tboie** [comment]
Looks like neither of these conditions are being called here:

https://github.com/Tonejs/Tone.js/blob/dev/Tone/core/Tone.js#L388

**Comment by tambien** [comment]
thanks for the heads up. i think [this line](https://github.com/Tonejs/Tone.js/blob/dev/Tone/core/Tone.js#L368) is supposed to be a "while" loop and not an if statement so that it can recursively check for and find the 'input' to disconnect from. similar to what `Tone.connect` does
