### ISSUE TITLE
PolySynth Oscillator is null when changing type while scheduled

### ISSUE THREAD

**Issue by tboie** [Tonejs/Tone.js#463]
v13.8.2

this._oscillator is null:
https://github.com/Tonejs/Tone.js/blob/dev/Tone/source/OscillatorNode.js#L216

Demo:
https://jsfiddle.net/timboie/x9y25v3n/

**Comment by tboie** [comment]
Thanks will try it out

**Comment by tboie** [comment]
Changing oscillator type occasionally throws an error:

Oscillator.js:141 Uncaught TypeError: Cannot read property 'disconnect' of null
    at s.default.Oscillator.<anonymous> (Oscillator.js:141)

https://github.com/Tonejs/Tone.js/blob/dev/Tone/source/Oscillator.js#L141

Demo:
https://jsfiddle.net/timboie/Lyprvash/

**Comment by tambien** [comment]
Removed the lines that were causing the issue. This was an unnecessary optimization which was causing more issues than it was supposed to help.
