### ISSUE TITLE
Tone.Buffer with sampleRate

### ISSUE THREAD

**Issue by mrwensveen** [Tonejs/Tone.js#466]
Hi.
I'm trying to convert some existing code to Tone.js. I want to load my PCM data (`Float32Array`) to a `Tone.Buffer` (using `fromArray`), but with a different sample rate.

`AudioContext` has a `createBuffer` method with a sampleRate argument, but `Tone.Buffer` has not.

`Tone.BufferSource` allows me to use an `AudioBuffer` instead of a `Tone.Buffer`, but I want to utilize Tone.js as much as possible. Furthermore, I can't seem to get to the underlying `AudioContext` from Tone.js (`Tone.Context.rawContext` is undefined?).

**Comment by mrwensveen** [comment]
Apparently I was using an older version of Tone.js. I can now use `Tone.context.rawContext.createBuffer` to create an `AudioBuffer` with the correct sampleRate.

It would still be useful to be able to create a Tone.Buffer with the correct sampleRate directly, however.

**Comment by tambien** [comment]
Last i checked, there is a bug with Safari which doesn't let you easily resample buffers without bringing in a third party library to resample it. For this reason and for the sake of simplicity, the sampleRate is consistent throughout the library. If you don't need to support Safari, then i would recommend using the rawContext as you mentioned
