### ISSUE TITLE
Gain value should not change during offline rendering

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#467]
If I set the value of a gain to `0` before the `Offline` is called, I think it is fair to expect that the value stays the same during the offline rendering process. Here is a fiddle to illustrate the issue:

https://jsfiddle.net/39mt0bgL/5/

**Comment by tambien** [comment]
since the underlying context is changed, the internals of Tone.Gain also change under the hood now that it is referencing another context. it seems like the [value is restored](https://jsfiddle.net/yotammann/3r6csj1n/) when it exists from Tone.Offline.

**Comment by maximedupre** [comment]
If I understand this right, Tone just abstracts the underlying context, but really two gain nodes exist - one for the offline and one for the "online" context. Tone makes our lives easier by pretending that it's the same node, which is why I think the value should be the same and be consistent across contexts. 

A very common use case is to simply reproduce the "online context" audio nodes tree for the "offline context" to do a render. If the value of the gain is reset once the offline rendering starts, there is no way to reproduce the "online context" audio nodes tree, unless you keep updating a (somewhat) duplicate map of all the online node values. The "online" values of the nodes would normally be easily accessible, but since Tone pretends it's the same node for the "online" and offline context, it is not.

Thank you and let me know if I'm missing something. 

Cheers!

**Comment by tambien** [comment]
btw, this should be fixed on the typescript branch since it's been rewritten to use a context passed into the constructor and not the global audio context which was causing this issue: 

https://jsfiddle.net/yotammann/xb7owhsp/

**Comment by maximedupre** [comment]
@tambien Nice! What's the difference between the master, dev and typescript branch? Is the typescript branch as stable as tone@latest/master?

**Comment by tambien** [comment]
@maximedupre the typescript branch is not yet stable or even on par with the `dev` branch. It's still under active development rewriting everything in typescript with a number of breaking changes from `master`.

**Comment by maximedupre** [comment]
Ok I understand. Do you have an ETA for when it will be? I'm in no rush, I'd just like to know for planning purposes.

**Comment by tambien** [comment]
No ETA. a lot of the core modules are done, but a number of synths and effects still need to be converted. [Contributions](https://github.com/Tonejs/Tone.js/wiki/Typescripting-Tone.js) are appreciated if you have time.

**Comment by tambien** [comment]
This should be fixed now.
