### ISSUE TITLE
Change Synth type Dynamically

### ISSUE THREAD

**Issue by luisArandas** [Tonejs/Tone.js#468]
I don't see any possibility in changing dynamically say a PolySynth(6,Tone.Synth) to a PolySynth(6, MembraneSynth) on push of a button or so.
I am running all the API but can't find any method for this, like change type of synthesiser quickly without having to tweak it atribute by atribute.
I guess this is a feature request or a failure of mine
Thanks in advance, Luis

**Comment by tambien** [comment]
i think the easiest way to do this would be just make both synths and `dispose` the one that you don't want any more on a click of a button.
