### ISSUE TITLE
Documented size limits for FFT/Analyser are incorrect

### ISSUE THREAD

**Issue by colinmorris** [Tonejs/Tone.js#475]
[Tone.FFT](https://tonejs.github.io/docs/r13/FFT) and [Tone.Analyser](https://tonejs.github.io/docs/r13/Analyser) say that size should be "a power of two in the range 32 to 32768". The actual allowable range is 16-16384. If you try to set it to 32768, you'll get an error like: `Uncaught DOMException: Failed to set the 'fftSize' property on 'AnalyserNode': The FFT size provided (65536) is outside the range [32, 32768].`

32-32768 is the allowable size range for [AnalyserNode](https://webaudio.github.io/web-audio-api/#analysernode), but the size value that `Tone.Analyser` passes to its `AnalyserNode` is double the input size provided.

A couple options:
1. Stop doubling input size when setting fftSize
2. Change docs to reflect actual limits

Presumably number 2 would be preferable since it's a non-breaking change?

Could also consider renaming the parameter from `size` to something like `bins`. (I think this would make the semantics more clear, and make it more apparent why it's doubled to get fftSize).

**Comment by tambien** [comment]
thanks for the issue. the idea was to have the value given reflect the size of the values array since this feels most intuitive to use. defining a value of say 32 and only getting back 16 values seems a little strange, so best is option 2 which would just reflect the web audio limits divided by 2.
