### ISSUE TITLE
Output buffer doesn't contain effects

### ISSUE THREAD

**Issue by Catsvilles** [Tonejs/Tone.js#479]
Hi, everyone! I more a musician rathen than programmer, so please be gentle xD
What I'm trying to achieve is applying audio effects to a file and get the result as AudioBuffer and do stuff with it. (Render as wav or play it with Sampler). Until now I tried using Tone.Offline and did everything according to the example from docs, but unfortunately, all I get in the end is only a buffer (thus original file) with no effects. So, my question is it actually possible to apply effects to an audio file and get it as a buffer which contains them? 

I know about MediaRecorder. but unfortunately it works only with streaming and I want to do this behind scenes with recorder.js and its worker. Maybe I don't understand something, please kindly point me to it :) I suppose AudioNode itself is the thing that contains all the audio effects and stuff, so the logical question would be - is it possible to convert an AudioNode to a buffer/wav?

**Comment by tambien** [comment]
Without seeing the code, it's hard for me to debug. My guess is that maybe the source is not connected through the effect, but might be connected directly `toMaster` which would bypass the effect entirely. 

Try something like this: https://jsfiddle.net/yotammann/kf9401cs/
