### ISSUE TITLE
Player.restart() does not update state.

### ISSUE THREAD

**Issue by JordanRickman** [Tonejs/Tone.js#480]
If you use `restart()`, instead of `start()`, Player does not update the `state`. It stays at `'stopped'`.

Demonstration: https://jsfiddle.net/a2jx3n47/23/

**Comment by blechdom** [comment]
The jsfiddle example doesn't load for me.

**Comment by blechdom** [comment]
Yes, I can confirm that is what is happening if your demonstration.

**Comment by JordanRickman** [comment]
Thanks for fixing, Yotam! :)
