### ISSUE TITLE
Support creating players and buffers from blob URLs

### ISSUE THREAD

**Issue by griest024** [Tonejs/Tone.js#484]
It would be awesome if I could load audio in the form of blobs into Players like: `new Player('blob:http://localhost/asdlkjhfnsdf67asfdn-as7d6fhgs7da-fg9843ioj')`

**Comment by tambien** [comment]
AFAIK this is currently supported. All urls for player and buffer are loaded using XHR which supports blob urls. could you provide an example of the error that you hit?

**Comment by griest024** [comment]
okay I will go back and try again and if I still can't get it then I'll get a jsfiddle going with a repro.

**Comment by tambien** [comment]
Here's a little demo of using Tone.Player with a blobUrl: https://editor.p5js.org/yotam/sketches/O4ses3IoZ

**Comment by griest024** [comment]
whoops sorry I forgot to follow up on this, I did indeed get it working, something else had broken that I didn't expect. Thanks for the demo though.
