### ISSUE TITLE
Can Tone.MembraneSynth and Tone.MetalSynth extend Tone.Monophonic in order to use them as voices in Tone.PolySynth?

### ISSUE THREAD

**Issue by cgberry** [Tonejs/Tone.js#486]
This was something I noticed when I tried to make Tone.MembraneSynth and Tone.MetalSynth the voices of a PolySynth. 

![image](https://user-images.githubusercontent.com/26800775/57464566-f0867200-724a-11e9-94ae-c382d8c8ee08.png)

I was wondering if there was any good reason that these two (and I think a few other synths) only extend Tone.Instrument and not Tone.Monophonic? It would be cool if that were a feature so you didn't have to use multiple synths to make a drum machine and could just limit it to a couple?

It could also be a moot point if they already allow polyphony, but I don't think they do. Please correct me if I'm wrong.

**Comment by jbum** [comment]
Ditto with PluckSynth. :)

**Comment by tambien** [comment]
This has been updated on the typescript branch and both classes should now work with the PolySynth. It can now be used with `tone@^14.3.10`

@jbum Currently PluckSynth has a pretty different API (it does not have a triggerRelease) so it doesn't fit into the PolySynth. but i'll think about if it might be possible to include it later.
