### ISSUE TITLE
Is there any way to attach gain on player or grainplayer?

### ISSUE THREAD

**Issue by tareq0065** [Tonejs/Tone.js#489]
is there any way to attach the gain on a Player or GrainPlayer? I am not sure it is a feature request or not.  here what am I tried.

```
addnewtrack = new Tone.GrainPlayer({
            url : track.url,
            overlap  : 0.5 ,
        });
var crossFade = new Tone.CrossFade(0.5).toMaster();
            var gainer = new Tone.Gain( 0.6, 0).toMaster();
            var pitch = new Tone.PitchShift( 0.5).toMaster();
            addnewtrack.connect(crossFade, 0, 1);
            addnewtrack.connect(pitch, 0, 0);

            addnewtrack.connect(gainer, 0, 0);
            addnewtrack.toMaster().sync().start(`${track.position}`);
```

**Comment by tambien** [comment]
If you don't connect the GrainPlayer to the master output, but instead connect it to the Tone.Gain, it should have the outcome you expect. 

I think this should work: 

```javascript
const grainPlayer = new Tone.GrainPlayer()
const gain = new Tone.Gain()
grainPlayer.connect(gain)
gain.toMaster()
```

**Comment by tareq0065** [comment]
Hello there, Thanks for your reply. At the moment there is another problem I got if I do this I can't use `gain.toMaster().sync().start('0.5')`. It's showing me an error that `gain.toMaster().sync(); is not a function` But if I use like below its working.

`      const grainPlayer = new Tone.GrainPlayer();
       grainPlayer.sync().start('0.5');
       const gain = new Tone.Gain();
       grainPlayer.connect(gain);
       gain.toMaster();
`
Is it the write way I am doing?

**Comment by tambien** [comment]
Only the GrainPlayer would need to be synced to the Transport. The Gain does not have a `.sync()` method since it's not actually a source that needs to be started/stopped, it just passes audio through. 

The second block of code you wrote looks good to me for trying to accomplish what you're doing.
