### ISSUE TITLE
Tone.Meter getLevel method range min & max

### ISSUE THREAD

**Issue by ZachMoreno** [Tonejs/Tone.js#490]
`getLevel()` [seems](https://jsfiddle.net/zach__moreno/Lejh1fup/59/) to return values between `-100` & `0`. Is this the intended range & if so, can I propose an update to the type definition for [`Decibels`](https://tonejs.github.io/docs/r13/Type#decibels) or [`getLevel()`](https://tonejs.github.io/docs/r13/Meter#getlevel) in the docs? The exact min & max of the intended range would be helpful.

My intention is to build a VU Meter & the decibel scale for VU Meters is [typically](https://www.google.com/search?biw=1280&bih=698&tbm=isch&sa=1&ei=6kzbXOrGGJHY_wSJtqOIBQ&q=standard+decibel+levels+chart+vu+meter&oq=standard+decibel+levels+chart+vu+meter&gs_l=img.3...38203.39639..39809...0.0..0.66.557.9......1....1..gws-wiz-img.......0i30.a86ObA2MzeM#imgrc=qnxuRhBxaRS8XM:) between `-20` & `+3`. It's easy enough to map from one range to another & I've done the following.

```
const mapRange = (x, in_min, in_max, out_min, out_max) => {
    return Math.ceil((x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min);
}

const context = Tone.context;
const meter = new Tone.Meter();
const source = context.createMediaStreamSource(microphone);

source.connect(meter);

const raw = meter.getLevel();
const dB = mapRange(raw, -100, 0, -20, 3);
```

Thank You All for this awesome framework!!

**Comment by Idicious** [comment]
You can can the lower rang with a Math.max(-20, meter.getLevel()). The value returned should not have an upper bound, everything above 0db is digital clipping. Keep in mind the value returned is the RMS value, not the peak value. The RMS value is lower than the peak but higher than the average in general and an often used measurement in digital VU meters.

The +3dB value you are referring to on analog VU meters is equal to around -18dB on a digital meter if I remember correctly. Everything above 0dB is always digital clipping which you want to a void.

**Comment by tambien** [comment]
Thanks for following up with that info @Idicious 

The range is the decibel range which would be all numbers where silence is -Infinity. If you'd like to normalize this output to a 0-1 range if that's easier to work with, use `Tone.dbToGain(meter.getLevel())`. which will return 0-1 unless the signal is clipping in which case the output could be above 1.
