### ISSUE TITLE
Can't set volume below 0db ?

### ISSUE THREAD

**Issue by giann** [Tonejs/Tone.js#491]
When I set the volume below a certain db value, the volume stays the same:

```javascript
let player = new Player({
    url: "/test.mp3"
}).toMaster();

let channel = new Channel(-16);

player.connect(channel);

channel.volume.value = 10; // This is ok, the sound is louder
channel.volume.value = 0; // Lower
channel.volume.value = -80; // Sounds the same as when value is 0
```

**Comment by tambien** [comment]
looks like your routing is a little off. What you'd like is to go Player -> Channel -> Master, but currently you've got Player -> Channel && Player -> Master, so the audio is not passing through Channel at all and not being affected by the change of volume. 

Try something like this instead:

```javascript 
let player = new Player({
    url: "/test.mp3"
});
let channel = new Channel(-16).toMaster();
player.connect(channel);
```

**Comment by giann** [comment]
Thanks I figured it out while having the same issue with Envelope !
