### ISSUE TITLE
pausing and resuming a non-looping Part after it has finished will play a few notes

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [Tonejs/Tone.js#493]
Hi!

_To illustrate the issue, I made a jsfiddle: https://jsfiddle.net/lmeszaros/yL1zx78u/37/_

I made a Part with a few notes, which plays twice. After it has finished I wait for around a second, pause it, wait a bit more, then press play again to resume it. The Part will play the last 3-4 notes again. Then I repeat the procedure of pressing pause and play again, where the notes will no longer play. If I press stop to make the Transport go to the beginning again and do the procedure again, Part will behave the same: it will play a few notes, when it shouldn't.

I would expect Part to not play any notes after it has finished playing it's 2 loops.

One possible culprit for this incorrect behaviour is that `Transport.timeSignature` is `[3, 2]`, where the 1st number is greater, than the 2nd.

**Comment by blechdom** [comment]
Checked out your jsfiddle, it seems to be working correctly for me.
Also, changed the time signature to [4, 2] and it was easier to hear it play back the 8 notes as expected.

**Comment by tambien** [comment]
Just updated to the latest Tone.js (`tone@14.8.1`) and seems to be working. There's been a lot of changes since May 2019, so not sure which fix it was specifically. Here's your script with the latest tone which doesn't exhibit the issue: https://jsfiddle.net/kepumth9/
