### ISSUE TITLE
Feature request: negative transport time notation

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [Tonejs/Tone.js#495]
Hi!

I'm experimenting with the loops from Steve Reich's Electric counterpoint, where each guitar line is played in an offset compared to each other. I'm playing the loops using Parts, where I can say, that I start playing one sequence from `0:0:0`, another from `0:0:4`, yet another from `0:0:10`, but there is no way to specify offsetting in the other direction with negative values. I've tried `0:0:-6` and `-0:0:6`, but none of them worked.

I can calculate this using ```-Tone.Time(`0:0:{loopSize - Math.abs(offset)}`).toSeconds()```  ( or ```-Tone.Time(`0:0:${24-6}`).toSeconds()``` ), where it works perfectly, but it would be nice to have this feature among the time encoding formats: https://github.com/Tonejs/Tone.js/wiki/Time

Having this feature would mean, that Part should go to the end of the loop (based on the loopEnd property) and go backwards Math.abs(`-0:0:x`) amount and start the looping from that point.

Note: there is something called "now relative" in the wiki page, but it is only for seconds and only in the + direction.

Here is a jsfiddle, where I illustrate this: https://jsfiddle.net/lmeszaros/yL1zx78u/57/

**Comment by tambien** [comment]
I looked into this a bit, but there seems to be some circular logic that i couldn't wrap my head around. Currently loop duration is `loopEnd - loopStart`, but if loopEnd is a value which is relative to the loop duration, how could it be computed? 

If you've got an elegant solution for this, happy to accept a PR. but i'm going to close for now.
