### ISSUE TITLE
Loop not called without TriggerAttackRelease

### ISSUE THREAD

**Issue by gntsketches** [Tonejs/Tone.js#500]
This pen: https://codepen.io/gntsketches/pen/KjVdBm attacks and releases a synth through the Loop method. The function that the loop accepts makes a call to synth.triggerAttackRelease… If this is removed, the loop never gets called. Perhaps this has to do with Google's anti-autoplay policy?

**Comment by tambien** [comment]
yeah seems like an autoplay issue. Transport.start will start the audio context, but not loop.start. 

The best idea going forward might be to throw an error when a 'start' method is invoked but the context is not already started to alert people to this issue. 

going to close for now, the solution is just to put Tone.start, or Tone.context.resume in that click handler. but will keep this in mind for future development.
