### ISSUE TITLE
Cannot read property 'getTicksAtTime' of null

### ISSUE THREAD

**Issue by drumtj** [Tonejs/Tone.js#502]
hi
I'm TJ

In use of Tone.Part
Events at a particular point in time that are to be passed as parameters are not delivered with an intermittent error message.

After the first occurrence of this phenomenon, the same phenomenon is reproduced every time 'start ()', and it works normally from the next loop of Part.

This phenomenon occurs randomly, making error examples hard to come by, but often happens.

Can I get advice on how to fix it?

![이미지 426](https://user-images.githubusercontent.com/8894265/59728976-38031380-9277-11e9-8dc9-0a7f6596d0f7.png)

**Comment by tambien** [comment]
Hi TJ. could you post some code that caused this error? ideally a minimal example in codepen/jsfiddle or the live code running on a website somewhere with info on how to recreate the bug. a little more context would be helpful.

my only guess from this small snippet is that you've disposed an object that's still in use...? like the transport's clock or the part that you're still scheduling.

**Comment by drumtj** [comment]
Thank you for your advice.
