### ISSUE TITLE
Tone.js not working on iOS Safari

### ISSUE THREAD

**Issue by dkthehuman** [Tonejs/Tone.js#511]
Issue: Tone.js no longer seems to work on Safari on iOS (12.3.1)

Steps to reproduce:
- Navigate to any Tone.js demo (e.g. https://jsfiddle.net/1f60jkq4/ (tone@latest), https://tonejs.github.io/)
- None of them work

Safari Dev Tools shows that there's an error when `createBuffer` is called as Tone.js is loaded:
<img width="1000" alt="Screen Shot 2019-07-13 at 3 48 43 AM" src="https://user-images.githubusercontent.com/535248/61169353-e2daba80-a521-11e9-8199-24d8939089e9.png">

Background information:
I was trying to debug why my app suddenly stopped working on iOS Safari. After several hours, I realized that none of the Tone.js examples were working either. My app worked fine a week ago and given that nothing changed on the side of Tone.js, I suspect that perhaps something may have changed with Safari, but honestly, this all seems quite bizarre so I'm curious whether this is reproducible by anyone other than me.

Let me know if I can provide any more information!

**Comment by dkthehuman** [comment]
I wasn't able to reproduce this on my friend's iPhone X (iOS 12.3.1) so closing the issue as this seems to be specific to me and my iPhone 7.

**Comment by dkthehuman** [comment]
Surprise, surprise, restarting my phone fixed the problem.

**Comment by tambien** [comment]
@dkthehuman glad it works! thanks for following up with the resolution.

**Comment by remino** [comment]
Came here to say the same. Doesn't seem to work on Safari in iOS 17.
