### ISSUE TITLE
Bug: AudioParam is non finite

### ISSUE THREAD

**Issue by rayfoss** [Tonejs/Tone.js#515]
Tone crashes on playback with a webpack build.

Tone version 14.0.20, down to 13 

`"TypeError: Failed to execute 'setValueAtTime' on 'AudioParam': The provided float value is non-finite."`

# Steps to reproduce
0. run this code https://codesandbox.io/s/tone-crash-513-shared-nee6k
1. Hit play

**Comment by tambien** [comment]
Looks like you're trying to play the note: "C#" which is not a specific enough frequency. you've got to add an octave number like "C#4" in order for that note to be recognized as a note.
