### ISSUE TITLE
Tone, Phaser3 and ios

### ISSUE THREAD

**Issue by Ohmsey** [Tonejs/Tone.js#516]
I'm trying to build an audio visual physics based play thing using tone.js and Phaser 3 but no matter what I try I can't get the audioContext to work on iOS. Phaser's works but not Tone.

It's a shame because they work really well together and I should be able to build something really quickly. I'm not the best coder, I can work my way round an API but native code isn't really my thing.

The Tone examples page works on (my phone + iPad) iOS although I have tried resetting them. There was some mention of the mute/ringer switch making a difference. I have tried this.

I have tried StartAudioContext.js and the Mute one too as well as several examples on how to start the audioContext for Tone.

Has anyone got a basic Javascript example please?

Kind of pulling my hair out with this any help appreciated.

Thanks

**Comment by tambien** [comment]
it seems like you're probably not starting the audio context after a user interaction. I've used this snippet on many websites including the examples page, which you mentioned works for you. 

```javascript
//attach a click listener to a play button
document.querySelector('button').addEventListener('click', () => Tone.start())
```

just create a simple button and put it on your page. make sure you do it _before_ you try and play any audio.

**Comment by Ohmsey** [comment]
Many thanks.
