### ISSUE TITLE
Consider supporting 'ended' events on Tone.Player

### ISSUE THREAD

**Issue by lehni** [Tonejs/Tone.js#519]
I was looking for this for quite a while, until I found it on `BufferedSource`. Could these events be routed through to the player object, perhaps?

**Comment by tambien** [comment]
i named it `onstop` instead of `onended` since the player is able to start and stop multiple times

**Comment by lehni** [comment]
Great, thanks @tambien !

**Comment by tambien** [comment]
This is currently only on the `typescript` branch, which will eventually make its way into the 'dev' branch and then into the next release.

**Comment by flyandi** [comment]
Was this ever  merged? I can't seem to get onstop to work on the Player.

**Comment by wavinginspace** [comment]
wondering the same..

**Comment by peppelorum** [comment]
Wondering the same thing, I can never get onstop to be triggered.
