### ISSUE TITLE
Dynamically setting Player startTime leads to duplicate sounds and unable to stop

### ISSUE THREAD

**Issue by kerryz** [Tonejs/Tone.js#525]
Hi,

The issues are reproduced here: 
https://codepen.io/kerryz/pen/KOGvmE?editors=1111

I am creating a DAW with a timeline where you can drag an audio waveform in order to change its start time. As suggested in [this reply](https://github.com/Tonejs/Tone.js/issues/419#issuecomment-451172111), I dynamically update the startTime of a Player by unsyncing and then syncing again: `player.unsync().stop().sync().start(newStartTime, 0)`.

This works, however, if I set `Transport.seconds` (in the DAW, this would be equivalent of clicking on the timeline and the playback goes to that point) after changing the startTime, strange things happen, such as duplicate sounds and `Transport.stop()` not working, as shown in the codepen.

**Comment by tareq0065** [comment]
@kerryz I got this issue too I was about to start an issue, you just opened thanks. Also after setting/updating the `Tone.Transport.seconds` the previous tracks are not playing. the transport goes through the current tracks and playing from the next one. This is a great library to use. Another issue is on the tempo changing. After changing tempo sync and re-sync position is just going to a mess.

**Comment by protectedvar** [comment]
Same problem. I create 8 identical players every 4m, after setting the Transport.seconds, some of them start to sound louder, sometimes out of sync.
