### ISSUE TITLE
lack of d.ts

### ISSUE THREAD

**Issue by jcapinc** [Tonejs/Tone.js#532]
hey I am opening this issue because I am working on a d.ts for this library, if noone here cares about it I will publish it separately and try to submit it into the @types/ directory. If you are interested in incorporating a module.d.ts than I want to start the conversation about it.

With the documentation as good as it is, I just dont think it will take a lot of time to get the typings banged out.

Let me know if the maintainers want to incorperate a module.d.ts for their users who would like to see typescript incorperation, and just additional documentation in general.

**Comment by jcapinc** [comment]
here is my WIP

https://github.com/jcapinc/tonetypings

**Comment by tambien** [comment]
Thanks for the contribution! there’s already a couple efforts underway around typescripting the lib. Take a look at [this repo](https://github.com/Tonejs/Typescript), maybe your work can be integrated in there. 

Also working on typescripting the entire library. You can find more info on the typescript branch. check out [this wiki](https://github.com/Tonejs/Tone.js/wiki/Typescripting-Tone.js) if you’re interested in contributing! PRs very welcome!
