### ISSUE TITLE
Incorrectly documented constructor param on Gain

### ISSUE THREAD

**Issue by jcapinc** [Tonejs/Tone.js#533]
Misdocumented constructor parameter on the Gain class

https://github.com/Tonejs/Tone.js/blob/13.8.25/Tone/core/Gain.js#L12

I don't mind fixing, im guessing it was just supposed to be a string. let me know if you want this fixed.

**Comment by tambien** [comment]
It is a string, but here it is referring specifically to an enum string defined [here](https://github.com/Tonejs/Tone.js/blob/dev/Tone/type/Type.js).

The typescript branch contains a more specific string type for that parameter, so i don't think it needs to be fixed on this branch which will soon be replaced by the typescript branch.
