### ISSUE TITLE
Firefox popping noises

### ISSUE THREAD

**Issue by palmenros** [Tonejs/Tone.js#534]
I have found the following bug which happens in Firefox 68.0.2, it doesn't occur on chrome.

If you instantiate a `Tone.Synth` with `envelope:{release: 0.07}` and try multiple times to `triggerAttackRelease` with multiple notes, randomly there will appear popping noises at the start of the note. It happens randomly and I haven't been able to get the pop to appear consistently, but it appears pretty often with the options given.

**Comment by tambien** [comment]
Thanks for the issue, given the inconsistency in reproducibility, my guess is it is performance issues with firefox's web audio implementation which i've found tends to be slightly more sluggish than chrome causing it to crackle sooner.

Unfortunately, if it is performance issues of its web audio implementation, there is nothing that Tone.js can do, other than the incremental optimizations which are added whenever they are found. I could not reproduce a Tone.js issue related to that release time in my testing (seemed to work the same with any release value that i used). Sorry i couldn't be more helpful. If you have a specific performance issue which might be web audio-related and firefox specific, it can be helpful to file it with [bugzilla](https://bugzilla.mozilla.org).
