### ISSUE TITLE
notes get cut off and play short after multiple plays

### ISSUE THREAD

**Issue by multiplayer-shop** [Tonejs/Tone.js#541]
Hello, I am scheduling a list of notes to be played from an array containing note, note length, and time to start:

function schedule_music() {
	for (var i = 0; i < music_data.length; i++) {
		Tone.Transport.scheduleOnce(play_music, music_data[i][2]);
	}
}

function play_music(time) {
    if (music_counter < music_data.length ) {
	piano.triggerAttackRelease(music_data[music_counter][0], music_data[music_counter][1], time);
       music_counter++;
    }
}

It works, except after multiple plays on my "ipad mini" and "ios phone" the notes begin to get cut off and shortened. It will play fine for awhile and then randomly play weird.

It has something to do with how long the app is open, because it takes time to happen as though there is some kind of memory leak.
It also seems have something to do with a rogue trigger release envelope, because if I just do do triggerAttack, I don't have the issue.

I've played with every scheduling variation of Tone.Transport and not using Tone.Transport  but triggering directly use Tone.now and the issue persists.
any ideas?
Thanks

**Comment by tambien** [comment]
could you provide an interactive example using codesandbox or jsfiddle?

**Comment by multiplayer-shop** [comment]
Hello, Here is a link to the composer activity:
http://toytheater.com/composer/

If I add 15 notes or so and replay many times on my ipad, the notes begin to cut off. It takes a little while to reproduce, as though there is something running that takes time to exhaust resources.

**Comment by tambien** [comment]
Very cool demo, but since the code is minified and lumped together with all of the application code, it's hard for me to debug the parts which are relevant to only Tone.js. Can you create a minimal jsfiddle with just the relevant lines of code?

**Comment by multiplayer-shop** [comment]
Thanks, here is a jsfiddle:
https://jsfiddle.net/pondjsfiddle/nceg3bth/9/

the "create data" button creates a random array of 20 notes, note lengths, and trigger times.
the "play" button schedules the array using scheduleOnce

I was able to reproduce the error in the fiddle, by letting my ipad sit for about five minutes after playing the same data about five times... again it seems like something impacts performance over time like something is running in the background,  or it somehow gets out of sync or holds on to old transport events that should be gone

**Comment by tambien** [comment]
thanks for creating that fiddle. I don't see anything obvious in the code that would be causing the issue and from your description it does sound like a performance issue. The sampler removes completed notes to free them up for garbage collection once the note is done playing [in this block](https://github.com/Tonejs/Tone.js/blob/dev/Tone/instrument/Sampler.js#L153-L160). It's possible that iOS is not freeing the underlying Web Audio nodes and so it degrades the performance over time. 

The next version of Tone.js is more [explicit about disposing](https://github.com/Tonejs/Tone.js/blob/typescript/Tone/source/OneShotSource.ts#L188) all the web audio nodes which were created once the node has completed by disconnecting all of the created nodes to help with situations like that.

**Comment by multiplayer-shop** [comment]
Ok, sounds good. I'm using using v13.8.25. I see v13.8.27 on the CDN is that the latest version? What is the difference between the v14s and the v13s available on the CDN?  What version will have that fix?

Thanks

**Comment by tambien** [comment]
Those changes are currently only on the typescript branch which is published as `tone@typescript` with the latest version being `14.3.17`. The typescript branch is a total rewrite in typescript so it still doesn't have all of the classes implemented yet. but if you have a chance to try it out, i'm curious if your issue is solved by it.

**Comment by multiplayer-shop** [comment]
I did a quick test but I think Tone.context has been renamed, because where I test its “state”, I get this error:
Cannot read property 'state' of undefined

**Comment by tambien** [comment]
There's been a number of changes. it'll take a little more work for the API to reach parity with `tone@^13.8.0`. i think you can get the context with `Tone.getContext()`, but using this typescript version will take a little more reading through the code since the docs haven't been generated for it yet either.

**Comment by multiplayer-shop** [comment]
Ah, well I am going to build a number of activities using Tone js, so I will live with the bug for now and update the library when this version comes out.  What do I look for to know its got these changes in it?

**Comment by tambien** [comment]
Going to close this. let me know if this is still an issue.
