### ISSUE TITLE
Tone error on new iphone 11 ios Safari

### ISSUE THREAD

**Issue by stoppiNeobiz** [Tonejs/Tone.js#550]
Hi, we receive this error on new iphone:

NotSupportedError: The operation is not supported.
jquery.min.js:2:31126ReferenceError: Can't find variable: Tone

**Comment by tambien** [comment]
Could you share a way to reproduce this error?

**Comment by tambien** [comment]
Seems like a stale issue. might be a problem with importing Tone.js. I am going to close for now, but feel free to reopen or comment if you can create a way to test and reproduce the error
