### ISSUE TITLE
Edge - accessing Tone context cause error

### ISSUE THREAD

**Issue by wiserim** [Tonejs/Tone.js#553]
I'm using Tone.js to generate / modify audio, which is send with use WebRTC to other users.
For this I access Tone context to create media stream destination node like below:
`Tone.context.createMediaStreamDestination()`

Unfortunately on Edge accessing Tone context cause error:
SCRIPT5007: Unable to get property 'bind' of undefined or null reference

[https://jsfiddle.net/v1kdyps0/1/](https://jsfiddle.net/v1kdyps0/1/)

**Comment by chrisguttandin** [comment]
Unfortunately there is no `createMediaStreamDestination()` method on the `AudioContext` in Edge and as far as I know there is no way to polyfill it.

The next version of Edge which will be based on Chromium will have it, though.

**Comment by tambien** [comment]
thanks for the response @chrisguttandin 

going to close, since it's not supported and there's no polyfill available.

**Comment by wiserim** [comment]
Thank you @chrisguttandin for explanation. It'll save me a lot of time (especially that according to multiple sources createMediaStreamDestination is suuported by Edge).

As I wrote in the first post, accessing Tone context **itself** cause error.
`console.log(Tone.context)`
[https://jsfiddle.net/v1kdyps0/1/](https://jsfiddle.net/v1kdyps0/1/)

Probably I haven't wrote this legible enough, for which I apollogize.

**Comment by chrisguttandin** [comment]
If the GitHub search works correctly `createMediaStreamDestination()` is only used once in the source code of the master branch. https://github.com/Tonejs/Tone.js/blob/34405caeb19721acf250a46f4639c7e4cd788bf8/Tone/core/Context.js#L7

I guess the error is thrown when Tone later tries to bind it. https://github.com/Tonejs/Tone.js/blob/34405caeb19721acf250a46f4639c7e4cd788bf8/Tone/core/Context.js#L37

@tambien Would you welcome a fix for this which checks for the function to be defined before binding it? I guess the problem will be solved anyway once the next major version will be released.
