### ISSUE TITLE
Delayed audio generated from Tone.Offline

### ISSUE THREAD

**Issue by jasoncslaughter** [Tonejs/Tone.js#554]
I am having an issue when using Tone.Offline. I am able to generate a buffer and then play the buffer just fine... I am also using console.log to confirm that the notes that I am playing from a sequence are being triggered at the correct time. 

However, when listening to the audio, I hear one note at the beginning, then no notes for 50% of the rendered time, then at the 50% point you will be able to hear the sequence.

here is a link to a demo: https://jsfiddle.net/y8ksn5hb/6/ (please wait a few seconds for the audio to generate... Or look for the 'buffer complete' message in the console.log).

I am following very closely what is in the demo (https://tonejs.github.io/examples/offline.html), so I believe there might be a bug.

**Comment by tambien** [comment]
I wonder if it's related to #551. i've modified your code seems to work ok running on the typescript branch, but the API is slightly different: https://jsfiddle.net/yotammann/nreh1uz2/

**Comment by jasoncslaughter** [comment]
Cool, yeah the typescript branch seems to work. Am I correct in assuming that the typescript will be merged into the main branch sometime in the future, and the API changes are the "correct" way to do things going forward? Is the typescript branch fairly stable?

**Comment by tambien** [comment]
The typescript API will eventually be merged into dev and then master, so this is the API going forward. I'd say it's somewhat stable but still missing a number of effects and synths at this point which are being added regularly. If you're feeling adventurous, give it a shot!

**Comment by tambien** [comment]
I'm going to close this and track this issue just in #551.
