### ISSUE TITLE
How to Connect With Audio Element in HTML Using Tone js?

### ISSUE THREAD

**Issue by aadarshvelu** [Tonejs/Tone.js#562]

**Comment by tambien** [comment]
You can use the Web Audio API's `createMediaElementSource(mediaElement)` by doing something like this `Tone.context.createMediaElementSource(mediaElement)`

In the future please use the forum for questions that are not bugs or issues

**Comment by aadarshvelu** [comment]
> You can use the Web Audio API's `createMediaElementSource(mediaElement)` by doing something like this `Tone.context.createMediaElementSource(mediaElement)`
> 
> In the future please use the forum for questions that are not bugs or issues

Yes I'll But how to implement it I didn't sense can I get some example on this, please!
