### ISSUE TITLE
No Sound From StereoXFeedbackEffect!!

### ISSUE THREAD

**Issue by binatricx** [Tonejs/Tone.js#564]
I'm just fall in love with tone.js with awesome work!

There no Example for Effects like StereoXFeedbackEffect(), MidSideEffect()...

Why this code below code isn't working i add effects to player but the player works when effects isn't connected??

```
var buffer = new Tone.Buffer("/audio/bgm.[mp3|ogg]",() => {console.log("Buffer Loaded!")});
        var effects = new Tone.StereoXFeedbackEffect().toMaster();
        var player = new Tone.Player({
            "url" : buffer,
            "loop": true
        }).connect(effects).start();

```
So I request you to give a Example About this Please Or Give Me Solution Dude!!

**Comment by aadarshvelu** [comment]
> Thanks for your question. These are abstract base classes which other classes use. For example PingPongDelay extends StereoXFeedbackEffect and the StereoWidener extends MidSideEffect. They don't actually do anything by themselves.

So how should I implement it could you give me an example code, please!

**Comment by binatricx** [comment]
I didn't get it give me Example Plz Dude😢..

**Comment by binatricx** [comment]
Extend mean is this correct way..

`     var buffer = new Tone.Buffer("/audio/bgm.[mp3|ogg]",() => {console.log("Buffer Loaded!")});
      var pingpongDelay = new Tone.PingPongDelay(0.3).toMaster();
      var effects = new Tone.StereoXFeedbackEffect().toMaster();
      pingpongDelay.connect(effects);
        var player = new Tone.Player({
            "url" : buffer,
            "loop": true
      }).connect(pingpongDelay).start();
`

Why this above code also not producing any noise than?

**Comment by tambien** [comment]
These classes are used internally inside Tone.js. They don't actually make any sound at all, but are infrastructure that other classes rely on. In the next version of the library (`tone@typescript`), i've made it so they are not exposed publicly to avoid this type of confusion.

**Comment by binatricx** [comment]
> These classes are used internally inside Tone.js. They don't actually make any sound at all, but are infrastructure that other classes rely on. In the next version of the library (`tone@typescript`), i've made it so they are not exposed publicly to avoid this type of confusion.

Sorry to disturb you dude!
So that right to left and left to right effect doesn't occur! right dude?
