### ISSUE TITLE
typescript branch does not work in node

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#566]
I've attempted to upgrade to the `typescript` branch but I think there's been a regression for how it behaves in a node environment.

I am using SSR so the code at least needs to be able to initialized (like it does on master).

On the non-esm version I get a `window is not defined error`. I get the same error when running `npm run test:node`. It doesn't look like travis is running that test right now.

However, I was successful in using the ESM module after some modifications. 

I would get `bind` issues for `now` and `immediate` from [these lines](https://github.com/Tonejs/Tone.js/blob/typescript/Tone/index.ts#L11-L18).

But I added the following to [these lines](https://github.com/Tonejs/Tone.js/blob/typescript/Tone/core/Global.ts#L11-L14):

```
now: function() {},
immediate: function() {}
```

and everything appears to work for me locally.

Not sure which direction you want to go in :man_shrugging:

**Comment by tambien** [comment]
good catch. exactly as you mentioned, that `dummyContext` is there so that it's able to run in Node. Seems i left out the latest interfaces when i updated Tone/index.ts. Might also need "Draw" in there. It'd be great if you could submit a PR with your fix. Thanks!

**Comment by tambien** [comment]
reintroduced `npm run test:node` back into the travis testing and those tests passed, so we can close this now.
