### ISSUE TITLE
non-default lookahead causing GrainPlayer skipping

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#568]
I have been using the default `lookAhead` of `0.1` but have found it's not the best setting for a vital `Tone.Part` I am using, so I'd like to increase it to schedule events further in advanced.

However, doing so breaks my originally perfectly pitch-shifted GrainPlayers.

When changing `latencyHint` to `balanced` the GrainPlayers become very choppy. I've attempted to tweak `overlap` and `grainsize` but haven't been able to create something that sounded like the original `lookAhead`. Is there a direct relationship between the default GrainPlayer settings and the default lookAhead?

I'm not sure if this is a bug or a lack of understanding of how `lookAhead` could negatively affect a GrainPlayer's quality.

[Example. (warning: autoplay annoying sound)](https://jsfiddle.net/rmaoeb45/)

**Comment by tambien** [comment]
Seems to be mitigated mostly on the typescript branch. [Here's a fork of your fiddle](https://jsfiddle.net/yotammann/d0yq295e/). 

Occasionally you can hear the envelope ramp up, i think that's probably an issue with handling the loop point.

**Comment by JackCA** [comment]
You're right. Awesome.
