### ISSUE TITLE
Transport.position sometimes can't invoke the callback in the timeline.

### ISSUE THREAD

**Issue by moayuisuda** [Tonejs/Tone.js#573]
It seems the Transport.position is a little Inaccurate.

I scheduled a callback like this:
`Tone.Transport.schedule((time) => {
  console.log('0');
}, '0:0:0');` 

And when i set the Transpost.time to '0:0:0', sometimes the callback was not be invoked.
It can be fixed by this :
`Tone.Transport.position = Tone.Time('0:0:0') - Tone.Time('32n');`

The demo here:
https://jsfiddle.net/moayuisuda/bgu4nd0s/20/#

Did i used it in the wrong way or it's just so?

**Comment by tambien** [comment]
thanks for the issue, i can confirm i'm seeing the same thing. will look into it when i've got a moment.
