### ISSUE TITLE
Some problem in Tone.Part.

### ISSUE THREAD

**Issue by moayuisuda** [Tonejs/Tone.js#581]
I'm confused how Tone resolve the situation when calling Tone.Part.start() multiple times.

Code Snippet:

```js
let loop = new Tone.Part(time => {
	console.log('loopAt', time);
}, [{time: '0:0:0'}, {time: '0:1:0'}]);
loop.loop = 1;

loop.start('0:0:0');
loop.start('0:2:0');
// loop.start('0:0:0');

Tone.Transport.schedule((time) => {
  console.log('scheduleAt', time);
}, '0:0:0');

Tone.Transport.schedule((time) => {
  console.log('scheduleAt', time);
}, '0:1:0');

Tone.Transport.start()
```

If i code like this(just as same as the code above):
```js
loop.start('0:0:0');
loop.start('0:2:0');
// loop.start('0:0:0');
```
The event in '0:2:0' won't be invoked, and the event in '0:0:0' will be invoked;

But if I code like this:
```js
// loop.start('0:0:0');
loop.start('0:2:0');
loop.start('0:0:0');
```
The event in '0:2:0' and '0:0:0' all will be invoked.

Demo here:
https://jsfiddle.net/moayuisuda/54pLqk0g/

**Comment by tambien** [comment]
All of the event classes (and pretty much all scheduling in Tone.js) works only when the events are scheduled in an increasing time order. There's a short note in the docs for [Sources](https://tonejs.github.io/docs/13.8.25/Source), but the same is true for the event classes like Tone.Part. 

Unfortunately this detail is not that well documented other than in that one spot. I've just pushed a change which will throw an error when you try to schedule events not in increasing time order like your example. This should hopefully alleviate this confusion in the future. 

The error that is now thrown would read: `"The time must be greater than or equal to the last scheduled time"`
