### ISSUE TITLE
Custom Effect

### ISSUE THREAD

**Issue by hector** [Tonejs/Tone.js#583]
Hi,

I have a custom audio effect (pitch shift + time stretch) implemented in WASM.
Currently I have been able to use it with a ScriptProcessorNode, which I know is not the best in terms of performace.
I would like to integrate it in a Tone.js audio chain. It seems the best idea would be to create my own effect by extending Tone.Effect, but it is not clear how to do that.
Could you give me some directions please?

PS: This old issue seems related https://github.com/Tonejs/Tone.js/issues/148

**Comment by tambien** [comment]
Sounds like a cool effect! As long as the script processor node is created with the same context it can be used with Tone.js. Just connect it using `Tone.connect`

```javascript
const customEffect = Tone.context.rawContext.createScriptProcessor(...args)
customEffect. onaudioprocess = yourProcessingFunction
Tone.connect(anyToneAudioNode, customEffect, Tone.context.destination)
```

You'll see i'm grabbing the 'rawContext' since createScriptProcessor is deprecated it's not actually implemented on Tone.context.

**Comment by hector** [comment]
Lots of thanks for the answer, will try it soon!

One more question, if I may.
I am not very worried for the performance of using ScriptProcessor since it only copies audio to the WASM plugin, which handles the expensive processing and I believe it is running separate from the main JS thread. If I were to have problems with performance do you know what could be the correct web audio API to use?

**Comment by tambien** [comment]
Take a look at the API for the AudioWorkletNode. That's what the ScriptProcessorNode has been replaced with.

**Comment by MysteryPancake** [comment]
@hector Sorry to bother you, but I am wondering about your effect. I am struggling to find an effect which does these two tasks, and I am wondering what audio effect you are using to do this? I have seen a repository called Rubberband, and I was wondering if you were using this or something different?

**Comment by hector** [comment]
Hi @MysteryPancake,

I am using an effect from our company [Voctrolabs](https://www.voctrolabs.com/).
You can try some online demos here: https://www.voiceful.io/demos.html
The code is not open-sourced and available for free though.

**Comment by MysteryPancake** [comment]
Darn, thanks for replying anyway!
