### ISSUE TITLE
`Tone.Transport.bpm.value` is 0 for a brief moment when page loads

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#587]
**Current behaviour**

For some reason, `Tone.Transport.bpm.value` is equal to 0 instead of it's default value 120 while "Tone is initializing". This causes unexpected bugs if operations are done right when the page loads.

As a very specific example, if you start the transport with a loop, Tone.Transport.loopStart will be equal to `NaN`, because the `loopStart` getter ends up calling `TimeBaseClass._beatsToUnits()` which does a calculation with the bpm.

If I do `await new Promise(resolve => setTimeout(resolve))` before doing my logic, Tone has time to initialize and set the bpm correctly.

Or I can set the bpm to 120 manually before doing anything else.

**Expected behaviour**

Calling `Tone.Transport.bpm.value` at anytime should return the real BPM (either 120 or a value that has been set by the user)

**EDIT 1**

Using the tone@typescript version (14.5.3)

**Comment by tambien** [comment]
Could you provide a way to reproduce this issue? 

Here's a [minimal sandbox](https://codesandbox.io/s/transport-bpm-test-df2bq) which is printing 120 bpm.

**Comment by maximedupre** [comment]
So it seems like the problem occurs when setting the `latencyHint`.

https://codesandbox.io/s/transport-bpm-test-x8vnk

**Comment by maximedupre** [comment]
Commit fixes the issue. Thanks!
