### ISSUE TITLE
Can't access split left or right in the typescript version

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#588]
https://codesandbox.io/s/transport-bpm-test-3i7nw

**Comment by maximedupre** [comment]
Should I use

`splitNode.connect(otherNode, 0)` instead of `splitNode.left.connect(otherNode)`?

**Comment by maximedupre** [comment]
Yep, the solution above works.

**Comment by tambien** [comment]
I've updated the API to remove some of the stereo bias that the split/merge objects had since they can support more than 2 channels and it doesn't make sense to enumerate all of the outputs in that way.
