### ISSUE TITLE
CrossFade has no inputs (typescript version)

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#590]
`Uncaught Error: Cannot connect to node with no inputs` when trying to connect anything to a CrossFade

https://jsfiddle.net/m61xycg0/11/

**Comment by tambien** [comment]
The updated API is that CrossFade has two named inputs:  'a' and 'b'. 

https://tonejs.github.io/docs/14.5.3/CrossFade#input

This is a byproduct of a refactor as part of v14 where i got rid of input/output arrays which simplified the connect/disconnect code. It meant that in the case of CrossFade i'd have to make two named inputs `a` and `b`.

**Comment by maximedupre** [comment]
I wasn't aware of the new doc. I dit it! 

Thanks
