### ISSUE TITLE
(build request) ESM browser version?

### ISSUE THREAD

**Issue by Pomax** [Tonejs/Tone.js#595]
Right now the code looks to be a UMD library, which actually means it _can't_ be run in the browser when using modern ES module code. Would it be possible to generate a `Tone.umd.js` as well as a `Tone.esm.js` so that folks who are writing modern module-based code can simply write `import { Tone } from "Tone.esm.js"` in their scripts?

**Comment by tambien** [comment]
this is currently available in the typescript branch. `npm i tone@typescript`. `package.json` should already be pointed at the right files. I've been able to use it directly in the browser. let me know if that works for you

**Comment by Pomax** [comment]
I don't use typescript, though. I'm working on pure module JS loaded directly into the browser on a page, without node, or build tools, etc.

**Comment by tambien** [comment]
the built files from that branch are just js files, no need to use any typescript tooling and they get exported into an 'esm' folder. [for example](https://unpkg.com/tone@14.5.17/build/esm/index.js). i've been able to load tone.js directly in the browser using module loading without any tooling. 

I don't host built files in the repo so the only way to get the files would be to download the npm package or from unpkg.com. 

The [examples](https://tonejs.github.io/docs/14.5.15/CrossFade) in the latest version of the docs pulls the module files directly from unpkg.com when you click 'run'.

**Comment by Pomax** [comment]
ah, cool, thank you!

**Comment by Pomax** [comment]
Actually, before I close this: could that information be added to the README.md? That's pretty valuable to have immediately discoverable.

**Comment by tambien** [comment]
Added a note to the [installation wiki](https://github.com/Tonejs/Tone.js/wiki/Installation)
