### ISSUE TITLE
Tiny time inaccuracy in Part looping

### ISSUE THREAD

**Issue by cbossut** [Tonejs/Tone.js#596]
Hi,

I have a really simple setup with Tone.Part where the loop seems to shift in time: [fiddle](https://jsfiddle.net/0f3w5jLp/3/)

I just set two events that should repeat at fixed times, and track the time the callback is called and the time I think it should be called, and it slips.

The very same thing with intergers doesn’t slip: [fiddle](https://jsfiddle.net/0f3w5jLp/4/)

So I think there’s a rounding happening inside the loop that I’m not aware of.

**Comment by cbossut** [comment]
Looking at the internals of Part, loopEnd seem to be stored as an integer. Is this integer usable to achieve time accuracy in looping or should I use Transport.schedule as a workaround?

**Comment by tambien** [comment]
In the end, all values scheduled along the Transport are converted into "ticks". A tick is a quarter note divided by Transport.PPQ (pulses per quarter note). So if you're just trying to schedule highly specific timing values that don't align to any global bpm, you can try using Tone.Clock which isn't bound to a tick. The alternative is to adjust your Transport.bpm and PPQ to match a common divisor of your timing.

**Comment by cbossut** [comment]
Ok, thanks for the quick response.
Just my two cents, but in many places in the docs it is said that Tone.Transport permits sample-accurate scheduling, and my research in the forum, wiki, examples and docs never put me on the track of Tone.Clock, that’s why I interpreted that as a bug.

Then, do you know if I can find examples using Clock, because reading the docs, I don’t really understand how I can use the sample-accurate time to trigger other events as it will be converted to ticks anyway a moment or another.

Thanks again anyway, I’ll dig in Clock.
