### ISSUE TITLE
new Tone.ScaledEnvelope is not a constructor

### ISSUE THREAD

**Issue by Knapptr** [Tonejs/Tone.js#597]
Trying to create a scaled envelope with:

`var env = new Tone.ScaledEnvelope();
env.connect(filter.frequency);`

Met with an error of `script.js:4 Uncaught TypeError: Tone.ScaledEnvelope is not a constructor`

Bugs and feature requests only please.

For help questions, check out the forum: https://groups.google.com/forum/#!forum/tonejs

If possible, please include a link which illustrates the issue.

https://jsfiddle.net/1f60jkq4/ (tone@latest)
https://jsfiddle.net/z9marxbt/ (tone@next)

**Comment by everythingability** [comment]
I have similar music.js:420 Uncaught TypeError: Tone.Channel is not a constructor

**Comment by everythingability** [comment]
This may be the answer. Drop a version.

https://stackoverflow.com/questions/57047017/how-to-use-cdn-in-local-javascript-file/57047432
