### ISSUE TITLE
ToneJS React TypeScript useRef

### ISSUE THREAD

**Issue by styk-tv** [Tonejs/Tone.js#599]
I understand React might be a bit out of scope here but I know no better place to ask.

From what I understand,  in React useRef along with useEffect can be used to hook up to a reference of a main instance of an object (like ToneJs). So potentially it would be possible to organize elements like Sampler and Transport as React components. Is there anyone trying to work this out?

https://medium.com/@rossbulat/react-using-refs-with-the-useref-hook-884ed25b5c29

**Comment by unkleho** [comment]
Hi, I've been working on some React components that wrap around Tone JS (https://reactronica.com). useRef can definitely be used to store Tone JS instances, with useEffect manipulating them. Here is an example - https://github.com/unkleho/reactronica/blob/master/src/components/Instrument.js

**Comment by styk-tv** [comment]
@unkleho Music to my ears.. I will study your approach. Thank you!

**Comment by eoghanmccarthy** [comment]
Update to the typescript branch too. Performance improvements in React are off the charts.
