### ISSUE TITLE
React example with hooks 

### ISSUE THREAD

**Issue by nndv** [Tonejs/Tone.js#600]
Hi, in the React with hooks example there is a problem in the way `useRef` is used. Every time component renders it will create a new Sampler. I've made a fork of the example where this can be fixed with `useEffect` https://codesandbox.io/s/tone-sampler-example-sjohx . If you want I can update the wiki, it would be my first contribution to OS 🙂

**Comment by ejarzo** [comment]
I believe I wrote that part (with minimal hooks experience). Yes, please update it!

**Comment by tambien** [comment]
that'd be great if you could update it! thank you!

**Comment by nndv** [comment]
I've updated it, thanks guy
