### ISSUE TITLE
Tone.Players & Loop sometimes not starting at same time

### ISSUE THREAD

**Issue by designcourse** [Tonejs/Tone.js#606]
Hey,

I'm working within Vue here, here's my code:

```
import Tone from "tone";
import A1 from "./assets/sounds/A1.mp3";
import C1 from "./assets/sounds/C.mp3";
import F1 from "./assets/sounds/F.mp3";
import G1 from "./assets/sounds/G.mp3";
import drums from "./assets/sounds/drums-basic.mp3";
```

```
player() {

      const notes = ["C1", "F1", "G1", "F1"];
      const drum = ['drums'];
      
      var kit = new Tone.Players({C1, G1, F1, drums }, {
        onload: () => {

          var loop = new Tone.Loop((time) => {
            kit.get('drums').start()
          }, "4").start(0);

          var progression  = new Tone.Sequence(
            function(time, note) {
              kit.get(note).start()
            },notes,"4");

            progression.start();

          }
        }).toMaster();

      Tone.Transport.start();
}
```

This plays a 4/4 time with drums continually looping, and the chord progression switches on top of it. Sometimes on desktop, it will start with JUST C1 playing with no drums, and other times they all come in together.  Most of the time it works.  On mobile, sometimes the drums come in too soon and it's completely off time.

I just need to ensure that all instruments come in *on* time and play at the same time. Any thoughts based on my code?

**Comment by tambien** [comment]
The timing should be corrected if you use the `time` value passed in from Loop and Sequence passed into `start()`. 

Also looks like you're starting the Transport immediately but adding events to the transport dynamically. specifically `loop.start(0)` will add an event to the beginning of the transport timeline, but `progression.start()` invoked with no time value will add the progression to the current transport position which will probably not be 0 anymore, so i'd expect them to not be aligned and for the timing to really depend on the loading time of the device that your testing it on.
