### ISSUE TITLE
FrequencyEnvelope's baseFrequency/octaves not working as expected

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#607]
https://stackblitz.com/edit/tone-js-issue-607

The way I understand FrequencyEnvelope, it should modify the filter's frequency in my example, by starting at `baseFrequency` and going up to the frequency defined by `octaves`. So it should go from 0hz to whatever 6 octaves is in hertz. Is that how it's supposed to work?

**Comment by tambien** [comment]
4 octaves above 0hz is also 0hz given the formula that FrequencyEnvelope uses:

```js
const maxFreq = baseFrequency * Math.pow(2, octaves)
```

If you've got a specific range in mind, i'd just use Tone.Envelope routed through Tone.Scale which will let you define your min and max to any values.

**Comment by maximedupre** [comment]
Right. Ok thanks, this works better: https://stackblitz.com/edit/tone-js-envelope-spike?file=index.ts
