### ISSUE TITLE
multiPlayer not working

### ISSUE THREAD

**Issue by kyoukhana** [Tonejs/Tone.js#610]
I am trying to use the multiPlayer  but it doesn't seem to work any ideas as to what I am missing here is the link.

https://codesandbox.io/s/naughty-tdd-9mzl9

**Comment by tambien** [comment]
players wraps up multiple Tone.Player, so you need to reference the player you want using `get` in version 13.x or `player` in version 14.x 

https://codesandbox.io/s/issue-610-it2kd

**Comment by kyoukhana** [comment]
Thanks for the help.  I tried that also added a play link to play the file but it isn't working.  

https://codesandbox.io/s/issue-610-8u5h9

I am not sure what I am missing.

**Comment by tambien** [comment]
Make sure that the player is connected to the speakers using `toMaster()` in 13.x or `toDestination()` in 14.x

**Comment by kyoukhana** [comment]
Thanks for the help I tried that but didn't work take a look at the code.  Sorry just really new at learning this library once I get going I am good to go.

https://codesandbox.io/s/issue-610-8u5h9

**Comment by tambien** [comment]
@kyoukhana you'll also want to change `start(0)`. it should just be `start()` which will have it play immediately. the start argument refers to a time, and time 0 is when the page first loads (which has already passed). If you use no arguments, the time is interpreted as 'immediately' which is i think what you want. 

https://codesandbox.io/s/issue-610-gcg10

**Comment by tettusud** [comment]
@tambien  is there a way to call start on Players? and start all tracks at once? Or what is the right way , I have multiple tracks ( like drum , guitar etc) I want to play them together and do some mixing how can I achieve it?
