### ISSUE TITLE
Use wave data from Tone.Player() to build WaveSurfer.js peaks?

### ISSUE THREAD

**Issue by styk-tv** [Tonejs/Tone.js#612]
Has anyone try to figure out how to use Tone.Player() wave data to feed peak building in WaveSurferJs? I mean the two would make such an awesome combo. Tone with Player and Transport to do proper synchronization and manipulation and WS to do pretty peaks? I'm only learning JS for the past few months so aksing here maybe for others its easy to figure out. Any hints would be awesome as I've been really kicking this with no effect last 3 days.

<img width="712" alt="Screenshot 2020-01-26 at 20 12 07" src="https://user-images.githubusercontent.com/838921/73141113-31901200-4078-11ea-92b4-4e5c494de52f.png">

**Comment by tambien** [comment]
Maybe someone here knows how to better integrate with wavesurfer.js. The only hint i could offer is that you can access the raw audio buffer values using `player.buffer.toArray()` or get the raw AudioBuffer if that's what wavesurfer requires using `player.buffer.get()`.

**Comment by noaLeibman** [comment]
Hi!
I was thinking about the same issue for a few days now, and after seeing this other [issue](https://github.com/Tonejs/Tone.js/issues/707),
I tried to create a class that extends ToneAudioNode that contains a WaveSurfer object.
I could get it to play by syncing it with Tone.Transport (but I feel that I did it in a stupid way) and I couldn't get it to connect to an Effect node like Reverb or Distortion.

This is my class:
```
class WaveSurferNode extends ToneAudioNode {
  name: string;
  input: Tone.InputNode | undefined;
  output: Tone.OutputNode | undefined;
  waveSurfer: WaveSurfer;
  
  constructor(ref: any) {
    super();
    this.name = "WaveSurferNode";
    this.input = undefined;
    this.output = Tone.Destination;
    this.waveSurfer = WaveSurfer.create({
      container: ref,
      waveColor: 'violet',
      progressColor: 'purple',
      responsive: true,
      normalize: true,
      partialRender: true
    });
  }

  load(url: string) {
    this.waveSurfer.load(url);
  }

  sync() {
    this.context.transport.on("start", () => {this.waveSurfer.play()});
    this.context.transport.on("stop", () => {this.waveSurfer.stop()});
    this.context.transport.on("pause", () => {this.waveSurfer.pause()});
    return this;
  }
}
```

1. I wasn't sure on how to define the `input` and `output` properties.. What is the right way?
2. For connecting this node to an effect I tried `waveSurferNode.connect(effectNode)` but that didn't seem to work.

I would really appreciate any advice on this! Thanks in advance.

**Comment by DaniyarSarasenov** [comment]
Hi
I also wanna show the wave surfase the combined music using Tonejs in real time like this
![image](https://user-images.githubusercontent.com/92083200/175482299-e54558d4-bab1-4d2c-9761-cc9c027445cf.png)

This is my code
const sampler = new Tone.Sampler({
  urls: urls,
  release: collect === WEAREKLOUD ? KLOUDTIME : BACKTIME,
}).toDestination();

Tone.loaded().then(() => {
 toneSampler?.triggerAttackRelease(["C1", "C2"], 30);
});
But I dont know how to show the wav surface using tonejs

**Comment by marcelblum** [comment]
@DaniyarSarasenov WaveSurfer and Tone can work great together, just have to watch out for unnecessary resource use and make sure both libs can share resources when possible (i.e. no need for WaveSurfer to use a separate audio context or duplicate buffers already decoded by Tone). So you can do
```
const waveSurferInstance = WaveSurfer.create({
	audioContext: Tone.getContext().rawContext._nativeAudioContext
        // ...other options etc.
});
waveSurferInstance.loadDecodedBuffer(someToneBufferObject._buffer);
```
One gotcha is that WaveSurfer will then store its own reference to the buffer so if you ever want to unload it you have to remember to dereference it in wavesurfer also so it can be GCed.

**Comment by DaniyarSarasenov** [comment]
Hi thanks for your reply
In your sample, you described _buffer value.
But I cant found the _buffer after combining the urls
I hope you explain more in details about someToneBufferObject._buffer

**Comment by marcelblum** [comment]
@DaniyarSarasenov when you load audio files via Tone, whether through `Tone.Player` or `Tone.Sampler` etc., the base class that is used to store the decoded audio data for each sound file is [`ToneAudioBuffer`](https://tonejs.github.io/docs/14.7.77/ToneAudioBuffer), which is a wrapper of the native `AudioBuffer`. To use Wavesurfer's `loadDecodedBuffer` method you'll need to pass in a native `AudioBuffer` object which can be found under `ToneAudioBuffer._buffer`.

In the case of your example you're using `Tone.Sampler` which represents a collection of buffers and to get the native buffers you'll need to drill down into the `Sampler` object a bit. `sampler._buffers._buffers` will get you map object of all the `ToneAudioBuffer` objects contained within `sampler` such that `[...sampler._buffers._buffers.values()][0]._buffer` returns the native `AudioBuffer` from the first file in the sampler.

**Comment by DaniyarSarasenov** [comment]
Thanks for your effort.
You are right.
But ToneAudioBuffer._buffer represent the buffer of only one file.
I wanna show the combined buffer of several sound files.
const urls = {
"C1": "1.wav",
"C2": "2.wav",
"C3": "3.wav",
}
const sampler = new Tone.Sampler({
  urls: urls
}).toDestination();
I remember we can add only one buffer to wavesurfer
How can I add the combined the sampler.buffers to wavesurfer.

**Comment by marcelblum** [comment]
@DaniyarSarasenov I'm not really clear on what you're trying to do, are you saying you want to display a waveform representing the mixed down audio of all of the sounds, as if they were all started at the same time like multitrack stems of a song? In that case you could use an [offline context](https://tonejs.github.io/docs/14.7.77/fn/Offline) to generate a buffer of the mixdown and feed that single buffer to Wavesurfer. But if these are fixed sound files (not user-supplied, not varying), then it doesn't make much sense to do that work client side in realtime, you might be better off generating the mixdown waveform in advance, Wavesurfer provides a way to do this, see [the Wavesurfer FAQ ](https://wavesurfer-js.org/faq/).

Also note you can have more than one Wavesurfer instance going, with each showing a different buffer, if you wanted to show multiple waveforms.

**Comment by jgentes** [comment]
> waveSurferInstance.loadDecodedBuffer(someToneBufferObject._buffer);

@marcelblum thanks for the suggestion here.

I found that reusing the AudioContext from Tone didn't change the memory profile, however I believe the buffer could offer huge savings.

Unfortunately I found this not working:
```js
const source = URL.createObjectURL(file)
const player = new Tone.Player(source).toDestination()

const wavesurfer = WaveSurfer.create(config)

// using loadBlob works
waveform.loadBlob(file)

// using loadDecodedBuffer does not
waveform.loadDecodedBuffer(player.buffer._buffer)
```

I was curious if there might be something else I'm missing? The `._buffer` does look correct when I inspect the `player.buffer` object, so this may be a wavesurfer issue.

**Comment by marcelblum** [comment]
@jgentes since the buffer decoding done by the `Player` constructor is async, you would need to delay calling `loadDecodedBuffer()` until after the buffer's loaded. The constructor can accept an onload callback as the second argument so you could do something like:

`const player = new Tone.Player( source, ()=>wavesurfer.loadDecodedBuffer(player.buffer._buffer) ).toDestination();`

**Comment by jgentes** [comment]
@marcelblum thank you! That just saved my browser about 1gb of memory for visualizing 8 stems :)

I also found big memory savings by using PCM data to visualize the waveform while using Tone for playback.

Thanks again.

**Comment by jgentes** [comment]
Only bummer is the TS warning: `Property '_buffer' is private and only accessible within class 'ToneAudioBuffer'` :(

It seems the getter `player.buffer` should return `this._buffer` according to https://github.com/Tonejs/Tone.js/blob/c313bc6/Tone/source/buffer/Player.ts#L346

Otherwise there's always //@ts-ignore :)

**Comment by marcelblum** [comment]
I think `player.buffer.get()` should return what you need (the native `AudioBuffer` object)

**Comment by corysimmons** [comment]
Did anyone ever get this to work? I'm trying to share the same audio instance between both Tone and Wavesurfer so when I scrub in Wavesurfer or tweak a Tone.js effect, it is reflected in the same audio.

**Comment by jgentes** [comment]
> Did anyone ever get this to work? I'm trying to share the same audio instance between both Tone and Wavesurfer so when I scrub in Wavesurfer or tweak a Tone.js effect, it is reflected in the same audio.

This code should work: 
```ts
const waveform = WaveSurfer.create(config)

// create the Tone Player
const source = URL.createObjectURL(file)
const player: Player = new Player(source, async () => {
  // use Tonejs buffer to render waveform
  waveform.loadDecodedBuffer(player.buffer.get())
}).toDestination()
```

**Comment by corysimmons** [comment]
@jgentes I don't think `loadDecodedBuffer` exists in Wavesurfer.js anymore.

I _can_ use the `getChannelData(n)` (from Tone) and pass those to `peaks` (in Waveform) to create peaks, but it just creates it once and doesn't stay synced with the audio from Tone, so I think your method would be better if I could get it working.

**Comment by marcelblum** [comment]
See https://github.com/katspaugh/wavesurfer.js/discussions/2806 and https://github.com/katspaugh/wavesurfer.js/discussions/3201 for more info, but yeah `loadDecodedBuffer` is only found in Wavesurfer <7. The workaround proposed by the project's maintainer is memory-inefficient and incomplete. I'm still using Wavesurfer v6 partly for this reason (and partly out of laziness TBH) though v7 does perform impressively for things like quick deep zooms into long sounds. Seems like v6 still gets occasional maintenance updates. In general I found it best to use Tone for audio and Wavesurfer for visuals only, otherwise you'll be bending over backwards trying to get Wavesurfer's relatively primitive audio playback to output through Tone, and without much benefit. I found it easier to just use Wavesurfer for visualizations and UI functions but keep actual playback in Tone and draw my own playhead over Wavesurfer waveforms.

**Comment by corysimmons** [comment]
@marcelblum 

>In general I found it best to use Tone for audio and Wavesurfer for visuals only, otherwise you'll be bending over backwards trying to get Wavesurfer's relatively primitive audio playback to output through Tone, and without much benefit. I found it easier to just use Wavesurfer for visualizations and UI functions but keep actual playback in Tone and draw my own playhead over Wavesurfer waveforms.

That is _exactly_ what I'm trying to do, but I'm already struggling with performance so I can't imagine going back to v6.

Honestly, at this point I'm considering just making my own Wavesurfer.js alternative (I already have a pretty solid prototype).

It's wild these two projects haven't been married already. They're perfect for each other.

**Comment by jgentes** [comment]
When v7 came out I removed Tone.js altogether as it was causing huge memory consumption. But I was only using Tone for it's sychronization, and v7 seemed to address the sync issues I had with v6.
