### ISSUE TITLE
Short Attack, Long Decay AmplitudeEnvelope Quick Succession Issue

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#614]
I'm encountering a bug where if an `AmplitudeEnvelope` with a very short `attack` and a very long `decay` is quickly triggered and released, the envelope won't start until what seems to be a delay equal or close to the value of the `decay` value.

[Here's an example.](https://jsfiddle.net/JackCA/Ldo9us4e/)

1. Click Play
2. Env is triggered
3. Env is released
4. Env is triggered
5. silence until around 10sec later

**Comment by tambien** [comment]
Seems like the very short attack is part of the issue. When i set the attack time to be >= 2 samples it works ok, but the decay envelope still seems a little weird since the attack phase doesn't bring it all the way to 1 where it should be.

**Comment by tambien** [comment]
Very short attacks (< 1 sample) would be put through a different branch of the envelope, and that branch was missing a `cancelScheduledValues` so the scheduling timeline wasn't cleared of the previous decay which was causing that issue. 

This is how the curve looks when i plot it: 
![image](https://user-images.githubusercontent.com/1323402/73622315-32401f80-4607-11ea-93e7-8a10345ffc84.png)

**Comment by JackCA** [comment]
Brilliant, and thanks for the explanation here. Confirmed the fix solves what I was hearing. Great work 🍾
