### ISSUE TITLE
Types Property in package.json

### ISSUE THREAD

**Issue by tabuckner** [Tonejs/Tone.js#615]
For v13.8.35, it would be really nice to have the type definitions file referenced in the popular `types` property of the `package.json`. 

This is used by a lot of tooling setups, including the Angular CLI. After reviewing the `next` branch it looks like you guys already intend to make use of this in future releases. But for those of us still using the current release, it would be nice to also have this feature.

There are workarounds, I think (?), but I had issues getting it to work just the way I wanted. After forking the repo and making this change, everything worked the way I wanted it to.

No idea if this is a trivial fix or not--the split between current release and the next branch makes me think it's more of a hot-fix situation and not quite so simple.

**Comment by tabuckner** [comment]
This was a silly issue to open. I've since started using the next branch and have been very happy. 

IGNORE ME 😄

**Comment by tambien** [comment]
thanks for following up! glad the next version is working for you
