### ISSUE TITLE
Can't set a new buffer to the convolver

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#616]
When it enters the `setTimeout` to set a new buffer, the sound stops.

I would have posted a stackblitz repro, but you can't upload assets on there.

Uses `tone@typescript`.

```javascript
const convolver = new Tone.Convolver("1.wav");
const osc = new Tone.Oscillator(440, "sine");

osc.connect(convolver);
convolver.toDestination();

setTimeout(() => {
  console.log("setting new buffer");
  // convolver.buffer.load("2.wav");     <--------- Also not working
  convolver.buffer = new Tone.ToneAudioBuffer("2.wav");
}, 3000);

document.addEventListener("click", () => {
  Tone.start();

  if (osc.state === "started") {
    osc.stop();
    console.log("osc stopped");
  } else {
    osc.start();
    console.log("osc started");
  }
});

```

**Comment by tambien** [comment]
@maximedupre Thanks for the test case! Forgot to reconnect the convolver to the output it after setting the new buffer. 

Should be fixed now.

**Comment by maximedupre** [comment]
@tambien Thanks for the fix! Can you specify what version you are talking about?

**Comment by tambien** [comment]
@maximedupre Does the latest `tone@next` fix the issue for you?

**Comment by maximedupre** [comment]
It does! Thanks
