### ISSUE TITLE
No sounds on Android Google Chrome 

### ISSUE THREAD

**Issue by asanzdiego** [Tonejs/Tone.js#617]
No sounds on [Android Google Chrome](https://play.google.com/store/apps/details?id=com.android.chrome)

Source: [https://github.com/asanzdiego/taller-p5js-con-tonejs/tree/master/ejemplo-01](https://asanzdiego.github.io/taller-p5js-con-tonejs/ejemplo-01/index.html)

Live: [https://asanzdiego.github.io/taller-p5js-con-tonejs/ejemplo-01/index.html](https://asanzdiego.github.io/taller-p5js-con-tonejs/ejemplo-01/index.html)

Thanks

**Comment by tambien** [comment]
My guess is this is probably an autoplay issue. Check that `Tone.context.state === "running"`

if it's `"suspended"`, make sure you invoke `Tone.start()` on a user action.

**Comment by asanzdiego** [comment]
It works now. Thanks ;-)
