### ISSUE TITLE
Performance? timeline.forEachAtTime iterates through 0 to the given time

### ISSUE THREAD

**Issue by vegertar** [Tonejs/Tone.js#618]
[this._iterate(0, upperBound)](https://github.com/Tonejs/Tone.js/blob/e68fe68e4c4fef5b6eb3771491e9362c5b93579c/Tone/core/util/Timeline.ts#L379)

This function is invoked by Transport._processTick which used as callback in Clock, I'm confused that is there any reason to have calling from the array beginning?

**Comment by tambien** [comment]
@vegertar true it could be optimized. The reason it iterates from the beginning is that the `_search` method returns the index of the _last_ item if there are multiple items with the same time, so iterating from the beginning guarantees that it gets all of the items at that time. I'll test out iterating from the lowerBound by modifying `_search` to return the lowerBound

Thanks for the tip
