### ISSUE TITLE
Memory Leak from Tone.Player / Tone.Buffer not correctly disposing

### ISSUE THREAD

**Issue by Awendel** [Tonejs/Tone.js#620]
I built a small app with Tone.js loading local mp3 and playing them through Tone.Player.

After a song is finished, I create a new Tone.Player and call .stop() and .dispose() on any existing ones.

Yet, even though the Players and internal Buffers are marked as disposed, the RAM never gets freed. 

Since AudioBuffers are quite big compared to mp3s, to memory quickly overfills after awhile.

I have also tried manually disposing the internal Buffers of the player, but to no avail.

Can perhaps post a link if clarification needed, just not as easy on jsfiddle because of CORS.

best regards

**Comment by Awendel** [comment]
I managed to find a solution by not using the Tone.Player / Buffer to play back music, but instead by using the native Web Audio .createMedialElementSource( ) alongside an html <audio> which seems to be working a lot better for large audio files / mp3s.

They can be connected to Tone.JS Element through Tone.connect(), which sadly only works in 13.8.25 but not in the latest dev release 14.5.35 (could be files as another bug, but I may also be a spec change).

This doesn't of course solve the solution of Buffers / Players not disposing correct, e.g. for use in video games etc., but anyone encountering this problem for building a music player coudl fallback to this solution.

Perhaps the .createMediaElementSource could also be added to the Tone spec as an internal module, as maybe something like Tone.MediaPlayer or something, with the note that it's a lot more performant in terms of memory use than going through a buffer.

best regards

**Comment by tambien** [comment]
@Awendel thanks for the issue. I looked into it a bit and it turns out it's not caused by Player, but the static list of 'downloads' in ToneAudioBuffer. That list is never cleared once the file is downloaded making it get bigger and bigger as files are downloaded. 

Working on a fix now. Shouldn't be too complicated 🤞🏻

**Comment by jroyvde** [comment]
I'm experiencing this problem now with Tone 15.1.22. Calling .dispose() on my Player doesn't properly free any memory, so a nasty memory leak results.

**Comment by tambien** [comment]
@jroyvde do you have a way to reproduce this?
