### ISSUE TITLE
Add typings to package.json

### ISSUE THREAD

**Issue by hector** [Tonejs/Tone.js#623]
I had to add the typings to the package.json file so that typescript correctly picked them up.
I tried to to do a Pull Request but for some weird reason it doesn't allow me.
This are the changes: https://github.com/Tonejs/Tone.js/compare/13.8.25...hector:13.8.26

**Comment by tambien** [comment]
thanks for the issue. This should be taken care of on the `tone@next` version or on the `dev` branch.

**Comment by hector** [comment]
Indeed, I finally switched to tone@next for the moment.
There is already a "types" entry on the `package.json` which is working fine for me.

BTW, glad you moved to typescript, it is gonna help me so much :)
