### ISSUE TITLE
Transport + Players. Events go out of sync after 25-50 repetitions.

### ISSUE THREAD

**Issue by styk-tv** [Tonejs/Tone.js#626]
I'm layering 4 bar loops at 126.25bps (ogg with 6 decimal places of timing accuracy) at 320kbps so fairly light. After 25-50 iterations timing goes out of sync and eventually eliminates as much as a quarter note out of the loop. Inlcuding performance summary from Chrome representing structure of a single Task. I'm using React and not sure how you tested this (with loops) so might be a good opportunity to take a look as setup is in CodeSandbox. I'm attaching player in Track.jsx and using player object loop like this for every track.

https://codesandbox.io/s/github/MusicAsCode/set-player/tree/master/

```
    player.autostart = false;
    player.loop = true;
    player.loopStart = "0:0:0";
    player.loopEnd = "4:0:0";
    player.toMaster().sync();
    player.start();
```

This is quite a big Task structure that takes over 20ms to execute (this is from a still correctly audible iteration) Are they normally as complex or am I doing something wrong. Any recommendations?

<img width="2540" alt="Screenshot 2020-03-02 at 09 13 09" src="https://user-images.githubusercontent.com/838921/75661888-0e074b00-5c66-11ea-9c3d-4fdaff7aa616.png">

**Comment by tambien** [comment]
Seems related to [this issue](https://github.com/Tonejs/Tone.js/issues/540#issuecomment-528618747)

could you try upgrading to 13.8.27 and see if that fixes it for you?

**Comment by styk-tv** [comment]
@tambien Yotam, no change. After 3-5+ minutes (first quarter note missing starting at 0:1) it becomes audible and progressively worse (loosing time form the loop).  It seems to cut the beginning of the loop and start the iteration not at 0:0 but at 0:1 and then after few more minutes at 0:2

<img width="380" alt="Screenshot 2020-03-04 at 18 10 48" src="https://user-images.githubusercontent.com/838921/75909203-84ad6f80-5e43-11ea-8f51-afbe028a09c0.png">

**Comment by styk-tv** [comment]
tested with 3.8.34 and issue still remains. interesting fact is that this incremental start offset (issue) being added on every loop restart persists Tone.Stop() and Tone.Start() 

All digging points to conclusion that player settings are honoured:
```
    player.autostart = false;
    player.loop = true;
    player.loopStart = asset.posStart;
```

but transport settings especially start position is slowly shifting forwards, so it manifests with empty space then proper loop start, then loop cut off at the end repeat. in case of my example it takes 32 iterations to be audible. with tempo at 60/126.25bpm and loop at 4 bars = 7.603960396039604 per loop and audible at 243+ seconds

attaching paste of the transport beat positions. standard 4/4 signature 4 bars so 16 beats per iteration. you can see that scheduler seems to be doing a good job for a while, but after average above the error is so big that it jumps into the next quarter note and completely looses a beat.

this ubuntu pastebin is valid for a year until 2021-03-08, it represents 4 tracks (for same size loops) being played over and over, each one independently reporting its playback beat position.

https://paste.ubuntu.com/p/SywzwNmzwn/

**Progressively Shifting Transport Start 0:0:0 Position:**
```
Iteration 01 --> line 0004 --> Transport Beat Position: 0:0:0 
Iteration 02 --> line 0068 --> Transport Beat Position: 0:0:0.101
Iteration 03 --> line 0132 --> Transport Beat Position: 0:0:0.203
Iteration 04 --> line 0196 --> Transport Beat Position: 0:0:0.214
Iteration 05 --> line 0260 --> Transport Beat Position: 0:0:0.271
Iteration 06 --> line 0324 --> Transport Beat Position: 0:0:0.327
Iteration 07 --> line 0388 --> Transport Beat Position: 0:0:0.069 (seems schedule corrected)
Iteration 08 --> line 0452 --> Transport Beat Position: 0:0:0.171 (but then cycle repeats..)
..
..
Iteration 14 --> line 0836 --> Transport Beat Position: 0:0:0.33
..
..
Iteration 19 --> line 1156 --> Transport Beat Position: 0:0:0.388
Iteration 20 --> line 1220 --> Transport Beat Position: 0:0:0.489
..
..
Iteration 24 --> line 1476 --> Transport Beat Position: 0:0:0.58
..
..
Iteration 31 --> line 1924 --> Transport Beat Position: 0:0:0.616
..
..
Iteration 34 --> line 2116 --> Transport Beat Position: 0:0:0.83 (seems good recovery)
Iteration 35 --> line 2184 --> Transport Beat Position: 0:0:0.707 (but then slowly loosing the battle)
..
..
Iteration 39 --> line 2448 --> Transport Beat Position: 0:0:0.888
..
..
Iteration 41 --> line 2584 --> Transport Beat Position: 0:0:1.001 (and then unthinkable happens, we lost a full beat and loop is no longer 16 bars)
..
..
Iteration 45 --> line 2852 --> Transport Beat Position: 0:0:1.227 (keeps loosing time)
Iteration 54 --> line 3440 --> Transport Beat Position: 0:0:1.69 (keeps loosing time and eventually will loose another beat)
```
transport compensation lost the battle it seems

**Comment by styk-tv** [comment]
@tambien Yotam have you ever seen similar behaviour? I'm assuming asset types, browser version and system resources do not play a role here. Would you be able to replicate a simple loop player as above `.toMaster().sync()` to see if this occurs on a raw tonejs lib?

**Comment by tambien** [comment]
I haven't been able to replicate the issue yet. 

would it be possible to distill it down even further? i have seen something like this before where the TickSource calculations are susceptible to some floating point errors. It'd be really helpful to know if this is still an issue on `tone@next` where i tried to fix some floating point errors in timing calculations.

**Comment by styk-tv** [comment]
I am working to port this to 14+ ...

**Comment by styk-tv** [comment]
@tambien Yotam, 6am, I couldn't get the app to work, so i reduced to smallest possible setup for test, but it also doesn't play, probably missed something silly, would you mind taking a look to verify its as it should be? I didn't know how to iterate player in players so iterating assetList instead.

https://codesandbox.io/s/tonejs-next-loop-player-xfjmy

**Comment by tambien** [comment]
@styk-tv i tried to distill things down without the GUI: https://codesandbox.io/s/issue-626-47098

i think it's working ok, but let me know how it sounds to you.

**Comment by styk-tv** [comment]
@tambien Yotam, thank you for spending a bit of time on this, v14 seems improved but the changes are breaking my visualization so I will have to spend more time understanding why my code is breaking. CodeSandbox is great for quick demos, but not good to do any debugging of larger app. 

Actual issue described above seem to surface anymore in the row implementations (both yours and mine).

**Comment by eoghanmccarthy** [comment]
@styk-tv If this issue is still persisting it might be because you are setting state from within the Loop callback. I had a similar issue that I resolved by removing any state updates from within the callback. In React state updates are not instant so in this case they are causing issues.

```
var loop = new Tone.Loop(function(time) {
    // do something

    // removing the set state below might remove any timing lag
    setTracksPos(Tone.Transport.position.toString().split(".")[0]);
  }, "4n").start(0);
```
Also if you use Tone.Sequence instead you can keep track of the current step by using the second argument.

```
useEffect(() => {
    new Tone.Sequence((time, step) => {
        // do something

        console.log(step)
      },
      [0, 1, 2, 3], "4n"
    ).start(0);
  }, []);
```

**Comment by styk-tv** [comment]
Thank you @eoghanmccarthy, I will explore both examples immediately. I was blown away to discover how complex/expensive those events are (as per first picture). Funny how visual tiny delays are not bothering us as much but someone plays a loop with a 10ms delay and we're twisted in horror.

**Comment by eoghanmccarthy** [comment]
@styk-tv Agree, React state updates fall apart when such precision is needed. It's bizarre that React has no true synchronous state updater.

**Comment by tambien** [comment]
@styk-tv Do @eoghanmccarthy's suggestions resolve this issue?

**Comment by styk-tv** [comment]
@tambien Yotam, I will close this as tone@next seems to behave differently. For me personally issue cannot be replicated with 14+

Anyone feels different, please re-open. Thanks for all the help and assistance.

**Comment by eoghanmccarthy** [comment]
Just to draw a conclusion under my experiments on this. In the end to achieve consistent Sequence timing in a React app the solution for me was to not use component state, context, Redux etc to store updated values during playback. I store all values as data attributes on dom nodes or by adding / removing css classes. Results are much improved on any attempts I made using state. [http://theseboys.com/studio](http://theseboys.com/studio)

**Comment by MaartenBreeedveld** [comment]
@eoghanmccarthy:
I'm experiencing a similar problem, but only on iOS and mostly on safari
Also, I'm working with React. Unfortunately I'm relying quite a bit on state updates.
So, are you suggesting to store your state in data attributes? I guess it's an option since your app seems to work on iOS with Chrome

Unfortunately I'm unable to check out your page on safari. the page displays 'something wrong'. I've noticed that the StereoPanner class is unavailable on iOS so it may break there?

**Comment by Johnrobmiller** [comment]
I'm replicating this in my own project, the bug still remains and might be dependent on other factors such as performance/lag
