### ISSUE TITLE
Tone.Buffer error when loading from file:///

### ISSUE THREAD

**Issue by llaske** [Tonejs/Tone.js#628]
An error occur when trying to load a sound file from `file:///` thought the file is correctly load.

Step to reproduce:
* Clone the sample [here](https://github.com/llaske/tonejstest)
* Launch Chrome with the `--allow-file-access-from-files` to authorize XmlHttpRequest on local files
* Open the `index.html` file in Chrome
* Click on the `load tone` button to initialize Audio Context
* Click on the `play sound` button to play sound

The same sample exposed on a web server works, like you could see on the short video below:

![2020-03-11 17-56-49 2020-03-11 18_01_23](https://user-images.githubusercontent.com/981841/76443334-8ab2cb80-63c2-11ea-9081-896d41e1a0b9.gif)

**Comment by tambien** [comment]
The latest version of Tone has moved from XHR to `fetch`, which i think will complicate loading local files even more since there seems to be more explicit restriction on it. Even with the command line flag --allow-file-access-from-files, `fetch("file://path/to/cow.mp3")` returns this error: `URL scheme "file" is not supported.`

I wonder if there is a simple work around to what you're doing by using the FileReader API? or if creating a local server an option in your situation? That is at least how these things are meant to work.

**Comment by llaske** [comment]
Thanks for your answer.
Yes you're right if `fetch` is call internally, it can't work with, loading local file works only with XHR.

I can't create a local server in my context.
Is there a way to initialize the `Tone.Buffer` from the outside: i.e. loading myself the file using XHR then pass the content to the `Tone.Buffer` as an array or a blob object?

**Comment by tambien** [comment]
if you can get the file as a blob, then you should be able to create a blob URL from that, which can be loaded with XHR or fetch

**Comment by llaske** [comment]
Good shot!
Replacing file URL by a blob solve the issue.
See my change below.

Before:

```
function play() {
	console.log('pressed');
	var player = new Tone.Player();
	var pitchShift = new Tone.PitchShift({pitch: 2});
	player.load("cow.mp3");
	pitchShift.toMaster();
	player.connect(pitchShift);
	player.autostart = true;
}
```

After:

```
function play() {
	var xhr = new XMLHttpRequest();
	xhr.open("GET", "cow.mp3", true);
	xhr.responseType = 'blob';
	xhr.onload = function(){
		var blob = URL.createObjectURL(this.response);
		console.log('pressed');
		var player = new Tone.Player();
		var pitchShift = new Tone.PitchShift({pitch: 2});
		player.load(blob);
		pitchShift.toMaster();
		player.connect(pitchShift);
		player.autostart = true;
	};
	xhr.send();
}
```

Thanks for your help.

**Comment by tambien** [comment]
wonderful! glad you were able to find a resolution to this. this seems like a good workaround, i'm going to close this issue.

**Comment by manuelnelson** [comment]
@tambien Is there a similar way I could use a local file for the Tonejs Sampler?  I'm not able to use a blob for each note since the Sampler requires a BaseURL and SampleMap to load the files.

**Comment by gregston8** [comment]
Any luck with a workaround for the tonejs sampler manuelnelson? At the moment it seems I won't be able to use it in my Cordova Android app.
Thanks

**Comment by gregston8** [comment]
I managed to get the Tone.js sampler working using XMLHttpRequest, thanks to the above answers. My version just uses 8 samples and lets the sampler map them over the 88 notes. First I get my blobs and make them global so they can be found in the callbacks:

```
 for (var octave = 0; octave <= 7; octave++) {
        
	var xhr = new XMLHttpRequest();

        xhr.open("GET", "C" + octave + ".mp3", true);
        xhr.responseType = 'blob';
        xhr.oct = octave;
        
        xhr.onload = function () {
            window['blob' + this.oct] = URL.createObjectURL(this.response);
        };
      
        xhr.send();
 }
```

Then the first time a note is played:
   ```
   {
 const now = Tone.now();
 
	if (sampler == null) {
            sampler = new Tone.Sampler({
            urls: {
                "C1": blob1,
              [ .........]
                "C7": blob7,
            },
            release: 1,
            onload: () => {
                 sampler.triggerAttack(theNote, now);
            }
        }).toDestination();
      }
else
    sampler.triggerAttack(theNote, now);
}
```

Not sure if this is the best way but it works for now.
