### ISSUE TITLE
Broken Documentation

### ISSUE THREAD

**Issue by fantasyui-com** [Tonejs/Tone.js#632]
https://tonejs.github.io/docs/Sampler returns "404 page not found"
![bug](https://user-images.githubusercontent.com/22273943/77562311-3c0f3200-6e96-11ea-8f58-94c1f466fa84.png)

**Comment by tambien** [comment]
Do you have javascript enabled? I used a really simple javascript redirect to forward users to the latest page. So when i open that page, i see that for a moment before it forwards to: https://tonejs.github.io/docs/13.8.25/Sampler

**Comment by fantasyui-com** [comment]
Thank You, that solves my problem. If you ever have time maybe add a link directly to the doc so we can click on it, but this is not that important.

**Comment by tambien** [comment]
Glad that works for you now!

In issues, i typically link to a specific version of the documentation, but the advantage of the redirect is that all of the pages point to an updated version when i release a new version. 

Eventually i'll try to move things to a server-side redirect so people won't have this issue
