### ISSUE TITLE
Synchronise with video

### ISSUE THREAD

**Issue by hector** [Tonejs/Tone.js#633]
First, let me apologise in case this question doesn't belong here.

I am using Tone.js to play different audios in sync. Works like a charm.
Now, I would like to also add a video. Do you know of any way of synchronising it?

**Comment by tambien** [comment]
The HTMLVideoElement doesn't enable the same level of synchronization as Web Audio, but i think using the `schedule` callbacks from the Transport should give you approximate synchronization that is hopefully close enough for your needs. 

Hope that helps!

**Comment by hector** [comment]
Thanks for the answer.
The problem with this approach is that they might get unsynced while playing.

I know this doesn't belong here but in case somebody needs it. This is what I have done:
Use video.js library to support HLS format. Then you need to include all your audios and video in the HLS format (I am encoding them with ffmpeg). Sadly, tone.js is out of the equation then.
