### ISSUE TITLE
Not sure if this is possible

### ISSUE THREAD

**Issue by kyoukhana** [Tonejs/Tone.js#634]
When using .Players and adding a track using multiPlayer.add.  How can I get the percentage of the track being loaded from 0%-100%

**Comment by tambien** [comment]
under the hood samples are loaded with the `fetch` API which does not provide any progress indication, so it's not currently possible

**Comment by kyoukhana** [comment]
Lets say you have 5 tracks in a JSON object.  Can you add a loading then loaded after that once each track is loaded.  Keep it simple for now.  Just getting some ideas how to tackle this
