### ISSUE TITLE
[QUESTION] - ToneJs with WebAudioApi (standalone)

### ISSUE THREAD

**Issue by styk-tv** [Tonejs/Tone.js#635]
Has anyone considered experiments with ToneJs set directly against a WebAudioApi implementation without a browser? Is there one in existence? (with or without js interpreter) and to what extent they can be married?

```
      +----------+
      |  ToneJS  |
      |          |
      +----------+

     +------------+
     | JavaScript |
     |  Engine    |
     +------------+

     +-------------+
     | JavaScript  |
     | Interpreter |
     +-------------+

+------------------------+
| WebAudioApi            |
| Sandalone (no browser) |
+------------------------+
```

**Comment by tambien** [comment]
Currently there is no Web Audio API implementation that i know of outside the browser. I've had some luck with using headless chrome (puppeteer) to play sounds without a GUI from Node.js. 

If there were a Node.js implementation of the Web Audio API, it should be possible to work with Tone.js.
