### ISSUE TITLE
Make node.chain accept an array?

### ISSUE THREAD

**Issue by sandcobainer** [Tonejs/Tone.js#638]
Pretty simple request or looking for potential workarounds if possible?

I want to pass in array of audio nodes to node.chain and be able to shuffle these effects or perform other operations. I was hoping to set up an array and pass it to chain so it can be updated at each measure of music. 
```
var array = [lowpass, highpass, reverb, compressor, Tone.Master];
// use array.push, pop, shift shuffle etc.
sampleNode.chain(array);
```
The current `node.chain (panVol, compressor, Tone.Master)` is simple and easy to read but does not allow the above usage.

**Comment by pendragon-andyh** [comment]
I am away from my computer at the moment, but you should be able to use `sampleNode.chain.apply(null, array)`. The apply method is normal JavaScript. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply for details.

**Comment by tambien** [comment]
I'd also add if you're using es6 (or typescript) you can turn your array into arguments using the 'rest' parameters. 

So the call to chain might look like this: 
```typescript
Tone.chain(...arrayOfNodes)
```

**Comment by sandcobainer** [comment]
Thank you, the ES6 rest operator is what I was looking for!
