### ISSUE TITLE
Can't play on desired device

### ISSUE THREAD

**Issue by oxygen** [Tonejs/Tone.js#639]
```JavaScript
		const elAudio = document.createElement("audio");
		window.document.body.appendChild(elAudio);

		const audioContext = new window.AudioContext();
		
		const mediaStream = audioContext.createMediaElementSource(elAudio);

		const gainNode = audioContext.createGain();

		mediaStream.connect(gainNode);

		Tone.context = audioContext;

		const oscillator = new Tone.Oscillator(440, "sine");
		
		// Use the Tone.connect() helper to connect native AudioNodes with the nodes provided by Tone.js
		Tone.connect(gainNode, oscillator);
		Tone.connect(this._oscillator, audioContext.destination);

		// Shows a big hash which corresponds to the desired speakers (not main/default audio).
		console.log(this._elSelectAudioOutput.value);
		await elAudio.setSinkId(this._elSelectAudioOutput.value);

		elAudio.play();
		this._oscillator.start();
```

What am I doing wrong?
No matter what I tried, I ended up playing on the default speakers, which is not what I want to achieve.

**Comment by tambien** [comment]
I'm not aware of a way to play audio out of an audio device which is not the default device using the Web Audio API. 

This seems to be part of the discussion for the second version of the API 

WebAudio/web-audio-api-v2#10

**Comment by wegylexy** [comment]
@oxygen you created a source node from the audio element, and ultimately connected it to the default destination where the sound sank, so it never reached back the audio element which you set another sink.

**Comment by oxygen** [comment]
```JavaScript
		// Shows a big hash which corresponds to the desired speakers (not main/default audio).
		console.log(this._elSelectAudioOutput.value);
		await elAudio.setSinkId(this._elSelectAudioOutput.value);
```
The sink ID from the select was not the default audio, but a specific device. That's why I left this comment.

Is this what you meant?

**Comment by wegylexy** [comment]
No, the srcObj is not set to the stream of a destination node in the audio context, but its output is connected to another node in the context that could not be connected. In short, you only connected the oscillator to the default destination.

**Comment by wegylexy** [comment]
@oxygen See [https://github.com/wegylexy/rnnoise_wasm/blob/master/demo/rnnoise.js](https://github.com/wegylexy/rnnoise_wasm/blob/5f05535a0028780513822a5d9153a36bddd69ac8/demo/rnnoise.js#L42-L52)

Demo: https://rnnoise.timtim.hk/demo/

**Comment by EMazzaglia** [comment]
@wegylexy Hi! that demo is not working properly actually, if you switch your audio output device, it continues playing the sound from the default speakers.

**Comment by wegylexy** [comment]
@EMazzaglia Looks like I need to set the sink after setting the source instead. Maybe a recent Chrome update.
