### ISSUE TITLE
Adding a delay between each player loop

### ISSUE THREAD

**Issue by davidstellini** [Tonejs/Tone.js#640]
Hi,

First of all thank you for a great library!
I have a question - not sure if it's supported, but I couldn't find this in the docs.

I'm trying to play a loop from a file. But after each loop, I'd like to introduce a delay (before starting the next loop).

```
new Tone.Player({
  url: buffer,
  loop: true,
  autostart: true,
  loopStart: 10,
  loopEnd: 20,
  fadeIn: 1,
  fadeOut: 1
})

```

It's not entirely clear what "Delay" does in the docs, or how to use it - I can't find any examples.
I tried something like this with no luck.

```
const delay = new Tone.Delay(1);
new Tone.Player({
  url: buffer,
  loop: true,
  autostart: true,
  loopStart: 10,
  loopEnd: 20,
  fadeIn: 1,
  fadeOut: 1
})
.connect(delay)
.toDestination()
```

Do you have any ideas? :)

**Comment by tambien** [comment]
Hi @davidstellini Sounds like what you're looking for is a pause after the loop has ended and before the next loop begins. Delay is going to add a delay the entire output of Player (not just the end). 

The simplest solution would be to just extend the buffer. You do this in a DAW or use Tone.js to do this. The `Tone.Buffer.slice` method typically grabs a subsection of a buffer, but you can also extend the end with it. If you want to add 5 seconds of silence to the end of the buffer `player.buffer = player.buffer.slice(0, player.buffer.duration + 5)`

Another option would be to use Tone.Loop to retrigger the start of the Tone.Player at the loop duration that you'd like.
