### ISSUE TITLE
Panner not functioning correctly - Audio still when panned hard to one side

### ISSUE THREAD

**Issue by kwhohasamullet** [Tonejs/Tone.js#641]
Hi All,

Am working on a project that is making use of the Panner Component and am finding on some devices that with the panner set to either hard left or hard right (set to 1 or -1) there is still audio in the opposite channel. In the example of the panner being turned hard left the audio is still present in the right channel, it is the same as what is in the left channel but considerably quieter. 

I have tested this on a number of devices with two different set of headphones
**Working as expected**
PC (Win 10) with USB DAC (Focusrite 2i4)
**Displaying issue**
- PC (Same as before) - Realtek intergrated sound card
- Android phone (Pixel 4)
- iPad Air 2 (Latest Update)

**Examples**
The issue is occurring on the following
https://tonejs.github.io/examples/mixer.html
https://codepen.io/kwhohasamullet/pen/pojojVo?editors=1111
It is also present in a mozilla demo using the direct WebAudio API so this may be an issue deeper than this library?
https://mdn.github.io/webaudio-examples/stereo-panner-node/

Let me know if you need anything further

Cheers

kwhohasamullet

**Comment by tambien** [comment]
Thanks for the question @kwhohasamullet 

If it's happening on the raw web audio example and different across hardware, it's not something that i'd be able to fix in Tone.js. Seems like a hardware limitation especially since the same PC behaves differently depending on the audio card. 

Does the same bleed happen if you apply stereo panning using Audacity or a native software on your PC?

**Comment by ChristofferGylin** [comment]
I am having similar issues with pan not working properly.

I have a mixer built up where instrument channels feeds in to a master channel, and the master channel is sent toDestination.

The pan works on the master channel, but not on the instrument channels. 

The only difference between the two are that the master is connected using toDestination on creation, like this:

let masterOutput = new Tone.Channel(0, 0).toDestination();

and the instrument channels are connected using connect, like this:

let instrumentChannel = new Tone.Channel(0, 0);
instrumentChannel.connect(masterOutput);

Do I have to manually split the stereo signal when connecting channels together? How do I do that?
I did manage to get my vu-meter working correctly with left and right using split, but I can´t figure out how to connect the split signal into the masterOutput on separate channels (I get an error when I try to connect to input 1 that doesn´t exist).

**Comment by ChristofferGylin** [comment]
Since the vu-meter works for the instrument channels, my guess is that the instrumentChannels output is summed to mono before going into the masterOutput.

**Comment by dkovach** [comment]
Did this ever get solved or was it an actual issue or known problem? I hit a wall having sampler ---> pan ---> channel work... the channel pan does it overall. But the sampler or multiple samplers pan component wont pan. Followed the connect docs and I think I tried chain too, but nothing works. If I do sampler ---> pan ---> destination, they pan...

I will start a new issue given the OP's situation might not have been what was discussed in the thread e.g. similar to my situations, use, issue...

**Comment by tambien** [comment]
@dkovach Interesting, might be worth creating a new issue with a repro and we can try to debug it from there

**Comment by DDtMM** [comment]
I have a similar issue.  In my case I have an **inner** channel that connects to a **master** channel.  

* If I set a hard pan on the **master** channel it works as I expect.
* If I set a hard pan on the **inner** channel then 
  * the meter I attach to the **inner** channel shows as panned (only one side has values)
  * The audio output is not panned.
  * The *master* channel meter presents as though it was not panned.
* If I set `channelCount` explicitly to _2_ when creating the **inner** channel then...
  * The sound is much louder.
  * It sounds partially panned.
  * The *master* meter appears partially panned.
