### ISSUE TITLE
PulseOscillator is fundamentally broken

### ISSUE THREAD

**Issue by Powerlated** [Tonejs/Tone.js#642]
I've been making a Game Boy emulator with Tone.js for sound output, and I've always wondered why it just *didn't* sound right.  Turns out, the issue was the PulseOscillator implementation.

The fix is to use a triangle wave instead of sawtooth for the input wave, and then the resulting Square wave will sound correct at all pulse widths.

Pull Request: #643

**Comment by tambien** [comment]
Thanks for the PR! Merged #643
