### ISSUE TITLE
scheduleRepeat stops randomly with low updateInterval

### ISSUE THREAD

**Issue by Hannessa** [Tonejs/Tone.js#645]
Hi! Thanks for a great library. I noticed that Tone.Transport.scheduleRepeat (or Tone.Loop) stops looping at random times when Tone.context.updateInterval is low, and never resumes on its own. For me it happens at around updateInterval < 0.03, or when using Tone.context.latencyHint = "fastest".

For example, in one case I had a "4n" scheduleRepeat which played a Player clip (metronome sound), and it would always stop at beat 37. Everything else was running, but that specific loop would just stop repeating (other loops would continue playing, or stop later, and Tone.Transport.state was still "started"). I've also had it stop at other timings as well, e.g. 74 or after just after a few beats.

Here's a jsfiddle that kind of recreates it, although sometimes it just seems to work. And sometimes it stops after just a few beats or after a minute. Might require a few tries and page reloads.
https://jsfiddle.net/8xfnt17e/

This makes it feel very risky to use loops as I don't know if I can trust them to work consistently across devices, even if I set updateInterval higher. It also makes it hard to optimize for latency, if it increases the risk for loops not working at all.

I can understand why audio can crackle without buffers and that the timings are imprecise in JavaScript, but I can't wrap my head around why a loop would just stop running. If a precise timing is missed, shouldn't it just be called on the next tick, rather than being completely left out?

I'm running Chrome on Windows 10 on a new desktop PC.

**Comment by tambien** [comment]
Seems like it might be a floating point rounding issue with the times. Potentially related to #540 

Are you still getting this issue if you use `tone@next`?

**Comment by Hannessa** [comment]
Thanks for responding. I just tested with https://unpkg.com/tone@next and I seem to be getting the same issue. Actually now I got it even without changing updateInterval or latencyHint, just using the default values (latencyHint="interactive", updateInterval=0.05, lookAhead=0.1).

Here's an updated jsfiddle with tone@next that gives me this issue:
https://jsfiddle.net/pgz7dwLj/1/

**Comment by tambien** [comment]
Thanks for the test case. it does seem like it's a floating point issue, i just pushed a fix which i think should solve this. A new version should be deployed in the next 10 minutes or so that contains the fix. I'll test it against your example to confirm once it's published.

**Comment by Hannessa** [comment]
Thanks a lot for the quick fix! Works great now with tone@next.

**Comment by gvido** [comment]
Just dropping by to say thanks for the awesome library! It's saving me a ridiculous amount of time on a personal project I've been hacking on the past month.
I was also running into similar issues as the ticket, and I can confirm that upgrading to tone@next made things work super smooth! <3
