### ISSUE TITLE
Tone.Transport does not start with bluetooth on

### ISSUE THREAD

**Issue by stephaneeybert** [Tonejs/Tone.js#646]
When using my Android phone I can start the Tone.Transport and hear sounds all right:
```
  private startTransport() {
    Tone.Transport.stop();
    Tone.Transport.start(TRANSPORT_START_DELAY);
  }

```
on my oscillator:
```
    const synth: any = new Tone.PolySynth(1, Tone.Synth, {
      oscillator: {
        type: 'sine',
      }
    }).toMaster();

```
But when I switch on the bluetooth the Tone.Transport will not start.

This occurs on a Huawei 20 Lite and a Nokia 7.2 Android phones on the Chrome browsers.

Using the same browser on the same phone, I can play and hear a YouTube video (in Chrome) on the bluetooth device all right.

My application is at:
https://stephaneeybert.github.io/stephaneeybert/musicng/

I tried the test page at: 
https://googlechrome.github.io/samples/webaudio-suspend-resume/index.html
and it worked fine when the bluetooth device was paired to the phone.

And its dependencies are:
```
"tone": "^13.8.25",
"@tonejs/midi": "^2.0.20",

```

UPDATE: From my phone, I could hear the following Tone.js blitz on my paired bluetooth device:
https://stackblitz.com/edit/angular-tone
so I suppose the issue lies within my Angular implementation.

UPDATE: When running the app on the phone with the remote debugger and seeing console log statements, I can see that switching off the bluetooth on the phone immediately makes the following assertion true: `Tone.Transport.state == 'started'`
Now, if switching on the bluetooth on the phone and then reloading the application web page then the `Tone.Transport.state` remains at `stopped` even when checking it every second.

**Comment by stephaneeybert** [comment]
I tried to again start the transport if the check stated it was not started:
```
  private startTransport() {
    Tone.Transport.stop();
    Tone.Transport.start(TRANSPORT_START_DELAY);
  }

  private stopTransport() {
    Tone.Transport.stop();
  }

  public synthTransportIsStarted$(): Observable<boolean> {
    return interval(1000)
      .pipe(
        map((value: number) => {
          const isStarted: boolean = this.transportIsStarted();
          if (!isStarted) {
            this.stopTransport();
            this.startTransport();
          }
          return isStarted;
        }),
        filter((isStarted: boolean) => isStarted),
        take(1)
      );
  }

  private transportIsStarted(): boolean {
    return Tone.Transport.state == TRANSPORT_STATE_STARTED;
  }

```
I enabled the bluetooth on the phone and reloaded the page to see if the transport would start. I did it more than 5 times and it started only once.

**Comment by tambien** [comment]
This sounds like an autoplay issue to me. Make sure you call `Tone.start()` on a button click before starting the Transport or trying to play any other sounds. My guess is that the AudioContext is suspended still which is why you're getting this behavior. 

You can check the state of the AudioContext to see if it is in fact suspended by logging `Tone.context.state`. That should equal `"running"` if your AudioContext is ready to play sound

**Comment by stephaneeybert** [comment]
All right. Now I start the transport after a user interface event.

It's strange that I would only see the issue when the bluetooth speaker was paired with the phone.

**Comment by tambien** [comment]
Did that fix it? Maybe it's possible that browsers add more strict autoplay controls when going over bluetooth?

**Comment by stephaneeybert** [comment]
By starting the transport when pushing the Play button I avoided the issue altogether.

I still feel like I would have preferred to start the transport at page load time, if only with a time lag, like I did. It work great on the computer and on the phone. Except when the JBL speaker was paired to the phone, in which case the transport was not starting.

**Comment by tambien** [comment]
I tried to summarize the solution in [this wiki article](https://github.com/Tonejs/Tone.js/wiki/Autoplay)

Autoplay is inconsistent in how its implemented across browsers and scenarios, the only consistent solution is to start playing only after a click or user gesture.
