### ISSUE TITLE
when playing a "chord" certain notes "stick"

### ISSUE THREAD

**Issue by adrizos** [Tonejs/Tone.js#647]
Im sending a group of notes (one of the 3 below) and for some reason, something with one of these "chords" is causing a note to "stick" and not stop playing. Other groups of notes dont have this issue. Any ideas?

`  0 : ['G', 'C', 'E', 'G', 'B','G', 'C', 'E', 'G', 'B', 'G', 'C'],
    1 : ['A', 'D', 'F#', 'G', 'B', 'A', 'D', 'F#', 'G', 'B', 'A', 'D'],
    2 : ['A', 'E', 'A', 'B', 'E', 'A', 'E', 'A', 'B', 'E', 'A', 'E'],
`

Calling the synth as below:

` Tone.context.resume(); // needed to address auto play of audio browser issues without user interaction
                polySynth = new Tone.PolySynth(chord.length,Tone.AMSynth).connect(phaser).toMaster();
                polySynth.set(AudioDefaults.AMSYNTH_DEFAULTS);
                polySynth.triggerAttackRelease(chord, '8n');`

**Comment by adrizos** [comment]
Im just repeating the first 5 notes in the above arrays FYI.

**Comment by tambien** [comment]
is it possible to create a minimal jsfiddle example which illustrates your issue?

**Comment by adrizos** [comment]
I couldn't get it to work in JSFiddle for some reason but here is the general idea:

`const Tone = require('tone');
let chords = {
    1: ["C4", "G2", "C2"],
    2: ["E4", "G2", "C2"],
    3: ["C4", "E4", "G2", "C2"],
    4: ["G4", "B4", "G2", "C2"],
    5: ["G4", "B4", "G2", "C2"],
    6: ["G2", "C2"],
    7: ["G2", "C2"],
    8: ["G4", "B4", "E3", "G3", "G2", "C2"],
    9: ["G4", "B4", "G3", "C3", "E3", "G3", "G2", "C2"],
    10: ["B4", "E3", "G2", "C2"],
    11: ["B4", "E3", "G2", "C2"],
    12: ["G4", "B4", "G3", "C3", "E3", "G3", "G2", "C2"],
    13: ["G4", "B4", "E3", "G3", "G2", "C2"],
    14: ["G2", "C2"],
    15: ["G2", "C2"],
    16: ["B2", "G2", "C2"],
    17: ["B4", "G2", "C2"],
    18: ["G4", "B4", "G3", "G2", "C2"],
    19: ["G4", "G2", "C2"],
    20: ["G2", "C2"],
    21: ["G2", "C2"],
}

let counter = 1;
setInterval(() => {
  var polySynth = new Tone.PolySynth(chords[counter%21].length, Tone.AMSynth).toMaster();
  polySynth.triggerAttachRelease(chords[counter], '8n');
  counter+=1;
}, 1000);
`

**Comment by adrizos** [comment]
Here is the general idea: 

```const Tone = require('tone');
let chords = {
    1: ["C4", "G2", "C2"],
    2: ["E4", "G2", "C2"],
    3: ["C4", "E4", "G2", "C2"],
    4: ["G4", "B4", "G2", "C2"],
    5: ["G4", "B4", "G2", "C2"],
    6: ["G2", "C2"],
    7: ["G2", "C2"],
    8: ["G4", "B4", "E3", "G3", "G2", "C2"],
    9: ["G4", "B4", "G3", "C3", "E3", "G3", "G2", "C2"],
    10: ["B4", "E3", "G2", "C2"],
    11: ["B4", "E3", "G2", "C2"],
    12: ["G4", "B4", "G3", "C3", "E3", "G3", "G2", "C2"],
    13: ["G4", "B4", "E3", "G3", "G2", "C2"],
    14: ["G2", "C2"],
    15: ["G2", "C2"],
    16: ["B2", "G2", "C2"],
    17: ["B4", "G2", "C2"],
    18: ["G4", "B4", "G3", "G2", "C2"],
    19: ["G4", "G2", "C2"],
    20: ["G2", "C2"],
    21: ["G2", "C2"],
}

let counter = 1;
setInterval(() => {
  var polySynth = new Tone.PolySynth(chords[counter%21].length, Tone.AMSynth).toMaster();
  polySynth.triggerAttackRelease(chords[counter%21], '8n');
  counter+=1;
}, 1000);
```

**Comment by tambien** [comment]
This should be fixed in `tone@next`. There's a very small API change to the PolySynth that it no longer requires the polyphony count. 

https://jsfiddle.net/yotammann/v3oupaqk/1/

**Comment by adrizos** [comment]
How do I address this using the traditional NPM install?  Im using this in a react app. 

Calling it with es6 styling: 
```import * as Tone from "tone";```

**Comment by tambien** [comment]
`npm install tone@next` and that import statement should still work.

**Comment by adrizos** [comment]
So after installing this version of Tone, and removing the array length argument, the sticking notes issue goes away! However, in Chrome now it seems to run much slower and after a few seconds all the audio gets cracky and then just stops playing. In Firefox it stutters out almost immediately. Safari has more similar results to Chrome. Im using a 2019 MBP, Catalina and the newest versions of all three browsers.

**Comment by adrizos** [comment]
Update: In my app Im playing several chords per second. It appears that if I slow down the interval to even 500ms it seems to work much better in Chrome. The same interval in Firefox actually plays for 20 seconds or so now (which it never did before) but still fizzles out and drops the audio. Ive sort of recreated the issue as well in the jsfiddle example you posted above by lessening the interval done from a full second per chord where it when loaded.

**Comment by tambien** [comment]
Sorry i had an issue in the code where it was creating a new PolySynth in each update which will end up creating hundreds of PolySynths after about 20 seconds. 

I fixed that issue https://jsfiddle.net/yotammann/v3oupaqk/

**Comment by adrizos** [comment]
Thanks! I was going to say it always happened like 15-20 seconds in even with note randomization.
