### ISSUE TITLE
Have some sync issue when scheduling several Sequence(s)

### ISSUE THREAD

**Issue by chaosprint** [Tonejs/Tone.js#648]
https://jsfiddle.net/chaosprint/s3r9uz7g/

```
var synth = new Tone.MonoSynth().toMaster()

var synth2 = new Tone.PluckSynth().toMaster()

var bd = new Tone.MembraneSynth().toMaster()

var kick = new Tone.Sequence( (time, note) => {
	console.log("kick progress:", kick.progress)
	  console.log("lead.progress", lead.progress)
	  console.log("lead2 progress:", lead2.progress)
    console.log("----")
	bd.triggerAttackRelease(note, "16n", time)
	}, ["c2"], "1m")
	
	
	var lead = new Tone.Sequence( (time, note) => {
	synth.triggerAttackRelease(note, "16n", time)
	  
	}, [20, 22, 24, 25, 27, 29, 31, 32].map(x=>Tone.Midi(x)), "16n")

var lead2 = new Tone.Sequence( (time, note) => {
	synth2.triggerAttackRelease(note, "16n", time)
}, [20, 22, 24, 25, 27, 29, 31, 32].map(x=>x+12).map(x=>Tone.Midi(x)), "16n")

Tone.Transport.start()

kick.start()
kick.stop("12m")

lead.start()
lead.stop("4m")

lead2.start("4m")
lead2.stop("8m")

lead.start("8m")
lead.stop("12m")
```

The ```progress``` shown in the console seems to be different every time and it seems to be too large.

**Comment by tambien** [comment]
@chaosprint Is the audio out of sync or just the `progress` reporting?

**Comment by chaosprint** [comment]
> @chaosprint Is the audio out of sync or just the `progress` reporting?

In my application, I have several ```Sequence``` playing together.

I try to add one new ```Sequence``` as follows:

```
// First, calculate the current position:
const nextBar = () => {
    let pos = Tone.Transport.position.split(":")
    pos[0] = (parseInt(pos[0]) + 1).toString()
    pos[1] = "0"
    pos[2] = "0"
    pos = pos.join(":")
    return pos
}
```

```
// Then I add the ```Sequence```
new_seq.start(nextBar())
```

Often they are out of sync, especially when there are many ```Sequence```.

So I tried to use this ```progress``` log to see what's the problem and report here.

**Comment by tambien** [comment]
`progress` is just an approximation of where the sequence is at the time of reading the value, so i wouldn't necessarily use it as the source of truth for progress. 

My guess as to why things might be getting out of sync with your example is that you don't explicitly start the sequences at time 0 when you invoke `kick.start()` with no arguments. Without any time argument, the sequence will start from the current Transport's position which might have progressed to a time greater than 0 by the time you invoke that function. 

Try adding a start time to each of your sequence `start` methods and see if that helps with the sync issue. (e.g. `kick.start(0)` and `lead.start(0)`)
