### ISSUE TITLE
polySynth notes are no longer synced in tone/next / memory issue

### ISSUE THREAD

**Issue by adrizos** [Tonejs/Tone.js#650]
Hi, 

Creating a new issue stemming from previous (https://github.com/Tonejs/Tone.js/issues/647).

1. Im noticing that when triggering chords the notes are not playing at the same time with extremely noticeable lag. This is evident in both your last jsfiddle example in the above linked issue as well as in my application. I uninstalled tone and reinstalled to the most current next version.

2. It appears the previous object creation issue is happening as well. This time after like 30-40 seconds the audio fizzles out and stops playing like before. 

Thanks!

**Comment by tambien** [comment]
Could you link to a way to reproduce this issue?

PolySynth is definitely going to work better if you schedule events (using Tone.schedule/scheduleRepeat) instead of invoking them to play immediately like in the jsfiddle

Here's an example of what i mean: https://jsfiddle.net/yotammann/v3oupaqk/7/

**Comment by adrizos** [comment]
I was having some trouble creating a version in JSFiddle. Here is a simplified version of the function I call that plays audio. This function gets called many times. 

```
    playAudio = async () => {
        const { cellMap } = this.state;
        const newCellMap = JSON.parse(JSON.stringify(cellMap));;
        let chord, octave;
        const polySynth = new Tone.PolySynth(Tone.AMSynth).toMaster();

        // iterate by column
        for (let c = 0; c < GRID_WIDTH; c++) {
            chord = []; // reset chord at start of each column
            // iterate over cells in this column to make active, build a chord array
            for(let r = 0; r < GRID_HEIGHT; r++) {
                // check if cell is alive
                if (cellMap[`${r}-${c}`].alive === true) {
                    // change temp cell to active for UI class which will be added to main cell map below
                    newCellMap[`${r}-${c}`].active = true;
                    // set note ocatve based on position in the grid
                    octave = (r >= GRID_HEIGHT*.67) ? '2' : (r >= GRID_HEIGHT*.34) ? '3' : '4';
                    // add our note to the chord array to be played later
                    chord.push(this.scale[r]+ octave);
                } else if (cellMap[`${r}-${c}`].alive === false ) {
                    // turn on class for UI to display that the current column is "being looked at"
                    newCellMap[`${r}-${c}`].activeColumn = true;
                }
            }
            // swap grids and update the UI to show the active cells
            this.setState({ cellMap: newCellMap });
            // play the chord if there are active cells in this column and we have chord data
            if (chord.length > 0) {
                Tone.context.resume(); // needed to address auto play of audio browser issues without user interaction
                //polySynth.set(AudioDefaults.AMSYNTH_DEFAULTS); // add custom synth settings
                polySynth.triggerAttackRelease(chord, '8n');
                await this.wait(100); // pause before making cells visibly "inactive"
                //iterate over the column again to make cells inactive
                for(let r = 0; r < GRID_HEIGHT; r++) {
                    newCellMap[`${r}-${c}`].active = false;
                    newCellMap[`${r}-${c}`].activeColumn = false;
                }
                // swap grids and update the UI to show the inactive cells again
                this.setState({ cellMap: newCellMap });
            }
            // change chord/notes after each traversal of the grid
            if (c === Constants.GRID_WIDTH-1) {
                //increment notesCounter
                this.notesCounter = (this.notesCounter+1)%3; // we circle back over the 3 chords
                this.scale = Notes[this.notesCounter];
            }
            await this.wait(115); // wait before moving to next column
        }
```

**Comment by tambien** [comment]
If `playAudio` is being called many times, looks like you are going to be creating a lot of PolySynth objects. PolySynth is meant to be reused since the underlying audio graph is not disposed unless you call `polySynth.dispose()`. so better to hoist the synth outside of the function so that it can be reused. Otherwise you will probably get degrading performance and memory usage over time

**Comment by adrizos** [comment]
Makes sense for the disappearing audio issue. Though, if I hoist the synth outside of the function, after the first iteration I get: ```×
Unhandled Rejection (InvalidAccessError): Failed to execute 'connect' on 'AudioNode': cannot connect to a destination belonging to a different audio context.```

If I try and keep the synth in playAudio() and call polySynth.dispose() at the end I get:
``` Error: Synth was already disposed ```

**Comment by adrizos** [comment]
Looks like putting the polySynth initialization in the constructor solved the runaway object creation issue. 
As far as the out sync chord notes, I tried a few different transport methods, but since Im not handling the repeats in the callback, I should be using transport.scheduleOnce, correct? 

Ive tried a bunch of different things without any luck, or it only plays like the third chord voicing and thats it. 

If I want to just schedule a chord immediately, it should look like this yeah? 

```
                Tone.Transport.scheduleOnce( (chord) => {
                    this.polySynth.triggerAttackRelease(chord, '8n');
                });
                Tone.Transport.start();
```

**Comment by tambien** [comment]
Glad that PolySynth is not exhibiting that issue when you hoist it out of the repeated callback function.

If you'd like to schedule a chord immediately, there's no need to use Tone.Transport. Just invoke `polySynth.triggerAttackRelease`. I should also point out that the arguments to scheduleOnce are a function (which returns time as a parameter, not the chord) and then the time you'd like to schedule things at.
