### ISSUE TITLE
Playing again after having stopped does not schedule events any longer

### ISSUE THREAD

**Issue by stephaneeybert** [Tonejs/Tone.js#652]
If I play a series of chords and then stop and play it gain, no scheduling is happening any more.
To stop the playing I cancel the transport and set its time to 0. Am I doing enough for resetting it ?
I made a live [example](https://stackblitz.com/edit/angular-tone-q9vw31).

**Comment by tambien** [comment]
at first glance, it looks like you might be cancelling all of the timeline events that you're scheduling in line 166. Transport.cancel removes all scheduled events. If you just want to replay that series of notes from the beginning of the Transport timeline, better to just stop and then restart the Transport with `Transport.stop()` and then `Transport.start()`

**Comment by stephaneeybert** [comment]
I understood that the Tone.Transport.cancel(); command is supposed to remove all events. And that is indeed what I want it to do. I don't want to keep these events as you are suggesting. I want them gone. And then I want to create new ones.

**Comment by tambien** [comment]
@stephaneeybert I tried to reproduce the issue by simplify things a little and removing some of the angular code from your example.

[Here's a quick fork](https://stackblitz.com/edit/angular-tone-8ddth5?file=main.ts) which cancels all previous values when start is clicked and schedules 10 random notes. Let me know if this is a minimal example of what you are having an issue with

**Comment by stephaneeybert** [comment]
@tambien I had to move the Tone.Transport.start() call to the start of the method implementation so as to avoid a console warning stating the audio context should be started following a use action. Yes, this example works fine and notes are scheduled again after a stop and play. I will try to see in my example why the issue is still there then.

**Comment by tambien** [comment]
@stephaneeybert Glad we could figure it out! Thanks for being so responsive here so we could work through it
