### ISSUE TITLE
How can I use fractions of measures as transpose time and durations?

### ISSUE THREAD

**Issue by danijar** [Tonejs/Tone.js#653]
I'm creating two loops with the same interval of 1 measure. The first loop starts after 1 measure and the second one after half a measure. I would expect this to jump between the two notes with equal pauses in between them. However, the pause from D3 to C3 is three times as long as the pause from C3 to D3.

```javascript
inst = new Tone.Synth()
inst.toDestination()

new Tone.Loop(
  (time) => inst.triggerAttackRelease('c3', 0.2, time),
  '1m').start('1m')
new Tone.Loop(
  (time) => inst.triggerAttackRelease('d3', 0.2, time),
  '1m').start('0.5m')

Tone.Transport.start(1)
```

https://jsfiddle.net/4octx731/

**Comment by danijar** [comment]
Fractions of notes ('2.6667n' for a 3/8 note duration) also seem to be broken, unless I'm misunderstanding something.

**Comment by tambien** [comment]
Fractional subdivisions aren't supported. Only integers

The easiest solution is to just use the subdivision for the fractions that you're looking for. For example "0.5m" = "2n", or "3/8" = "8t"

**Comment by danijar** [comment]
Oh, that's surprising. There really should be a way to specify time points and durations as a fraction of a measure. Your suggestion doesn't work in general, i.e. most durations are not possible to create this way.

**Comment by tambien** [comment]
Yeah that's a good suggestion to support fractional time. in this case, the dot might interfere with the dot notation ability of the notation strings, but might be worth testing out. 

In the mean time, there are plenty of other ways to represent time to get the exact duration that you're looking for. Bars:Beats:Sixteenths lets you add durations in fractions. for example "0:0:"0:0:1.3333" would give you 3/8ths. You could also do math operators on the Time class, so for example you could compute 0.5 measures with the operation `0.5 * Time("1m")`.

**Comment by danijar** [comment]
Okay, cool. Maybe I've missed this but if not it seems worth highlighting this in the documentation.
