### ISSUE TITLE
Ramping up the tempo gives an exception

### ISSUE THREAD

**Issue by stephaneeybert** [Tonejs/Tone.js#654]
When ramping up the tempo I can get an exception depending on the tempo value used.

If not ramping up, but changing instead, then there is no exception.

I created an [example](https://stackblitz.com/edit/angular-tone-q9vw31).

**Comment by tambien** [comment]
Should be fixed when updating to `tone@next`. Throws no error

https://stackblitz.com/edit/angular-tone-izlw6x?file=app/app.component.ts
