### ISSUE TITLE
What overhead is associated with re-creating instruments and effect nodes?

### ISSUE THREAD

**Issue by danijar** [Tonejs/Tone.js#656]
Currently, I'm sharing the the instrument and effect instances and just updating their parameters when necessary. However, sharing state this way breaks down for fast melodies where the effects should change in between notes that are faster than the callback lookahead time:

```js
var instrument = new PolySynth(tone.FMSynth);
var reverbNode = new Tone.Reverb(0);
var volumeNode = new Tone.Volume(0);
instrument.chain(reverbNode, volumeNode, Tone.Destination);

function playChordStateful(time, chord, duration, volume, reverb) {
  volumeNode.volume.value = volume;
  reverbNode.reverb.value = reverb;
  instrument.triggerAttackRelease(chord, duration, time);
}
```

I'm now wondering whether I should create an instrument and effect instances for each individual chord that is played. It seems that this should work conceptually, although ToneJS is probably not meant to be used this way:

```js
function playChordStateless(time, chord, duration, volume, reverb) {
  var instrument = new PolySynth(tone.FMSynth);
  var reverbNode = new Tone.Reverb(reverb);
  var volumeNode = new Tone.Volume(volume);
  instrument.chain(reverbNode, volumeNode, Tone.Destination);
  instrument.triggerAttackRelease(chord, duration, time);
}
```

Does this seem like a valid solution or would you expect performance problems due to either overhead of re-creating audio nodes or previous instances not being cleaned up automatically?

**Comment by tambien** [comment]
I would recommend that you reuse the instruments instead of recreating them in a callback. The startup overhead is going to depend on which synths and effects you are using. Reverb has an especially large startup overhead since it has to generate the impulse response. 

Beyond the startup overhead, each synth and effect adds multiple audio processing nodes to the underlying audio context graph which will stick around unless you explicitly disconnect/dispose those nodes using `.dispose()`.

**Comment by danijar** [comment]
Thanks for pointing our `.dispose()`. Do you have an idea how to solve the problem described above, i.e. timing exactly when effects should change? With the example above, the effects switch look ahead time too early, which affects notes that are being played before the one that should get the new effect setup. Thanks!

**Comment by tambien** [comment]
I would probably have both effects chains setup in parallel each with a gain in front of it. At the moment that you want the effects to change, set one gain to 0 and the other to 1 using `setValueAtTime` or `rampTo`.

**Comment by danijar** [comment]
Thanks for your input! Let's say there is a fast melody playing, where each note starts 0.01 seconds after the previous one. The default lookahead time in ToneJS is 0.1 seconds. The user may choose to change effects on every note. This means I would need at least 10 parallel effect chains to alternate between, e.g. in round-robin fashion.

**Comment by danijar** [comment]
Thanks again for your input! Searching for `setValueAtTime` in the docs did not return any results -- where can I learn more about it? Would this feature allow me to schedule changes to the effect parameters as well? In that case, there would be no need for duplicating the effect chain anymore.
