### ISSUE TITLE
latencyHint on actual AudioContext

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#658]
The web audio api itself [supports `latencyHint` as a constructor option](https://developer.mozilla.org/en-US/docs/Web/API/AudioContextOptions/latencyHint) and after a bit of digging, it seems like that's entirely separate from the Tone.js `latencyHint` option ([there are no options passed into the AudioContext constructor](https://github.com/Tonejs/Tone.js/blob/dev/Tone/core/context/AudioContext.ts#L13)).

Is it correct to say that the `latencyHint` on the real `AudioContext` is not being set? If so, how could Tone.js be instructed to use it? The Tone.js API allows for writes on the value after initialized, but I don't think the real `AudioContext` does.

**Comment by tambien** [comment]
I think the right move would be to mimic the native AudioContext and move all that stuff into the constructor instead of an attribute. To give some backstory, i had added that feature a long time ago while it was still in flux how it was going to be handled in the specification (i believe at some point it was a settable attribute like i have it). 

The only small complication is that Tone.js creates the AudioContext when the page loads, so you'll have to create a _new_ Context if you'd like to access this feature, which isn't ideal.

**Comment by JackCA** [comment]
> I think the right move would be to mimic the native AudioContext 

That seems like a great idea to me!

> The only small complication is that Tone.js creates the AudioContext when the page loads

I'd personally prefer to manually call the initialization and do avoid anything with side-effects.

Is that feature designed around ergonomics for users? Could it be disabled somehow?

**Comment by tambien** [comment]
Once the `next` version is published, you should be able to take advantage of this by doing something like this: 

```js
Tone.setContext({
  context : new Tone.Context({ latencyHint : "playback" })
})
```

I think for now i won't disable creating an AudioContext on startup. It's been around since the first version and would change the user experience and break a lot of people's code.

**Comment by JackCA** [comment]
that works great! Trying it out shortly. Thank you so much

**Comment by JackCA** [comment]
I think the API is actually `Tone.setContext(new Tone.Context())` (without the inner `context:`), right?

**Comment by tambien** [comment]
whoops! yeah you're totally right

```js
Tone.setContext(new Tone.Context({ latencyHint : "playback" }))
```

**Comment by jhurliman** [comment]
It would be helpful to update the docs reflecting this new usage. I had to Google around for a bit to stumble upon this closed ticket.
