### ISSUE TITLE
[Feature Request] OscillatorNode-based implementation of PulseOscillator

### ISSUE THREAD

**Issue by Powerlated** [Tonejs/Tone.js#659]
The current implementation of creating pulse waves with PulseOscillator creates clear high-frequency artifacts in the output. A method of creating higher quality PulseOscillator output could be to calculate the Fourier series of the pulse wave of specified duty cycle, and then feeding those frequencies to an OscillatorNode for the browser to do high-quality additive synthesis with.

**Comment by tambien** [comment]
Does #643 resolve this issue?

**Comment by tambien** [comment]
Going to close this. hopefully this is resolved by that pull request

let me know if there is a better fix for this issue
