### ISSUE TITLE
Docs having bug on redirection to API pages

### ISSUE THREAD

**Issue by CarloCattano** [Tonejs/Tone.js#661]
When visiting [https://tonejs.github.io/docs/Sampler](url)
redirect starts but /latest/latest/latest keeps being added in an infinite loop :-( , was just checking the docs for some hints

**Comment by tambien** [comment]
whoooops! Thanks for the catch. I think it should be mostly fixed now. There are a few situations where spins into an infinite 'latest' loop when there's not a page there. I'm still trying to figure out the best way to fix this
