### ISSUE TITLE
Confused Noob

### ISSUE THREAD

**Issue by cupcakearmy** [Tonejs/Tone.js#664]
Hi everyone 👋
I basically want to A/B some tracks in the browser. I thought Player would be the right way to go. 
I tried 2 methods, both don't seem to work

1. Mute one of the player

```
// Simplified
const a = new Player(...)
const b = new Player(...)

a.start()
b.start()

setInterval(()=> {
  a.muted = false
  b.muted = true
}, 3000)
```

2.  Pause the other one and resume pausing the other one. But i could not find a way to get the current "seek" in order to start the other track on the current time.

I'm probably missing something here, would be glad for some guidance :)
Thanks!

**Comment by danijar** [comment]
I think the problem is that the samples take time to load and you need to wait for that before calling start(). Is there any error message in the developer console?

**Comment by cupcakearmy** [comment]
The console is empty :) The sound starts playing and works, just the switching and setting the mute attribute does not work unfortunately

**Comment by danijar** [comment]
I see. I think you can do this with a gain node in front of each player that multiplies the amplitude of its signal:

```
player = ...
gain = new Tone.Gain(1)
player.chain(gain, Tone.Destination)
// Mute after 3 seconds.
gain.gain.setValueAtTime(0, 3)
```

**Comment by tambien** [comment]
@danijar thanks for chiming in on the thread. I think the Gain fix would do the trick

@cupcakearmy you've got a typo in your setInterval callback: it should read `a.mute` not **`a.muted`**
