### ISSUE TITLE
No sound on iOS WKWebView

### ISSUE THREAD

**Issue by martijnmichel** [Tonejs/Tone.js#666]
As title says Tone.js wont play a sampled sound on a cordova iOS app in WKWebView mode.

The sound works fine on any other platform, on web (desktop), Android (browser and app) and even on iOS in the browser. But not in the iOS app.

I've tried the solution to start the audio on user input but it still does not work. Due to a closed repo I have no way of giving you code to reproduce the issue.

You can test out the app here > https://web.sonid.app or download Sonid in play store/app store.

I hope someone can help me out.
Thanks!

**Comment by tambien** [comment]
The app works fine for me! Make sure that your device is not on silent

There is a trick to get Web Audio to come out of a muted device on iOS by also starting an HTMLAudioElement at the same time, though in my experience it doesn't work very reliably.

**Comment by martijnmichel** [comment]
You really have sound on the iPhone app? v0.6.3? on which iOS version?
My iPhone 11 with latest iOS has no sound...actually i forgot to mention it does have sound when I am running the devserver (vue/nodejs) aswell but not when built :S sound is on.

**Comment by tambien** [comment]
I'm testing on an iPhone 11 with the latest iOS. As i said, i had to turn the phone off silent with the rocker switch in order to get any sounds, but once i did that, it works fine when testing the page "Naturals 1".

**Comment by martijnmichel** [comment]
ow okay.. very weird then it has no sound for me, but thanks a lot for testing!

**Comment by martijnmichel** [comment]
I know it hasnt anything to do with tonejs but would you know any other reason sound is not working for me on the same device and versions as youve tested it..?

**Comment by tambien** [comment]
Can you test if other web audio websites work for you? Like the [Tone.js examples](https://tonejs.github.io/examples/oscillator.html) or [Ableton's Learning Synths](https://learningsynths.ableton.com/)

**Comment by martijnmichel** [comment]
The ToneJs examples are working fine but, to be clear, my app works fine when used in browser version (web.sonid.app) but I have no sound when using the cordova WKWebView app version! (found here: https://apps.apple.com/us/app/sonid/id1490221762?ls=1) Did you tryout the web or app version?

**Comment by tambien** [comment]
oh i see, sorry for my misunderstanding. No i didn't test out the downloaded app, only tested in the browser. 

Check out [this issue's comment](https://github.com/Tonejs/Tone.js/issues/208#issuecomment-299119794 ) to see if those permissions do anything for you.

**Comment by martijnmichel** [comment]
I am unsure of what damage this could do to other working app parts (even on other devices)

`
<meta http-equiv="Content-Security-Policy" content=
"default-src 'self' ws: data: gap: https://ssl.gstatic.com 'unsafe-eval' 'unsafe-inline';
child-src 'self' blob: * ;
style-src 'self' 'unsafe-inline' http://fonts.googleapis.com/;
font-src *;
media-src 'self' blob: data: ">
`

**Comment by martijnmichel** [comment]
I still havent found a solution for this :S

**Comment by tambien** [comment]
sorry to hear that. Seems like it's a Web Audio + WKWebView issue. You've probably tried searching Cordova's forums. Have you created an issue with them?

**Comment by Seanitzel** [comment]
I have ran into this issue as well.

What's weird is that synths do work, but it's impossible to play any audio that was loaded with a buffer - any mp3 files.

This is really frustrating, don't think it's an issue with Tone though...

**Comment by martijnmichel** [comment]
I still have this issue. Please re-open.

**Comment by Seanitzel** [comment]
Might help someone, after a LONG time of having this problem i found that what caused it was that i was trying to access the caches object which for some reason does not exist within the WKWebView....

Not sure why it doesn't exist there since it does exist in Safari, and not sure how we should otherwise cache mp3 files.

**Comment by martijnmichel** [comment]
How did you find out and do you have a solution?

**Comment by Seanitzel** [comment]
What solved it for me was checking if the app is running within a WKWebView and if so, load the samples without caching them using the 'caches' object.

After that everything was working properly, and tears of joy ran down my eyes.

I was still getting warning from xcode though, and was surprised to see they had nothing to do with whether the samples were really playing or not...

**Comment by martijnmichel** [comment]
And how do I load the samples without caching them? :/

**Comment by Seanitzel** [comment]
what so you mean? loading samples doesn't have anything to do with caching them, just load them regularly.

If you havent used the caches object than there's probably something else causing the bug...

**Comment by martijnmichel** [comment]
After all this time ive found a solution. I dont completely understand why but with this plugin things started working > https://github.com/globules-io/cordova-plugin-ios-xhr
