### ISSUE TITLE
Delay when triggering note onclick

### ISSUE THREAD

**Issue by ArKaneVision** [Tonejs/Tone.js#668]
I'm building a React synth using Tone.js, I am experiencing a delay when running an onClick event. I explored the issues and found this: https://github.com/Tonejs/Tone.js/issues/306. Neither of the fixes mentioned here work for me

here is my function:
```
function playNote (noteToTrigger) {
    Tone.context.lookAhead = 0
    synth.current.triggerAttack(noteToTrigger, Tone.context.currentTime, 100)
  }
```

```
const WhiteKey = ({ playNote, note }) => {
  return (
    <div
      onClick={() => playNote(note)}
    >
      White key {note}
    </div>
  )
}
```
am I implementing this correctly?

**Comment by tambien** [comment]
onClick is usually handled onmouseup which might be causing a perceived delay. You could try onmousedown instead. In the configuration you've got, Tone.js shouldn't be introducing any additional latency/delay

**Comment by ArKaneVision** [comment]
That helped but something is still causing some delay, I'll keep testing and respond when I rule everything else out. Thank you for your help

**Comment by tambien** [comment]
Have you tested with other Tone.js or Web Audio examples to see if the same latency persists? for instance, is it the same or more delay/latency as in this example: https://tonejs.github.io/examples/sampler.html

There's also a few ways that your system could be introducing latency. Bluetooth headphones introduce quite a lot of latency. Or if you audio device has a very high buffer size (sometimes this is configurable on your system)

**Comment by ArKaneVision** [comment]
I feel really silly but I forgot about the Bluetooth latency, it works now! thanks for taking the time to help out

**Comment by tambien** [comment]
That's alright! This exact problem is actually pretty common. Now it's documented for other people who might come across the same thing

**Comment by johankitti** [comment]
Haha finally figured out my delay thanks to this post. I guess I'll keep my delay compensation code as an option for users with bluetooth headphones :)
