### ISSUE TITLE
Could not find a declaration file for module 'tone'

### ISSUE THREAD

**Issue by rnikitin** [Tonejs/Tone.js#669]
Hi! First of all thank you for such a great library!

However I encountered a strange issue while importing Tone.js. I'm building Ionic app, based on TypeScript and React. If I import, as described in docs and examples:
```
import * as Tone from "tone";
```

I'm getting error:
```
Could not find a declaration file for module 'tone'. '/Users/rnikitin/dev/world-of-drums/node_modules/tone/build/Tone.js' implicitly has an 'any' type.
  Try `npm install @types/tone` if it exists or add a new declaration (.d.ts) file containing `declare module 'tone';`ts(7016)
```

But this works fine on my local machine
```
import Tone from 'tone/Tone';
```

At the same time if I leave it that way, ionic CI fails with following error:
```
TypeScript error in /builds/rnikitin/drumvox/src/components/DrumMachine.tsx(4,18):
Could not find a declaration file for module 'tone/Tone'. '/builds/rnikitin/drumvox/node_modules/tone/Tone/index.js' implicitly has an 'any' type.
  Try `npm install @types/tone` if it exists or add a new declaration (.d.ts) file containing `declare module 'tone/Tone';`
```

It will go if I disable strict mode, but I don't really like that idea. 

have you ever encountered this error?

**Comment by tambien** [comment]
tone@latest doesn’t have typings but tone@next does. are you using tone@next?

**Comment by rnikitin** [comment]
It looks like I was using tone@latest. With tone@next it works fine, thanks! 
Although it looks like the API is slightly different and I've got some unexpected errors. Is it stable?

**Comment by tambien** [comment]
yeah it's stable. just haven't had time to release it yet since there's still a couple small things left to take care of

**Comment by VictorKolb** [comment]
@tambien hello! Where I can find documentation for tone@next? Seems like some methods is deprecated
