### ISSUE TITLE
Change effects of instrument live

### ISSUE THREAD

**Issue by ArKaneVision** [Tonejs/Tone.js#671]
Is there a way to change the effects of a synth after the attack has been triggered. to to have live changes to the sound being generated. I have seen examples where this seems possible but have not been able to recreate it.

**Comment by ArKaneVision** [comment]
either, I notice there that you can change 'Partial Count' while holding a note down and it will adjust. Can you do that with effects? how is that example different from the second thing you described?

**Comment by ejarzo** [comment]
You can do this with either the effect [Dry/Wet](https://github.com/Tonejs/Tone.js/wiki/Effects#drywet) or you can also modify individual parameters eg.
```js
const distortion = new Tone.Distortion();
// ...
distortion.distortion = 0.3
// or using `set`
```

**Comment by tambien** [comment]
thanks for chiming in @ejarzo!

yeah easiest is if you're using a connected effect and then you can modify it's parameters totally independently of the triggerAttack/Release. 

Oscillator parameters (like partials) may also be possible to change (except with the PolySynth i believe) while the synth is playing, but it'll probably produce a click when it changes as the oscillator has to stop and restart on those changes. 

If you have a specific synth in mind, you could always trigger two synths simultaneously and then cross-fade between the two which will give you a similar effect.
