### ISSUE TITLE
PolySynth with React and TypeScript

### ISSUE THREAD

**Issue by brentbrinkley** [Tonejs/Tone.js#673]
So I've got tone working in React perfectly my only issue is when I change the synth over to PolySynth the object I'm passing in just will not work. It gives me a long message about the acceptable types. My issue is the list is truncated and I can't see what the defaults are so I don't know what to pass in. I tried following the definitions and this codebase is just incredibly dense. Here's what I'm attempting to pass into PolySynth as the second argument.

```typescript
const harp = {
    oscillator: {
        type: 'sine'
    },
    modulation: {
        type: 'basic'
    },
    envelope: {
        attack: 0.01,
        decay: 0.1,
        sustain: 0.1,
        release: 1.2,
        attackCurve: 'linear',
        decayCurve: 'exponential',
        releaseCurve: 'exponential'
    }
}
```
This works perfectly fine in normal JS. But not in TS set to strictmode. Any help would be appreciated.

**Comment by tambien** [comment]
What is the error that you're getting? and PolySynth code which is throwing the error? 

One thing i can see by glancing at it is that i don't think there is a `modulation: { type: 'basic' }` which is what typescript might be throwing an error about. But if you could provide more context it'd be easier to debug.

**Comment by brentbrinkley** [comment]
@tambien Thank you for getting back in touch. I grabbed a screenshot of the error for you

<img width="998" alt="Screen Shot 2020-05-18 at 2 31 56 PM" src="https://user-images.githubusercontent.com/3386882/82247542-8cde5c80-9914-11ea-9c02-1d0243f47c6b.png">

**Comment by tambien** [comment]
yeah looks like it is because you've got 'basic' as the oscillator type in "modulation" which is not a valid oscillator type. Try "sine", "square", "triangle" or "sawtooth"

**Comment by brentbrinkley** [comment]
When I update the property a similar error message pops up:

<img width="1001" alt="Screen Shot 2020-05-18 at 3 15 12 PM" src="https://user-images.githubusercontent.com/3386882/82250976-6d4a3280-991a-11ea-8281-7fde91209d77.png">

Here's the updated object that's causing the error: 

```typescript
export const harp = {
    oscillator: {
        type: 'sine'
    },
    modulation: {
        type: 'sine'
    },
    envelope: {
        attack: 0.01,
        decay: 0.1,
        sustain: 0.1,
        release: 1.2,
        attackCurve: 'linear',
        decayCurve: 'exponential',
        releaseCurve: 'exponential'
    }
}
```

**Comment by tambien** [comment]
"sine" is a string and a type and for some reason typescript is not recognizing the string literal as the type. [Related to this issue](https://github.com/microsoft/TypeScript/issues/25889). 

The simplest solution seems to be 

```typescript
export const harp = {
    modulation: {
        type: 'sine' as const
    }
}
```

**Comment by brentbrinkley** [comment]
Still not responding.

Updated code: 
```typescript
export const harp = {
    oscillator: {
        type: 'sine' as const
    },
    modulation: {
        type: 'sine' as const
    },
    envelope: {
        attack: 0.01,
        decay: 0.1,
        sustain: 0.1,
        release: 1.2,
        attackCurve: 'linear',
        decayCurve: 'exponential',
        releaseCurve: 'exponential'
    }
}
```

Updated Error: 

<img width="997" alt="Screen Shot 2020-05-18 at 8 08 25 PM" src="https://user-images.githubusercontent.com/3386882/82270618-5d931400-9943-11ea-8fde-8e1372f81e79.png">

I decided to try adding const to the other "strings" on the object and when I did this was the new error message:

<img width="987" alt="Screen Shot 2020-05-18 at 8 11 17 PM" src="https://user-images.githubusercontent.com/3386882/82270744-c7132280-9943-11ea-964e-50416fd291ea.png">

Updated Object:

```typescript
export const harp = {
    oscillator: {
        type: 'sine' as const
    },
    modulation: {
        type: 'sine' as const
    },
    envelope: {
        attack: 0.01,
        decay: 0.1,
        sustain: 0.1,
        release: 1.2,
        attackCurve: 'linear' as const,
        decayCurve: 'exponential' as const,
        releaseCurve: 'exponential' as const
    }
}
```

**Comment by tambien** [comment]
oh i think it's much simpler than i realized. the synth type you've chosen does not have a 'modulation' property. try removing it.

**Comment by brentbrinkley** [comment]
Updated Code: 

```typescript
export const harp = {
    oscillator: {
        type: 'sine' as const
    },
    envelope: {
        attack: 0.01,
        decay: 0.1,
        sustain: 0.1,
        release: 1.2,
        attackCurve: 'linear' as const,
        decayCurve: 'exponential' as const,
        releaseCurve: 'exponential' as const
    }
}
```

Error:

<img width="993" alt="Screen Shot 2020-05-18 at 10 26 16 PM" src="https://user-images.githubusercontent.com/3386882/82277841-df406d00-9956-11ea-89af-a3dcdf4d0a67.png">

Here's the repo if you want to take a further look https://github.com/brentbrinkley/mosaic

**Comment by tambien** [comment]
I think the issue it that on [this line](https://github.com/brentbrinkley/mosaic/blob/master/src/NoteGrid.tsx#L21) you're declaring synth as a `Synth` where it should be a `PolySynth`. 

Here's a simplified version of your code: https://codesandbox.io/s/cool-sun-pp1et?file=/src/index.ts

Let me know if that fixes it for you

**Comment by brentbrinkley** [comment]
That worked thank you so much for you're assistance! I can't believe I missed something that simple.
