### ISSUE TITLE
Tone.Transport is not exported in v14.7.2?

### ISSUE THREAD

**Issue by edjah** [Tonejs/Tone.js#674]
I've installed `tone@next` using npm which got me v14.7.2, and I'm using typescript within a project created using create-react-app.

I'm trying use the `Tone.Transport` module, but I'm getting an error message saying that:
```
Namespace '"my_project/node_modules/tone/build/esm/index"' has no exported member 'Transport'.  TS2694
```

I find this odd since other modules like `Tone.ToneBufferSource` and `Tone.Draw` are perfectly recognized. I was wondering if there was a simple way to fix this.

**Comment by tambien** [comment]
How are you importing Transport? 

I've got it working [here](https://codesandbox.io/s/transport-674-bmqvd). Let me know if your setup looks like that and is still not working

**Comment by edjah** [comment]
Sorry, it looks like I was misunderstanding how Transport worked. I initially thought that I should be able to construct a new Transport for each source, but it's actually the case that there's just a single global Transport. I must have missed that in the docs.

So, I was trying to do something like [this](https://codesandbox.io/s/transport-674-z80n5).

With proper usage, Tone.Transport works just fine.

**Comment by tambien** [comment]
Exactly. there is one Transport per Context and since there is a global Context created on initialization, there's also a singleton global Transport which is created.
