### ISSUE TITLE
PolySynth releaseAll sometimes leaves voices playing forever

### ISSUE THREAD

**Issue by shaylew** [Tonejs/Tone.js#676]
It seems that the combination of releaseAll and (scheduled) triggerAttackRelease can leave some of the voices of a PolySynth stuck playing indefinitely. They don't stop when their scheduled release time comes up, and they also don't stop on any future calls to releaseAll. (They do stop if you iterate through the synth's _voices and release each one.)

I don't have a 100% reliable way to reproduce this issue, but here's an example where rapidly clicking a button to call releaseAll triggers the misbehavior for me within a couple of attempts (in both Firefox and Chrome): 
- demo: https://tone-releaseall.stackblitz.io/
- code: https://stackblitz.com/edit/tone-releaseall

**Comment by tambien** [comment]
could you share the code?

**Comment by shaylew** [comment]
Oops, edited in the editor link just now. (If some of it looks familiar it's because the start-schedule-play-stop code is adapted from the working example in #652, to make sure it's not the usage that's wrong.)
