### ISSUE TITLE
Submix

### ISSUE THREAD

**Issue by weepy** [Tonejs/Tone.js#678]
How easy is it to create a submixer ? I.e. right now it seems that you can only do "toDestination" - I wanted to create a submix so I could get away with only having one reverb unit and routing different amount of each instrument to it as well as to the master.

**Comment by tambien** [comment]
You could use the `connect` method to connect nodes to each other before going to the speakers

```typescript
const submix = new Tone.Gain().connect(reverb)
sourceA.connect(submix)
sourceB.connect(submix)
```

**Comment by weepy** [comment]
Can you also connect a source to multiple submixes ?

So I'd need to do something like :

```

const submix = new Tone.Gain().connect(reverb)

const mainmix = new Tone.Gain().toDestination()

const sourceA_ReverbGain = new Tone.Gain()

sourceA_ReverbGain.connect(submix)

sourceA.connect(sourceA_ReverbGain)

sourceA.connect(mainmix)

```

**Comment by tambien** [comment]
yup! that should work just fine
