### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by ofirgeller** [Tonejs/Tone.js#680]
Seems like it had been a while, and a new version will offer typescript users the use of the decleration files and many other changes.

I did try to directly depend on thr HEAD commit, but since the build output is not in version control i also has to try building the package as part of the install script of my app, it builds fine when cloning the repo, but not when it is used as a package, it seems in that case the TS compiler assumes a node environment which changes many types.

If there is some work to be done that will help along with making a release/making the package build as part of installing it I might be able to do it, please let me know.

**Comment by Seanitzel** [comment]
I believe you can just use tone@next,
That's what i've been doing.

But i do wonder when is the release of the next major version...

**Comment by tambien** [comment]
the last thing that's left is to update the examples to work with the latest version. i think once that's in there, it's pretty much ready to go.

**Comment by xerosanyam** [comment]
is there a page where changelog/breaking changes are mentioned?
will prepare in advance, thanks :)
