### ISSUE TITLE
Need Help Fixing a Trigger Release Issue in my App

### ISSUE THREAD

**Issue by brentbrinkley** [Tonejs/Tone.js#683]
I'm using the polyphonic synth in my app and I'm having two issues 1) Sometimes released notes get stuck and continuously trigger 2) there appears to be clipping and audio pops on most devices.

Here's the link to the live app so that hopefully you can trigger the issues yourself. Try hitting notes in very rapid succession on mobile. 

[https://prismatone.netlify.app/](url)

And here's the link to the corresponding repository

[https://github.com/brentbrinkley/prismatone](url)

Just a heads up this is a Svelte project. The corresponding code can be found in `/src/NoteGrid.svelte` and `/src/Note.svelte`

I only have access to Apple devices so I'm not sure how this performs on Android. Outside of the notes sticking and pops it should be smooth on most newer devices.

Any help would be greatly appreciated as this is an mvp for a much larger project I'm working on.

**Comment by tambien** [comment]
Try upgrading to tone@next. Seems to be related to #647 which should be fixed now.

**Comment by brentbrinkley** [comment]
Hey tambien thanks for getting in touch so fast. My project is currently using tone@next.

**Comment by brentbrinkley** [comment]
Figured it out I had to put an event listeners on the window object to ensure certain states were prevented.
