### ISSUE TITLE
Multiple Transports

### ISSUE THREAD

**Issue by hector** [Tonejs/Tone.js#684]
Is it possible to have more than one Transport?
I use the main transport to play a song (with multiple audios).
I want to play a small audio to compute the recording latency.
I know I could mute all tracks, but this would still fire all events on the main transport.
I could also put this audio very far on the end of the Transport... but none of this looks very clean.
I am open to ideas :)

**Comment by tambien** [comment]
In the latest version (tone@^14) you can create multiple contexts and each context has it's own transport. 

```js
const context = new Tone.Context()
// context-specific Transport
context.transport
```

**Comment by hector** [comment]
That's awesome!
Thanks for your great work and you fast response.

**Comment by hector** [comment]
Hi!
I have managed to do some things from the new context but I get an error trying to create a Player and a Channel:
```javascript
const context = new Tone.Context()

const channel = new Tone.Channel(0, 0);
const player = new Tone.Player(buffer);
player.sync().start(0).chain(channel, context.destination);
```

This throws the error: `Failed to execute 'connect' on 'AudioNode': cannot connect to a destination belonging to a different audio context.`

Could you point me in the right direction to create a new Player and Channel with my new context?

**Comment by hector** [comment]
I dug into the source code and I think I found the answer: using the options object to create instances.
I hope it helps somebody :)
```javascript
const context = new Tone.Context()

const channel = new Tone.Channel({volume: 0, pan: 0, context});
const player = new Tone.Player({url: fromBuffer, context});
player.sync().start(0).chain(channel, context.destination);
```
