### ISSUE TITLE
Sequence.start(time, ofsset) doesn't start on specified time

### ISSUE THREAD

**Issue by rnikitin** [Tonejs/Tone.js#685]
Hi there. 

I'm making a small app with drum sequencer, where I want to loop the melody and I would like to add some kind of pre-count. 
I found problematic it problematic to start a sequencer at exact time after the pre-count.

The initialize code for a sequencer, called on page load.
```js
// generate sequencer events
for (var i = 0; i < melody.beats.length; i++) {
    this.sequenceEvents.push(i)
}

// load players
this.drumPlayers = new Tone.Players(DRUM_NOTES, () => {
	this.drumPlayers.volume.value = -10
	this.drumPlayers.toDestination()
})

Tone.Transport.bpm.value = this.bpm

console.log("KonnakolGameAudio.constructor", DRUM_NOTES, this.sequenceEvents, this.bpm)

// create sequencer
this.Sequencer = new Tone.Sequence((time, beat) => {

	console.log("KonnakolGameAudio.sequencerCallback", time, beat)

	let melodyBeat = this.melody.beats[beat]
	this.playNotes(melodyBeat.notes, time)
}, this.sequenceEvents, "16n")
```

This code executed on play button tapped:
```js
Tone.start().then(() => {
	// stop in case it was playing
	if (Tone.Transport.state == "stopped")
		Tone.Transport.start()

	// schedule drums
	let time = Tone.Transport.now()
	let measureTime = 60 / this.bpm
	let snare = this.drumPlayers.player("Snare")

	console.log("Ta on", time)
	snare.start(time, 0) // Takadimi
	time += measureTime

	console.log("Ta on", time)
	snare.start(time, 0) // Takadimi
	time += measureTime

	console.log("TaKa on", time)
	snare.start(time, 0) // TaKa
	time += measureTime / 2

	console.log("TaKa on", time)
	snare.start(time, 0) // Taka
	time += measureTime / 2

	console.log("TaKa on", time)
	snare.start(time, 0) // Taka
	time += measureTime / 2

	console.log("TaKa on", time)
	snare.start(time, 0) // Taka
	time += measureTime / 2

	console.log("Play", time, this.Sequencer)

	this.Sequencer.start(time, 0)

	Tone.Draw.schedule(() => {
		onStart()
	}, time)
})
```
So I just calculate timings for each step and then want's to start my melody, loaded to sequencer.

But sequencer starts few seconds later, which is totally unexpected to me. The log looks like:
```
15:34:00.792 KonnakolGameAudio.ts:136 Ta on 1.9866213151927439
15:34:00.792 KonnakolGameAudio.ts:138 Ta on 2.986621315192744
15:34:00.793 KonnakolGameAudio.ts:142 TaKa on 3.986621315192744
15:34:00.794 KonnakolGameAudio.ts:146 TaKa on 4.486621315192744
15:34:00.795 KonnakolGameAudio.ts:150 TaKa on 4.986621315192744
15:34:00.796 KonnakolGameAudio.ts:154 TaKa on 5.486621315192744
15:34:00.797 KonnakolGameAudio.ts:158 Play 5.986621315192744 
15:34:06.777 KonnakolGameAudio.ts:45 KonnakolGameAudio.sequencerCallback 7.970996315192735 0
```
Sequencer supposed to start at ```5.9866```, but started at ```7.9709```. 

OK, let's try to schedule sequence log. First way:
```js
Tone.Transport.scheduleOnce(() => {
	console.log("scheduleOnce", time)
	this.Sequencer.start()
}, time)
```
Result:
```
...
15:49:21.610 KonnakolGameAudio.ts:158 Play 4.105804988662132
15:49:25.755 KonnakolGameAudio.ts:161 scheduleOnce 4.105804988662132
15:49:25.809 KonnakolGameAudio.ts:45 KonnakolGameAudio.sequencerCallback 4.256846655328798 0
```
As expected, starting sequencer takes time so first sound is delayed by 0.15-0.25 and sometimes (especially on mobile device) it doesn't play a first event.

Let's try other way of scheduling and put some adjustment for timing:
```js
Tone.Draw.schedule(() => {
    this.Sequencer.start("16n", 0)
}, time)
```
Result: 
```
...
KonnakolGameAudio.ts:154 TaKa on 3.6058049886621317
15:56:53.132 KonnakolGameAudio.ts:158 Play 4.105804988662132
15:56:57.180 KonnakolGameAudio.ts:45 KonnakolGameAudio.sequencerCallback 4.105804988662131 15
```

Now timings are fine. But the result is not what I'm expecting: the melody starts later and first event is now 15th, but I'm expecting to start with 0 event.

Am I using Sequencer wrong way? Or is there a bug?

**Comment by tambien** [comment]
Thanks for the detailed description. I think the issue at the center of this is the discrepancy between AudioContext time and Transport Time. There's [this wiki article](https://github.com/Tonejs/Tone.js/wiki/TransportTime) which goes into it a little (haven't updated it in years, so hopefully that info is up-to-date enough). By scheduling things using `Transport.now()` (which inherits from `Tone.now()` which uses the AudioContext time) you are scheduling events along the Transport using AudioContext time. 

If you'd like to get the current time of the Transport use `Transport.seconds`. So i think if you changed this line: `let time = Tone.Transport.now()` to `let time = Tone.Transport.seconds` it should work as expected.

**Comment by rnikitin** [comment]
Hi @tambien! Thanks for pointing me to the source of issue.
Unfortunately your solution didn't help, the start of sequencer was not precise. But what I found, analyzing the log:
```
15:34:00.792 KonnakolGameAudio.ts:136 Ta on 1.9866213151927439
15:34:00.792 KonnakolGameAudio.ts:138 Ta on 2.986621315192744
15:34:00.793 KonnakolGameAudio.ts:142 TaKa on 3.986621315192744
15:34:00.794 KonnakolGameAudio.ts:146 TaKa on 4.486621315192744
15:34:00.795 KonnakolGameAudio.ts:150 TaKa on 4.986621315192744
15:34:00.796 KonnakolGameAudio.ts:154 TaKa on 5.486621315192744
15:34:00.797 KonnakolGameAudio.ts:158 Play 5.986621315192744 
15:34:06.777 KonnakolGameAudio.ts:45 KonnakolGameAudio.sequencerCallback 7.970996315192735 0
```

The sequencer start is delayed on by the time of the first event, so I can do:
```
this.Sequencer.start(time-firstTime, 0)
```
where firstTime  is the time when first Ta has to be played or just the length of the pre-count, using time here more like a delay:
```
this.Sequencer.start(4, 0)
```
