### ISSUE TITLE
Large number of Filters causes Silence

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#686]
It appears that if a relatively large number of `Tone.Filter` objects are created, audio becomes completely silent.

Here's a [reproduction](https://jsfiddle.net/JackCA/b0xhcgyt/5/).
 Notes about it:
- this doesn't happen with the native filters (there is a flag to demonstrate this in the repro)
- the number I've chosen (500) is one that triggers the issue for me but I'm assuming it may be environment specific

**Comment by tambien** [comment]
Tone.Filter includes a number of other AudioNodes which enables the rolloff factor to be more than the default of -12db/octave. It seems like at some point over a few thousand AudioNodes the Web Audio API implementations just gives up trying to process. 

The solution here would either be to write a simpler wrapper around the BiquadFilterNode which doesn't include the rolloff factor or just use the native Web Audio APIs and Tone.connect to connect things up.

**Comment by tambien** [comment]
adding Tone.BiquadFilter which is a basic wrapper around the BiquadFilterNode so should perform exactly the same as the WAA BiquadFilterNode but with the unit-conversions of Tone.Param

**Comment by JackCA** [comment]
That's perfect. Thank you so much!
