### ISSUE TITLE
Tone.Context is not a constructor

### ISSUE THREAD

**Issue by endurance21** [Tonejs/Tone.js#689]
hey ! 
i have been utilizing this library's interfaces for my projects , however with the latest version 
( 13.8.25 ) i am not able to set the audioContext explicitly !! 

the following error is showing up in the console !
`Uncaught TypeError: Tone.Context is not a constructor`

it might be that i am not aware of setting the audio conText explicitly , as far as i know this is the way 
https://github.com/Tonejs/Tone.js#audiocontext  , but this way i am getting the above error !

**Comment by tambien** [comment]
could you share a short snippet of code to reproduce the error?

**Comment by endurance21** [comment]
@tambien  sorry for the delay , i was making snippet for the same 
# https://github.com/endurance21/project-cappuccino/tree/master 
 ## this is the small project that have tone.js latest (13.x ) as its external dependency , i have simply tried to import the Tone  and adding  AudioContext explicitly using setContext() method 

![image](https://user-images.githubusercontent.com/43696525/84603413-edc56a00-aeab-11ea-8d3a-787eba05e8b9.png)


##  but as i tried to run the build file in  browser , the following error poped up in console


![image](https://user-images.githubusercontent.com/43696525/84603442-206f6280-aeac-11ea-8775-6fc909a8fb62.png)

`
## further  inspecting i got 
`
![image](https://user-images.githubusercontent.com/43696525/84603452-31b86f00-aeac-11ea-8d76-2d2096d26229.png)








hope it would be easy to reproduce the bug !

**Comment by tambien** [comment]
Try importing '../node_modules/tone' instead. Before `tone@^14` it didn't work quite as well with dependency resolution of deep imports like you're doing.

**Comment by endurance21** [comment]
@tambien i think that will import whole tone's interfaces?
We just need to use some of it, and this will increase the build size 
Is there any better option for doing  so?

**Comment by tambien** [comment]
You can import Tone.Context from `tone/Tone/core/Context` (as well as any other classes you'd need to work with) or you could use `tone@next` which handles dependencies much better.
