### ISSUE TITLE
Tone.js scripts in IPhone 8  navigators ? 

### ISSUE THREAD

**Issue by JTorresConsulta** [Tonejs/Tone.js#690]
Hello,

I have a Tone.js script that is running correctly in PCs navigators, Android navigators and  Iphone 5 navigators.
Today I tested in a Iphone 8 and doesnt work.

This is the link of my script:
https://www.nt8.trade/tone.js/github.example.php

The oficial examples of Tone.js works on IOs 8 navigators.

Do you know if its a common problem? How could I fix it?
Thanl you very much

**Comment by tambien** [comment]
Hi @JTorresConsulta, i'd say this is quite common. Most of the time the issue has to do with [autoplay](https://github.com/Tonejs/Tone.js/wiki/Autoplay). Another common situation is that the phone is on mute or has the volume all the way down (embarrassingly this still happens to me regularly).

**Comment by JTorresConsulta** [comment]
Hi Yotam, 
Thank you for your response.

Its not the problem. You can see that my script havent an autoplay and the Iphone 8 is not muted.

**Comment by tambien** [comment]
ok thanks for the clarification. I'd recommend you update to the latest Tone.js and that you invoke explicitly `Tone.start()` when the button is clicked like in this example:

```javascript
document.querySelector('button').addEventListener('click', async () => {
    await Tone.start()
    // your page is ready to play sounds
})
```

Autoplay can be an issue even when you don't play things when the page is loaded. If `Tone.start()` or `Tone.context.resume()` is not explicitly called, the browser will stay silent until it is. 

let me know if that helps

**Comment by JTorresConsulta** [comment]
Hi again Yotam.
Its Ok now. I just update to the next version. 
Thank you!
