### ISSUE TITLE
Desync players with Offline Render buffers

### ISSUE THREAD

**Issue by protectedvar** [Tonejs/Tone.js#692]
I'm trying to render 8 buffers for 8 **Tone.Player** with **Tone.Offline** and play them every **'4m'** 
The result is a desync playing... :(

With tone@next all is perfect... but not one example does not work on a mobile device... (IOS, Android - no sound...)

_(you can switch version on html code)_
https://jsfiddle.net/rekursia/crwqj683/15/

**Comment by tambien** [comment]
not sure exactly what the issue is. i've experienced that Offline rendering can take much longer on mobile devices. in line 25 of your fiddle, you start the Transport, i would wait to start the Transport until after all of the Offline rendering is done.

Is it logging that it's rendering each of the buffers?

**Comment by protectedvar** [comment]
I would like to render buffers during playback (synchronously). I assumed that offline rendering makes in a different context...

I repeat, in **tone@next** everything is okay... 
But as I understand, the new library does not work on mobile devices... (IPhone 7, Samsung A8). No sound with simple examples :(
Is mobile support expected in the future?

**Comment by tambien** [comment]
Offline rendering is only possible asynchronously, there is no synchronous version. 

Also, in all my testing tone@latest and tone@next work on iOS and Android. Are you not getting any sound from [these examples](https://tonejs.github.io/examples/) on your device?

**Comment by protectedvar** [comment]
I am about "trick of synchronicity" - rendering buffers, and play after they are ready.
Sorry my mistake...  forgot to put Tone.start() before playing (on mobile devices) 
Anyway, thanks for the answers, and your awesome library!
