### ISSUE TITLE
Part#loopEnd inclusive?

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#694]
I have a MIDI file that has an event scheduled at the end of a track and am noticing that it does not trigger the callback.

[Here's a simple example.](https://jsfiddle.net/JackCA/ysuh8roj/) -- should `loopEnd` be inclusive of events that occur at that exact time?

**Comment by tambien** [comment]
This is the desired behavior. loopEnd is exclusive of the end point. this is hopefully consistent across all of the classes. and i just double checked, but also consistent with how loopEnd is handled in the AudioBufferSourceNode in the WAA.

**Comment by JackCA** [comment]
@tambien thanks, for checking. Not sure if adding docs about it would help others.

My specific use case is that I use https://github.com/Tonejs/Midi to parse a midi file, but instead of having a single event in the part for a specific start/release combo, I add separate start and release events to be a bit more flexible.

If anyone else finds this, I'm fixing this by scheduling the last release a tick earlier.
