### ISSUE TITLE
Outdated documentation w/ Offline

### ISSUE THREAD

**Issue by bduffany** [Tonejs/Tone.js#696]
https://github.com/Tonejs/Tone.js/blob/dev/Tone/core/context/Offline.ts

The callback doesn't accept `Transport` - actually it accepts OfflineContext. Docs could make it more clear how to access the Transport

**Comment by bduffany** [comment]
NVM, the issue is because I'm on Tone 14.

**Comment by milianmori** [comment]
Hey @bduffany ,

Thanks for mentioning this, I've been trying for a too long time how to accessing `Tone.Transport()`. Like you mentioned, it doesn't works like it's documented. But I still didn't figure out how to access the `Tone.Transport()` in a `Tone.Offline()` nor `Tone.OfflineContext()`. How did you do it? Thank you! Below my code!

Thank you so much!

Greetings,
Milian

```
return Tone.Offline((Transport) => {
        
        const out = new Tone.Volume(1).toDestination();

        const env = new Tone.AmplitudeEnvelope({
            attack: 0.001,
            decay: 0.0001,
            sustain: 0.1,
            release: 0.0001,
        })

        const noise = new Tone.Noise("pink").start();
        noise.chain(env,out);


        Transport.scheduleRepeat(function(time) {
            env.triggerAttack("8n");
            console.log("Hallo: " + time);
        }, "8n");

        Transport.start(0.2);

    }, 10,1).then(buffer => {
        console.log("----> finished loading <----");
        return buffer
    });
```

**Comment by Seanitzel** [comment]
The Transport is inside an object within the callback, as seen in the docs as well:

```js
Tone.Offline(({ transport }) => {
	const osc = new Tone.Oscillator().toDestination();
	transport.schedule(time => {
		osc.start(time).stop(time + 0.1);
	}, 1);
	// make sure to start the transport
	transport.start(0.2);
}, 4).then((buffer) => {
	// do something with the output buffer
	console.log(buffer);
});
```
