### ISSUE TITLE
setting getter-only property "Transport" with tone@14.7.12 on codesanbox

### ISSUE THREAD

**Issue by 4lejandrito** [Tonejs/Tone.js#699]
Hi! 

I was trying to create a codesandbox using tone `14.7.12` and I got the following error:

```
setting getter-only property "Transport"
```

See https://codesandbox.io/s/shy-wood-b7p43.

I've rolled back to 13.8.25 and everything works as expected.

Thanks!

**Comment by JohannesKlauss** [comment]
This also happens with the latest version.

**Comment by JohannesKlauss** [comment]
@tambien This error still pops up in 14.7.34

**Comment by tambien** [comment]
i'm not sure what is causing this issue since as far as i can tell, it doesn't appear anywhere but with codesandbox. I can't tell what they are doing differently than other bundlers.

**Comment by JohannesKlauss** [comment]
Yeah it's super weird. Maybe we should raise an issue there? Its super hard to build minimal repro cases without it.

**Comment by tambien** [comment]
that's a great idea! would you link to this issue so we can track on this thread also?

**Comment by tambien** [comment]
Fixed with the latest tone (tone@14.7.56)

Here's an example: https://codesandbox.io/s/green-night-gkk4v?file=/src/index.ts
