### ISSUE TITLE
Pause, then play, then seek (Transport.seconds = ...) results in long delay

### ISSUE THREAD

**Issue by bduffany** [Tonejs/Tone.js#706]
Repro: https://jsfiddle.net/b9Ldj0mu/16/

1. Press **play**
2. Wait a second, then press **pause**
3. Press **play** again
4. Click the audio player to **seek** to the given time
5. Observe the long **delay** before the transport actually seeks to the given position

Tested on Chrome 83 / Linux (Ubuntu 20.04)

**Comment by bduffany** [comment]
A workaround is to change the implementation of `pause` to

```typescript
const sec = Tone.Transport.seconds;
Tone.Transport.stop();
Tone.Transport.seconds = sec;
```

but I'm not sure if this has any downsides?

**Comment by tambien** [comment]
thanks for the test case. I think this should be fixed as soon this commit builds

**Comment by bduffany** [comment]
Can no longer reproduce the problem in the JSFiddle. Huge thanks for the fix, and for the work you've been doing on this library!
