### ISSUE TITLE
Is there any chance to connect oscilloscope.js with tone.js?

### ISSUE THREAD

**Issue by doubledare704** [Tonejs/Tone.js#707]
`            const scope = new Oscilloscope(Tone.Destination)
`
I try to connect oscilloscope to tone.js, but it requires AudioNode instance. I thought every base class of tone.js is audionode.

**Comment by pendragon-andyh** [comment]
oscilloscope.js is throwing an exception if the ```source``` is not a "proper" AudioNode instance. Tone.js nodes "wrap" around proper AudioNodes.

You should be able to create a normal WebAudio GainNode, then it connect from Tone.Destination (or any ToneAudioNode object) to that GainNode ... and then connect the GainNode to oscilloscope.js

**Comment by tambien** [comment]
if you are connecting from a raw Web Audio node, you could use `Tone.connect(WebAudioNode, ToneAudioNode)`. If that doesn't work, all Tone.js AudioNodes have an `input` and `output` property. You could try `scope.connect(Tone.Destination.input)`

**Comment by doubledare704** [comment]
@tambien and @pendragon-andyh thank you for advice, I'll try it

**Comment by doubledare704** [comment]
I'm using oscillator from tone.js to produce sound, and connecting oscilloscope to gain doesn't work for me.
```
 const gainNode = new Gain(0).toDestination();
 const osc = new Oscillator(freq, "sine4").connect(gainNode);
 osc.toDestination().start();
 const scope = new Oscilloscope(gainNode)
 let canvas = document.getElementById('osc');
 scope.animate(canvas.getContext("2d"))
```
Uncaught Error: Oscilloscope source must be an AudioNode

**Comment by pendragon-andyh** [comment]
For my suggestion you needed to create a web audio gainNode ... something like:
```
osc.context.createGainNode()
```

Or @tambien's would definitely work.

In both cases you will be using a plain web audio node instead of a wrapper object.

**Comment by tambien** [comment]
To expand on @pendragon-andyh point, try this code out: 

```javascript
const webAudioGain = Tone.getContext().createGain()
const toneOsc = new Tone.Oscillator().connect(webAudioGain)
const scope = new Oscilloscope(webAudioGain)
```

Basically just connects the Tone.js node you want to visualize to a raw gain node before using it within Oscilloscope
