### ISSUE TITLE
The note velocity is ignored or overwritten by some other note

### ISSUE THREAD

**Issue by stephaneeybert** [Tonejs/Tone.js#708]
The velocity which is supposed to be within a NormalRange of 0 and 1 is not affecting the loudness of the playing when the notes are on several tracks in a soundtrack.

The [stackblitz](https://stackblitz.com/edit/angular-tone-9k2yhg) tries to show an example.

**Comment by tambien** [comment]
Thanks for the issue, but i don't understand the intended behavior of this example. I don't hear the harmony and melody played at the same time. When i click "Play both harmony and melody", i only hear one voice.

**Comment by stephaneeybert** [comment]
Yes, that is the issue, me too I hear only one voice when I click the Play both harmony and melody button. I reckon we should hear the two voices, since we can hear each of them when played alone.

**Comment by tambien** [comment]
One issue might be that the polyphony of your PolySynth (first argument) set to 1, which means that only one voice can be played simultaneously. 

[Here's a minimal example](https://stackblitz.com/edit/angular-tone-vxganw?file=main.ts) of a PolySynth where each note has a different velocity. It sounds like it's not ignoring the other voice's velocity argument.

**Comment by stephaneeybert** [comment]
I updated the example to use my synth:

    this.synth = new Tone.PolySynth(2, Tone.Synth, {
      oscillator: {
        type: 'sine',
      }
    }).toMaster();

It's a poly synth but still the issue persists.

I found the sound of this synth:
    //this.synth = new Tone.PolySynth(2, Tone.MonoSynth).toMaster();
too poor.

**Comment by tambien** [comment]
I'm not sure i understand what you mean when you say the velocity is ignored. It sounds like the velocity that you pass in is used, this is more evident if you make the velocity much smaller like `this.playMeasures(this.harmonyMeasures, 0.01);`

**Comment by stephaneeybert** [comment]
I could fix the example and indeed with the loud enough velocities I can hear the two tracks at the same time now.

**Comment by stephaneeybert** [comment]
I'm now onto something more precise.

The [example](https://stackblitz.com/edit/angular-tone-9k2yhg) shows the behaviour.

On a multi tracks soundtrack, when two SAME NOTES of different tracks are played at the SAME TIME, only the note with the softer velocity is heard.

Here are my observations:

If the two notes are different and at the same time, then both are heard. Correct.

If the two notes are identical but not at the same time then both are heard. Correct.

If the two notes are identical and at the same time then only the softer velocity note is heard. Incorrect. We should hear the loud velocity note.

I hope I'm not wrong in my expectation :-)

**Comment by tambien** [comment]
ok got it, thanks for clarifying. From what i can tell from your example, this is the expected behavior. The API metaphor is like a piano keyboard: you can't press the same note twice at the same time. You have to release the note some you can press it again. I think it's just going with lower velocity because that's the second one that's triggered. 

My recommendation is to use two synthesizers, one for each voice if there's a chance that the voice will play twice.

**Comment by stephaneeybert** [comment]
All right ! Thanks a lot for the explanation and the hint ! Will give it a try.
