### ISSUE TITLE
Tone.Meter only receives hard left panned value from Tone.Channel

### ISSUE THREAD

**Issue by JohannesKlauss** [Tonejs/Tone.js#709]
I have a simple mono channel connection: `Tone.Player -> Tone.Channel -> Tone.Meter -> Tone.Destination`

But the `Tone.Meter` receives values depending on the pan settings of `Tone.Channel`. When it's panned hard left I get high values, when it's panned hard right it goes to -Inf, even though the volume doesn't change.

Is this a bug? Or do I have to connect them differently? I also used `channel.fan(meter, Tone.Destination)`, but the result was the same.

**Comment by tambien** [comment]
Tone.Channel is outputting a stereo signal, and Tone.Meter is only reading one channel (the left channel. Pass in the channel parameter to the constructor `new Tone.Meter({channel: 2})` in order to make Tone.Meter listen for stereo signals.
