### ISSUE TITLE
FR: Ramp n Oscillators in frequency sync. ex: two Oscillators playing a musical third apart, when source Osc is ramped, the connected Oscillators still stays a third apart 

### ISSUE THREAD

**Issue by OscarDev** [Tonejs/Tone.js#710]
feature request

Currently the value that you pass in to an oscillator's frequency field is static, if it could be dynamic via reference, that would be so awesome

using `web audio api` syntax
`
oscillatorA.frequency.value = 0;
oscillatorA.frequency.linearRampToValueAtTime(4000,
                context.currentTime + 2
              );
oscillatorB.frequency.reference = oscillatorA.frequency.value * 2;
// oscillatorB will always stay an octave apart as oscillatorA ramps, I chose an octave for simplicity. A musical third would some float number representing the ratio
`

**Comment by tambien** [comment]
You can connect a control signal to both frequency values and use Tone.Multiply to specify a ratio between the two signals like this: 

```javascript
const ctrlFreq = new Tone.Signal(440)
const thirdMult = new Tone.Multiply(Tone.intervalToFrequencyRatio(4))
const osc0 = new Tone.Oscillator().toDestination().start()
const osc1 = new Tone.Oscillator({type: "square"}).toDestination().start()
  
ctrlFreq.connect(osc0.frequency)
ctrlFreq.chain(thirdMult, osc1.frequency)
  
ctrlFreq.rampTo(880, 4)
```

Here's [a live example](https://jsfiddle.net/yotammann/2gehLytp/)
