### ISSUE TITLE
Using vanilla AudioWorklet and ScriptProcessor nodes with Tone 14+

### ISSUE THREAD

**Issue by jackschaedler** [Tonejs/Tone.js#712]
Assuming that you have some code or a library which provides you with vanilla `ScriptProcessor` and/or `AudioWorklet` nodes...

Prior to the use of `standardized-audio-context`, it was relatively easy to have these nodes happily co-existing with a Tone-built audio graph. Calling the normal `connect` functions just worked for both Tone nodes as well as nodes created directly through the normal WebAudio API. 

In Tone 14+, it now doesn't seem possible to add native nodes to the graph, unless they were created through either the `standardized-audio-context` or Tone API(s).

I wonder if there is some way to make it easier for people to "bring their own" native WebAudio nodes to Tone, especially if they are in a situation where it isn't feasible to change the code which creates those nodes, or they need to use ScriptProcessor for Safari support.

I could imagine something like a utility call which would allow a client to "wrap" a native node for use inside Tone?

@chrisguttandin and I briefly chatted about this over slack...

**Comment by tambien** [comment]
does it work if you use `setContext` with the AudioContext belonging to your own nodes? You'll miss out on the cross-browser compatibility provided by standardized-audio-context, but i think something like that should work. Does that accomplish what you're looking to do?

**Comment by tambien** [comment]
Here's a minimal example of using a "vanilla" AudioWorklet inside Tone.js. The only difference here is that you've got to extend standardized-audio-context's AudioWorkletNode to allow it to work Tone.js' context. You'll also need to connect it up using `Tone.connect`

```js
import { getContext } from "tone";
import { AudioWorkletNode } from "standardized-audio-context";

class MyWorkletNode extends AudioWorkletNode {
  constructor(context) {
    super(context, "my-worklet-processor");
  }
}

// get the raw AudioContext
const context = getContext().rawContext;

context.audioWorklet.addModule("./processor.js").then(() => {
  let node = new MyWorkletNode(context);
  console.log(node);
});
```

Unfortunately you won't be able to make a ScriptProcessorNode since it's deprecated and standarized-audio-context doesn't implement it. 

Hope this answers your question!

**Comment by jackschaedler** [comment]
Hi Yotam! thanks for taking a look at this. In broad strokes this certainly does allow for a path forward for AudioWorklet. It's a bummer that AudioWorklet isn't in Safari yet, but it looks like that might be coming soon: https://trac.webkit.org/changeset/267744/webkit

**Comment by micbuffa** [comment]
One of my students is using the Tone Sequencer along with a Tone synth. We are using our own AudioContext, and Tone.setContext to tell Tone to use it too. When we try to connect a Tone synth with a regular audio node (i.e a gain node) we get a DOM Exception error. Also, when we try to use the Tone.context or Tone.context.rawContext objects to instanciate a WebAudio Module (i.e Audio Worklet node/processor), it crashes always in the addModule call, saying that the context is not a proper BaseAudioContext.... How can we connect a tone synth to a regular webaudio subgraph?

**Comment by dirkk0** [comment]
@micbuffa can you create a minimal codepen or jsfiddle to show the problem?
