### ISSUE TITLE
No playback on iOS WKWebView when build and real device

### ISSUE THREAD

**Issue by martijnmichel** [Tonejs/Tone.js#713]
ToneJS will not load/play an mp3 sample on iOS. You can try out "Learn music theory with Sonid" live in the appstore or go to https://web.sonid.app to test out the web version (where audio works fine).

**Where it works:**
iOS - dev and build on all browsers
iOS - development on simulator
iOS - development on real device

**Where it does NOT work:**
iOS - build on real device (through TestFlight or ready to use build)

Testing is so hard having to upload to appstore connect for every little thing i try ;/

Please anyone come with a fix, ive had this issue for months now.

Thanks.

**Comment by tambien** [comment]
Sorry to hear you're still having this issue. I'm not sure this is a Tone.js bug and i don't know how to fix it or even reproduce the issue. 

It seems like it's an issue with WKWebView which might relate to Web Audio and not Tone.js specifically. Could you try building a vanilla Web Audio example and see if that makes sound? Is there an error reported?

**Comment by tambien** [comment]
Unfortunately i have no way of reproducing this issue, and don't know if it's related to Tone.js or the Web Audio implementation in this specific environment. I'll have to close. If people find work arounds, would be great to chime in.

**Comment by tambien** [comment]
Does [this SO answer](https://stackoverflow.com/a/62446136) help at all?

**Comment by martijnmichel** [comment]
Unsure how to apply that to my project as i am using cordova. However I did try loading my samples a bit later in my app (vue => created() hook) and also swapping around the preferences inside config.xml for cordova.

Still no luck ;/
