### ISSUE TITLE
Rhythm section of chrome music lab isn't working on chromebooks.

### ISSUE THREAD

**Issue by velois129** [Tonejs/Tone.js#715]
I don't write codes or do any programming. I want to use the rhythm section of chrome music lab and it's not working on my Chromebook - meaning it more likely won't on my students' either.

If this is not a suitable issue for this forum, I digress.

**Comment by tambien** [comment]
Thanks for the issue, but this is related to https://github.com/googlecreativelab/chrome-music-lab, not this repo. If you're looking for a fix, i suggest you file it there.
