### ISSUE TITLE
Emitter callbacks with off removed incorrectly

### ISSUE THREAD

**Issue by jounii** [Tonejs/Tone.js#717]
I noticed a small bug with Emitter off implementation. It is using forward traversing and inline splice modification of the same array it is traversing. This causes element skips and if the same callback is attached twice in a row, it skips check of the latter one. Fix is to traverse the array in reverse so the array is nudged on already traveled elements.

https://github.com/Tonejs/Tone.js/blob/ed0d3b08be2b95220fffe7cce7eac32a5b77580e/Tone/core/util/Emitter.ts#L75-L79

Normally you would just have attached the same callback only once, so the bug does not appear even though element check is skipped. And it does remove multiple instances of the same callback fine if they are not attached next to each other.

**Comment by tambien** [comment]
thanks for the detailed bug report. Happy to accept a PR so you can get contributor credit for your find, otherwise i'll push a fix when i have a spare moment.
