### ISSUE TITLE
iOS 14 broke reverb and vibrato

### ISSUE THREAD

**Issue by jasonhibbs** [Tonejs/Tone.js#720]
## What I know

Since iOS 14, adding vibrato or reverb no longer works on my iPhone XS.

An error suggests something to do with `panWaveShareNode.inputs`, something I can’t find in the Tone.js repository.

## What I have

To keep my project alive [I isolated my synth setup with a try/catch](https://github.com/jasonhibbs/ocarina/commit/0d75df057d61b29b0afd6dd8c960030535b92c07#diff-70baadf89fe3df4e2d8ccfd1fcad6233).

I couldn’t make a JSFiddle work, but [the repo is here](https://github.com/jasonhibbs/ocarina), and [playable here](https://ocarina.netlify.app/).

This is the error:

![Screenshot 2020-08-22 at 17 52 35](https://user-images.githubusercontent.com/919628/90961630-3009b980-e4a2-11ea-9507-bec0fabee7f9.png)

```
TypeError: undefined is not an object (evaluating 'panWaveShaperNode.inputs[0]')
  connectGraph — native-stereo-panner-node-faker-factory.js:109
  whenConnected — native-stereo-panner-node-faker-factory.js:240
  (anonymous function) — monitor-connections.js:13
  [native code]
  (anonymous function) — wrap-audio-node-disconnect-method.js:7
  connectNativeAudioNodeToNativeAudioNode — connect-native-audio-node-to-native-audio-node.js:8
  connect — audio-node-constructor.js:323
  CrossFade — CrossFade.js:77
  Effect — Effect.js:17
  Reverb — Reverb.js:24
  _callee2$ — SynthKeys.vue:133
  tryCatch — runtime.js:63
  invoke — runtime.js:293
  asyncGeneratorStep — asyncToGenerator.js:3
  _next — asyncToGenerator.js:25
  (anonymous function) — asyncToGenerator.js:32
  Promise
  (anonymous function) — asyncToGenerator.js:21
  setupSynth
  _callee$ — SynthKeys.vue:71
  tryCatch — runtime.js:63
  invoke — runtime.js:293
  asyncGeneratorStep — asyncToGenerator.js:3
  _next — asyncToGenerator.js:25
  promiseReactionJob
```

**Comment by chrisguttandin** [comment]
As @TaoJinjin-Thomas said the error comes from inside `standardized-audio-context`. However I think it's a good sign. Currently a bug is used to [detect Safari](https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/factories/native-wave-shaper-node-factory.ts#L20) and to apply a workaround. It looks as if this bug is fixed in the current preview of Safari. Although this was not mentioned in the release notes.

Do you have an idea when Safari v14 is going to be released?

**Comment by jasonhibbs** [comment]
It does seem positive. Major iOS updates have been released around 18th September for the last few years.

**Comment by lehni** [comment]
I am seeing this also, on macOS Safari 14, released today.

**Comment by lehni** [comment]
https://github.com/chrisguttandin/standardized-audio-context/blob/c7565cf469ade950832a773c7bdd24dcd0453717/src/factories/native-stereo-panner-node-faker-factory.ts#L49

**Comment by chrisguttandin** [comment]
Thanks for the heads up. A fix for standardized-audio-context is on it's way.

**Comment by lehni** [comment]
@tambien would be great to get a release with the above fix in ☝️

**Comment by lehni** [comment]
I don't mean to nag, is there be a new release planned for this fix?

**Comment by tambien** [comment]
tone@14.7.56 includes that fix

**Comment by lehni** [comment]
Thanks @tambien, I missed that because it's not listed on https://github.com/Tonejs/Tone.js/releases

**Comment by jordaneast1** [comment]
Hi, I have the same issue but with FeedbackDelay, I am on @14.7.58.
![image](https://user-images.githubusercontent.com/42902875/95795743-d6519d00-0d36-11eb-8fba-8209f657e135.png)
