### ISSUE TITLE
Tone.Players not working as expected

### ISSUE THREAD

**Issue by julian-aimusic** [Tonejs/Tone.js#723]
**Repro:**
Example working in @13.x: https://jsfiddle.net/1qtb0x3z/4/
Example not working in @latest: https://jsfiddle.net/1qtb0x3z/5/

Also, I think Typescript type for `Players.get()` is incorrect, I think it's coming from `ToneWithContext` class where the get() method receives no arguments - however the Players.get() requires passing the name of the player in.

Not sure if this warrants a separate issue or if it's related?

Hope this is clear enough

**Comment by tambien** [comment]
Thanks for the issue. This is caused by a breaking API change between 13 and 14. `Players.get('name')` is now `Players.player('name')`. This change makes Players more consistent with the rest of the classes which return the object's properties when you call `get`.

**Comment by julian-aimusic** [comment]
would be cool to get this updated: https://tonejs.github.io/docs/r13/Players
