### ISSUE TITLE
Save and load local files in playlist?

### ISSUE THREAD

**Issue by zilveer** [Tonejs/Tone.js#727]
Hi,
Is it possible to load local files both on desktop and mobile and in someway save the playlist on the client side (without any servers involved) so it can be loaded later on ?

How can achieve this without using 
Any advice would be appreciated. 

Regards Zilveer

**Comment by TaoJinjin-Thomas** [comment]
ipfs + localStoarge?
But you need to set up the environment to use ipfs, if you use docker, it will be more convenient.

**Comment by zilveer** [comment]
@TaoJinjin-Thomas thx for the quick reply. 
I am aware of IPFS and GunDB also, but there is no need to save any music at all since they are  in the users device hence I only want to save and load a playlist .

**Comment by tambien** [comment]
Thanks for chiming in @TaoJinjin-Thomas. I'll add: maybe the FileReader API would be helpful here? 

Going to close this issue since it's not specific to Tone.js

**Comment by zilveer** [comment]
@tambien indeed it would,  also consider to add localForge (https://github.com/localForage/localForage)

Regards
