### ISSUE TITLE
Dynamically change samples urls in a Tone.Sampler 

### ISSUE THREAD

**Issue by virouncode** [Tonejs/Tone.js#729]
Hi, 

I have a Tone.Sampler instrument defined as following : 
const piano = new Tone.Sampler(
    { 
        C1: "audio/piano-C1.mp3",
        G1: "audio/piano-G1.mp3",
        C2: "audio/piano-C2.mp3",
        G2: "audio/piano-G2.mp3",
        C3: "audio/piano-C3.mp3",
        G3: "audio/piano-G3.mp3",
        C4: "audio/piano-C4.mp3",
        G4: "audio/piano-G4.mp3",
        C5: "audio/piano-C5.mp3",
        G5: "audio/piano-G5.mp3"		
    }
);

I'd like to use an eventListener on a button to dynamically change the 'audio' folder while the Transport is started. 
Is there any way to access the url I entered ? If piano was an object I would access by piano.C1, piano.G1, etc...

But i don't really know what kind of entity is Tone.Sampler.

Thank you

**Comment by tambien** [comment]
Currently it's not possible to adjust the URL of the loaded samples in Tone.Sampler. I might recommend that you use two Samplers each preloaded with the set of samples you want. This will also save loading time when you switch between sample sets.
