### ISSUE TITLE
Cannot set property Transport of #<Object> which has only a getter

### ISSUE THREAD

**Issue by hackerxian** [Tonejs/Tone.js#731]
I used `tone.js` in react, but use 

```
import Tone from "tone";
```
get error : `Cannot set property Transport of #<Object> which has only a getter`

demo: https://codesandbox.io/s/angry-tereshkova-q07wl?file=/src/index.js

tonejs: 14.7.39

**Comment by tambien** [comment]
Try `import * as Tone from 'tone'`

**Comment by hackerxian** [comment]
@tambien  get the same error

**Comment by tambien** [comment]
Seems related to #699. Could you describe the setup to reproduce the error?

**Comment by hackerxian** [comment]
If I don't use codesandbox, in my project use webpack compile, it will show error: 

```
Uncaught (in promise) TypeError: Cannot assign to read only property 'Symbol(Symbol.hasInstance)' of function 'function AudioBuffer(options) {
      if (nativeOfflineAudioContextConstructor === null) {
        throw new Er...<omitted>... }'
    at audio-buffer-constructor.js:8
    at createAudioBufferConstructor (audio-buffer-constructor.js:8)
    at Module../node_modules/_standardized-audio-context@24.1.26@standardized-audio-context/build/es2019/module.js (module.js:215)
    at __webpack_require__ (bootstrap:837)
    at fn (bootstrap:129)
    at Module../node_modules/_tone@14.7.39@tone/build/esm/core/context/AudioContext.js (AudioContext.js:1)
    at __webpack_require__ (bootstrap:837)
    at fn (bootstrap:129)
    at Module../node_modules/_tone@14.7.39@tone/build/esm/core/Global.js (Global.js:1)
    at __webpack_require__ (bootstrap:837)
```

**Comment by OliCpg** [comment]
Saame issue both on local webpack or in codesandbox. Any news on this ?

**Comment by tambien** [comment]
Unable to recreate this error outside of the codesandbox example. These are my steps to try and reproduce it locally

```bash
npx create-react-app test-project
cd test-project
yarn add tone@next
yarn start
```

And added this import to index.js: `import { Transport } from "tone";`

It compiles and runs fine. could you walk me through the steps of reproducing this locally?

**Comment by tambien** [comment]
Going to close in favor of #699. Please continue discussion there. Still looking for a repro case, since i'm unable to reproduce this issue outside of codesandbox and unable to debug there.

**Comment by rileyjshaw** [comment]
I just encountered this same issue using tonejs `14.7.77` in a Gatsby v4 project:

> TypeError: Cannot assign to read only property 'Symbol(Symbol.hasInstance)' of function 'function AudioBuffer(options){if(nativeOfflineAudioContextConstructor===null){throw new Error('Missing the nati...<omitted>...;}'

I’ll read through the `AudioBuffer` code and see if I can come up with anything.

**Comment by rileyjshaw** [comment]
I haven’t been able to find a quick solution, but I may have found some clues. I think this is actually an issue with the dependency [`standardized-audio-context`](https://github.com/chrisguttandin/standardized-audio-context).

An expanded stack trace referenced “`createAudioBufferConstructor`”. This and `nativeOfflineAudioContextConstructor` are both from the `standardized-audio-context` dependency. Looking closer at that library, it seems to directly assign `Symbol.hasInstance` in a few places, which explains the error.

I’ll log a bug on that repo as well, but I don’t have more time to look into this today. Hopefully this helps someone encountering the same issue!

---

Steps to reproduce:

This is far from a minimal demo, but the site I’m working on is open source at https://github.com/rileyjshaw/rileyjshaw.github.io. To see the build error locally:

```
npm i -g gatsby-cli
gatsby telemetry --disable  # optional
git clone --single-branch --branch dev https://github.com/rileyjshaw/rileyjshaw.github.io demo-site
cd demo-site
npm i
BABEL_ENV=test gatsby build
```
