### ISSUE TITLE
FatOscillator: unknown behavior changes since 13.8.25

### ISSUE THREAD

**Issue by Matsyir** [Tonejs/Tone.js#733]
May not exactly be a bug, but FatOscillators played in a PolySynth sound different compared to 13.8.25, and I don't see them mentioned in the changelog so I'm having a hard time understanding what changed. I see we no longer specify voiceCount for PolySynth, so it may be related to that, but I don't see why that would change how FatOscillators are played/how they sound.

It sounds to me like "phase collision" (probably my made up name), where multiple oscillators play at the same phase so we get this odd beam/lazer sound in the background, it kind of sounds like there's a pitch bend going downwards for a part of the synth.

https://jsfiddle.net/uLptm5ck/5/
This example (in 14.7.40, the latest) will first play a chord with a fatsawtooth, where you can hear the odd phasing sound.
Afterwards, it plays the same chord with a regular sawtooth, which sounds clean.
With the same code in 13.8.25 (with an added voiceCount argument to the PolySynth constructor), the fatsawtooth chord would sound more "clean" similarly to the regular sawtooth one here, without the odd phasing noise: https://jsfiddle.net/9ejh4mtr/

You will probably need to re-run the fiddle to ensure the first chord's notes are played simultaneously. When they're slightly offset (whether it's intentional or from lag), it sounds clean which reinforces that this is likely related to the osc's phases.

This is very possibly the expected/desired default behavior, but I would like to see it mentioned in the changelog or explained otherwise because I'm not too sure how to approach this "problem". I could think of ways to randomize each voices' phase, but since they're dynamically created and disposed, it seems like that would be a very tedious and needlessly intensive process.

edit: the problem may be that the phases _are_ offset rather than synced, I forget which causes this kind of sound. Either way, I mostly just want to understand what has changed so I could reliably go back to the old behavior

**Comment by tambien** [comment]
Good catch! the phase was not being offset correctly which was causing the phaser-y sound of the oscillators. Just pushed a change which should fix that.
