### ISSUE TITLE
Bug : Part don't make a sound

### ISSUE THREAD

**Issue by sarahBuisson** [Tonejs/Tone.js#736]
I have issue with Tone. Part.

Nor my code not the sample in https://tonejs.github.io/docs/14.7.39/Part.html don't make any sound. I use chrome, last version, on a mac.

**Comment by tambien** [comment]
Thanks for pointing out the issue in the docs. They are missing the line `Tone.Transport.start()`. Since Part is synced to the Transport, it does not start until the Transport is also started.
