### ISSUE TITLE
"DOMException" when using AudioWorklets (Electron, Webpack)

### ISSUE THREAD

**Issue by dschu-lab** [Tonejs/Tone.js#738]
I'm currently building an Electron app using ToneJS, but I'm having issues when trying to instantiate a BitCrusher, which is using an AudioWorklet.

When executing `const bitCrusher = new Tone.BitCrusher(4);`, the app crashes with the following error:

```
Uncaught (in promise) DOMException
ToneAudioWorklet @  ToneAudioWorklet.js:21
BitCrusherWorklet @ BitCrusher.js:49
BitCrusher @  BitCrusher.js:25
```

Is there a webpack configuration I am missing or something?
Thanks!

**Comment by chrisguttandin** [comment]
Hi @dschu-lab, unfortunately the error messages thrown by the AudioWorklet are very generic. On top of that Tone.js creates a dynamic blob with the worklet code which gets then transformed again by standardized-audio-context. It's very hard to debug this.

Anyway I have a suspicion. Is it possible that you are already using another node of Tone which also uses and AudioWorklet internally? Can you please try using the BitCrusher in isolation? I wonder if that will work.

**Comment by dschu-lab** [comment]
Thanks @chrisguttandin  for the quick reply. The`transformed again by standardized-audio-context` part is interesting, since I'm creating my own AudioContext using the build-in AudioContext (new AudioContext()) and after that use `Tone.setContext()` to set the correct context.

I will try to use `standardized-audio-context` instead to see if that helps!

**Comment by dschu-lab** [comment]
Replacing the built-in `AudioContext` with the `standardized-audio-context` results in new errors (`Uncaught Error: param must be an AudioParam @Debug.js:8`) 😞

**Comment by chrisguttandin** [comment]
Interesting. When you say "replacing" do mean just doing nothing or do you set the context from outside? Since Tone v14 standardized-audio-context is used for the built-in context which means you don't have to do anything special to use it.

**Comment by dschu-lab** [comment]
It was like this before
```
const audioContext = new AudioContext();
Tone.setContext(context);
```

And I just added `import { AudioContext } from "standardized-audio-context";` at the beginning of the file.

I'm creating my own context simply because I need to attach them to HTMLAudioElements via `createMediaStreamDestination` and figured that would be the way to do so.

**Comment by dschu-lab** [comment]
Oh, I just figured it out!

Instead of `const audioContext = new AudioContext();`, I just had to do `const audioContext = Tone.Context()` and leave the rest as it is (`audioContext.createMediaStreamDestination`, etc).

I can now use `BitCrusher` without any errors being thrown!

Thanks again, the audio context part was indeed the thing I had to look at to resolve my issue!

**Comment by chrisguttandin** [comment]
I'm glad you found a solution.
