### ISSUE TITLE
Errors when bundling with Webpack

### ISSUE THREAD

**Issue by virouncode** [Tonejs/Tone.js#739]
Hello, 

Thank you for creating this amazing library.
I'm having issues when using webpack. To reproduce the error : 

**/src/index.js** 
import Transport from 'Tone/core/clock/Transport';

**/dist/index.html** 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tone.js with webpack</title>
</head>
<body>
    <button id="play-button">Play</button>
    <script src="bundle.js"></script>
</body>
</html>

/node_modules : a bunch of modules including 'tone' and 'babel'

**webpack.config.js** 
const path = require('path');

module.exports = {
    entry: './src/index.js',
    mode : "production",
    module: {
      rules: [
        {
            test: /\.tsx?$/,
            use: 'ts-loader',
        },
        {
            test: /\.m?js$/,
            use: {
                loader: 'babel-loader',
                options: {
                  presets: ['@babel/preset-env']
                }
            }
        }
      ],
    },
    resolve: {
      extensions: [ '.tsx', '.ts', '.js' ],
      modules: [path.resolve(__dirname, 'node_modules/tone'), 'node_modules']
    },
    output: {
      filename: 'bundle.js',
      path: path.resolve(__dirname, 'dist'),
    },
};

**tsconfig.json** 
{
    "compilerOptions": {
      "outDir": "./dist/",
      "noImplicitAny": true,
      "module": "es6",
      "target": "es5",
      "jsx": "react",
      "allowJs": true
    }
  }

When i 'npx webpack' in the terminal i get those errors : 

ERROR in /Users/myname/Desktop/ToneTest/node_modules/tone/Tone/core/clock/Transport.ts
[tsl] ERROR in /Users/myname/Desktop/ToneTest/node_modules/tone/Tone/core/clock/Transport.ts(190,17)
      TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.

ERROR in /Users/myname/Desktop/ToneTest/node_modules/tone/Tone/core/clock/Transport.ts
[tsl] ERROR in /Users/myname/Desktop/ToneTest/node_modules/tone/Tone/core/clock/Transport.ts(311,17)
      TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.

ERROR in /Users/myname/Desktop/ToneTest/node_modules/tone/Tone/core/clock/Transport.ts
[tsl] ERROR in /Users/myname/Desktop/ToneTest/node_modules/tone/Tone/core/clock/Transport.ts(314,11)
      TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.

etc...........

Sorry, I can't find what i'm doing wrong :-(

**Comment by tambien** [comment]
Definitely seems related to #731 and #699 

Thanks for putting together a detailed reproduction case! i will try to take a look soon and see if i can debug anything. my first impulse is that this somehow is creating an ES3 target instead of an ES5 target. Because it seems like the issue is that babel is not compiling Tone which currently is setup to output ES5 code (that includes things like `Object.assign()`)

**Comment by tambien** [comment]
Just tried reproducing your code and there's a couple of small fixes that seems to make it work. doesn't seem like a Tone.js issue to me, but maybe just a way that your project is configured:

If i remove these lines from your webpack.config

```
resolve: {
  extensions: [ '.tsx', '.ts', '.js' ],
  modules: [path.resolve(__dirname, 'node_modules/tone'), 'node_modules']
}
```

and change the import to `import {Transport} from 'tone'`, then it all compiles ok for me.
