### ISSUE TITLE
IOS inconsistent after two Minutes. (Android-no Problem)

### ISSUE THREAD

**Issue by SimeonLukas** [Tonejs/Tone.js#742]
Dear Tambien
thanks for your great tone.js Software.
I love it.

I have a Problem on Iphone.
Please take a look at
http://pastoralculture.de/bist/index.html

After two minutes the ticks are inconsistent.
On Chrome I have no Problem, just Safari on IOS has this issue.

Please help.
Greetings from Bavaria,
Simeon

const panner = new Tone.Panner(1).toDestination();
const panner2 = new Tone.Panner(-1).toDestination();
panner.pan.setValueAtTime(1, 0.5);
panner2.pan.setValueAtTime(-1, 0.5);
var leftEar = new Tone.Synth(
{
	"oscillator" : {
		"type" : "sine"
	},
	"envelope" : {
		"attack" : 0.001,
		"decay" : 0.001,
		"sustain" : 0,
		"release" : 0,
	}
}
);
var rightEar = new Tone.Synth(
{
	"oscillator" : {
		"type" : "sine"
	},
	"envelope" : {
		"attack" : 0.001,
		"decay" : 0.001,
		"sustain" : 0,
		"release" : 0,
	}
}
);
var x1 = document.getElementById("bpm").value;
document.getElementById("anzeige_bpm").innerHTML = x1 + " bpm";
var x2 = document.getElementById("volume").value;
document.getElementById("anzeige_volume").innerHTML = x2 + " dB";
var x3 = document.getElementById("hoehe").value;
document.getElementById("anzeige_hoehe").innerHTML = x3 + " Hz";
var vol = 0;
function lefttriggerSynth(){
    leftEar.connect(panner2).triggerAttackRelease(tonhoehe, 0.003);
	Tone.Transport.clear();

}
function righttriggerSynth(){
    rightEar.connect(panner).triggerAttackRelease(tonhoehe, 0.003);
	Tone.Transport.clear();
	
}
Tone.Transport.context.debug = true;
Tone.Transport.context.latencyHint = 0;
Tone.Transport.context.lookAhead = 1;
Tone.Transport.context.updateInterval = 0.001;
Tone.Transport.context.clockSource = "timeout";
Tone.Transport.setLoopPoints(x1-x1, x1/100);
Tone.Transport.loop = true;
rightEar.volume.setValueAtTime(vol);
leftEar.volume.setValueAtTime(vol);
Tone.Transport.schedule(righttriggerSynth, x1-x1);
Tone.Transport.schedule(lefttriggerSynth, x1/200);
tonhoehe = document.getElementById("hoehe").value;
Tone.Transport.bpm.value = x1 / 2;
document.querySelector('#start').addEventListener('change', function(e){
	if (e.target.checked){
Tone.Transport.context.resume();
Tone.Transport.start();
AVAudioSession.setCategoryWithOptions(
    AVAudioSession.Categories.PLAYBACK,
	AVAudioSession.CategoryOptions.MIX_WITH_OTHERS,
);
}
else {
Tone.Transport.stop();
	}
});
document.querySelector('#bpm').addEventListener('input', function(e){
	Tone.Transport.bpm.value = parseInt(e.target.value) / 2;
	var x1 = document.getElementById("bpm").value;
    document.getElementById("anzeige_bpm").innerHTML = x1 + " bpm";
})
document.querySelector('#volume').addEventListener('input', function(e){
	Tone.Master.volume.value = parseInt(e.target.value);
	var x2 = document.getElementById("volume").value;
    document.getElementById("anzeige_volume").innerHTML = x2 + " dB";
})
document.querySelector('#hoehe').addEventListener('input', function(e){
	tonhoehe = parseInt(e.target.value);
	var x3 = document.getElementById("hoehe").value;
    document.getElementById("anzeige_hoehe").innerHTML = x3 + " Hz";
})

**Comment by tambien** [comment]
hi @SimeonLukas. These lines jump out to me as potentially causing a problem

```javascript
Tone.Transport.context.latencyHint = 0;
Tone.Transport.context.lookAhead = 1;
Tone.Transport.context.updateInterval = 0.001;
Tone.Transport.context.clockSource = "timeout";
```

if you remove them does that help?

**Comment by SimeonLukas** [comment]
Thanks for your quick answer.
I'm sorry but the Problem is still there.

Is this specific to ios/safari?

**Comment by tambien** [comment]
Pass in the time which is given by `Transport.schedule` in order to precisely schedule events: 

```js
// a time value is given to the callback as the first argument from Transport.schedule
function righttriggerSynth(time){
  // don't need to reconnect it to the panner each time
  // rightEar.connect(panner).triggerAttackRelease(tonhoehe, 0.003);

  // use the time value to schedule the attackRelease
  rightEar.triggerAttackRelease(tonhoehe, 0.003, time);
}

Tone.Transport.schedule(righttriggerSynth, x1-x1);
```

**Comment by SimeonLukas** [comment]
Thank you for you answer.

I'm sorry.
It is still not working.


function lefttriggerSynth(time){
    leftEar.triggerAttackRelease(tonhoehe, 0.003, time);

}
function righttriggerSynth(time){
  rightEar.triggerAttackRelease(tonhoehe, 0.003, time);
	
}
Tone.Transport.setLoopPoints(x1-x1, x1/100);
Tone.Transport.loop = true;
rightEar.connect(panner);
leftEar.connect(panner2);
Tone.Transport.schedule(righttriggerSynth, x1-x1);
Tone.Transport.schedule(lefttriggerSynth, x1/200);

**Comment by Freeride91** [comment]
I think it could be related to my recently posted issue: https://github.com/Tonejs/Tone.js/issues/784

**Comment by tambien** [comment]
Seems like this is no longer an issue on #784, so might have been a bug with Safari which was patched. I'm unable to verify using your link that you provided both because i can't easily inspect/edit the code, and also the page is throwing an error now so can't get the example to run. 

Please let me know if it's still an issue and maybe you could move a minimal version of your example to codesandbox or jsfiddle so it'e easier to inspect.
