### ISSUE TITLE
High CPU use when idle on Firefox / MacOS

### ISSUE THREAD

**Issue by 4lejandrito** [Tonejs/Tone.js#743]
Hi!

I am a happy user of Tone in my guitar project (https://react-guitar.com). However I found that the battery of my Mac dies too quickly while I have the site open. After investigating I found that Tone is to blame :(

I have set up a little site to reproduce the issue: https://4lejandrito.github.io/tone-js-firefox-cpu-issue ([source](https://github.com/4lejandrito/tone-js-firefox-cpu-issue/blob/master/index.html)).

1. Open the site on Firefox on MacOS.
2. Open the activity monitor.
3. Check that the coreaudio process is consuming around 10% of CPU.
4. 😢
5. If you close the tab the process goes away after a few seconds.

I believe this is because Tone [initializes the audio context on load](https://github.com/Tonejs/Tone.js/blob/dev/Tone/index.ts#L33) even when there is no active use of it. Maybe the initialization could be somehow delayed until the library is actually used.

Thanks!

**Comment by tambien** [comment]
very cool app. You could try suspending and resuming the app when it's not in use. 

```js
// to suspend the underlying AudioContext
Tone.getContext().rawContext.suspend()

// to resume the AudioContext
Tone.getContext().rawContext.resume()
```

**Comment by 4lejandrito** [comment]
Hi @tambien,

Thanks for your reply! That worked fine. However I think there might be a better approach.

My library offers [an optional React hook](https://github.com/4lejandrito/react-guitar/blob/master/packages/react-guitar/src/hooks/sound.ts) that uses Tone under the hood to play the guitar strings. Just by importing the library (even if the consuming code doesn't use the hook) the audio context will be initialized. 

I have to warn users to manually disable the audio context (this is what I will be doing tonight on the demo site), because if I disable it from my library I risk breaking users that were already using Tone for something else (since the context is global). I don't like having to expose the fact that my internal implementation uses Tone and forcing users to do that if they are concerned about this issue.

I see you already have a [start method](https://github.com/Tonejs/Tone.js/blob/dev/Tone/core/Global.ts#L58-L60) that resumes the context. Ideally the context would be suspended by default waiting for that method to be called, but I am sure this can have big implications for your existing userbase. 

Feel free to close this issue if you think this is not easily doable with the current way Tone is designed. I will try locally at some point to see if I can get something working. In that case I might come back with a pull request.

Thanks a lot for your work, Tone is really useful for me.

**Comment by tambien** [comment]
Yeah, thanks for understanding. i do fear that such a fundamental change like not initializing the AudioContext would break a lot of existing code. I am moving towards a way that defers the creation of the AudioContext until the first invocation of Tone.js, but i think that still wouldn't quite help your situation. 

I'll look into surfacing the `suspend` method a little more prominently for others that want to do a similar thing.
