### ISSUE TITLE
Insufficient 'Getting Started' instructions

### ISSUE THREAD

**Issue by dbchristopher** [Tonejs/Tone.js#744]
I'm currently trying to experiment with Tone.js in a simple react app. I started with the `create-react-app` boilerplate and webpack config, and then followed the basic instructions of `npm install tone`.

However, something is broken about the way the tone is bundled and delivered. When I just wanted to test out the simple Hello Tone example in my app, I tried importing Tone. Since the actual import statement wasn't listed in the examples I guessed at `import Tone from 'tone'`, but that resulted in the following error:

`Attempted import error: 'tone' does not contain a default export (imported as 'Tone')`

I then tried a named import and got a similar result. Eventually, while viewing source on your example page I discovered the cdnjs version I was finally able to load on the page. That's not ideal, but sufficient for my needs. 

I'd really hate if others had so much trouble just getting a simple example running on a page. You should at least mention the cdnjs option in the getting started instructions, but ideally it would be great if it could actually be able to be imported into a standard webpack bundle.

**Comment by tambien** [comment]
Thanks for the issue. I think there used to be a quick guide on how to import Tone.js into your project at the top of the README, but i guess that got lost in the recent transition to typescript. I just added it back at the top of the README. 

This should work in create-react-app:

```js
import * as Tone from 'tone';
```

**Comment by dbchristopher** [comment]
Awesome, thanks @tambien!
