### ISSUE TITLE
Cannot initialize 'PitchShift' in iOS 14

### ISSUE THREAD

**Issue by justin-cotarla** [Tonejs/Tone.js#745]
After updating to iOS 14, I've encountered a bug when trying to initialize a `PitchShift` effect. 

The error can be reproduced by running the following on any iOS 14 browser: https://jsbin.com/gonayajima/edit?js,console

Stacktrace:
```
Unhandled Rejection (TypeError): undefined is not an object (evaluating 'panWaveShaperNode.inputs[0]')

connectGraph
node_modules/standardized-audio-context/build/es2019/factories/native-stereo-panner-node-faker-factory.js:109

whenConnected
node_modules/standardized-audio-context/build/es2019/factories/native-stereo-panner-node-faker-factory.js:240

(anonymous function)
node_modules/standardized-audio-context/build/es2019/factories/monitor-connections.js:13

(anonymous function)
node_modules/standardized-audio-context/build/es2019/helpers/wrap-audio-node-disconnect-method.js:7
connectNativeAudioNodeToNativeAudioNode
node_modules/standardized-audio-context/build/es2019/helpers/connect-native-audio-node-to-native-audio-node.js:8

connect
node_modules/standardized-audio-context/build/es2019/factories/audio-node-constructor.js:323

CrossFade
/home/Tone/component/channel/CrossFade.ts:111

Effect
/home/justin/Tone/effect/Effect.ts:24
  21 |  * signal, 0 = 100% dry signal.
  22 |  */
  23 | this.wet = this._dryWet.fade;
> 24 | /**
     | ^  25 |  * connect the effectSend to the input of hte effect
  26 |  */
  27 | this.effectSend = new Gain({ context: this.context });

FeedbackEffect
/home/justin/Tone/effect/FeedbackEffect.ts:41

PitchShift
/home/justin/Tone/effect/PitchShift.ts:93
  90 |  * pitchShift.pitch = 7; // up a fifth
  91 |  */
  92 | get pitch() {
> 93 |     return this._pitch;
     | ^  94 | }
  95 | set pitch(interval) {
  96 |     this._pitch = interval;
```

I suspect this has to to do with `standardized-audio-context` breaking in iOS14, so [I opened an issue there](https://github.com/chrisguttandin/standardized-audio-context/issues/959) as well.

**Comment by tambien** [comment]
seems related to #720. could you install `tone@next` and try again? that patch should have the iOS 14 fix in there.

**Comment by justin-cotarla** [comment]
Thanks for taking a look at this.
It seems the commit that updates `standardized-audio-context` to a version that doesn't break on iOS 14 (8915e1b) isn't in `tone@next` because it has failing tests. Otherwise it looks like it would do the trick.

**Comment by justin-cotarla** [comment]
I tried cloning `14.7.39`, manually updating `standardized-audio-context` to 25.0.3, and npm linking it to my project. I can confirm that bumping `standardized-audio-context` fixes the bug in iOS 14. I'll be watching for the next release!
Thanks for the help!
