### ISSUE TITLE
deepEquals metho not supported in typescript 4

### ISSUE THREAD

**Issue by sarahBuisson** [Tonejs/Tone.js#747]
If you use your lib in a typescript 4 project, the "deepEquals" method make compilation error

using this implementation instead seem to work:

export function deepEquals(arrayA: any[], arrayB: any[]): boolean {
  return arrayA.length === arrayB.length && arrayA.every((element, index): boolean => arrayB[index] === element);
}

**Comment by tambien** [comment]
Thanks for the update. Pull Requests welcome!

**Comment by sarahBuisson** [comment]
https://github.com/Tonejs/Tone.js/pull/749

I haven't test it.

**Comment by tambien** [comment]
Closed by #749
