### ISSUE TITLE
Reuse already downloaded samples

### ISSUE THREAD

**Issue by dgrcode** [Tonejs/Tone.js#750]
I found that Tone.js doesn't automatically reuse already downloaded samples, but instead it downloads the samples again. Is there already a simple way of reusing samples that I'm missing?

From digging a bit in the code –by the way, very clean and easy to navigate 👍– I found a way of doing it myself. This would be an example code of how to do it.
```js
const samples = {...} // a `SamplesMap` (see references below)
const originalSampler = new Tone.Sampler(samples, samplerOptions).toDestination()

const bufferCopy = originalSampler._buffer._buffer // same shape of `SamplesMap`
const copiedSampler = new Tone.Sampler(bufferCopy, samplerOptions).toDestination()

// samplers can't be disposed, or the `ToneAudioBuffer`s get cleaned
```
_Reference: [SamplesMap][1]_

This way we download the samples just once.

My use case is a web app where a user can use different instruments. When the user goes back to a previously used instrument, it would be nice if they didn't have to re-download the samples.

I was wondering if there's something already implemented, or if a feature like this could be interesting for the project. If this feature would be too specific for my use case I can use the workaround described above.

Thanks!

[1]: https://github.com/Tonejs/Tone.js/blob/dev/Tone/instrument/Sampler.ts#L14

**Comment by tambien** [comment]
One way to achieve this without reaching into private variables would be to load the ToneAudioBuffer outside of the sampler and then pass it into each of the samplers. 

```ts
const urls = {
  "C3" : new ToneAudioBuffer('./path/to/C3.mp3'),
  "C4": new ToneAudioBuffer('./path/to/C4.mp3')
}
const sampler1 = new Sampler(urls);
const sampler2 = new Sampler(urls);
```

Both would share the same underlying buffers so it wouldn't need to reload it on construction.

**Comment by dgrcode** [comment]
Awesome, will do that. Thanks for the pointers 🙌
