### ISSUE TITLE
Safari 14 issues with OscillatorNode constructor

### ISSUE THREAD

**Issue by johankitti** [Tonejs/Tone.js#751]
Hi!

We're having production errors with 14.7.39 on recently released Safari 14 (Both on macOS and iOS). They seem to have dropped support for OscillatorNode?

https://developer.mozilla.org/en-US/docs/Web/API/OscillatorNode 

Status is unconfirmed on mozilla.org.

**Comment by chrisguttandin** [comment]
Just in case someone else stumbles upon this. There is now an issue covering this in the WebKit bug tracker. https://bugs.webkit.org/show_bug.cgi?id=216814
