### ISSUE TITLE
Recording and creating url for Tone.Player()

### ISSUE THREAD

**Issue by lisaorii** [Tonejs/Tone.js#752]
Hi,

I wanted to ask if it is possible to create a url from a mic recording and pass the url into Tone.Player(audioURL) where audioURL is the url we created from our recording.
It seems like there is only instruction on how to upload a url from a pre-created audio file (not recording). For context, I am hoping to use Tone.PitchShift() to pitch shift the audio from my original audio file.

I am currently stopping the recording and creating the url:
`let blob = new Blob(chunks, { type: 'audio/ogg; codecs=opus' });
  audioURL= URL.createObjectURL(blob);`

However, Tone.Player(audioURL) is not fetching the url.

Additionally, is it possible to pitch shift in real-time during recoding?

Thanks.

**Comment by tambien** [comment]
Player should work with blob urls. It uses `fetch` under the hood, so anything that a browser can fetch should be ok.

[Here's a quick example](https://codesandbox.io/s/mic-recorder-player-eflu0?file=/src/index.ts:0-811) of creating a blob url from a microphone recording and then playing it back through a pitch shift.

 I think the one gotcha that i discovered while putting together this example is that loading and decoding a blob url is still async, so you've gotta give it a moment to load the audio file before you can play. Either listen for the onload callback or set `player.autostart = true` to start the buffer immediately once it's loaded.
