### ISSUE TITLE
ReferenceError: Can't find variable: OscillatorNode with the new iOS 14

### ISSUE THREAD

**Issue by rondog** [Tonejs/Tone.js#754]
Just updated my phone to iOS14 and a site I am working on that utilizes tone is throwing a couple errors.

In the console, I see:
`* Tone.js r13-dev *`

followed by 
```
[Error] ReferenceError: Can't find variable: OscillatorNode
	(anonymous function) (Tone.min.js:2:192168)
	(anonymous function) (Tone.min.js:2:192410)
	s (Tone.min.js:2:328)
	(anonymous function) (Tone.min.js:2:266219)
	s (Tone.min.js:2:328)
	(anonymous function) (Tone.min.js:2:739)
	(anonymous function) (Tone.min.js:2:749)
	(anonymous function) (Tone.min.js:2:187)
	Global Code (Tone.min.js:2:190)
```

I was not having this issue with iOS13. When I was trying to debug this issue, I came across this: https://trac.webkit.org/changeset/264657/webkit which mentions OscillatorNode. Not sure if that has something to do with it.

I am also getting `ReferenceError: Can't find variable: Tone` but I think that is because of the previous error. If I type `Tone` in the console and hit enter, it says `ReferenceError: Can't find variable: Tone`

I am not receiving this error in safari or chrome and I can type `Tone` in the console and all is good.

**Comment by tambien** [comment]
Seems related to #745. Try upgrading to the latest tone using `npm install tone@next`. That should fix it

**Comment by rondog** [comment]
I feel like its more related to https://github.com/Tonejs/Tone.js/issues/751, however, updating to the latest does indeed get rid of those errors, but now it looks like my script needs updating as some methods have changed between v13 and v14. Thanks @tambien

**Comment by tambien** [comment]
yes good catch. that's the more relevant issue to reference. 

Going to close if it's fixed in `tone@next`. i'll push next to `latest` soon so other's can avoid this issue as iOS 14 is rolled out
