### ISSUE TITLE
Safari issues & ToneAudioBuffer loader question

### ISSUE THREAD

**Issue by jordaneast1** [Tonejs/Tone.js#757]
Hi, I also had the issues regarding Safari updates, which has broken my project that was built in r13.8.32.

Following the advice in #754 I have upgraded the project to r14.7.60 but now I've run into some conflicts with the new ToneAudioBuffer.. previously I had a loading screen something like

```
Tone.Buffer.on('load' ()=>{
			console.log("loaded music!")
});

Tone.Buffer.on('progress', (prog) => {

		fill.style.width = `${(prog * 100).toFixed(2)}%`
			
})
```

but according to the docs we are required to use  Tone.loaded ( ) => Promise<void>. 
apologies for my lack of knowledge for typescript & promises but could someone give an example of how to write this in javascript?
I also noticed there is now no 'progress' method, how would I go about creating a loading screen as above using the new ToneAudioBuffer?

Sorry for the question, not issue. please let me know if you would like me to remove and ask elsewhere.

Thanks

**Comment by tambien** [comment]
Here's an example of how to use the new `loaded()` API

```js
// create all your samples before calling 'loaded'
Tone.loaded().then(() => {
  // all your samples are loaded
})
```

"progress" events was removed in version 14 with no replacement for now
