### ISSUE TITLE
this.context.createScriptProcessor is not a function

### ISSUE THREAD

**Issue by DaniilFawkes** [Tonejs/Tone.js#759]
Using Tone.js for my virtualpiano project
after apple ios update decided to use new version of tone (14.7.39) coz old one (13.8.25) stopped working on ios devices 
im using webaudio recorder (https://github.com/higuma/web-audio-recorder-js) to record audio context of how users playing piano to let the download how they play a songs 
after updating tone js recorder stopped working with error comming in console // Uncaught TypeError: this.context.createScriptProcessor is not a function//
any ideas how to deal with it?

**Comment by chrisguttandin** [comment]
Hi @DaniilFawkes,

Tone.js v14 uses standardized-audio-context for cross browser support. It doesn't have a ScriptProcessorNode anymore. @tambien rewrote the internal code to use an AudioWorklet instead. You basically need to do the same with your ScriptProcessor code. #712 contains an example which shows how that could be done.

I hope this helps.

**Comment by tambien** [comment]
thanks for chiming in @chrisguttandin 

Like Christoph said ScriptProcessorNode is deprecated and won't be available in future versions. hopefully your functionality isn't too hard to reproduce in the AudioWorklet
