### ISSUE TITLE
Documentation for Tone.Event needs to be updated to Tone.ToneEvent

### ISSUE THREAD

**Issue by stephendwolff** [Tonejs/Tone.js#760]
The Events examples here:

 - https://tonejs.github.io/examples/events.html

link to

 - https://tonejs.github.io/docs/13.8.25/Event.html

whereas, using 14.7.x, I couldn't compile with Webpack, and then found that it had been renamed:

 - https://tonejs.github.io/docs/14.7.39/ToneEvent

**Comment by stephendwolff** [comment]
I'm not sure the best way to update the tonejs.github.io examples, and what wording should be used on the wiki

 - https://github.com/Tonejs/Tone.js/wiki/Events

All very helpful examples, but it tripped me up until i found the new class name

**Comment by tambien** [comment]
PRs welcome if you've got time to make the fix yourself. The file in question [is here](https://github.com/Tonejs/Tone.js/blob/dev/examples/events.html). 

Otherwise i'll get to it when i have a spare moment

**Comment by tambien** [comment]
closed by #763
