### ISSUE TITLE
Time.toNotation not returning anything larger than 1m

### ISSUE THREAD

**Issue by MikeSult** [Tonejs/Tone.js#769]
When updating to the new version I am finding Tone.Time.toNotation() is not working the same.

code pen example at 
https://codepen.io/mikesult/pen/abZpVoN

const t1 = Tone.Time(Tone.Time('1m') + Tone.Time('1m') );
console.log(t1.toMilliseconds()); // returns 4000
console.log(t1.toNotation()); // returns '1m' expected '1m * 2'

const t2 = Tone.Time(6);
console.log(t2.toMilliseconds()); // returns 6000
console.log(t2.toNotation()); // returns '1m' expected '1m * 3'

I was testing this with an older version and I was getting the expected results
of '1m * 2' and '1m * 3'
------------------------------------------

Bugs and feature requests only please. For help questions, check out the [forum](https://groups.google.com/forum/#!forum/tonejs).

**Note**: Browsers' [Autoplay Policy](https://github.com/Tonejs/Tone.js/wiki/Autoplay) leads to a lot of subtle and inconsistent bugs where Tone.js produces no sound. Check out the link for more information and the solution. 

Please include a way to reproduce your issue

https://jsfiddle.net/1f60jkq4/ (tone@latest)
https://jsfiddle.net/z9marxbt/ (tone@next)

**Comment by tambien** [comment]
This is the new behavior of toNotation as of `tone@14.x`. Notation values no longer support the arithmetic notation for the past few versions (e.g. `"2 * 1m"`), so it also made sense that `toNotation` shouldn't return those types of values.

**Comment by MikeSult** [comment]
Thanks for clarifying.  I'm reworking some code that uses .toNotation(), I'll use .toSeconds() instead.
Love the Tone.js framework.
