### ISSUE TITLE
Tone.Microphone not allowing different inputs

### ISSUE THREAD

**Issue by polyrhythmatic** [Tonejs/Tone.js#77]
`Tone.Microphone` doesn't seem to allow setting different inputs. I believe part of the issue is something that I've run into with p5 audioIn - the `MediaStreamTrack.getSources` call is asynchronous and takes a moment to return the list of devices. I'm still working on trying to fix it but it may require a secondary method for `.setSource(num)`

Because chrome is really the only browser supporting `MediaStreamTrack.getSources`, I propose keeping Tone.Microphone and optimizing it for use with the default input (which is almost always the microphone). Tone.Microphone can be extended to work with Firefox and Opera and function just as the microphone.

I would propose then introducing an AudioInput class for capturing other inputs outside of the default, and either make it Chrome only or have exceptions for dealing with Chrome/Firefox differences. 

Another option would be to merge the two under one class name with sufficient documentation, but I think calling it Microphone is misleading when it could be a variety of other inputs.

**Comment by polyrhythmatic** [comment]
Everything is working now! the only issue is that mic.start() will not set the correct input until after the getSources call is complete, and instead uses the default input.

This could be solved by making a handle similar to `Tone.Buffer.onload', named `Tone.AudioIn.onload`. I think this still makes more sense with a separate `AudioIn` class.

**Comment by tambien** [comment]
Addressed by PR #89.
