### ISSUE TITLE
Swing and iregular loop issue

### ISSUE THREAD

**Issue by KoSv** [Tonejs/Tone.js#774]
Hi there,
I'm experiencing drifts and transport misbehavior when looping over odd numbers of sixteenths (i.e. 5/16) and using swing (i.e.16th) at the same time.
Can u please confirm?
Cheers!
KoSv

**Comment by tambien** [comment]
Could you provide a minimal example?

**Comment by KoSv** [comment]
> Could you provide a minimal example?

https://jsfiddle.net/KoKoSv/bzw4x1dv/49/

**Comment by tambien** [comment]
thanks for the example. I made a small adjustment. Make sure you use the time passed in, otherwise the scheduled timing will not be accurate. 

https://jsfiddle.net/yotammann/sebvcz65/

**Comment by tambien** [comment]
oh yeah you're right. good catch.
