### ISSUE TITLE
getContext call leading to "The AudioContext was not allowed to start."

### ISSUE THREAD

**Issue by matschaffer** [Tonejs/Tone.js#776]
I'm still fairly new to Tone.js and typescript and webpack. But in trying to use them all together today I noticed as much as I try not to, I'm still getting the "The AudioContext was not allowed to start." error.

It looks like it's coming from the call to `getContext` in https://github.com/Tonejs/Tone.js/blob/14.7.39/Tone/index.ts#L33

Is there a way to suppress that or should I just live with the error?

Here's the code I've got webpack building at the moment.

```
import * as Tone from "tone";

const playButton = document.getElementById("play-button");

playButton.addEventListener("click", () => {
  if (Tone.context.state !== "running") {
    Tone.context.resume().then(() => {
      let synth = new Tone.Synth().toDestination();
      synth.triggerAttackRelease("A3", "4n");
    });
  }
});
```

Thanks in advance for any advice on avoiding the error.

**Comment by tambien** [comment]
[Here's a minimal example](https://codesandbox.io/s/starting-audio-context-gn4f8) based on your code. The code runs fine for me. As you pointed out, there's a warning (not an error) "The AduioContext was not allowed to start". As long as you start the AudioContext, like you're currently doing, it shouldn't be an issue in terms of playing any sound.

Eventually i will move away from instantiating an AudioContext when the page initializes and move towards only instantiating it the first time 'getContext' is called, but that will break a lot of current APIs so will have to deal with it delicately. For now, i would just ignore this warning.

**Comment by matschaffer** [comment]
Thanks @tambien - nice to see a more complete tsconfig example 👍 

I'm still getting the error here. Maybe has something to do with my webpack setup. I put it up at https://github.com/matschaffer/audibility incase you're able to have a look but totally no expectation of you to debug my busted webpack config 😆 

I'll go make some boops, warnings or no. :)
