### ISSUE TITLE
EQ3 cuts cross-over frequencies

### ISSUE THREAD

**Issue by firelex** [Tonejs/Tone.js#780]
Please see here: https://ibb.co/PM5MyLf

This is a multi-track mix - once without EQ3 on the master FX chain and once with two chained EQ3s and zero gain in all frequency bands.  EQ3 cuts the cross-over frequencies.  This is also the case if gain values are applied, leading to a mix where individual frequencies are suddenly missing.

Is this a bug or am I doing something wrong?

Bugs and feature requests only please. For help questions, check out the [forum](https://groups.google.com/forum/#!forum/tonejs).

**Note**: Browsers' [Autoplay Policy](https://github.com/Tonejs/Tone.js/wiki/Autoplay) leads to a lot of subtle and inconsistent bugs where Tone.js produces no sound. Check out the link for more information and the solution. 

Please include a way to reproduce your issue

https://jsfiddle.net/1f60jkq4/ (tone@latest)
https://jsfiddle.net/z9marxbt/ (tone@next)

**Comment by firelex** [comment]
It's not the equalizer.  It's the splitting into multiple bands.  When I EQ with the biquad filter, I have no issues.  SImilarly, I have no issues compressing with the compressor.  Both multi-band versions (MultibandCompressor and EQ3) weaken the signal at the cross-over points.  Still experimenting to see if I can pinpoint the issue further.

**Comment by firelex** [comment]
Yeah, so EQ3 and compressor are fine.  It's the multi-band splits that behave unexpectedly.  In a normal DAW, if I use a multi-band EQ, I can put a gain on different frequency bands but the transition between the bands is smooth.  With EQ3 (and the multi-band compressor), the cross-over frequencies cut out as shown in the screenshots I posted above.  My workaround for now is to apply multiple biquad filters in succession, which leads to the desired result.  Would be good to understand if this is a bug or it's somehow intended.

**Comment by tambien** [comment]
Thanks for the detailed issue 

EQ3 is implemented very simply: each crossover is achieved using a pair of highpass/lowpass biquad filters which are connected to the same frequency signal controlling both filters cutoffs. BiquadFilters aren't precise enough to cutoff just at the given frequency, but seem to start before. I would recommend adjusting the Q factor of the EQ3 to fine-tune how that cutoff is handled. 

Currently the default Q=1, but maybe a higher Q value would lead to a flatter response curve with no dips at the crossover frequencies. If you are able to find a better Q value for this module, it would be great to know! i can update the defaults for Tone.MultibandSplit.

> Is this a bug or am I doing something wrong?

i think neither a bug nor are you doing anything wrong, but i wouldn't expect Tone.js would behave exactly the same was as a DAW

**Comment by marcelblum** [comment]
Hello, I too have noticed this EQ3 behavior, just going by ear I arrived at Q=10 as the best value (totally unscientifically but after a lot of subjective listening) to achieve a sound more similar to the source when all bands are at 0 and more pleasant sounding smoothness between the bands.

**Comment by Asmatzaile** [comment]
@tambien hi! We can't adjust the Q from the multibandsplit from the EQ3, could you make that possible plz?

**Comment by tambien** [comment]
it should be exposed already and assigned or schedule like this: `eq3.Q.value = 10`

**Comment by Asmatzaile** [comment]
I tried using the options object when initializing the EQ ( with v14.7.77) and it didn't apply to the multiband splitter though
