### ISSUE TITLE
Envelope - exponential decay very snappy for large values

### ISSUE THREAD

**Issue by Razz21** [Tonejs/Tone.js#782]
Hi there, 
for values >1s envelope is still very snappy and signal drop is very fast, for example with 1.5s decay and 0.5 sustain after 0.5s signal is almost on sustain stage level.
![newplot](https://user-images.githubusercontent.com/32792205/98563095-0f841b00-22ab-11eb-9979-6d5a8c756cf7.png)

Is it possible to add some exponent control to this parameter?

EDIT:
after little experimenting I've created custom exponential function for decay curve. 
Example envelope for same values as above:
attack=0.1s,
decay=1.5s, 
sustain=0.5,
exponent = 3 // value for custom easing function
![customEG](https://user-images.githubusercontent.com/32792205/98571469-d3ee4e80-22b4-11eb-85a1-76972ff23b09.png)
As you can see after 0.5s signal still has value >0.6.

It is possible to create even convex curves with exponent <1; 
curve for exp=0.5:
![newplot(2)](https://user-images.githubusercontent.com/32792205/98572921-7bb84c00-22b6-11eb-8f44-f1435079df51.png)

This is only workaround, is it possible to add native support for eased decay curve?

**Comment by tambien** [comment]
I'm assuming that `envelope.decayCurve = 'linear'` does not fit your needs? It would cause the decay curve to be higher for longer like you're looking for. 

the attack and release curves support much more control of the curve. it seems like extending that capability to the decayCurve is what you're looking for, yeah?

**Comment by Razz21** [comment]
yes, linear curve sounds a little too artificial to me, and I am looking something more natural, but, as I mentioned, existing exponential decay curve just fade too fast. I am not sure, if additional decay curve calculation is more expensive than attack or release stage.

**Comment by Razz21** [comment]
@tambien Do you have in plans extending Envelope curves options? It would be possible to add similar control over exponential curve to any Envelope stage, but will require some change in code and new properties in class. My solution simply transforms linear curve array [0, 1] to exponential values and next eases them to fit range [min, max] (depends on stage, for decay is [min=sustain, max=1]). Nevertheless presented solution works for me and this issue would be considered as resolved.

**Comment by mmcdermott1** [comment]
working on a project that requires a very precise decayCurve -- would be super helpful to be able to this value with a custom array.
