### ISSUE TITLE
Safari 14 compatibility

### ISSUE THREAD

**Issue by AboveTauCeti** [Tonejs/Tone.js#785]
Are there any known features or methods which do not work with Safari 14 ?
E.g. is the vibrato issue fixed?

https://github.com/Tonejs/Tone.js/issues/720

**Comment by ttm** [comment]
I don't get `DCMeter()` to work in safari 14. All ok in Chrome and Firefox.

**Comment by ttm** [comment]
`Meter()` is also frozen.

**Comment by ttm** [comment]
You can check that in [this example](https://l4bs.github.io/?p=ttest). `Meter` and `DCMeter` are measuring a modulator wave. This is the code:
```
  const synth = maestro.mkOsc(0, -200, -1, 'sine')
  const synth2 = maestro.mkOsc(0, -200, 1, 'sine')
  const mod_ = maestro.mkOsc(0.1, 0, 0, 'sine', true)
  const mul = new t.Multiply(190)
  const mod = mod_.connect(mul)
  const add400 = new t.Add(400)
  const add410 = new t.Add(410)
  mul.connect(add400)
  mul.connect(add410)

  const met = new t.Meter()
  const met2 = new t.DCMeter()
  add400.connect(met)
  add400.connect(met2)
  add400.connect(synth.frequency)
  add410.connect(synth2.frequency)

  const grid = utils.mkGrid(2)
  const vonoff = $('<div/>', { id: 'vonoff' }).appendTo(grid).text('Stopped')
  $('<input/>', {
    type: 'checkbox'
  }).appendTo(grid).change(function () {
    if (this.checked) {
      t.start()
      t.Master.mute = false
      synth.volume.rampTo(-40, 1)
      synth2.volume.rampTo(-40, 1)
      mod.frequency.rampTo(0.05, 120)
      vonoff.text('Playing')
    } else {
      synth.volume.rampTo(-200, 1)
      synth2.volume.rampTo(-200, 1)
      vonoff.text('Stopped')
    }
  })
  $('<div/>').text('meter').appendTo(grid)
  const m1 = $('<div/>', { id: 'meter1' }).appendTo(grid)
  $('<div/>').text('meter DC').appendTo(grid)
  const m2 = $('<div/>', { id: 'meter2' }).appendTo(grid)
  setInterval(() => {
    m1.text(met.getValue().toFixed(3))
    m2.text(met2.getValue().toFixed(3))
  }, 100)
```

**Comment by ttm** [comment]
found out some further issues in Safari:
*) DC meter doesn't work with values outside [-1, 1];
*) Resolution of amplitude is very poor, I'll probably put an example online. I don't know if it is a `DCMeter` problem or something with the webaudio (or tonejs) calculations in Safari.

**Comment by tambien** [comment]
If DCMeter is the only compatibility issue, we can track that issue [here](https://github.com/chrisguttandin/standardized-audio-context/issues/971). I think other safari-specific issues should probably have their own tickets instead of being clumped together.
