### ISSUE TITLE
PitchShift throws Error in Safari

### ISSUE THREAD

**Issue by stephandue** [Tonejs/Tone.js#787]
When I try to initialize PitchShift like so:

const pitchShift = new Tone.PitchShift();

Safari 14.0 on Mac 10.15.7 give me these error:

TypeError: this._context.createStereoPanner is not a function. (In 'this._context.createStereoPanner()', 'this._context.createStereoPanner' is undefined)

Line 6608 in Tone.js

From what I know createStereoPanner is not available in Safari but createPanner can be used instead.

**Comment by chrisguttandin** [comment]
Hi @stephandue,

Tone uses standardized-audio-context internally which has an implementation of `createStereoPanner()`. Is it possible that you explicitly set the context used by Tone yourself?

**Comment by stephandue** [comment]
Hi Chris,

thanks for your quick feedback.

I do set the context before like so:

var AudioContext = window.AudioContext || window.webkitAudioContext;
var mAudioContext = new AudioContext();
Tone.setContext(mAudioContext);

This does not throw any error.

Best,
Stephan

**Comment by stephandue** [comment]
Sorry here is the whole code:

`var video = document.getElementsByTagName('video')[0]

var AudioContext = window.AudioContext || window.webkitAudioContext;
var mAudioContext = new AudioContext();

var source = mAudioContext.createMediaElementSource(video);
var pitchShift = new Tone.PitchShift();

Tone.connect(source, pitchShift);
pitchShift.connect(Tone.getContext().destination);

pitchShift.pitch = pitchShift.pitch + 1`

**Comment by chrisguttandin** [comment]
You can probably solve the issue by rewriting your code like this:

```js
var video = document.getElementsByTagName('video')[0];
var source = Tone.getContext().createMediaElementSource(video);
var pitchShift = new Tone.PitchShift();

Tone.connect(source, pitchShift);
pitchShift.connect(Tone.getContext().destination);
```

**Comment by stephandue** [comment]
This gives me

TypeError: Tone.getContext().createMediaElementSource is not a function. (In 'Tone.getContext().createMediaElementSource(video)', 'Tone.getContext().createMediaElementSource' is undefined)

on the second line:
var source = Tone.getContext().createMediaElementSource(video);

**Comment by chrisguttandin** [comment]
Oh sorry. The instance of standardized-audio-context is one level deeper.

Using ...
```js
var source = Tone.getContext().rawContext.createMediaElementSource(video);
```
... instead of ...
```js
var source = Tone.getContext().createMediaElementSource(video);
```
... should work.

**Comment by stephandue** [comment]
@chrisguttandin I was about to write that .rawContext did the trick. Thanks so much for your help! Now I don't get any error. But the connection somehow does not work. I don't get the pitch shifted sound. But I hope to figure that out myself :-)

**Comment by stephandue** [comment]
@chrisguttandin I cannot figure it out. I get no error. The pitch value changes, but the sound of the video does not change.

```
var source = null
var isConnected = false
var pitchShift = null

function changePitchUp(){

    var video = document.getElementsByTagName('video')[0]
    
    if (source == null){
        source = Tone.getContext().rawContext.createMediaElementSource(video);
    }

    if (!isConnected){
        pitchShift = new Tone.PitchShift();
        Tone.connect(source, pitchShift);
        Tone.connect(pitchShift, Tone.getContext().destination);
        isConnected = true
    }
    
    pitchShift.pitch = pitchShift.pitch + 1

    showAnimation("♪ "+pitchShift.pitch, false)

}
```

**Comment by chrisguttandin** [comment]
Does it work if you replace ...
```js
Tone.connect(pitchShift, Tone.getContext().destination);
```
... with ...
```js
pitchShift.toDestination();
```
?

**Comment by stephandue** [comment]
Same result. No error, pitch value goes up but the sound of the video does not change.

**Comment by stephandue** [comment]
Just put a jsfiddle together. Here however the tone stops entirely when I try to pitch up. In my safari extension project the regular (not pitched) tone keeps playing.

https://jsfiddle.net/z9dav314/

**Comment by stephandue** [comment]
Ok this does not seem to work with jsfiddle. So I uploaded my initial script here:
http://duechtel.com/tonejstest/

This is working fine in Chrome but gives me this error in safari:
TypeError: this._context.createStereoPanner is not a function. (In 'this._context.createStereoPanner()', 'this._context.createStereoPanner' is undefined)

Here´s HTML:

```
<video width="320" height="240" controls>
  <source src="testvideo.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>

<button onclick="changePitchUp()">Pitch Up</button>
<button onclick="changeSpeedUp()">Speed Up</button>

<script src="Tone.js"></script>
<script src="app.js"></script>
```

And Here the app.js:

```
document.addEventListener('DOMContentLoaded', function(){
  initToneJs();
}, false);

var AudioContext = window.AudioContext || window.webkitAudioContext;
var mAudioContext = new AudioContext();
var pitchShift = null

function initToneJs(){
  Tone.setContext(mAudioContext);
}

var source = null
var isConnected = false

function changePitchUp(){

    var video = document.getElementsByTagName('video')[0]

    if (source == null){
    	source = mAudioContext.createMediaElementSource(video);
  	}

  	if (!isConnected){
      pitchShift = new Tone.PitchShift();
      Tone.connect(source, pitchShift);
      pitchShift.connect(Tone.getContext().destination);
      isConnected = true
  	}

    pitchShift.pitch = pitchShift.pitch + 1

    console.log("♪ "+pitchShift.pitch)

}

function changeSpeedUp(){

    var video = document.getElementsByTagName('video')[0]

    if (video.playbackRate >= 1.5){
        return
    }

    var newPlaybackRate = video.playbackRate + 0.05
    newPlaybackRate = Math.round((newPlaybackRate + Number.EPSILON) * 100) / 100
    video.playbackRate = newPlaybackRate
    var speedInPercent = 100 * newPlaybackRate
    speedInPercent = Math.round(speedInPercent)

    console.log(speedInPercent+"%")

}
```

**Comment by chrisguttandin** [comment]
Thanks for providing the larger snippet and example. I guess the missing piece of the puzzle is to resume the context inside of the click handler.

```js
changePitchUp () {
    Tone.getContext().resume();

    // ...
}

**Comment by stephandue** [comment]
Same error:

TypeError: this._context.createStereoPanner is not a function. (In 'this._context.createStereoPanner()', 'this._context.createStereoPanner' is undefined)

Ihm preparing the other solution you suggested 
var source = Tone.getContext().createMediaElementSource(video);...

**Comment by stephandue** [comment]
I also prepared a version that @chrisguttandin suggested:
http://duechtel.com/tonejstest/index-safari.html

Here is the html:

```
<video width="320" height="240" controls>
  <source src="testvideo.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>

<button onclick="changePitchUp()">Pitch Up</button>
<button onclick="changeSpeedUp()">Speed Up</button>

<script src="Tone.js"></script>
<script src="app-safari.js"></script>
```

And here the js:

```
var source = null
var isConnected = false
var pitchShift = null

function changePitchUp(){

    var video = document.getElementsByTagName('video')[0]

    if (source == null){
        source = Tone.getContext().rawContext.createMediaElementSource(video);
    }

    if (!isConnected){
        pitchShift = new Tone.PitchShift();
        Tone.connect(source, pitchShift);
        //pitchShift.toDestination();
        Tone.connect(pitchShift, Tone.getContext().destination);
        //pitchShift.connect(Tone.getContext().destination);
        isConnected = true
    }

    pitchShift.pitch = pitchShift.pitch + 1

    console.log("♪ "+pitchShift.pitch)

}

function changeSpeedUp(){

    var video = document.getElementsByTagName('video')[0]

    if (video.playbackRate >= 1.5){
        return
    }

    var newPlaybackRate = video.playbackRate + 0.05
    newPlaybackRate = Math.round((newPlaybackRate + Number.EPSILON) * 100) / 100
    video.playbackRate = newPlaybackRate
    var speedInPercent = 100 * newPlaybackRate
    speedInPercent = Math.round(speedInPercent)

    console.log(speedInPercent+"%")

}
```

This also seems to work fine in chrome. However in safari as you can see if you visit the site it totally throws the video out of sync with the audio. A bigger problem is that when I try to use this exact same on YouTube (I'm working on a safari browser extension that is inserting this script) the sound does not change as described earlier.

**Comment by tambien** [comment]
thanks so much for jumping in @chrisguttandin 

@stephandue is the original `TypeError` issue resolved on Safari? in my quick test right now, i see that your script doesn't throw an error and seems to work fine for me.

**Comment by stephandue** [comment]
@tambien Thanks for your reply! The problem in Safari is that the video is no longer synchron with the audio after I use the pitch shift. Chrome does not have this problem. Bigger problem is that it is not working at all with YouTube videos in safari. I'm working on a browser extension for chrome and safari. While the script is verging fine in chrome in safari the pitch does not change at all when I use it on YouTube. I'm not sure how I can demonstrate that. I try to provide an example with an iframe where I inject the script. Give me a few hours :-)
