### ISSUE TITLE
Jest & ReferenceError: AudioBuffer is not defined

### ISSUE THREAD

**Issue by sarahBuisson** [Tonejs/Tone.js#788]
I use your lib, when I run it , it's okay , when I run my test with jest, it's okay but 

but when I try to make my test run with jest on the IDE to debug , I have this error :

"ReferenceError: AudioBuffer is not defined"

Any idea what it is? Where this class "AudioBuffer' is suppose to be defined?

**Comment by sarahBuisson** [comment]
solution here: https://github.com/Tonejs/Tone.js/compare/dev...sarahBuisson:patch-3

**Comment by FractalHQ** [comment]
I also have this issue when trying to use Tone with Svelte and Rollup.  Would be nice to have this merged.

**Comment by guilhermecomum** [comment]
I'm getting this error too.

```
import Clave from "./clave.js";
import agogo1 from "../samples/brazilian-percussion/agogo1.wav";
import * as Tone from "tone";

describe("Clave class", () => {
  let samplers;

  beforeEach(() => {
    samplers = new Tone.ToneAudioBuffers({
      urls: { agogo1 },
    });
  });

  it("should instance a new Clave", () => {
    const clave = new Clave("10101", 120, "agogo1", samplers.get("agogo1"));
    expect.instanceOf(Clave);
  });
});

```
