### ISSUE TITLE
normalize audio and set volume

### ISSUE THREAD

**Issue by Archieeeeee** [Tonejs/Tone.js#791]
Sorry for not reporting a bug, just a question, I'm using Tone.js to play some audio files but I do not want it too loud or silent, how can I normalize the audio and then set volume when playing

> var channel = new Tone.Channel(-16).toDestination();
var player = new Tone.Player("https://tonejs.github.io/audio/berklee/gong_1.mp3").toDestination();
Tone.loaded().then(() => {
	player.connect(channel ).start();
});

I have searched and found Tone.Normalize() was deleted

**Comment by tambien** [comment]
Take a look at Tone.Compressor which reduces the dynamic range of an audio input. [Tone.Normalize](https://tonejs.github.io/docs/13.8.25/Normalize) wasn't actually a normalization technique but mapped an input signal between two numbers to the range 0-1, so wouldn't exactly accomplish what you're looking to do.
