### ISSUE TITLE
Delay when using Transport.start() and Midi files

### ISSUE THREAD

**Issue by Hopson97** [Tonejs/Tone.js#792]
I am aware of Issue #369 but this may be slightly different as I am using a `Tone.Sampler` and Midi files.

I have created a minimal page in the fiddle, where you can upload a MIDI file and have the `Tone.Sampler` play the track after creating a piano.

It works perfectly, except there seems to be a huge delay between starting the transport, and the library actually playing the track.

https://jsfiddle.net/p7renax0/11/

Is there something I should be doing differently to mitigate the issue? 

Notes:

* I am using the latest Google Chrome on windows

* The longer the page stays open, the longer the delay is. Sometimes it appears to not be working.

**Comment by tambien** [comment]
You're scheduling the transport time relative to Tone.now(). Tone.now() is the AudioContext time which starts from 0 and counts up while the context is running. Transport.schedule has it's own time scale which it controls. So if you change line 23 from `}, note.time + now);` to `}, note.time);` when scheduling the event, it should work.

**Comment by Hopson97** [comment]
Makes sense. Worked beautifully, thank you!
