### ISSUE TITLE
Unable to create custom Instrument

### ISSUE THREAD

**Issue by zqevans** [Tonejs/Tone.js#795]
I'd like to create a custom Tone.Instrument, but the Instrument class is not exposed in the global Tone export (i.e. I can't reference `Tone.Instrument`).

Is there a reason instrument/index.d.ts doesn't expose `export * from "./Instrument"` to allow custom Instruments to be created?

**Comment by tambien** [comment]
Tone.Instrument is used internally, and not really meant to be exposed as part of the API. You can still get it by reaching into the file where it's defined. You can get the instrument classes like so: `import {Instrument} from "path/to/tone/Tone/instrument/Instrument"`.

**Comment by zqevans** [comment]
Understandable. Is composition of Instruments not a supported part of the framework? I'd like to make some more complex synths that play nicely with the rest of the Tone infrastructure, particularly the functions in Instruments.ts. Since it's not meant to be exposed as part of the API, can I not expect that to be stable over later releases?

**Comment by tambien** [comment]
definitely use it if it's useful! since it's internal, i could imagine it changing over time, but i have no intention to at the moment.
