### ISSUE TITLE
Uncaught Error: buffer is either not set or not loaded (Tone.Sampler)

### ISSUE THREAD

**Issue by joedickey** [Tonejs/Tone.js#798]
Hi,
I have recently been encountering the issue "Uncaught Error: buffer is either not set or not loaded" on a drum machine app I am building using Tone.Sampler. I am using Vercel to deploy my app and I am storing my audio samples client-side. Everything was working great until I tried to redeploy with my Node back-end. All of a sudden it seems that the audio samples won't buffer (although it works on my local network). Under the Chrome Network tab you can see it making requests for the audio files however it seems to be returning my Index.html file instead of the audio file. You can view a working version of the app here:

https://tr-bot.vercel.app/trbot

And this is the newest version where I am encountering the issue.

https://tr-bot-project.vercel.app/trbot

**Comment by tambien** [comment]
Is there a minimal example code that you could provide? It seems like most likely the file isn't loaded by the time you're trying to play it. Make sure you wait for the Tone.Sampler's `onload` callback to resolve before trying to trigger any notes.

**Comment by joedickey** [comment]
Here is the Sampler which I export as a variable into my App component in React. 

``export const allSampler =
    
    new Tone.Sampler({
        urls: {
            C4: "trbotkick.mp3",
            D4: "trbotsnare.mp3",
            E4: "trbothh1.mp3",
            F4: "trbothh2.mp3",
            G4: "trbotclap.mp3", 
            A4: "trbotperc.mp3",
        },
        onload: function() {console.log('samples loaded')},
        baseUrl: "/audio/",
    })

It seems no matter how long I wait the samples won't load. The Network tab in Dev Tools is saying that it is fetching the audio samples but then it returns my index.html file instead of the audio. I haven't had issues with this on previous builds. You can reference the two builds from the links in my initial post if you want to observe the different behaviors.

**Comment by tambien** [comment]
If you're working with react, make sure you import the links the way that React prefers. I'm not positive, but i think something like this might work:

```js
import Kick from "./audio/trtbotkick.mp3";

new Tone.Sampler({
  C4: Kick
})

```

**Comment by joedickey** [comment]
Yes this appears to have worked! Thanks for your help!
