### ISSUE TITLE
How to use Synth.onsilence ?

### ISSUE THREAD

**Issue by Low-Hiss-Systems** [Tonejs/Tone.js#799]
Hello,
I am trying to get the onsilence callback to work on synths but in my code it never gets called.
I need to know when the synth is silent so I can safely `dispose()` of it.

Here is a snippet where it doesn't seem to be called:
```javascript
const type = 'Synth';
this.synth = new Tone[type]().toDestination();
this.synth.onsilence = () => {
    console.log('silence');
    this.isSilenced = true;
};
```

**Comment by tambien** [comment]
I'm unable to reproduce this issue. Here's a live example: https://codesandbox.io/s/synth-onsilence-coxtx?file=/src/index.ts

**Comment by mildfuzz** [comment]
This is maybe related to this 
![image](https://github.com/user-attachments/assets/aaea78f8-501c-4f0f-9c92-44d5d93e474d)
