### ISSUE TITLE
How to reduce pitch shift artifacts

### ISSUE THREAD

**Issue by acondurache** [Tonejs/Tone.js#803]
This has been brought up before (2 years ago) in issue #383, was wondering if there is any way to reduce the artifacts? Also, with using Tone.GrainPlayer there isn't any clear example on how to connect these and modify pitch. 

Was hoping that there be a workaround for reducing the artifacts while using PitchShift or GrainPlayer, any example code would be helpful. 

Audio file is provided as either .wav or .mp3

**Comment by acondurache** [comment]
@tambien thanks a lot for labelling this for docs! But apart from the example code, I am wondering if there is any way to reduce noise/artifacts when using Pitch Shift or GrainPlayer?

**Comment by tambien** [comment]
The parameters you choose really depend on amount of pitch shifting you do and also your source audio (i.e. percussive, drone, noisy). I would say there is no magic values, it's just about finding what sounds right for you given your source. In general the more of the pitch shifting you apply, the greater your artifacts are going to be. In the case of GrainPlayer you can adjust the grainSize and overlap to try to reduce artifacts. PitchShift does not have as many controls, you can adjust the windowSize to something that sounds right to you.

**Comment by liJie-wk** [comment]
This question was very helpful to me
