### ISSUE TITLE
Note release time increases incrementally when wrapped in PolySynth

### ISSUE THREAD

**Issue by dmquinn** [Tonejs/Tone.js#804]
I very new to dev so if someone answers this can they please bear that in mind.  I've been experimenting with toneJs API with mostly great success.  with tone.synth I've been using triggerAttackRelease(key-to-notes object).  When trying to wrap each synth in a PolySynth, the duration (so I suppose release) gets longer on each keypress.  here are a couple snippets of code to show you what I mean: 

var synthOne = new Tone.PolySynth(Tone.Synth, {
	oscillator: {
		type: "sine",
		detune: 0,
		volume: 0,
	},
	envelope: {
		attack: 0,
		decay: 100,
		sustain: 1,
		release: 0.001,
	},
})
	.connect(dist)
	.connect(eq)
	.connect(merge, 0, 0)
	.connect(filter);

////////////////////////

function onkeydown(e) {
	synthOne.triggerAttack(keyToPitch[e.key]);
}

is this a known issue, or does anyone have any idea how to resolve this?

I have controls to set oscillator types, release, attack, etc, but even when everything is removed but the polysynth and synth, the problem persists.  

Thanks in advance

**Comment by tambien** [comment]
@dmquinn did you resolve your issue? maybe you could post the solution so anyone else coming across this issue can find it

**Comment by dmquinn** [comment]
Hi tambien, thanks for your response.  I haven't resolved the issue but the reason I closed it was I became dubious about calling it a 'bug' (as I'm I believe it is more likely there's just logic I haven't fully grasped) and didn't want to spam the page with irrelevant stuff.  If you think this is worth addressing on the issues page I can reopen it?  Let me know what you think.  Thanks!

**Comment by dmquinn** [comment]
Hey there. I have resolved the issue (somewhat).  As I said before, I'm not very experienced in development so fair warning, my explanation maybe won't seem all that concrete. 

It seems like the means of accessing key values is different when dealing with polySynth than with regular (mono)Synths, i.e. when using eventListeners to alter values like volume and oscillator type in the oscillator object, or ADSR values in the envelope object.  

Before, I was accessing these values as follows: synthOne.envelope.release = oscOneRelease; - where oscOneRelease corresponds to a range slider.  But getting rid of the ".envelope" seems to have fixed the issue of note release value increasing. So now it reads: synthOne.envelope.release = oscOneRelease;

 How or why this works I'm not sure but if anyone is having a similar issue, at least there's one place to look.
