### ISSUE TITLE
Tone.Filter negative gain values not attenuating

### ISSUE THREAD

**Issue by pathime** [Tonejs/Tone.js#807]
When using 'lowshelf' or 'highshelf' modes in Tone.Filter, setting the gain with a negative value is not producing any attenuation to the signal. I can hear the effect of positive values, but not for negative. Using Tone.BiquadFilter instead works as expected. 

I'm using Tone v14.7.58 on Chrome OSX.

**Comment by tambien** [comment]
decibels here was being converted to a value between 0-1. This should be fixed when the next release is built and published.
