### ISSUE TITLE
Double-Accidental Support

### ISSUE THREAD

**Issue by mjhasbach** [Tonejs/Tone.js#81]
I am using [Teoria.js](https://github.com/saebekassebil/teoria) with Tone.js. Teoria sometimes returns notes in double-accidental format, which isn't supported by Tone. As a workaround, I am using Teoria to convert notes to frequencies, then feeding those frequencies into `triggerAttackRelease`.

    var synth = new Tone.MonoSynth().toMaster();

    synth.triggerAttackRelease("Cbb4", 3); // double-flat
    synth.triggerAttackRelease("Cx4", 3); // double-sharp

    // Uncaught TypeError: Failed to execute 'setValueAtTime' on 'AudioParam': The provided float value is non-finite.

**Comment by tambien** [comment]
Definitely! I will add this soon.

**Comment by stephaneeybert** [comment]
The sharp accidental is an x and not a # here ?

**Comment by tambien** [comment]
@stephaneeybert Sharp is `#`, double sharp is `x`
