### ISSUE TITLE
Many effects throw error `IndexSizeError: input index is out of bounds` [Safari 14.0.2]

### ISSUE THREAD

**Issue by brokyo** [Tonejs/Tone.js#813]
**Problem:** A number of effects [Tremolo, Chorus, Freeverb, JCReverb, Phaser, and PingPongDelay] throw the error `IndexSizeError: input index is out of bounds` on Safari 14.0.2 on an M1 Macbook Air which prevents audio from playing; the exact same code works on Chrome and Firefox. 

**To Reproduce:** This behavior can't be cleanly replicated on CodePen - I'm guessing there's something strange with the engine there? - so I've uploaded an .html file (as .txt to get passed format checking) to allow this to be quickly reproduced. 

[tremolo.txt](https://github.com/Tonejs/Tone.js/files/5752536/tremolo.txt)

**Context:** I'm attempting to port a fairly involved Tone.JS project over to a NativeScript WebView and I'm running into a bunch of problems that seems to be some combination of NativeScript, desktop Safari, and the latest version of Tone. Are there fundamental compatibility issues with NativeScript that make this a bad idea?

Thank you! I constantly use the library and it's one of my favorite creative tools.

**Comment by tambien** [comment]
@chrisguttandin does this sound familiar to you? would it be fixed by upgrading to the latest patch of standarized-audio-context?

**Comment by chrisguttandin** [comment]
No, I haven't heard of that problem before. It's new to me. Unfortunately I don't have one of the new MacBooks to test it myself.

@brokyo Can this also be reproduced when using the AudioNodes from the Web Audio API with and without standardized-audio-context?

**Comment by brokyo** [comment]
Hey all, appreciate the look.

I can create a `vibrato` and `tremolo` effect using the standard Web Audio API and basic nodes from Tone (though reading the Tone source, my approach is a bit different?) 

The rest of the effects are a bit outside of my immediate understanding, and I don't have the time at the moment to try to back out how they work. If it's useful for debugging, I can follow up over the next day or so on the rest :)

**Working Tremolo - Web Audio**
```
let context = new window.webkitAudioContext()

// Volume fluctuations
let gainOsc = context.createOscillator()
gainOsc.frequency.value = 10

let oscillatingGainNode = context.createGain()
oscillatingGainNode.gain.value = 0.1
gainOsc.connect(oscillatingGainNode.gain)

// Core pitch oscillator
let pitchOsc = context.createOscillator()
pitchOsc.frequency.value = 440

// Effect output    
let effectOut = context.createGain()
effectOut.gain.value = 0.5

// Connect everything
gainOsc.connect(effectOut.gain)
pitchOsc.connect(effectOut)
effectOut.connect(context.destination)

pitchOsc.start()
gainOsc.start()
```

**Working Tremolo - Tone JS**
```
// Volume fluctuations
let gainOsc = new Tone.LFO().start()
let oscillatingGainNode = new Tone.Gain(0.1)
gainOsc.connect(oscillatingGainNode.gain)

// Core pitch oscillator
let pitchOsc = new Tone.OmniOscillator(440).start()

// Effect output    
let effectOut = new Tone.Gain(0.5)

// Connect everything
gainOsc.connect(effectOut.gain)
pitchOsc.connect(effectOut)
effectOut.connect(Tone.Destination)
```

**Working Vibrato - Web Audio**
```
var context = new window.webkitAudioContext()

// Oscillator to modify detune
let modifyingOscillator = context.createOscillator()
modifyingOscillator.frequency.value = 10
modifyingOscillator.start()

// Gain node to control intensity of effect
let detuneGain = context.createGain()
detuneGain.gain.value = 100

// Core pitch oscillator
let baseOscillator = context.createOscillator()
baseOscillator.frequency.value = 440
baseOscillator.start()

// Connect Everything
modifyingOscillator.connect(detuneGain)
detuneGain.connect(baseOscillator.detune)
baseOscillator.connect(context.destination)
```

**Working Vibrato - Tone**
```
// LFO to modify detune
let modifyingOscillator = new Tone.LFO().start()

// Core pitch oscillator
let baseOscillator = new Tone.OmniOscillator(440).toDestination().start()

// Hook everything up
modifyingOscillator.connect(baseOscillator.detune)
```

**Comment by chrisguttandin** [comment]
Hi @tambien, I added some fixes to standardized-audio-context for Safari v14.0.2. I'm not 100% sure if those changes also fix this issue but it might be worth a try.

**Comment by tambien** [comment]
thanks, giving it a shot! 

@brokyo after it builds a new `tone@next` release, could you test out if it works when you have a moment?

**Comment by brokyo** [comment]
I'm sorry for the slow response! This was working on a straightforward implementation but I was getting inconsistent behavior in a more complex app. I'm now convinced it's user error and this fix does it :D

Thank you very much @tambien and @chrisguttandin. I have to imagine keeping Safari compatible is a nightmare and I appreciate you doing it :)

**Comment by teganscott** [comment]
@brokyo Did you do anything in particular to fix the issue? I am also having the same problem and only with Safari

**Comment by brokyo** [comment]
I'm afraid I didn't do anything special and a straightforward implementation worked. 

The project I'm working on is fairly involved so it's hard to pick out the source of my issue, but some early causes of this error were: multiple instances of Tone mounted on the page and, possibly, overwriting nodes without disposing of the old ones. 

The latter needs more investigation before I know that it's even real? But it's something I do regularly and maybe is the cause of what you're seeing?

**Comment by teganscott** [comment]
It sounds similar to my implementation as well. It is very involved with multiple instances of Tone. I'll see if there are any duplicates to it. I am a maintainer on a project and am not very familiar with Tone, so thank you for your direction!

**Comment by brokyo** [comment]
Yeah, I'm trying to build something for iOS on a webview and it's required me really tearing down most of what I've built :/ Lmk (assuming it's not annoying to @tambien) if you bump into other things as I suspect they'll be shared problems.

**Comment by Nek** [comment]
Hey.

I'm having the same problem. Any hints on the fix?

**Comment by Nek** [comment]
I've worked around the problem by avoiding disposal and recreation of the audio nodes network. Still, would be great to know if there is a more straightforward way to use Tone.js with Safari. Thanks!

**Comment by tambien** [comment]
@nek Have you tried using `tone@next`?

**Comment by Nek** [comment]
That's exactly what I'm using.
