### ISSUE TITLE
ScheduleRepeat varies time intervals when calling TriggerAttackRelease

### ISSUE THREAD

**Issue by twohiccups** [Tonejs/Tone.js#819]
When I schedule simple oscillators with stop/start functions the timing is precise. 

However when I schedule MembraneSynth, a Sampler, e.g, the timing becomes unstable. I suspect it might have something to do with TriggerAttackRelease function. 

Way to reproduce: 

```
const synth = new Tone.MembraneSynth().toDestination();

synth.trigger = function(time) {
    synth.triggerAttackRelease("C2");    
}

Tone.Transport.scheduleRepeat((time) => {
	// use the callback time to schedule events
	synth.trigger(time)
}, "8n");

Tone.Transport.start();
```

**Comment by tambien** [comment]
Make sure you pass in the time value that scheduleRepeat gives you to schedule the event accurately. Try something like this: 

```js
synth.trigger = function(time) {
    const duration = "8n";
    synth.triggerAttackRelease("C2", duration, time); 
}
```

**Comment by twohiccups** [comment]
Worked ty!
