### ISSUE TITLE
Multiple fade-ins and fade-outs causing overlapping effect

### ISSUE THREAD

**Issue by JeffreyCA** [Tonejs/Tone.js#821]
JSFiddle: https://jsfiddle.net/zb0roed9/3/

If you set fadeIn/fadeOut to something long like 1.5 seconds, and then repeatedly pause and play something in quick succession, multiple instances of the source track can be heard for a brief moment, creating an overlapping/stacking effect.

If the player is in the middle of fading out (due to pause) and the user clicks play, I would instead expect the fade-out to stop at that moment and switch to a fade-in.

Is this overlapping effect intended?

**Comment by tambien** [comment]
Yeah this is intentional. The fadeOut time happens _after_ 'stop' is hit. 

Check out [this issue](#725) for more discussion on this.
