### ISSUE TITLE
Getting current time

### ISSUE THREAD

**Issue by Christilut** [Tonejs/Tone.js#828]
I thought getting the current time would be something like this:
`Tone.TransportTime().toSeconds()`
or
`player.toSeconds(Tone.Transport.position)`

Both work until I do a seek like this:
`player.seek(progress * this.player.buffer.duration)`

Then they keep giving me the time of the context. How should I get the current playing time from a Player?

**Comment by phewitt** [comment]
I too am struggling to get the current player time.
