### ISSUE TITLE
Sampler to load local mp3 files

### ISSUE THREAD

**Issue by gouny-peto** [Tonejs/Tone.js#829]
Hi, First time here.  I'm launching an HTML file locally with a Sampler code below to load local mp3 files.

   const sampler = new Tone.Sampler({
	urls: {
		"C4":  "C4.mp3",
		"A4":  "A4.mp3",
	},
	baseUrl: "file:///home/john/Desktop/",
   }).toDestination();

But, it does not seem to work.  The baseUrl is same as that of the HTML file where I stored the mp3 files.  Thanks in advance for any help.

**Comment by vibertthio** [comment]
Tone.js uses `fetch` to send the request for the mp3 data and accessing file through file protocol (`file://`) is a [complicated thing](https://github.com/github/fetch/pull/92#issuecomment-174730593). I would suggest you use local server like [serve](https://github.com/vercel/serve) in the directory where you put the HTML and put your mp3 in the same folder. You can go to [Tone.js forum](https://groups.google.com/forum/#!forum/tonejs) to find more helps.

**Comment by tambien** [comment]
@vibertthio 🙏🏻
