### ISSUE TITLE
iOS playback in silent mode

### ISSUE THREAD

**Issue by davidfloegel** [Tonejs/Tone.js#832]
I'm not sure if this is a bug or a feature request - or both?

Basically, I'm building a web app that I want to be able to be used on a phone as well. On the iPhone I have, I have to unmute my phone. 

I did some research and it looks like that's required, _but_ I'm also using the Duolingo web app which plays sound just fine when my phone is silenced.

Is there any way that this might be possible with Tone? I'd rather not have my users have to unmute their phones...

Thanks!

**Comment by chrisguttandin** [comment]
Hi David, I'm also not sure if that is a bug or a feature. :-) However there is a workaround. @feross turned it into an npm package.

https://github.com/feross/unmute-ios-audio

**Comment by davidfloegel** [comment]
Interesting I'll check that out! Thanks so much
