### ISSUE TITLE
How can I create a single delay with lower amplitude?

### ISSUE THREAD

**Issue by danijar** [Tonejs/Tone.js#833]
The `Delay` node repeats the incoming signal once but does not seem to have a gain node for the delayed signal. The `FeedbackDelay` node has a gain node for the delayed signal but it feeds the delay back, resulting in a series of multiple delays. Is there currently a way in ToneJS to achieve a single delay with given time offset and amplitude? Thanks!

**Comment by tambien** [comment]
If you're happy with the way the FeedbackDelay reduces the amplitude, you could set FeedbackDelay.feedback.value = 0 so it wouldn't have any feedback delay. You could also use Tone.Delay combined with Tone.Gain to reduce the output of your delayed signal like this:

```
         +---> Output
Input ---|
         +---> Delay -> Gain -> Output
```

**Comment by danijar** [comment]
Thanks for the explanation, delay followed by gain and then connect both input and gain node to the output node was what I was looking for.
