### ISSUE TITLE
channelInterpretation cannot be changed from 'discrete'

### ISSUE THREAD

**Issue by diogocvaz** [Tonejs/Tone.js#842]
Newbie here. After bumping from v13.8.27 to v14.7.77 I started getting the following error when creating new components (Tone.Panner, Tone.Reverb, etc): 

Uncaught DOMException: Failed to set the 'channelInterpretation' property on 'AudioNode': ChannelSplitter: channelInterpretation cannot be changed from 'discrete'

**A simple example**

```
const panner = new Tone.Panner(1).toDestination();
const synth = new Tone.AMSynth().connect(panner).start();
synth.triggerAttackRelease("C4", "4n");
```

The error appears right after calling Tone.Panner. No issue when just calling Tone.AMSynth

Many thanks,
Diogo

**Comment by tambien** [comment]
Unable to recreate this error. Is there more context that you can give? platform or other parts of your setup? 

[Here's an example](https://codesandbox.io/s/affectionate-wind-e4bwb?file=/src/index.ts) of your code running. I had to remove `synth.start()` in the second line because that's not part of the API.

**Comment by diogocvaz** [comment]
Ok my apologies, found the issue. Apparently some conflict was occurring when also calling a web audio API script:

https://jsfiddle.net/w0a1of8t/4/

Here it throws a "Script error", but running it locally I get the error mentioned before (both on Chrome and Firefox).
Both scripts appear to be identical, so I'm not sure where the problem comes from, or why it gives problems with Tone v14 but not v13. !

**Comment by tambien** [comment]
great! glad you found the issue
