### ISSUE TITLE
Tone.Player() new Blob not generated

### ISSUE THREAD

**Issue by acondurache** [Tonejs/Tone.js#843]
I want to create a new audio blob with added Pitchshift, but when I try to create the blob is not generated and a recorder error is outputted see below. 

Error Message
 **Failed to execute 'stop' on 'MediaRecorder': The MediaRecorder's state is 'inactive'.**

Also, code below:

```
    navigator.mediaDevices.getUserMedia({ audio: true })
      .then(stream => {
        this.recording = true;
        this.startTimer();
        const mediaRecorder = new MediaRecorder(stream);
        mediaRecorder.start();

        const audioChunks = [];
        mediaRecorder.addEventListener("dataavailable", event => {
          audioChunks.push(event.data);
        });

        mediaRecorder.addEventListener("stop", () => {

          const audioBlob = new Blob(audioChunks, { 'type' : 'audio/wav; codecs=0' });

          var file = new File(audioChunks, "audio.wav", {
            type: "audio/wav",
          });

          const audioUrl = URL.createObjectURL(audioBlob);
          this.audioFileName = audioUrl;
          this.audioBlob = audioBlob;


          //const audio = new Audio(audioUrl);
          //audio.play();

          this.player = new Tone.Player({
              url: audioUrl,
              loop: false,
          });

          const actx  = this.player.context;
          const dest  = actx.createMediaStreamDestination();
          const recorder = new MediaRecorder(dest.stream);
          const chunks = [];
          
          const pitchShift = new Tone.PitchShift(9).toDestination();
          
          this.player.connect(pitchShift);
          Tone.getDestination().connect(dest);
          

          Tone.loaded().then(() => {
            this.player.start();
            recorder.start();
            recorder.ondataavailable = evt => chunks.push(evt.data); 
          });

          console.log(chunks);

          
          if(this.player.state == "stopped") {

            //recorder.stop();

            let blob = new Blob(chunks, { type: 'audio/ogg; codecs=opus' });
            let audioFinal = URL.createObjectURL(blob);

            console.log(blob);

            var filex = new File(chunks, "audio.ogg", {
              type: "audio/ogg",
            });

            console.log(filex);

          }

          this.presentRecordModal('none');
          this.modalAlreadyOpen = true;
          this.progressBar = 0;

        });

        setTimeout(() => {
          mediaRecorder.stop();
          this.modalAlreadyOpen = true;
        },10000);
      });

```

**Comment by marcelblum** [comment]
You're missing a call to `recorder.start()`. But also note that the way you have it set up you would only be recording the Player's output and not the pitchshift processed audio, because you only have the Player node connected to the `MediaStreamDestination` and not the PitchShift node. If you have no other nodes playing that you need to exclude from the recording, you can just hook up all of Tone's output to `recorder` by doing `Tone.getDestination().connect(dest)` instead of `this.player.connect(dest)`.

**Comment by acondurache** [comment]
@marcelblum thanks! I tried your code, however, the Blob size or File size is always 0. It doesn't seem like anything is being pushed into the chunks[] array.

**Comment by marcelblum** [comment]
Ok I see you edited your original posted code snippet, it looks like you're trying to record from a mic and then process the recording with pitchshift, yes? That means you have 2 different streams to manage - the mic's and Tone's output - and it looks like you're only fully handling the mic's `mediaRecorder`. In your posted code as of this writing :) it's missing a handler for `recorder.onstop` and the call to `recorder.stop()` is commented out so is never reached. I recommend you throw up your code on Codepen or similar to more easily allow for help and live editing.

Here's a basic example of losslessly recording the output of Tone.js for 10 seconds, works in Chrome at least (I don't know what browser you're testing/targeting):

```
const recorderStreamDestination = Tone.getContext().createMediaStreamDestination();
Tone.getDestination().connect(recorderStreamDestination);
const recorder = new MediaRecorder(recorderStreamDestination.stream, {mimeType: "audio/webm;codecs=pcm"});
const recorderChunks = [];
recorder.ondataavailable = function (e) {
	recorderChunks.push(e.data);
}
recorder.onstop = function stopRecording(e) {
	//do something with recorderChunks...
	//e.g. new Blob(recorderChunks)...
	//or if you want to allow the user to save to a local file:
	//URL.createObjectURL(new Blob(recorderChunks), { 'type': 'audio/x-matroska' })...
}
recorder.start();
setTimeout(function() {
	recorder.stop();
}, 10000);
```

**Comment by tambien** [comment]
@acondurache Is your issue resolved? 

I'll also point out [Tone.Recorder](https://tonejs.github.io/docs/14.7.77/Recorder.html) which wraps the Media Recorder API and works with Tone.js.
