### ISSUE TITLE
Sampler has considerable delay

### ISSUE THREAD

**Issue by brunocalou** [Tonejs/Tone.js#848]
**Describe the bug**

When using a **Sampler** to play sound according to a **Part**, the sound has a considerable delay. Also, sometimes it stops playing intermittently.

**To Reproduce**

https://jsfiddle.net/brunocalou/763pvwxr/7/

**Expected behavior**
The **Sampler** should play just like the **Synth**. Removing the **Synth** does not solve the problem.

**Additional context**

Tested on Mac Os Catalina, 10.15.6
* Chrome  88.0.4324.192 (x86_64)
* Firefox 86.0 (64 bits)
* Safari 13.1.2

It happens on all browsers I have tested

**Comment by tambien** [comment]
Thanks of the issue, the solution here is to remove `sampler.sync();` Here's an example of it running without the delay: https://jsfiddle.net/L39j2fsm/

After calling 'sync' all subsequent calls to triggerAttackRelease are scheduled using Transport time instead of the Audio context time.
