### ISSUE TITLE
Toggling Solo occasionally leaves another channel un-soloed

### ISSUE THREAD

**Issue by drumnickydrum** [Tonejs/Tone.js#849]
I have a drum kit of 9 samples being setup as shown below.  This has been working well throughout my React app. (for context: `kitRef.current` is an array of objects with properties for each sample. Each `sample` property is a url)
```
for (let i = 0; i < 9; i++) {
      kitRef.current[i].sampler = new Tone.Sampler({
        C2: kitRef.current[i].sample,
      });
      kitRef.current[i].channel = new Tone.Channel({
        volume: 0,
        pan: 0,
        channelCount: 2,
      }).toDestination();
      kitRef.current[i].sampler.connect(kitRef.current[i].channel);
```
Elsewhere, I implemented 'Solo' and 'Mute' toggles by setting `kitRef.current[i].channel.solo = !prev` .  It works _ok_ but at random `.solo = true` leaves one other sampler playing.  It's not always the same channel that is left open. 

I tried getting rid of Tone.Channel and using Tone.Solo instead to see if that would help, but in that case my toggle doesn't work at all.  Sorry if I'm misunderstanding how this is supposed to work.

**Comment by tambien** [comment]
Could you provide an example which demonstrates the issue? i'm unable to recreate the issue from the code that you included.

**Comment by drumnickydrum** [comment]
Thx pls give me a few days.

**Comment by tambien** [comment]
sure thing, thanks!

**Comment by drumnickydrum** [comment]
Problem has disappeared with some refactoring.  Was likely my own error.  Will open new issue if it happens again.
