### ISSUE TITLE
Start time must be strictly greater than previous start time for specific MetalSynth

### ISSUE THREAD

**Issue by jamesb93** [Tonejs/Tone.js#851]
**Describe the bug**

A description of what the bug is. 

`Start time must be strictly greater than previous start time` for a synth where I am passing the audio context's time in via a loop. This only happens with a MetalSynth instance and not any of the other instruments I have created.

**To Reproduce**
The code is hosted privately sorry. I have included the snippets I can below.

**Expected behavior**
Time should be resolved in a sensible way such that the time passed to subsequent triggers is always in the future.

**Additional context**
This is the construction of the Tone.Loop here
```js
const FM1 = 0
    const FM2 = 1
    const M1 = 2
    const M2 = 3
    const SNARE = 4;
    const KICK = 5;

    const loop = new Tone.Loop(time => {
        if (grid[SNARE][pos]) {
            snare.trigger(time)
        }

        if (grid[M1][pos]) {
            metal1.trigger(time)
        }
        
        if (grid[M2][pos]) {
            metal2.trigger(time)
        }

        if (grid[KICK][pos]) {
            kick.trigger(time)
        }

        if (grid[FM1][pos]) {
            fm1.trigger(time)
        }

        if (grid[FM2][pos]) {
            fm2.trigger(time)
        }
```
The MetalSynth is composed as an object which is imported elsewhere in the app like so:

```js
import * as Tone from "tone";

const out = new Tone.Gain(1)
const limiter = new Tone.Limiter(-1).connect(out)
const waveshaper = new Tone.Chebyshev(1).connect(limiter);
const source = new Tone.MetalSynth().connect(waveshaper);

export const metal = {
    out,
    waveshaper,
    source,
    trigger: (time) => {
        source.triggerAttackRelease(source.frequency.value, "8n", time)
    }
}
```

Perhaps I am performing the attack release trigger in a suboptimal way? I set the frequency value from elsewhere in the app.

**Comment by tambien** [comment]
Your code looks ok to me. I've seen this error happen when the audio context is not started on a button click (with `Tone.start()`)

I understand you can't share all the code, but is it possible to create a minimal functional example which reproduces this error in jsfiddle or codesandbox? Since running just the above code doesn't trigger the error when i run it.

**Comment by jamesb93** [comment]
I found the source of the issue. I moved the definition of each instrument to a class rather than as an object and made `new` instances for each. The error went away thusly...
