### ISSUE TITLE
scheduleRepeat adding steps randomly on restart

### ISSUE THREAD

**Issue by drumnickydrum** [Tonejs/Tone.js#854]
I wish I could rig up an online sandbox to replicate this but I can't get them to read my samples, I think something to do with cors.

See this vid for the behavior issue:
[https://youtu.be/aUGIwwGepiI](https://youtu.be/aUGIwwGepiI)

```
  const stop = () => {
    Tone.Transport.stop();
    Tone.Transport.cancel(0);
    stepRef.current = 0;
  };

const start = () => {
    if (Tone.Transport.state === 'started') return;
    schedulePattern();
    Tone.Transport.start();
  };

const schedulePattern = () => {
    console.log('schedulePattern');
    const cells = document.querySelectorAll(`.cell`);
    Tone.Transport.scheduleRepeat((time) => {
      console.log(stepRef.current);
      animateCell(time, cells[stepRef.current]);
      scheduleCell(time); // inside this function stepRef.current is incremented and then returned to 0 at end of loop.
    }, '16n');
  };

```

I've left out the implementation of scheduleCell(), as I think the problem happens before that.  You can see in the console in the video that scheduleRepeat starts getting called 3 times as fast.  If I keep restarting eventually it'll keep adding steps.

**Comment by tambien** [comment]
Is it possible that 'scheduleRepeat' is being called multiple times? that's what it kind of sounds like from watching the video. Maybe if you called `Tone.Transport.cancel(0);` at the top of schedulePattern to make sure that the timeline is totally clear before scheduling new events?

**Comment by drumnickydrum** [comment]
Tried that and still get the behavior randomly.  I added a console.log to the top of scheduleRepeat... check out what it shows when two steps are being played at the same time:

```
time: 13.500816326530613, stepRef.current: 0
time: 13.653941326530614, stepRef.current: 1
time: 13.650816326530613, stepRef.current: 2
time: 13.803941326530609, stepRef.current: 3
time: 13.800816326530613, stepRef.current: 4
time: 13.953941326530611, stepRef.current: 5
time: 13.950816326530614, stepRef.current: 6
time: 14.103941326530613, stepRef.current: 7
time: 14.100816326530614, stepRef.current: 8
time: 14.253941326530608, stepRef.current: 9
time: 14.250816326530613, stepRef.current: 10
```
It looks to me like step 0 is alone, then its being called in pairs (offset by about .0031) for steps 1/2, 3/4, etc.

**Comment by tambien** [comment]
If you take a look at the private variable `Tone.Transport._repeatedEvents` it should be empty after you call `Tone.Transport.cancel(0)`, is it?

**Comment by drumnickydrum** [comment]
No.  It is length: 0 until it starts repeating steps, then it is length: 1 or however many additional steps are playing (3 simultaneous steps -> length: 2, etc)

**Comment by tambien** [comment]
I'm unable to recreate this issue, here's an example that just uses a synth (so no CORS headaches)

https://codesandbox.io/s/schedule-pattern-issue-d6r30?file=/src/index.ts

**Comment by drumnickydrum** [comment]
Thank you so much for taking the time with this... That works great, and I can't see why my app should behave any different.  Is there any known issue with React and maybe with the global Tone object being duplicated or some other object reference weirdness that would cause `cancel()` to not clear the `_repeatedEvents` ?

**Comment by drumnickydrum** [comment]
I worked out a hack to ensure events are cancelled which has solved my issue:
```
Tone.Transport.cancel(0)
const scheduledEvents = Tone.Transport._scheduledEvents;
    Object.keys(scheduledEvents).forEach((id) =>
      Tone.Transport.clear(id)
    );
```
I saw that some scheduled events were remaining after the `cancel()` call, so this individually wipes them out.  Sorry if this is ugly but it works for now.  Thanks for your help and thanks for this dope library!

**Comment by tambien** [comment]
🙏🏻

**Comment by shahramSo** [comment]
I encountered with this issue in an Angular project, as example of @tambien, there is a problem to execute the schedulePattern method. this method should be executed one time in SPA projects like Angular or React.
So to solve this issue, I executed this method in ngOnInit separately.
