### ISSUE TITLE
Barrier to entry

### ISSUE THREAD

**Issue by theslyprofessor** [Tonejs/Tone.js#855]
I find the docs extremely confusing. I wish they were simpler and/or more interactive. I can't figure out how to make a simple sequencer that uses [bars:beats:sixteenths] for the life of me. Miller Puckette is my PhD advisor, and when I showed him the docs both of us couldn't figure out what to do. 

Also, I can't find the source file for Tone.js anywhere within the GitHub page. I heard that I need to update it so that I can get ToDestination() to work. Currently, only ToMaster() works.

**Comment by tambien** [comment]
Sorry to hear that you and MSP were having trouble finding the source. It's all located [here](https://github.com/Tonejs/Tone.js/tree/dev/Tone) in a folder called `Tone` in the main repo page. 

If you've got specific suggestions for how to make the docs more beginner friendly, i would gladly review a pull request. I know there's a lot in there and it can be hard to get started. I've been working on making more interactive examples (there's already at least 150 interactive snippets in the current docs) and onboarding tutorials, but it's deceptively difficult to make complex information simple. 

The main Tone.js [webpage](http://tonejs.github.io/) contains a little interactive walk through of the library which is intended to help people get the basics.

**Comment by theslyprofessor** [comment]
Ah, thanks for the response. I will respond more in full, but I cannot find
a "tone.js" file anywhere obvious. Is that the file that I should be
looking for?

**Comment by tambien** [comment]
The build file isn't in the repo, but you can find it [here](https://unpkg.com/tone@14.7.77/build/Tone.js).
