### ISSUE TITLE
Calling dispose() on PolySynth after scheduled (using '+') triggerAttackRelease() creates error

### ISSUE THREAD

**Issue by kovatsgergo** [Tonejs/Tone.js#857]
This works without error:
`xSynth= new Tone.MonoSynth().toDestination();
xSynth.triggerAttackRelease(330,1,'+1',1);
xSynth.dispose()`

This causes error:
`xSynth= new Tone.PolySynth().toDestination();
xSynth.triggerAttackRelease(330,1,'+1',1);
xSynth.dispose()`

Error message comes at around every 50 ms:
Uncaught Error: Synth was already disposed
    at r (Debug.ts:8)
    at pn._scheduleEvent (PolySynth.ts:241)
    at Object.callback (PolySynth.ts:253)
    at H._timeoutLoop (Context.ts:510)
    at H.emit (Emitter.ts:98)
r @ Debug.ts:8
_scheduleEvent @ PolySynth.ts:241
(anonymous) @ PolySynth.ts:253
_timeoutLoop @ Context.ts:510
emit @ Emitter.ts:98
15:13:54.250

I am also curious about how to kill all scheduled notes. Like a 'panic' or 'killall' function.
Using triggerAttackRelease() with '+' timing creates events seems to be unstoppable. At least not using Transport.stop() or releaseAll().

Any help is appreciated.

**Comment by tambien** [comment]
Fixed by #859
