### ISSUE TITLE
Please Include Tone UI component source in the repository

### ISSUE THREAD

**Issue by akesling** [Tonejs/Tone.js#858]
As it stands, going from an example on https://tonejs.github.io/examples/ to a working prototype requires an annoying process of reverse engineering what is going on.

You currently have to do the following:

1) Find the example which most closely matches your use-case on https://tonejs.github.io/examples/
2) Google search for the Tone.js Github repo (because there are zero links from the examples page)
3) Figure out which file in https://github.com/Tonejs/Tone.js/tree/dev/examples maps to the example you were just looking at on https://tonejs.github.io/examples/
4) Figure out what ToneUI component implements the functionality you saw on the example page
5) Learn that these components come from `./js/components.js` and open that to search for your component
6) Realize that `examples/js/components.js` is a generated file and that you need to go find the `Tonejs/ui` repository to look up these web components in their source TypeScript

To short-circuit the above issues, the following would be amazing additions to the examples:

1) Stick a Readme.md file in `examples/js` that explains where these files come from and how to look up the particular component you care about
2) Stick links from every example to the respective components it uses in `Tonejs/ui`
3) Add links in the left-hand bar and in each example page to the `Tonejs/Tone.js/examples` folder on Github (preferably to the actual example file)

By doing all three, it will dramatically improve the usability of the Tone.js examples pages.

**Comment by tambien** [comment]
The README in the examples folder has a link to the UI library: https://github.com/Tonejs/Tone.js/blob/dev/examples/README.md, so maybe the first suggestion is already satisfied (though in a slightly different folder than you suggest)

Regarding the other two suggestions, I'll admit that i make it a little difficult to find the UI components on purpose, so i probably won't add a link to the components in each of the examples. I use them in the examples, but don't intend to support them beyond that.

**Comment by akesling** [comment]
@tambien Thank you for the quick response.

This leaves me a bit confused, however.  Is the goal of these examples _not_ to help people solve problems / build things with Tone.js?

By 1) implementing the examples using software you "don't intend to support", and 2) making it difficult to map from the example to the code, doesn't this make Tone.js that much harder to learn/use?

Are there plans to migrate the examples to something that you _do_ intend to support?

It feels a bit odd to provide an example for, say, [making a step sequencer](https://tonejs.github.io/examples/stepSequencer) and then effectively tell the prospective Tone.js user "nah, figure out how to implement it yourself" :/.

Is there anything I could do to help improve this?
