### ISSUE TITLE
Cannot change any phaser attributes once it is created ie while running?

### ISSUE THREAD

**Issue by cordial** [Tonejs/Tone.js#860]
**The feature you'd like**
I'd like the phaser attributes (Q, frequency, baseFrequency etc to be settable after the Phaser is construted. 
**Any alternatives you've considered**
It's possible that I'm missing something here or it is possible and I haven't worked out how. The only way I can think from looking at the docs is is of constructing a new Phaser Object whenever the values change, but this doesnt seem like a good idea. It is also possible that this isn't really how the Phaser should work i.e. the values shouldnt be settable. I am not a sound engineer but I am making something for one and he is asking for the above in the module that we're making. 

**Additional context**
I want to add a phaser to a noise component and then edit the noise on the fly - 

     noise.current = new Tone.Noise().toDestination();
     noise.current.volume.setValueAtTime(noiseVol, 0)
     phaser.current = new Tone.Phaser(phaserState).toDestination();
     noise.current.connect(phaser);

To do this I need to be able to set these attributes in the UI - 

const [phaserState, setPhaserState]  = useState(
    {
      frequency: 0,
      octaves: 0,
      baseFreq: 0,
      Q: 0,
    } 

**Feature Requests will eventually be closed if inactive**

**Comment by cordial** [comment]
hey - It appears that I might have misunderstood and phasers (or at least ours) doesn't need to edit its settings on the fly. I presume that is why it isn't even possible in tone.js?

**Comment by cordial** [comment]
<img width="649" alt="Screenshot 2021-03-25 at 13 50 04" src="https://user-images.githubusercontent.com/419893/112483534-059e1880-8d71-11eb-9a47-791ba7ce8358.png">
 
 This is the error message if i try and edit frequency for example.

**Comment by cordial** [comment]
Ugh. It's 'phaser.current.frequency.value = newValue' isn't it.

**Comment by tambien** [comment]
Glad you figured it out! yeah all those audio params need to be set through `.value` as you mentioned (e.g. `phase.frequency.value = 10`)

I will look into maybe surfacing a better error for this situation
