### ISSUE TITLE
Feature Request: Tone.AND

### ISSUE THREAD

**Issue by Hazmatron7** [Tonejs/Tone.js#863]
I noticed that in earlier versions of Tone.js that there was more logic in the library especially Tone.js version r13. It came to me that I want to see if it's possible to recreate some of them using the nodes that are available today in the latest version of Tone.js. One of them I discovered was making Tone.AND.

```javascript

//process:
let a = new Tone.Abs(); //input A
let b = new Tone.Abs(); //input B

let gtza = new Tone.GreaterThanZero();
let gtzb = new Tone.GreaterThanZero();

let sum = new Tone.CrossFade({fade: 0.5}); //sum together by crossfading at 0.5
let output = new Tone.GreaterThan({value: 1}); //check if value is greater than 1

a.chain(gtza, sum.a);
b.chain(gtzb, sum.b);
sum.connect(output);

```
The way it works is that:

- For A and B takes an input scale of [-1, 1] which is then converted to a positive number using Tone.Abs
- Then It checks if it greater than zero so we only get 0 and 1 not 0.xxxx
- Then with the Tone.CrossFade with fade set to 0.5 it sums a and b together using equal power. With that the result should be 1 or 1.xxxxxx or higher.
- Then finally we use Tone.GreaterThan set the value to 1 to check if the output of the Tone.CrossFade it greater than 1. 

So the output should return 1 if both A and B inputs are not 0 and return 0 if either A or B or both are 0. 

**Note:** any number between 0 and 0.00098 (including negative numbers) for either input A or B will result the output to return 0.

examples:
```javascript
let sigA = new Tone.Signal(); //input A
let sigB = new Tone.Signal(); //input B
let meter = new Tone.DCMeter();
let lib = new Tone.AND();

sigA.connect(lib.a);
sigB.connect(lib.b);
lib.connect(meter);

//example 1:
//A = 1, B = 1, output = 1;
sigA.value = 1;
sigB.value = 1;
meter.getValue(); // returns 1


//example 2:
//A = 0, B = 1, output = 0
sigA.value = 0;
sigB.value = 1;
meter.getValue(); // returns 0


//example 3:
//A = 1, B = 0, output = 0
sigA.value = 1;
sigB.value = 0;
meter.getValue(); // returns 0


 //example 4:
//A = 0, B = 0, output = 0
sigA.value = 0;
sigB.value = 0;
meter.getValue(); // returns 0


//example 5:
//A/B set any number bewtween 0.xxxx to 1 with count as true
//A = 0.5, B = 0.5, output = 1
sigA.value = 0.5;
sigB.value = 0.5;
meter.getValue(); // returns 1


//example 6:
//Even Negative numbers will work fine.
//A = 1, B = -1, output = 1
sigA.value = 1;
sigB.value = -1;
meter.getValue(); // returns 1

```

@tambien what do you think? :)
I've tested this on firefox and it works but I do suggest have a play around with this idea
to get your opinion on if it works well or not.

**Comment by tambien** [comment]
@Hazmatron7 thanks for the feature suggestion, do you have a use-case for Tone.AND? I actually took it out because i felt like there wasn't any real-world need for it. I figured if i can't find a reason to use it, potentially no one else can either, but maybe there's something that i missed?

**Comment by Hazmatron7** [comment]
@tambien Firstly, sorry for not replying, I have been busy with other commitments. Secondly, I honestly thought it may have been removed because of performance etc. but I do see your point. However, I can't find a use-case for it either but If I do can let you know by making a comment on this issue if you'd like. Besides that I'm not sure what you want to do. :)
