### ISSUE TITLE
Feature Request: Allow panning and 3D audio nodes to be connected to Tone Objects

### ISSUE THREAD

**Issue by frastlin** [Tonejs/Tone.js#867]
**The feature you'd like**
I would like to have my synths or samples positioned in 3D audio, or panned from left to right. It would also be very useful if there was a way to have a sound moved from one position to another over a period of time.

**Any alternatives you've considered**
[WadJS](https://github.com/rserota/wad) allows this functionality for its oscillators, but it doesn't have sampling.

**Additional context**
I would like this for adding sound sources around a game landscape.

**Comment by tambien** [comment]
Tone.js has [Tone.Panner](https://tonejs.github.io/docs/14.7.77/Panner.html) and [Tone.Panner3D](https://tonejs.github.io/docs/14.7.77/Panner3D.html) which i think should accomplish what you're looking for. Both support parameter automations so you could schedule the pan to move over some period of time, or even connect an oscillator to control the panning. 

Here's an example using the 3D panner: https://tonejs.github.io/examples/spatialPanner
