### ISSUE TITLE
Tone.Loop with Tone.Draw stops when tab/window is blurred, Tone.Pattern continues playing

### ISSUE THREAD

**Issue by freshlySqueezedBananas** [Tonejs/Tone.js#869]
Hi, I'm building a drum machine, and I'm running into an issue when minimizing the window or changing tabs the audio just stops playing. I'm using Tone.Pattern on another feature and I don't have this issue. This tool serves as a practice tool for Bassists, it "needs" to be active while the player is checking other resources (like music score) in another tab.

How can I prevent a Loop from stopping when leaving the tab or minimizing the window? 

Tone.Loop + Tone.Draw https://jsfiddle.net/zqcj5brg/ (tone@latest)
Tone.Pattern  https://jsfiddle.net/t04qkcyo/ (tone@latest)

**Comment by tambien** [comment]
Tone.Draw puts things into the draw loop with requestAnimationFrame, which won't work in a background tab. but this isn't a limitation of Tone.Loop. 

You can schedule things in windows out of focus by removing Tone.Draw:

```js
  new Tone.Loop((time) => {
    for(let j=0; j<arr.length; j++){
      synth.triggerAttackRelease("C4", "4n", time)
    }
  }, '4n').start(0);
```

**Comment by freshlySqueezedBananas** [comment]
Thank you @tambien!
