### ISSUE TITLE
Add Tone.Loop's `interval` to Tone.Part

### ISSUE THREAD

**Issue by brokyo** [Tonejs/Tone.js#870]
**The feature you'd like**
I'd like to be able to schedule `Tone.Part` event collections as repeating loops with rests in between. This is possible using `interval` in `Tone.Loop` but, as far as I can tell, there's no easy equivalent in `Tone.Part`

**Any alternatives you've considered**
I can accomplish the same thing using Tone and basic JS so this is really a request for convenience :) Currently, I'm finding the final event in a part; summing the duration, time, and desired rest; and setting the resulting value as the part's `loopEnd`. This totally works, but it's a bit of an annoyance and sets up little stumbles as a system grows.

Example:
``` 
let composition = [{ note: `C3`, duration: `0:2:0`, time: `0:0:0` }, { note: `E4`, duration: `0:2:0`, time: `0:2:0`}, { note: `G3`, duration: `0:2:0`, time: `0:2:0` }]
let lastNote = composition(composition.length - 1)
let compositionEnd = Tone.Time(lastNote.time) + Tone.Time(lastNote.duration)
let restDuration = Tone.Time(`2:0:0`)

let calculatedInterval = compositionEnd + restDuration

const part = new Tone.Part((time, event) => {
	synth.triggerAttackRelease(event.note, event.duration, time)
}), composition);
part.loopEnd = calculatedInterval
part.loop = true
part.start()
```

**Additional context**
I suspect you could also use `Tone.Loop` to schedule the start of `Tone.Part` but that also seems to come with problems? But maybe I'm misinterpreting what `Tone.Loop` is there for.

This is hardly a blocker, but it's something I bump into a lot so I thought I'd flag it.

As always, thanks for the library and all the work on it :)

**Comment by tambien** [comment]
Thanks for your thoughts. I think that the way that you've described doing it is probably the best way to accomplish what you're looking to do. 

Tone.Loop's `interval`, [is implemented with `loopEnd`](https://github.com/Tonejs/Tone.js/blob/053b5d4397b595ea804b5d6baf6108158c8e0696/Tone/event/Loop.ts#L136-L141). So it's pretty much equivalent to the code that you have above, so `interval` might be a confusing API name for this function, which seems like it  `loopEndDelay` or something like that. 

Another way to accomplish what you're doing would also be to add another event at the end of the part array where the note is `null`. That way Part would calculate the end for you so you don't need to compute it, and in the callback loop you could check if the `event.note === null` before triggering the synth.

**Comment by brokyo** [comment]
An event with a null note is an interesting approach and, I bet, better for maintainability in generative stuff. Appreciate the look :)
