### ISSUE TITLE
The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead.

### ISSUE THREAD

**Issue by rottbers** [Tonejs/Tone.js#872]
Hey, thanks for this great library! I've recently started a React + Tone project using `v14.7.77` and noticed that in future versions of Chrome (checked both beta `90.0.4430.51` and dev ` 91.0.4464.5`) the following deprecation warning appears in the console:

```
[Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
```
It seems easy to reproduce (not specific to React) by simply importing Tone. Minimal example below:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tone test</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tone/14.7.77/Tone.js"></script>
  </head>
  <body>
    <h1>Tone test</h1>
  </body>
</html>
```

**Comment by tambien** [comment]
Thanks @rottbers, we're not relying on the ScriptProcessorNode for any audio processing so shouldn't be an issue that the ScripProcessorNode is being phased fully out in Chrome. It might still be referenced in the code from [StandardizedAudioContext](https://github.com/chrisguttandin/standardized-audio-context/) for feature detection which is my guess as to what's triggering the warning. 

@chrisguttandin's code does a great job of keeping up to date with the most-recent official API, i would expect the warning shouldn't affect anything, but might be there for a while.

**Comment by chrisguttandin** [comment]
Yes, I can confirm that it's only used for feature detection if the `AudioWorklet` is available instead. It should not be a problem.

**Comment by chrisguttandin** [comment]
Just in case someone finds this issue and wonders what happened. I finally "fixed" it (aka made the warning go away) with this (chrisguttandin/standardized-audio-context#982) change.

standardized-audio-context v25.3.12 and above shouldn't show the warning anymore.

**Comment by tambien** [comment]
🙌🏻 amazing! i'll update soon! the build system is down bc of travis-ci's changes, so i'll get that up and running so i can make this patch.
