### ISSUE TITLE
Creating envelopes not based on ADSR construction

### ISSUE THREAD

**Issue by jamesb93** [Tonejs/Tone.js#874]
Hi,

I often use line~ or curve~ objects in Max/MSP to create envelopes for synths. The basic gist is that you ask these objects to go from origin > destination over a given amoutn of time. For my purposes I find this more intuitive than ADSR.

What would be the best way to go about this? I currently have *something* but it doesn't really do what I would expect. Just as a note, the following code is called within a loop where the context time is passed in as an argument as `time`.
```js
const sig = new Tone.Signal(0); // just for clarity there is a signal defined

// and this b it happens inside of the loop where time is passed as time variable
sig.exponentialApproachValueAtTime(1, time, 0) //go to 1 now
sig.exponentialApproachValueAtTime(0, time+1, 1) // go to 1 over 1
```

Is this a valid strategy or should I be looking to do something like this another way?

**Comment by tambien** [comment]
Seems like a valid strategy. You can also take a look at linearRampTo, exponentialRampTo and targetRampTo. which might be slightly more similar to line~ API.
