### ISSUE TITLE
When I tried to chain a filter, envelope and panner to an OmniOscillator I get an error when I add the envelope

### ISSUE THREAD

**Issue by cordial** [Tonejs/Tone.js#875]
**Describe the bug**

When I try and chain a filter, envelope and panner to an oscillator I get an error

**To Reproduce**

In Wrapper Machine component - 

> ` function initialiseEnvelope() {
>     return new Tone.Envelope({
> 		  attack: 0.2,
> 		  decay: 0.7,
> 		  sustain: 0.9,
> 		  release: 2,
> 	  });
>    }`

Envelope is then passed into the Oscillator component (the italic line is where the error is thrown when you add in the envelope component)

> function initialiseOscillator(panner:Tone.Panner, filter:Tone.Filter, envelope:Tone.Envelope){
>       const oscillator = new Tone.OmniOscillator(0,  'sine');
>       _oscillator.chain( panner, filter,  envelope, Tone.Destination);_
>       oscillator.volume.value = -50;
>       return oscillator;
>     };

**Expected behavior**
Envelope changes the wave shape of the filtered oscillator

**Additional context**
Error message displayed - 

<img width="1068" alt="Screenshot 2021-04-14 at 15 47 04" src="https://user-images.githubusercontent.com/419893/114730469-cf810280-9d38-11eb-9999-78ec6132271f.png">

Here is the goal in diagram form (although we are ok with just one Volume Shaper now which is an ADSR on the overall sound output, rather than two different ones with one on each output). 

<img width="554" alt="Screenshot 2021-04-14 at 15 51 23" src="https://user-images.githubusercontent.com/419893/114730991-44ecd300-9d39-11eb-9a6e-4d0f9584370e.png">

**Comment by tambien** [comment]
Tone.Envelope is actually an envelope generator, just has an output but no input. If you want an amplitude envelope, you can either connect the envelope signal output to `Tone.Gain` or simpler would be to use `Tone.AmplitudeEnvelope`.

**Comment by cordial** [comment]
If I use AmplitudeEnvelope, I have two issues -
i) If I use oscillator.chain( panner, filter, envelope, Tone.Destination); as before, there is no noise from the oscillator. 
ii) If I use oscillator.connect(envelope) for testing/isolating purposes I can hear the oscillator noise but when I try and change attack, release, sustain, decay while its running the noise doesnt' change. I have tried this via a combination of (with attack example) -

> ` function handleAttackChange(name, newAttack, envelope) {
>     envelope.attack = newAttack;
>     envelope.triggerAttack();` 

newAttack corrently has a new value you in it but there is no change of noise (i initially tried without the triggerAttack part).
