### ISSUE TITLE
Tone.Player output device

### ISSUE THREAD

**Issue by antonsolokha96work** [Tonejs/Tone.js#877]
Is it possible to somehow change the device for playback?

**Comment by marcelblum** [comment]
Yes but only via a convoluted API with limited cross browser support, and at a latency hit. Basically you have to create a `MediaStreamAudioDestinationNode` to connect your Player node to and then pipe that into an `HTMLAudioElement` by setting it's `srcObject`, which you then set to output to the desired device using `setSinkId()` after retrieving a list of device IDs via `navigator.mediaDevices.enumerateDevices()`. Oh and AFAIK this can only be done after getting the horribly misnamed "microphone" permissions from the user (unless in Electron).

Check out https://webrtc.github.io/samples/src/content/devices/multi/ in Chrome as an example (note you may have to manually give the page microphone permissions through Chrome settings in order for it to work).

Further reading:
https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamDestination
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement
https://github.com/WebAudio/web-audio-api-v2/issues/10

**Comment by tambien** [comment]
thanks for following up @marcelblum!

**Comment by derbov** [comment]
And i got the answer myself.
Smth like this, a cuts from my code:

```
var elAudio = document.createElement("audio");
//elAudio.setAttribute("controls",true);
elAudio.setAttribute("autoplay",true);
elAudio.setAttribute("crossorigin","anonymous");
elAudio.setSinkId("default");

$(document).ready(function(){
	$("<select id='skinId'></select>").on('change', async function() {
			elAudio.setSinkId( this.value );
	})
	.appendTo($('body'));

	navigator.mediaDevices.enumerateDevices().then( devices => {
			audiooutput = devices.filter( d => d.kind == 'audiooutput');
			$('#skinId').html('');
			for (var d of audiooutput) {
				$('#skinId').append( $('<option value="'+d.deviceId+'">'+d.label+'</option>') );
			}
		} );

	player = new Tone.Player({
		url: '',
		autostart: true,
		loop: false,
		onload: () => {
			player.start(0);
			console.log('Audio started');
		}
	});
		
	player.onstop = () => {
			console.log('Audio finished');
		};
		
	player.onstart = () => {
			console.log('started');
		};	
		
	srcStream = Tone.context.createMediaStreamDestination();
	elAudio.srcObject = srcStream.stream;
	elAudio.play();
	player.connect(srcStream);


	player.load( data.Speech );
});
```

Do not use player.toDestination() or player.toMaster()
