### ISSUE TITLE
Uncaught Error: Tone.Sampler: url keys must be the note's pitch using sampler

### ISSUE THREAD

**Issue by Poliuti** [Tonejs/Tone.js#885]
HI,
when i run this code

  const sampler = new Tone.Sampler({
			urls: {
				C2: "kick.mp3",
				D2: "snare.mp3",
				E2: "hihat.mp3",
			},
			release: 1,
			baseUrl: "https://tonejs.github.io/audio/drum-samples/CR78/",
		}).toDestination();

I get the following error

Uncaught Error: Tone.Sampler: url keys must be the note's pitch

I looked at forums and other issues but I didn't find anything, do you have any idea to solve it?
Thank you in advance

**Comment by drumnickydrum** [comment]
Hi @Poliuti ✋

Are you programmatically adding urls to the sampler anywhere else or is this the only place you configure the sampler?

**Comment by tambien** [comment]
Closing bc of inactivity.
