### ISSUE TITLE
Schedule function call on Transport.stop?

### ISSUE THREAD

**Issue by noaLeibman** [Tonejs/Tone.js#887]
Hi!
I would like something like `Transport.scheduleOnStop(() => {...})` so I could do some stuff when the synced audio stops.
Is that possible?
Thank you:)

**Comment by Seanitzel** [comment]
I don't think anything like that exists in the current API of Tone.

If you want something that will happen everytime the transport is stopped you can simply create your own function that will stop the transport and then take care of all the side effects.

`function stopTransportAndCancel() {
  Transport.stop();
  Transport.cancel();
  ...other side effects
}`

**Comment by noaLeibman** [comment]
I wan't these side effects to happen when all of the audio that is synced to the transport ends on it's own, not when I explicitly call `Transport.stop()`, so I think this doesn't solve my problem (correct me if I'm wrong)..
But thanks for your reply!

**Comment by Seanitzel** [comment]
I see, in that case what i usually do is concatinate an event to the end of the events i schedule that takes care of the side effects.

**Comment by tambien** [comment]
Good suggestion @Seanitzel, if you know the duration of your audio file, then just scheduling another event when it's supposed to end is a simple way to achieve the results you're looking for. 

There is also a callback when an audio file is finished playing if you're using Tone.Player

```js
player.onstop = () => {
 // callback when audio file is completed
}
```

Also if it's helpful to get a callback when `Transport.stop()` is invoke: 

```js
Transport.on('stop', () => {
  // callback when 'Transport.stop' is called
})
```

**Comment by noaLeibman** [comment]
`player.onstop` might do the trick:)

Thanks! @Seanitzel @tambien
