### ISSUE TITLE
First Tone.Player looped sample not reliably triggering (browser dependent) 

### ISSUE THREAD

**Issue by cantonbecker** [Tonejs/Tone.js#893]
I wonder if anyone has  advice on how to make my Tone.js composition a little more reliable:

https://pisongs.com/techno/

After the samples load and the play button is revealed, click the play button. After a few seconds  -- when the digit "1" lights up in the "3.14" tickertape) you should hear a bell rhythm and a banging beat, generated by:

```
// this is the banging beat
Tone.Transport.schedule(function(time){ loopDronePlayer500.start(3.8095238095238 + loopOffset); }, 3.8095238095238 + loopOffset);

// this is the bell rhythm
Tone.Transport.schedule(function(time){ loopPlayer497.start(0 + loopOffset); }, 0 + loopOffset);

```
- On Safari OS X this works reliably
- On Chrome & Firefox OS X, not so much. Especially if you open in an incognito window so that all the samples have to load from scratch, sometimes all you'll hear is a slow fading string type sound (from the sampler instrument, which is reliable on all browsers). No bell rhythm, no beat.
- On Edge Windows 10, those the bell and beat almost *never* kick in at the beginning. 

The way I've solved this in the past is by detecting the browser and adding extra silence at the beginning of the whole song, sometimes up to 6 seconds. But I wonder if there's something fundamentally wrong about how I'm invoking the Tone.js audio engine or something.

If you view source on the page, 100% of the javascript is right there in the html file. Nothing is external other than Tone.js, which makes it pretty easy to examine/debug.

Thanks for any tips!

**Comment by tambien** [comment]
Please post questions to the forums and not the issues page. 

My guess by glancing at your snippets: the timing issue is related to not using the transport time in the callback function. Make sure you pass the `time` given by `Transport.schedule` in when scheduling your samples.
