### ISSUE TITLE
Is there a way to get timing of when the note was .triggerAttack & .triggerRelease

### ISSUE THREAD

**Issue by silenceofthewans** [Tonejs/Tone.js#900]
I'm trying to add a record and replay feature to my piano. Essentially, I want to capture the notes during my `playNote()` function if the user has clicked on record button and then when they press play I want the array of notes to be played as they themselves originally played, as you can see in `playRecNotes()`. I though of passing array of notes to Tone.Sequence but it plays in the same rhythm then I looked into Tone.Part because you can pass time,value pairs. So, I thought I would capture the Tone.now() at that time and note like` ["23.444", "C3"]` and pass that to Tone.Part and It plays close enough but starts very late and doesn't loop so I try to offset the start of Tone.Part with `recordedNote[0][0] //Saved Tone.now() of the first note in array of notes` and it plays quickly and pretty accurately but still doesn't loop and also any additional note added will play quiet some time later . I think I'm missing here something with timing because I'm using Tone.now() to keep track of rhythm. I'm new to programming and very new to music so apologies if this isn't the right place to ask these question.

```
const playNote = (note) => {
    setCurrentNote(note);
    Tone.loaded().then(() => {
      if (isRecording) {
        setrecordedNote([...recordedNote, [Tone.now().toFixed(3), note]]);
      }
      piano.triggerAttack(Tone.Frequency(note), "+0.05");
    });
  };
```

```
const playRecNotes = () => {
    console.log(recordedNote);
    if (!recordedNote.length) {
      console.log("Nothing to play!");
      return;
    }

    const part = new Tone.Part((time, note) => {
      piano.triggerAttackRelease(note, "1m", time);
    }, recordedNote).start(0, recordedNote[0][0] - 0.5);
    part.loop = true;
    Tone.Transport.start();
  };
```

**Comment by tambien** [comment]
There is no API to get exactly what you're describing, but it looks like you're very close to a solution. My guess is the silence before it starts looping has to do with not setting the `loopStart` point. Try setting that to `recordedNote[0][0]`

**Comment by silenceofthewans** [comment]
Yep setting the loopStart & loopEnd did the trick! but I was still having issues so in the end I just started transport when I started capturing and used `Tone.Transport.seconds` without any offset and start argument in the Tone.Part. Thanks for your help & time!
