### ISSUE TITLE
Update standardized-audio-context

### ISSUE THREAD

**Issue by BrandonMathis** [Tonejs/Tone.js#907]
I have been using version 25.2.8 of standardized-audio-context with great success as Tone.js' AudioContext. I primarily had to do this to utilize the new `createMediaStreamTrackSource` method which allows me to work directly with a MediaStreakTrack as an audio source. 🎶

Out of curiosity, is updating Tone.js deps to the latest version of standardized-audio-context on the roadmap?

**Note:** I have issues with version 25.2.9 (initializing a new `Meter` object raises errors about `AudioParam`) but 25.2.8 works great!

**Comment by chrisguttandin** [comment]
Hi @BrandonMathis, can you share what problems you ran into with v25.2.9? Maybe there is something I need/can/should fix.

**Comment by BrandonMathis** [comment]
Actually... I think i was mistakenly using the browser's built-in `AudioContext` 😅

I moved back down to the current version of standardized-audio-context and `createMediaStreamTrackSource` works great.

I will close this issue.
