### ISSUE TITLE
iOS hardware switch mutes sound in cordova app

### ISSUE THREAD

**Issue by martijnmichel** [Tonejs/Tone.js#909]
Just as topic states, sound works in a cordova app. But when switching the hardware mute switch off tone js doesnt produce any sound. While other apps can still play sound.

This might not be ToneJS related but I am still wondering if anyone else has this problem and if anyone found a fix?

**Comment by tambien** [comment]
This package might work for you: https://www.npmjs.com/package/unmute-ios-audio

**Comment by martijnmichel** [comment]
Seriously, after nearly 2 years I have finally found a solution to the mute switch problem. Turns out it wasn't even cordova related, probably why I didn't find this earlier. Many thanks for pointing me in this direction.

Solved it by using this tiny js script:
https://github.com/swevans/unmute
