### ISSUE TITLE
HTML5 not working

### ISSUE THREAD

**Issue by joex92** [Tonejs/Tone.js#913]
**Describe the bug**

HTML5 loading not working anymore...
![image](https://user-images.githubusercontent.com/645579/125171719-28ff9e80-e17b-11eb-9d89-9a43c65d823f.png)
on other instances this happens:
```apache
Uncaught TypeError: Cannot read property 'connect' of undefined
    at is (tone:1)
    at tone:1
    at new r (tone:1)
    at Object.createConstantSource (tone:1)
    at Gi.createConstantSource (tone:7)
    at new Ao (tone:21)
    at new Do (tone:21)
    at new _r (tone:21)
    at new jr (tone:21)
    at <anonymous>:1:19
is @ tone:1
(anonymous) @ tone:1
r @ tone:1
createConstantSource @ tone:1
createConstantSource @ tone:7
Ao @ tone:21
Do @ tone:21
_r @ tone:21
jr @ tone:21
(anonymous) @ VM14187:1
```

**To Reproduce**

Just add `<script src="https://unpkg.com/tone"></script>` to a simple HTML5 page.

**Expected behavior**
Completed defined `Tone` variable.

**What I've tried**
used [simpleHtml exmaple](https://github.com/Tonejs/Tone.js/blob/dev/examples/simpleHtml.html) method.
used `<script src="node_modules/tone/build/Tone.js"></script>` after downloading it from `npm` command.

**Comment by tambien** [comment]
Is there an error above it that it can't load "mixed content"? It's possible that the URL is being blocked if you are loading `http://unpkg.com/tone` instead of `https://unpkg.com/tone` while on an `https` domain.

**Comment by joex92** [comment]
> Is there an error above it that it can't load "mixed content"? It's possible that the URL is being blocked if you are loading `http://unpkg.com/tone` instead of `https://unpkg.com/tone` while on an `https` domain.

yeah, tried both... Actually I tried the same example "simpleHtml" and it doesn't work...

**Comment by joex92** [comment]
> Is there an error above it that it can't load "mixed content"? It's possible that the URL is being blocked if you are loading `http://unpkg.com/tone` instead of `https://unpkg.com/tone` while on an `https` domain.

there wasn't any errors above that... but I tried again and now it works...
