### ISSUE TITLE
Setting volume on individual players has no effect

### ISSUE THREAD

**Issue by firelex** [Tonejs/Tone.js#917]
Possibly related to the issue I previously reported.  If I load a drumkit in to Tone.Players(), then loop through the drums by index and set the volume to -50, it has no effect.

For example:

let drums = Tone.Players( ... );
drums.player(0).volume.value = -50;

Even though the property is correctly set on the individual player (I can read it out again after setting it), the player plays with the volume of the Players object, not with the volume set on the individual player.

**Comment by tambien** [comment]
I'm unable to reproduce this issue. Here's a little example of loading two samples and setting one of the samples volume to -50db

```ts
import { Players, start, loaded } from "tone";

const players = new Players().toDestination();
players.add("gong", "https://tonejs.github.io/audio/berklee/gong_1.mp3");
players.add("quietGong", "https://tonejs.github.io/audio/berklee/gong_1.mp3");

players.player("quietGong").volume.value = -50;

document.querySelector("button")?.addEventListener("click", async () => {
  await start();
  await loaded();
  players.player("quietGong").start();
  players.player("gong").start("+1");
});
```

https://codesandbox.io/s/nostalgic-archimedes-le6qt?file=/src/index.ts
