### ISSUE TITLE
p5.Tone outdated link

### ISSUE THREAD

**Issue by joex92** [Tonejs/Tone.js#920]
just checked the [p5.Tone Wiki](https://github.com/Tonejs/Tone.js/wiki/p5.Tone) and the given link doesn't exist anymore... 
Is there no p5.Tone support anymore? or is the link outdated?

**Comment by tambien** [comment]
This link is old and no longer needed. 

I use p5 with Tone.js all the time, it doesn't really require any specialized build anymore and can be loaded and used together. You might need to remove p5sound from your p5 sketch so that there are no conflicts, but otherwise should work.

**Comment by joex92** [comment]
> This link is old and no longer needed.
> 
> I use p5 with Tone.js all the time, it doesn't really require any specialized build anymore and can be loaded and used together. You might need to remove p5sound from your p5 sketch so that there are no conflicts, but otherwise should work.

oh, you're right, just tried... then maybe you should update the p5.Tone Wiki...
