### ISSUE TITLE
@tonejs/ui doesn't compile to ESM

### ISSUE THREAD

**Issue by ShivamJoker** [Tonejs/Tone.js#930]
I installed the ui library with yarn but it seems there is no esm builds

![image](https://user-images.githubusercontent.com/23727670/129474490-842b7a65-13a4-4be6-bc7c-e853fc0b6076.png)

**Comment by tambien** [comment]
Unfortunately the UI that is part of the examples is not a supported part of the library beyond the examples page, so i wont be adding additional compile targets beyond what's used for the Tone.js examples page.
