### ISSUE TITLE
triggerAttackRelease always playing the same note

### ISSUE THREAD

**Issue by NathanWailes** [Tonejs/Tone.js#932]
I'm not sure if this is a bug or just me not using the library properly.

Here's a 4-minute video in which I show the issue: https://www.loom.com/share/b2cd90c04d1e423db07fdf8ff77a19fe

Basically, I have a data structure that represents the timing of rap lyrics, and I want to play tones as an indicator of what the lyrics would sound like if performed by a person.  I want the tone to alternate between two different tones so that it's easier to hear where one syllable ends and the next one begins.

The problem is that no matter what I pass as the note to triggerAttackRelease, it always plays the same note.   I have a console.log immediately before triggerAttackRelease is called which shows that I am passing different values to it.

**Comment by tambien** [comment]
Thanks for the video, i watched the it but couldn't really hear the notes that it was playing

Here's an example of something similar to the code that you show in the video that is able to play the desired notes: https://codesandbox.io/s/quirky-frog-4jh23?file=/src/index.ts

**Comment by NathanWailes** [comment]
I got it working!  It turns out I had another place in the code where I was setting triggerAttackRelease (I had refactored one function and pulled out its logic into a second function, but I somehow missed deleting some of the code in the earlier function, which was still being run to handle the visual display of the lyrics).

Thank you so much for your help!
