### ISSUE TITLE
FFT values vary across browsers

### ISSUE THREAD

**Issue by thegeminisociety** [Tonejs/Tone.js#933]
I am reading a buffers FFT values using the analyser and notice that I am getting slightly different values across browsers (chrome vs safari). Is this expected? Is there a way to somehow normalize this? Thanks

**Comment by tambien** [comment]
I think last i checked Safari still hasn't implemented a key component of the AnalyserNode which is used in the FFT class which might be why the values are so different. I think until Safari implements the full spec, there isn't anything we can do about it.
