### ISSUE TITLE
Pattern.index is very needed

### ISSUE THREAD

**Issue by davay42** [Tonejs/Tone.js#934]
I'm building a flexible step sequencer based on the Tone.Pattern. I've got variable number of lanes with dynamic step count. 

I use empty arrays that get a `true` value when user activates a cell. Every lane has it's own note to play. Everything works fine, but I can't find a reliable way to get the current position of the pattern. 

The callback gets only `time` and `value` is either `undefined` or `true` and the `Tone.Pattern` in Tone v.14. doesn't have the `.index` feature, that was there in v.13. https://tonejs.github.io/docs/r13/Pattern#index

For now I'm using a simple `up` pattern and can set a separate `Tone.Pattern` to count and array of consecutive numbers, but I have issues with them getting out of sync. So it seems there is no solution to track the position of the Pattern in the `values` array. Especially when using the fancy random modes. 

Please, can we have the `Pattern.index` property back any time soon?

**Comment by davay42** [comment]
May be it could be even more convenient and easy to implement: the callback may receive the index of the current array element as the third argument. 💡

**Comment by dirkk0** [comment]
Not entirely sure if this adresses your problem, but you could do
`const [bar, beat, sixteenth] = Tone.Transport.position.split(":");`
in a scheduleRepeat which would give you bar and beat.
So in a 4/4 measure `bar*4 + beat` modulo the pattern length should give you the index as the remainder?

**Comment by davay42** [comment]
@dirkk0 Nice trick, may be helpful in some cases.

**Comment by yifanmai** [comment]
The method was removed during the [conversion to TypeScript](https://github.com/Tonejs/Tone.js/commit/93eab5e6a3a39110096d2e9b1fb49182997452bd#diff-aa685a21d26f9d83955f372bb0140851daaf4c5563774488c70b70eb31349fee). I opened #1005 to add it back.
