### ISSUE TITLE
Determine the end of the buffer

### ISSUE THREAD

**Issue by shahramSo** [Tonejs/Tone.js#937]
This is not a bug but I have search in your doc but I couldn't to find a solution.
Inspired by this project:
https://learningmusic.ableton.com/index.html

I wanted to know how to determine the end of the buffer in a player?
As you can see in this example; If a drum player is playing and you start playing a melody, then the melody player waits for the drum to finish playing and then it starts.
To sync a multiplayer while is looping, ending of the buffer is needed for starting other players, is there any solution?
Thanks

**Comment by tambien** [comment]
You could either use the Player's [`onstop`](https://tonejs.github.io/docs/14.7.77/Player.html#onstop) method or just schedule an event to happen at the player's start time + the `player.buffer.duration`. 

Hope that helps!
