### ISSUE TITLE
Offset a Player relative to Tone.Transport.position

### ISSUE THREAD

**Issue by arpo** [Tonejs/Tone.js#938]
Offset a Player relative to Tone.Transport.position
=====================================

I have a song as a mp3 that I sync to the Transport using a Player.
This song begins with silence for some ms before it starts. 
What I would like to do, and haven't found how to, is to offset the players start time relative to the Tone.Transport.position with a negative number. I tried to set the player.start(-0.2) but that didn't work.

**Comment by tambien** [comment]
You can use the second argument of player.start to do this and start the player at a 0.2 second offset like this: 

```ts
player.start(0, 0.2)
```
