### ISSUE TITLE
Events that are launched prior to Tone.Transport.stop() are not removed from the queue

### ISSUE THREAD

**Issue by MechanicallyDev** [Tonejs/Tone.js#945]
**Describe the bug**

When changing between musics, or when reloading musics, the notes from the music that was playing earlier are not removed from que queue, and oftenly the old note times are more recent than the last ones (in `now()+overhead` time), giving the error: `Uncaught Error: The time must be greater than or equal to the last scheduled time`

**To Reproduce**
Added an example of the issue, try clicking the "start music" multiple times, until you get an error.
https://jsfiddle.net/0b64odpu/19/

**Expected behavior**
When using the Tone.Transport.stop() and/or the Tone.Transport.clear() methods, the event queue should be cleared so new notes can be played without garbage from the previous execution.

**Comment by tambien** [comment]
Instead of using the `note.time` as the time argument of `triggerAttackRelease` you should use the time which is passed in from Tone.Part. 

Check out this fiddle: https://jsfiddle.net/hkojax8L/1/

I think it fixes the issue that you're having.

**Comment by MechanicallyDev** [comment]
> Instead of using the `note.time` as the time argument of `triggerAttackRelease` you should use the time which is passed in from Tone.Part.
> 
> Check out this fiddle: https://jsfiddle.net/hkojax8L/1/
> 
> I think it fixes the issue that you're having.

Oh, thank you very much... I wasn't exactly sure how the part deals with time.

While using the time coming from the part fixes additional notes that were introduced by previous executions, there is still some garbage collection to be made.
You can check on your fiddle by clicking the play button several times. By the 10th run the sound is already quite distorted, and it quickly worsens from there.

Is there any function that removes any synth that is currently loaded or unused? 
I tried moving the synths array to a global scope and using a loop to use the dispose function on each synth, but it still keeps some (but not all) of the synths, so it is better but still worsens over time and throws an error on the console saying the synth was already disposed. 
https://jsfiddle.net/stjge0vq/4/

**Comment by tambien** [comment]
If you're trying to clear the timeline with `clear` between takes, [clear](https://tonejs.github.io/docs/14.7.77/Transport.html#clear) clears an ID number scheduled with `Transport.schedule`. i think the command you're looking for is `Transport.cancel(0)` which will clear the entire timeline after 0.

**Comment by MechanicallyDev** [comment]
Thanks @tambien, I just tried replacing the clear method with Transport.cancel(0) ( https://jsfiddle.net/vL8cnmyp/ ) and it seems to fix the issue.
