### ISSUE TITLE
How to use Tone.js to preserve audio's pitch when changing its playbackRate using AudioBufferSourceNode

### ISSUE THREAD

**Issue by Jun711** [Tonejs/Tone.js#951]
I used [sample code on MDN github](https://github.com/mdn/webaudio-examples/blob/master/offline-audio-context-promise/index.html) to change an audio's playbackRate but the original audio pitch is not preserved.

```
audioCtx.decodeAudioData(audioData, function(buffer) {
      myBuffer = buffer;
      source.buffer = myBuffer;
      source.connect(offlineCtx.destination);
      source.playbackRate = 1.5; // <<<<<<<<< added this to change playbackRate
      source.start();
      //source.loop = true;
      offlineCtx.startRendering().then(function(renderedBuffer) {
        console.log('Rendering completed successfully');
        
        let song = audioCtx.createBufferSource();
        song.buffer = renderedBuffer;

        song.connect(audioCtx.destination);

        play.onclick = function() {
          song.start();
        }
      }).catch(function(err) {
          console.log('Rendering failed: ' + err);
          // Note: The promise should reject when startRendering is called a second time on an OfflineAudioContext
      });
    });
    
 ```

It is the same question as this[ Stackoverflow question](https://stackoverflow.com/questions/31274895/changing-speed-of-audio-using-the-web-audio-api-without-changing-pitch)

Jacob suggested in this thread that we can use Tone.js to change the pitch. I am not really sure how to make it make it work.
<img width="735" alt="Screen Shot 2021-09-21 at 6 33 51 PM" src="https://user-images.githubusercontent.com/6880939/134269497-d350feec-9088-473d-a201-e592abcce1d0.png">

I am not sure how I can achieve this and I am not familiar with semitone / cents etc. Can you someone point me to the right direction? Thank you

**Comment by tambien** [comment]
I would use GrainPlayer which would give you that control. Tone.PitchShift might also work, but would likely introduce more artifacts. 

A semitone is a single step in a chromatic scale like between C to C#.

**Comment by Jun711** [comment]
@tambien 
Thank you for your help. I have 2 questions if you don't mind.

1.
I made a CodePen used GrainPlayer to play audioBook short clip at higher playbackRate and compared it with HTML audio element playing audio at a higher playbackRate. The audio playback by GrainPlayer seems to have some echo. Is that expected? 
```
source = new Tone.GrainPlayer({url: audioBuffer, playbackRate: 2})
source.toDestination()
source.start(0);
```
https://codepen.io/juny711/pen/abwjaJE
You can download the audio I used from my [github repo ](https://github.com/Jun711/html5-audio-rubberband/blob/dev/audio1.mp3)

2) It is the same question as the above.
How can I get the renderedAudioBuffer out from GrainPlayer so that I can pass it to OfflineAudioContext or how do I set the destination as OfflineAudioContext?
