### ISSUE TITLE
`Part` has extra notes and timing is imprecise.

### ISSUE THREAD

**Issue by Enteleform** [Tonejs/Tone.js#960]
# Describe the bug

### Expected
  
Playing a `Part` will:
- trigger each `ValueType` once
- result in precisely timed playback

### Actual

- `ValueType`s are intermittently triggered more than once

https://user-images.githubusercontent.com/10906415/137102718-904e2175-f43b-4d27-87cc-ec62ce229616.mp4

&nbsp;  
- there are intermittent variances in playback timing
  - bottom values show the most consistent interval
  - top values show variance
  - a single sample was used for this test, so there is no variance in sample length

![Tone - Timing Issue - Waveform](https://user-images.githubusercontent.com/10906415/137102716-433a98ff-c5a7-44e5-8681-d3fd2d6add46.png)

&nbsp;  
# To Reproduce

https://codesandbox.io/s/nervous-shape-yfnub?file=/src/index.tsx

&nbsp;  
# What I've tried

I used `ticks` and `Player` instances in the demo, but I've also experienced the same issues with `Synth` and `Transport` time.

**Comment by tambien** [comment]
The time passed into the Part will always be increasing because the AudioContext clock is always increasing. Part is essentially a converter between Transport time which loops/starts/stops and the AudioContext clock which is only increasing.

**Comment by FractalHQ** [comment]
@Enteleform I've been working with Tone for months and am running into this issue still, and no matter how many times I read the docs (which are mostly 1 vague sentence per class) and issues like this one, I'm still confused about all the different versions of `time` and how to properly use the `Part` depending on the context.  Whenever I feel like I understand what to do, the behavior winds up being very buggy and unpredictable.

Did you ever find an answer to your question?

**Comment by Enteleform** [comment]
@FractalHQ

I managed to get precise timing, but ended up using a custom algorithm to manage `Tone.Transport.schedule` events instead of using `Part`s.

https://user-images.githubusercontent.com/10906415/148649408-e57118f4-3f06-4865-97fc-f06bcba25ee2.mp4

Might be possible using `Part` as well but the `schedule` implementation covered the needs of the app, so I didn't look into it any further.
