### ISSUE TITLE
changing bpm effects the Transport scheduling

### ISSUE THREAD

**Issue by cordial** [Tonejs/Tone.js#962]
Should the bpm of transport effect the timings of schedule events? It currently seems like it does. 

**To Reproduce**

Schedule an event like- 
Transport.schedule((time) => {
							currentName = narrativeEmotion.name;
							handleAudioChange(narrativeEmotion.name, results);
							// setIntro(false);
							// setCurName(narrativeEmotion.name);
						}, 20);

If you however change the transport bpm like 

Transport.bpm.value = 120

This seems to effect when the schedule is hit - I would have expected this to be independent? Is that not the case? Is there a way to change bpm but not affect transport scheduling? Or does that not make any sense?
**Expected behavior**
Event happens after 20 seconds.

**Comment by cordial** [comment]
Sorry, to provide some context - what I am trying to achieve is the following -
i) a metronome that you can dynamically adjust the bpm for (it currently plays using scheduleRepeat every 4n using a 'player' object). 
ii) A timeline that triggers events, as above, after x seconds that doesn't respond / change if i edit transport.bpm.value (or if better another way to edit the speed of the metronome rather than editing transport.bpm.value)

I was kinda expecting if you triggered events in seconds, that it would ignore the bpm...

**Comment by tambien** [comment]
I've had similar questions to this in the past, even if you schedule something using seconds instead of a tempo-relative value it will be converted into ticks which will mean that it will stay tempo-relative. 

Currently there's no mechanism to do what you're looking for in Tone.js. sorry! 

Maybe a new method like `scheduleAtTime` or something like that would be useful for what you're doing.

**Comment by cordial** [comment]
When you say nothing is available, do you mean i'll have to adjust the timings myself? Does that mean if the bpm is 60 that transport schedule would happen at that actual time specified, and if it was 120bpm I would need to double the timings etc?

Or do you mean it just won't work?

scheduleAtTime sounds good - is this library still actively being updated with new versions?

**Comment by dirkk0** [comment]
Changing tempo and even time signature might not be straight forward but it is possible.

Here's an example that I did some time ago, and finally put it on CopePen:
https://codepen.io/dirkk0/pen/mdMVpzE?editors=1010

It changes the signature and the bpm twice before ramping the tempo down.
