### ISSUE TITLE
Envelope release problems

### ISSUE THREAD

**Issue by lukephills** [Tonejs/Tone.js#97]
Hi Yotam,

We're experiencing a few issues with the Envelope release. Here's an example.

Noise connected to an AmplitudeEnvelope with the attack set to 2 seconds.
Trigger the attack and then change the attack value to 0.01 and release whilst still in the attack phase (within those 2 seconds)

You will hear a loud bang. `_valueAtTime()` is evaluating to a high number above 1 (sometimes in the 40's).

Also occasionally when i triggerAttack in release phase and triggerRelease in the attack phase the audio fails to ramp back to to 0. 

Have you got any ideas?

**Comment by lukephills** [comment]
Here is an example of what `_linearInterpolate` is evaluating to:

A normal release: 
0.0001 + (1 - 0.0001) * ((86.07 - 85.74) / (86.74 - 85.74))
= 0.33

Loud volume increase: 
0.0001 + (1 - 0.0001) * ((92.28 - 91.95) / (91.97 - 91.95))
 = 16.63

**Comment by lukephills** [comment]
And here's a video example
https://drive.google.com/file/d/0B-FXQg_VQV3JaDFGbDhqZDliaEE/view

**Comment by tambien** [comment]
Is it possible to get this in a jsfiddle or something i can play with? I want to check if this has been fixed with the updated Envelope implementation in r6.

**Comment by lukephills** [comment]
I've created a mock example using a settimeout to replicate the user dragging the block as per the video. Hopefully this can shed some light. 

http://jsfiddle.net/LwLny67u/3/

**Comment by tambien** [comment]
Thanks for the example. it was really helpful in debugging this situation. [Here's your example with the new Tone.js build (r6-dev)](http://jsfiddle.net/yotammann/prespcLb/1/). No clicks or super loud pops. 

Unlike in r5, the new envelope implementation keeps track of all scheduled events, so changing the attack time during the attack doesn't cause any discontinuities.

**Comment by lukephills** [comment]
Ah cool! Which build are you using though? When I use r6-dev Tone.js it's not working. Sounds like this:
http://jsfiddle.net/prespcLb/9/

(In this example, I'm using in this: https://raw.githubusercontent.com/Tonejs/Tone.js/dev/build/Tone.js)

**Comment by tambien** [comment]
I don't often commit builds to the dev branch. The build i used in that example (and included in the html section of that jsfiddle) i created using the latest changes, but never committed. I just committed those files, so you should be able to make your own build and verify these changes.

**Comment by lukephills** [comment]
Yes all working great now thanks!
