### ISSUE TITLE
Cannot find module `tone/build/esm/core/Global`

### ISSUE THREAD

**Issue by lucpotage** [Tonejs/Tone.js#973]
I tried to use Tone.js on a new Nuxt 3 project. Unfortunately, I get the following error:

> Cannot find module '/.../node_modules/tone/build/esm/core/Global' imported from /.../node_modules/tone/build/esm/index.js

I import Tone this way:

```js
import * as Tone from 'tone'
```

Also tested this way:

```js
import * as Tone from 'tone/build/esm/index.js'
```

I tried with the latest version and the next version without success. Any idea of what could be wrong?

**Comment by dirkk0** [comment]
I just checked - for some reason I needed to re-install with `npm init tone` but `import * as Tone from 'tone'` works for me in a vanilla JS project.

**Comment by tambien** [comment]
Try also installing `tone@next` which changes the browser entry point (#914) and may also fix this issue.

**Comment by lucpotage** [comment]
It may be related to Nuxt 3 which is still in beta. I close bug since I didn't get any problem with a simple Vite.js starter project. Thanks for your help.

**Comment by naomiaro** [comment]
I'm getting this same error when I try importing in `next` `^12.1.0`. I tried both tone and tone@next.

**Comment by naomiaro** [comment]
I think it has to do with not having extensions if I manually change the import to `"./core/Global.js";` in the library it finds it and then moves on to complain about `export * from "./classes";`

**Comment by DronHazra** [comment]
I'm having this issue with next.js as well, see #1077

**Comment by julianwagle** [comment]
Any fix for this? Why was it closed?

**Comment by mxfng** [comment]
I got Tone v^14.8.49 to work in Next.js v14.0.2 this way (on my component using Tone):

```
"use client";

import * as Tone from "tone/build/esm/index";
```

**Comment by mrclay** [comment]
FYI I'm using Vite 5.0.12 and using SSG in Qwik and I found no solution other than to stick to 14.7

**Comment by dhawansolanki** [comment]
> I got Tone v^14.8.49 to work in Next.js v14.0.2 this way (on my component using Tone):
> 
> ```
> "use client";
> 
> import * as Tone from "tone/build/esm/index";
> ```

The same issue is with the same version of tone as well. Do you have any workaround for this?
