### ISSUE TITLE
Tone is not defined

### ISSUE THREAD

**Issue by Andrila-Yang** [Tonejs/Tone.js#974]
I add tone.js in p5.js but it always reports a ReferenceError: Tone is not defined.
I included `<script src="https://unpkg.com/tone@14.7.39/build/Tone.js"></script>` in the HTML file and tried a very simple example called Hello Tone on Tone.js homepage and the errors still remain.
I've tried different versions but it doesn't work.

**Comment by dirkk0** [comment]
Can you look at this example, and see if it works for you?
https://codepen.io/dirkk0/pen/yLMaMGa
If it does, can you apply this to your simple example and report back?

**Comment by Andrila-Yang** [comment]
> Can you look at this example, and see if it works for you? https://codepen.io/dirkk0/pen/yLMaMGa If it does, can you apply this to your simple example and report back?

Thanks for your reply! It works well in the code pen editor, but when I copy and past it into the p5 web editor, it reports the same error (Tone is not defined). It seems p5.js does not refer to this library. I'm thinking about Tone.js is not available in p5.js?

[https://editor.p5js.org/234438/sketches/IMqw3mxjb](url) This is my example, can you help me check what's wrong?

**Comment by dirkk0** [comment]
I know for sure that p5 and tone work well together, I built a big project with exactly that.
I'll look into this.

**Comment by dirkk0** [comment]
I think the main problem was that p5sound (which you don't need) doesnt play well with ToneJS, maybe a global name space collision:
https://editor.p5js.org/dirkk0/sketches/w9IPD0z_w

**Comment by Andrila-Yang** [comment]
> I think the main problem was that p5sound (which you don't need) doesnt play well with ToneJS, maybe a global name space collision: https://editor.p5js.org/dirkk0/sketches/w9IPD0z_w

Many thanks! It works well! I completely have no idea the two libraries will collide

**Comment by 7ombie** [comment]
This issue should be reopened. That example is misleading. It only works because it's a fiddle that runs the JS code globally, and `Tone` is bound to the `window`.

If you add `type=module` to the `script` tag, it stops working (you have to use `window.Tone` explicitly, and there's no way to import `Tone` from `Tone.js` using standard import syntax.

In short, Tone is not compatible with ES6.

**Comment by dirkk0** [comment]
https://github.com/Tonejs/Tone.js/wiki/Installation

**Comment by tambien** [comment]
@7ombie could you provide an example of it not working with es6? Tone.js exports an ES6 module from `tone/build/esm/index.js` and points to it from the package.json so compatible loaders should be able to parse that correctly.

**Comment by 7ombie** [comment]
@tambien - Sorry. I didn't know there was an `esm` build. I'll try that. Happy to close.

**Comment by tambien** [comment]
@7ombie let me know if that works for you

**Comment by 7ombie** [comment]
@tambien - yes. Thank you. That's fine. You can close this. Cheers.

**Comment by jtrujillo7** [comment]
I experience problems trying to build a simple exampe of Tone + typescript.

@tambien, Is this the right way to import Tone? into a typescript source?

`import * as Tone from "./node_modules/tone/build/esm/index.js";  `

(with this I get errors 404 for Classes, global, version, ToneAudioBuffer and some others.

(The only way I could make it to work was with a 
`<script src="./Tone.js" type="module"></script>`
in the html file, this makes the variable Tone visible everywhere but then I can not have type information.

**Comment by Paegasus** [comment]
The correct way to import everything in typescript is this:

`import * as Tone from "tone";`
