### ISSUE TITLE
join multiple tracks into 1 downloadable audio file

### ISSUE THREAD

**Issue by udielenberg** [Tonejs/Tone.js#979]
I have multiple tracks I want to join into 1 audio file and make it downloadable

I found `Tone.Recorder` helpful, because I can record live my scheduled tracks,
but since the final track can get to 30 mins long I'm looking for an `Offline` solution to render it much faster than the track's actual duration.

Is it possible to create this with `Tone.Offline`? I wasn't sure how to use it

**Comment by dirkk0** [comment]
You can render multiple tracks down, yes, by creating an offline context and starting your samples.
After a short time, the promise returns the AudioBuffer with your new sample.
You can then [turn this into a downloadable file](https://www.russellgood.com/how-to-convert-audiobuffer-to-audio-file/).
