### ISSUE TITLE
Monophonic Instrument Frequency Issue

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#98]
When executing the following code in `#r5`:
```javascript
new Tone.Monophonic().triggerAttack('C4')
```
you will get thrown `Uncaught TypeError: Cannot read property 'setValueAtTime' of undefined`

This syntax appears to be present in the [docs located here](http://tonejs.org/docs/#Monophonic).

The line that this is occurring on is [here](https://github.com/Tonejs/Tone.js/blob/3279e02c9233d22f8696bafb8b2d77aa53cd68fe/Tone/instrument/Monophonic.js#L107)

**Comment by tambien** [comment]
Tone.Monophonic is an abstract base class for other monophonic instruments. it doesn't actually make any sound. Instead, use one of the classes that extends Monophonic.

Sorry about the confusion. I will be sure to make this more clear in the documentation.

**Comment by JackCA** [comment]
woops! Thanks for clarifying -- sorry for the non-issue here.

**Comment by tambien** [comment]
no problem at all.
