### ISSUE TITLE
Fixing the bug

### ISSUE THREAD

**Issue by abirdwhale** [Tonejs/Tone.js#981]
This code (code A) is working:
https://editor.p5js.org/abirdwhale/sketches/JzjyxlscM
This code ( code B) is not working:
https://editor.p5js.org/abirdwhale/sketches/wVFbFZxlx

Could anyone point out what's wrong with code B?

Many thanks,
Masa

**Comment by dirkk0** [comment]
you are missing the "C1":
cymbalSynth.triggerAttack("C1", time, 0.3);

**Comment by abirdwhale** [comment]
Oh, such a simple misunderstanding of how .triggerAttack ( ) works.
Thank you, @dirkk0 !

**Comment by abirdwhale** [comment]
I made the mistake because I was looking at the old document.
https://tonejs.github.io/docs/r13/MetalSynth

I should have checked the latest document.
https://tonejs.github.io/docs/14.7.77/MetalSynth
