### ISSUE TITLE
Popping sound when starting a player in fast succession

### ISSUE THREAD

**Issue by Specy** [Tonejs/Tone.js#982]
Hey, this is not really a bug but more of a question, I have an app where there is a instrument of 21 notes made of an array of 21 players, one player per note, whenever I press a single note in fast succession I hear a "pop/click" noise at the very start of the note, I tried adding a small offset but the noise is still there. 

I firstly started making this app with the normal webaudio API but it wasn't the best so I wanted to use tone.js because of its features but I feel like I'm remaking the same code that I had in webaudio API.
I haven't had such problem with the webaudio API but I noticed that I create a new player (in webaudio API) for every note that I play, without disconnecting it, is that a memory leak?

I saw some posts saying that this pop issue is due to the player overloading and to fix the issue its better to use a "player pool" with many players in it and use them one by one when playing a note.
Is that the correct approach or there is a more simple way to solve the issue to the root?

**Comment by marcelblum** [comment]
Would have to see/hear some example code to help more but note that Tone's `Player` attempts to be an abstraction of web audio's `AudioBufferSourceNode` system and is not meant to be "fire and forget". Under the hood 1 `Player` can be managing multiple source nodes with the same buffer depending on fade times, scheduled events, etc. I think it's best to keep 1 `Player` for each buffer (note?) and avoid constantly creating new Players. That said, if you want more complex polyphony for the each buffer then you would need to manage multiple Players per buffer.

**Comment by Specy** [comment]
I'm not sure how to give a reproducible example but i can share the code i'm using to play the audio. This is the instrument class which accepts a instrument name in the constructor and will fetch the audio files for each note.
[This is my current code](https://www.toptal.com/developers/hastebin/loqugutegu.js) I'm simply calling the play function with the index of the note and the pitch changer

This is a video of the issue i'm having [and here are the audio files in case they might be useful](https://github.com/Specy/genshin-music/tree/dev/public/assets/audio/Lyre)

https://user-images.githubusercontent.com/59029985/143083763-ab33bb38-624f-438e-9f94-411bd967d8ca.mp4

**Comment by Specy** [comment]
Ok i managed to make a [https://codesandbox.io/s/young-cdn-evtpr?file=/src/index.js](codepen)

**Comment by marcelblum** [comment]
Your codepen link seems to be broken, it does not seem to link to any example code pertaining to this.

In any case looking at your hastebin code, is `Instrument.play()` what's being called with each click? Try setting a small `fadeOut` for each `Player`. That way when the `Player` gets restarted Tone will automatically fade out the previously playing instance and should avoid clicks. Also there's no need to set the `playbackRate` before each `start()`, assuming that will be staying constant it can be set once at `Player` creation (same goes for `fadeOut`).

**Comment by Specy** [comment]
> Your codepen link seems to be broken, it does not seem to link to any example code pertaining to this.

Yes sorry i forgot to save, i remade it [here](https://codesandbox.io/s/vigorous-moore-1ylo9?file=/index.html)

**Comment by marcelblum** [comment]
I think the main problem is with your reverb impulse response file. Looks like it has a slightly malformatted/exotically formatted header that is getting rendered as a click at the beginning of the sound by `decodeAudioData` (typically this means it contains some metadata that is misread as audio data. the wav format is weird). Try using this fixed wav.
[Ajjc-reverb4_m.zip](https://github.com/Tonejs/Tone.js/files/7596837/Ajjc-reverb4_m.zip)

Aside from that, you may want to lower the gain on the convolver to avoid clipping, and adding something like `note.fadeOut = .1` when you instantiate the `Player` will help further.

**Comment by Specy** [comment]
But the reverb isn't applied, you manually decide to toggle it, the noise appears in both the one with and without the reverb. Gain node is at 2.5 because the convolver node with that reverb sounds really low volume without it. I'll try to use the reverb you gave tho, but the base issue is still there. 
I'll also try with the fadout later, but it appears that the click noise is there also when playing a single note at a time, very faint but you can hear it. I'm not having this issue working directly with buffers in the webaudio API.

Also one thing, as a workaround before I decide to redo the instrument stuff, if I disconnect the buffer source after it finished playing, will it be deleted from memory or?

**Comment by marcelblum** [comment]
Aside from the reverb, I think it's just a matter of avoiding clipping from overamplification and adding a small `fadeOut` to avoid non-zero-crossing issues. In your codesandbox, if I add `note.fadeOut = .01` and lower `config.volume` to `.5` that seems to do the trick unless I really madly click.

**Comment by Specy** [comment]
https://user-images.githubusercontent.com/59029985/143282601-3908c576-5466-4e41-a495-6b1ea5fa34bc.mp4

It's better but it's still there, i added on the side the current[ rewrite im doing without tone.js](https://www.toptal.com/developers/hastebin/wecofopawa.js) and there isn't any

**Comment by Specy** [comment]
Eh I guess no tone.js for me, I remade everything using webaudio API and even managed to record and download as .webm.

Thanks for the help anyway, I managed to do this only thanks to what I learnt those days with tone.js

**Comment by marcelblum** [comment]
FWIW, I believe this is fixed with #968
