### ISSUE TITLE
Control .playbackRate and .reverse with one random value (negative to positive)?

### ISSUE THREAD

**Issue by tmhglnd** [Tonejs/Tone.js#986]
Hi! I'm trying to use one single value (positive or negative) to control the playbackrate and reverse of a sample in a `Tone.Loop()`. The problem that I'm having is that it seems that every time `.reverse = true` is used it actually literally reverses the sound (so 2x `true` is back to regular playback). I'm looking for a way that setting `.reverse = true` keeps the sample reversed, and setting `.reverse = false` would play it back regularly. Now my code looks something like this (simplification):

```js
let sample = new Tone.Player('mysoundfile').toDestination();
sample.autostart = false;

let loop = new Tone.Loop((time) => {
	// random speed between -1 and 1
	let s = Math.random() * 2 - 1;
	
	// when sample is loaded, start
	if (sample.loaded){
		// set the sample to reverse or regular playback
		sample.reverse = (s < 0) ? true : false;

		// playbackrate can not be 0 or negative
		sample.playbackRate = Math.max(Math.abs(s) * n, 0.0001);

		sample.start(time);
	}
}, '1m').start(0);
``` 

Any suggestions or things I'm missing that would allow me to do this? Much appreciated :)

**Comment by tambien** [comment]
I'm unable to reproduce this issue. 

Here's my attempt: https://codesandbox.io/s/still-monad-3nhqy?file=/src/index.ts

```ts
import { Player, loaded, start } from "tone";

const player = new Player(
  "https://tonejs.github.io/audio/drum-samples/Bongos/kick.mp3"
).toDestination();

document.querySelector("#reverse")?.addEventListener("click", async (e) => {
  await loaded();
  player.reverse = Math.random() > 0.5;
  (e.target as HTMLElement).textContent = `reverse: ${player.reverse}`;
});

document.querySelector("#start")?.addEventListener("click", async () => {
  await start();
  await loaded();
  player.start();
});
```

One button randomly reverses the sample and the other plays it back. I always hear the sample as reversed when `reverse: true` and normal when it's false. I'm not getting the issue where if i assign `reverse = true` twice it goes back to normal. 

Could you send me a minimal example where i could reproduce this issue?

**Comment by tmhglnd** [comment]
Thanks for having a look. Now that I try to isolate the issue in a small example I'm actually also not able to reproduce. So I'll have to dive back into my bigger project and see where this issue comes from. I'll report back when I know more and maybe reopen the issue if I found a reproducable example to send.

**Comment by tmhglnd** [comment]
Okay, I've found the issue I think. It is because I'm also in that same loop swapping out/setting the buffer content of the player. Maybe this is not the best approach for this?

https://codesandbox.io/s/intelligent-fermi-csm6z?file=/src/index.ts

```js
import { ToneAudioBuffers, Loop, Transport, Player, loaded, start } from "tone";

const buffers = new ToneAudioBuffers({
  hh: "https://tonejs.github.io/audio/drum-samples/Bongos/hihat.mp3",
  kc: "https://tonejs.github.io/audio/drum-samples/Bongos/kick.mp3",
  sn: "https://tonejs.github.io/audio/drum-samples/Bongos/snare.mp3"
});

const sample = new Player().toDestination();

const loop = new Loop((time) => {
  let select = Math.trunc(Math.random() * 3);
  sample.buffer = buffers.get(["hh", "kc", "sn"][select]);

  if (sample.loaded) {
    sample.reverse = Math.random() < 0.5;
    console.log("reverse?", sample.reverse);

    sample.start(time);
  }
}, "1n");

document.querySelector("#start")?.addEventListener("click", async () => {
  await start();
  await loaded();
  await Transport.start();
  loop.start(0);
});
```

**Comment by tambien** [comment]
I see so the issue is when multiple Players are sharing the same buffer. 

The expected behavior is that if you reverse the buffer, that state is stored on the buffer. So any player pointing at that buffer will also be reversed, even when `reverse` was initiated on by a player. 

That seems consistent with what's going on in the example that you posted right?

**Comment by tmhglnd** [comment]
Ah, I see. So what would be the best approach/workaround for this where multiple players share the same buffer and individually need to either be able to play it regularly or reversed? I come from environments like maxmsp, pd, sc and in there usually the buffer is unaltered and reversing a sample is determined by the player. So that's why I'm not really able to wrap my head around this approach. Thanks for the help so far! :)

**Comment by tambien** [comment]
In this case i would recommend cloning or duplicating the ToneAudioBuffer so that each Player can point to its own. The easiest way to do that if you've already loaded the url is `buffers.get('sn').slice(0)`;

I just pushed a clarification to the docs of Player.reverse which will hopefully avoid this confusion in the future. Thanks for the issue!

**Comment by tmhglnd** [comment]
Great! This seems to work good so far indeed, thanks a lot :). Just one more question, will this approach create unique copies of the buffer as well, meaning more memory usage? I'm not sure how this works under the hood. Just wondering if this will scale well when I have loaded > 100 samples in ToneAudioBuffers and dynamically add/remove Players.

**Comment by tambien** [comment]
yeah these buffers are all copies of each other and all held in memory so it will definitely take more memory than when they pointed at the same buffer.
