### ISSUE TITLE
NoiseSynth will not play more than once.

### ISSUE THREAD

**Issue by jacksoncapper** [Tonejs/Tone.js#989]
The NoiseSynth will not play more than once.

```
let noiseSynth;
document.body.addEventListener("click", function () {
      noiseSynth = noiseSynth || new Tone.NoiseSynth().toDestination();
      noiseSynth.triggerAttackRelease("8n", 0.05);
});
```
MembraneSynth, MonoSynth, PolySynth ect. will all play again onclick.

**Comment by jacksoncapper** [comment]
Using the single parameter solved the problem:

`noiseSynth.triggerAttackRelease("8n")`

**Comment by curtgrimes** [comment]
Thanks, I experienced the same problem. I think the documentation should be updated if this is not a bug.
