### ISSUE TITLE
wet property not available for Convolver in Tone.JS 14.7.77 ?

### ISSUE THREAD

**Issue by dippid** [Tonejs/Tone.js#994]
Hello, and congratulations for this fantastic library. 

I'm learning to code while discovering it, so excuse my question if it's something I didn't understand. I'm using Tone.JS v14.7.77, the "wet" property is not available for the Convolver, while it existed in previous versions. How to mix between sound with/without convolver in this case? (I use the convolver to make a reverb).

Thanks

**Comment by joeljansonjohansen** [comment]
Hello!

Don't know if something has changed between version and that the "wet" property disappeared for some reason but what you could do is to use a CrossFade and then use that as a way to mix between the wet and dry signal.

Read more about how to implement it here:
https://tonejs.github.io/docs/14.7.77/CrossFade

**Comment by dippid** [comment]
Thanks for the tip, I will try this

**Comment by tambien** [comment]
This is the updated API going into 14.7 as noted in the [CHANGELOG](https://github.com/Tonejs/Tone.js/blob/dev/CHANGELOG.md#features). It seemed better to me to just keep that component simple, but maybe worth adding a ConvolverEffect which behaves similar to the previous Tone.Convolver if there is a demand for it. PRs are very welcome if this is a component that you'd like to add.
