### ISSUE TITLE
How to set Volume in 0 - 1

### ISSUE THREAD

**Issue by mtrucc** [Tonejs/Tone.js#997]
https://tonejs.github.io/examples/oscillator

I can set `volume` -100 to 0

But I want to set Volume like https://alemangui.github.io/pizzicato/

0 to 1

What should I do?

**Comment by dirkk0** [comment]
You can add a Gain Node, which accepts values from 0 to 1:
https://tonejs.github.io/docs/14.7.77/Gain

**Comment by mtrucc** [comment]
> You can add a Gain Node, which accepts values from 0 to 1: https://tonejs.github.io/docs/14.7.77/Gain

```
		const gainNode = new Tone.Gain(0).toDestination();

		gainNode.gain.setValueAtTime(1, Tone.context.currentTime);

		const osc = new Tone.Oscillator({
			type: "square",
			frequency: 440,
			volume: 0
		}).connect(gainNode);
```

Thank you!

volume is 20 -> Doesn’t increase the size of the sound, maybe this is my illusion.............

**Comment by dirkk0** [comment]
there's a volume: 0 in your synth ... ?

**Comment by mtrucc** [comment]
> there's a volume: 0 in your synth ... ?

yes， the demo is -16 ,I think if it is adjusted to 0, there will be no effect on the sound? I don't know what its default value is

**Comment by dirkk0** [comment]
You want to ramp up the volume of the synth, right? And this doesn't work?
If you open up a CodePen or Glitch, this can be solved, I think.

**Comment by mtrucc** [comment]
I have solved the problem, I don’t want to increase the volume, I just saw some doubts about the volume parameter, I don’t know what will happen if the parameter value is 20

**Comment by dirkk0** [comment]
ok, great! Then you can close this issue.
