### ISSUE TITLE
Only 1 second can be played in ios chrome browser

### ISSUE THREAD

**Issue by mtrucc** [Tonejs/Tone.js#998]
**Describe the bug**

https://tonejs.github.io/examples/oscillator

Only 1 second can be played in ios chrome browser，Safari Can continue to play after clicking

But https://alemangui.github.io/pizzicato/ Can continue to play after clicking

**To Reproduce**

https://tonejs.github.io/examples/oscillator

**Expected behavior**
Can continue to play after clicking

**What I've tried**

```
     document
        .querySelector('tone-momentary-button')
        .addEventListener('down', () => {
          // Tone.context.resume() ;osc.start()
          Tone.context.resume().then(() => {
            osc.start();
          });
        });
```

**Additional context**
https://bugs.chromium.org/p/chromium/issues/detail?id=807017

But https://alemangui.github.io/pizzicato/ is normal

**Comment by mtrucc** [comment]
https://tonejs.github.io/examples/stepSequencer
Also does not work in ios chrome

**Comment by tambien** [comment]
Just tested on iOS chrome and worked fine for me. Make sure the phone's mute rocker switch is not in the `mute` position. 

Also not able to reproduce the initial issue. The desired behavior of that component is that the oscillator is playing for as long as you are pressing and holding the button. Is that not what you are experiencing?

**Comment by mtrucc** [comment]
> Just tested on iOS chrome and worked fine for me. Make sure the phone's mute rocker switch is not in the `mute` position.
> 
> Also not able to reproduce the initial issue. The desired behavior of that component is that the oscillator is playing for as long as you are pressing and holding the button. Is that not what you are experiencing?

Sorry, I am doing some related tests

When the phone is set to mute, it can only play for 1 second, when the phone is set to non-mute, it can play continuously.

But I don’t know why there is no sound, I’m investigating the reason

https://tonejs.github.io/examples/player
https://tonejs.github.io/examples/stepSequencer

**Comment by mtrucc** [comment]
`<tone-momentary-button></tone-momentary-button>`

The interesting thing is that the event listener is placed on this element in the code. I changed the'down' event to'click' because I expected it to be played continuously, and it also failed.
So I added a <button>.

`<button id="content"></button>`

```
document
.querySelector('#content')
.addEventListener('click', () => {
  const gainNode = new Tone.Gain(0).toDestination();

  gainNode.gain.setValueAtTime(1, Tone.context.currentTime);

  const osc = new Tone.Oscillator({
    type: 'square',
    frequency: 440,
    volume: 0,
  }).connect(gainNode);

  Tone.context.resume() ;osc.start()
});
```

Now it can work normally.

So I should correct the description of the problem, it is not accurate enough
